### ISSUE TITLE
correct sense for getobjbound

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1003]
I think what we're doing is incorrect for maximization and conic models, for example, since there's an objective sign flip that JuMP does for the objective value but not for ``getobjbound``.

**Comment by mlubin** [comment]
Strictly speaking, we could disallow maximization objectives for conic models if we're going through with the "no transformations" idea.

**Comment by joehuchette** [comment]
That seems unnecessarily restrictive.

**Comment by mlubin** [comment]
Then we should consider adding objective senses to the MPB conic interface.

**Comment by blegat** [comment]
Why not just flip sign for getobjbound and try to do "no transformations" ?

**Comment by mlubin** [comment]
> Why not just flip sign for getobjbound

It's inconsistent with what we do when we send the problem to the ``LinearQuadratic`` interface or the ``Nonlinear`` interface, so we'd potentially have to maintain an extra piece of state in the model to know which interface on the last call to ``solve()``.

**Comment by mlubin** [comment]
Resolved vacuously. `getobjbound` doesn't exist anymore, and JuMP is no longer responsible for the sign flip in the objective.
