### ISSUE TITLE
 Internal error defining local variables in macros

### ISSUE THREAD

**Issue by loylobo** [JuliaOpt/JuMP.jl#1007]
I obtained the following error:
ERROR: Internal error defining local variables in macros; please file an issue at https://github.com/JuliaOpt/JuMP.jl/issues/new

Following is my constraint:
 @constraint(Ccs,[n=NODES],sum(Transport[a] for a = ARCS,FromNode[a]=n)-sum(Transport[a] for a = ARCS,ToNode[a]=n)-Produce[n]+Store[n]== 0)

 FromNode and ToNode are parameters

Please help me resolve or suggest options to specify this constraint.

**Comment by mlubin** [comment]
``sum(Transport[a] for a = ARCS,FromNode[a]=n)`` is incorrect syntax. It should be ``sum(Transport[a] for a = ARCS if FromNode[a]=n)``.

**Comment by loylobo** [comment]
When i used  sum(Transport[a] for a = ARCS if FromNode[a]=n), I got the following error:

ERROR: LoadError: syntax: unexpected "="

**Comment by mlubin** [comment]
I've edited my response

**Comment by loylobo** [comment]
Thank you so much!
