### ISSUE TITLE
HessVec for JuMP model evaluator

### ISSUE THREAD

**Issue by edljk** [JuliaOpt/JuMP.jl#1011]
````julia MathProgBase.eval_hesslag_prod(dJ,h,x,σ,μ) ```` 

does not seem to be available when ```` dJ ```` is a  ```julia JuMP.NLPEvaluator``` whereas 

 ````julia MathProgBase.initialize(dJ,[:Grad,:HessVec])```` is accepted.. ?

**Comment by mlubin** [comment]
What is the error message you're seeing?

**Comment by edljk** [comment]
````julia
m = Model()
@variable(m, x)
@variable(m, y)
@NLobjective(m, Min, sin(x) + sin(y))
values = zeros(2)
values[linearindex(x)] = 2.0
values[linearindex(y)] = 3.0
h = rand(2)
d = JuMP.NLPEvaluator(m)
MathProgBase.initialize(d, [:Grad,:HessVec])
h = rand(2); v = rand(2)
````
gives

````julia
jjulia> MathProgBase.eval_hesslag_prod(d,h,values,v,1.,[])
ERROR: MethodError: no method matching eval_hesslag_prod(::JuMP.NLPEvaluator, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Array{Any,1})
Closest candidates are:
  eval_hesslag_prod(::JuMP.NLPEvaluator, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Array{Float64,1}) at ${HOME}/.julia/v0.5/JuMP/src/nlp.jl:639
````

Thus I understood that the problem is perhaps the last argument.

````julia
julia> MathProgBase.eval_hesslag_prod(d,h,values,v,1.,zeros(0))
````
seems to be ok.  Is it the right way to call eval_hesslag_prod without constraints ?

**Comment by mlubin** [comment]
``zeros(0)`` and ``Float64[]`` are both ok

**Comment by edljk** [comment]
Perfect, thanks !

**Comment by edljk** [comment]
It seems there is a conflict with default call of ̀ 

```MathProgBase.eval_hesslag_prod(d,h,x,v,σ,μ) ```

when ```d``` is a julia ```JuMP.NLPEvaluator``` and ```KnitroSolverInterface.jl```

```eval_hv_cb(x, lambda, sigma, hv) = eval_hesslag_prod(d, hv, x, sigma,lambda)```

which uses the same vector for the input and the result of the product. No ?

**Comment by mlubin** [comment]
JuMP follows the [MathProgBase definition](http://mathprogbasejl.readthedocs.io/en/latest/nlp.html#eval_hesslag_prod). If KNITRO.jl doesn't, that's an issue with KNITRO.jl. I suspect the hessvec functionality hasn't been well tested with Knitro.
