### ISSUE TITLE
SCIP solver callbacks

### ISSUE THREAD

**Issue by amirmm11** [JuliaOpt/JuMP.jl#1015]
Hi

It seems that SCIP callbacks are not supported because when I used simpleheur.jl to use SCIP, I got this error:
```julia
ERROR: LoadError: Solver does not support heuristic callbacks
 in attach_callbacks(::JuMP.Model, ::Array{JuMP.HeuristicCallback,1}) at .julia/v0.5/JuMP/src/ca  llbacks.jl:155
 in registercallbacks(::JuMP.Model) at .julia/v0.5/JuMP/src/callbacks.jl:199
 in #build#114(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at .julia/v0.5/Ju  MP/src/solvers.jl:431
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
 in #solve#109(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at .julia/v0.5/  JuMP/src/solvers.jl:166
 in solve(::JuMP.Model) at .julia/v0.5/JuMP/src/solvers.jl:148
while loading .julia/v0.5/JuMP/examples/simpleheur.jl, in expression starting on line 62
```
Thanks

**Comment by mlubin** [comment]
Could you clarify what issue you're reporting with JuMP and how you expect it to be addressed?

**Comment by amirmm11** [comment]
If you look at simpleheur.jl example which is provided in JuMP package, it uses  JuMP/Gurobi to implement a call back function  "addheuristiccallback(m, myheuristic)"

I changed this example to use SCIP instead of Gurobi because it seems that SCIP Callbacks are supported by changing the example as follows:

using JuMP, AmplNLWriter
m = Model(solver=AmplNLSolver("/usr/local/bin/scipoptsuite-4.0.0/scip-4.0.0/interfaces/ampl/bin/scipampl"))

Then I got the above error 
ERROR: LoadError: Solver does not support heuristic callbacks

I need to mention that I can use SCIP to solve other examples such knapsack.jl therefore SCIP has been installed correctly.

**Comment by mlubin** [comment]
The error message is correct. You cannot access callbacks of any kind through the ``AmplNLWriter`` package. SCIP.jl supports callbacks to a greater extent.

**Comment by amirmm11** [comment]
In installation Guide (https://jump.readthedocs.io/en/latest/installation.html#other-ampl-compatible-solvers), It was never mentioned about SCIP package. But anyhow, when I use "Pkg.add("SCIP")", I get this error

_julia> Pkg.add("SCIP")
INFO: Installing SCIP v0.3.0
INFO: Building SCIP
================================[ ERROR: SCIP ]=================================

LoadError: AssertionError: Environment variable `SCIPOPTDIR` not set!
while loading /home/amirm@dev.oati.local/.julia/v0.5/SCIP/deps/build.jl, in expression starting on line 11

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: SCIP had build errors.

 - packages with build errors remain installed in /home/amirm@dev.oati.local/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("SCIP")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated_

**Comment by blegat** [comment]
According to [SCIP's README](https://github.com/SCIP-Interfaces/SCIP.jl), you need to set `SCIPOPTDIR` to the directory where SCIP is installed.
