### ISSUE TITLE
JuMP.prepProblemBounds(m) function cannot use in julia 0.5 and above version

### ISSUE THREAD

**Issue by henry8527** [JuliaOpt/JuMP.jl#1016]
As title ,The error message is there is no corresponding function in Jump Package

**Comment by blegat** [comment]
`prepProblemBounds` has been removed in #942. You now need to use `prepAffObjective` and `prepConstrBounds`.

**Comment by mlubin** [comment]
This method was unexported and undocumented as far as I can tell, so there should be no expectations that it remains available across JuMP releases.
