### ISSUE TITLE
Using Mosek in JuMP

### ISSUE THREAD

**Issue by Reza-rn** [JuliaOpt/JuMP.jl#1018]
Hi everybody.

I am trying to use Mosek solver in the JuMP modeling tool to solve my optimization problem but I faced error.
Could you please provide me a very simple example in this solver or just look at a very simple code for using Mosek and help me what is the problem? 
```julia
using JuMP
using Mosek
m=Model(solver=MosekSolver())
@variable(m,0<=x<=2)
@variable(m,0 <=y<=30)
@objective(m, Max, 5x+3y)
@constraint(m, 1x+5y<=3)
print(m)
status=solve(m)
println("objective value=", getobjectivevalue(m))
println("x=",getvalue(x))
println("y=",getvalue(y))
```

**Comment by blegat** [comment]
The same code produces
```Max 5 x + 3 y
Subject to
 x + 5 y ≤ 3
 0 ≤ x ≤ 2
 0 ≤ y ≤ 30
objective value=10.6
x=2.0
y=0.2
```
for me on Julia 5.1. What is the error you get ?

**Comment by Reza-rn** [comment]
Thanks for replying me. I am using the same version of Julia but I get the below error by running the code.

Max 5 x + 3 y
Subject to
 x + 5 y <= 3
 0 <= x <= 2
 0 <= y <= 30
objective value=NaN
x=NaN
y=NaN
WARNING: Not solved to optimality, status: Error
WARNING: Variable value not defined for x. Check that the model was properly solved.
WARNING: Variable value not defined for y. Check that the model was properly solve

**Comment by joehuchette** [comment]
This isn't a JuMP issue, it doesn't sound like you have Mosek installed correctly. See the [README](https://github.com/JuliaOpt/Mosek.jl/blob/master/README.md) for instructions.
