### ISSUE TITLE
Inconsistency between getobjbound() and getobjectivevalue()

### ISSUE THREAD

**Issue by adowling2** [JuliaOpt/JuMP.jl#1021]
Small example:

```julia
using JuMP, Gurobi
m = Model(solver=GurobiSolver())
@variable(m, 0 <= x <= 5)
@variable(m, y, Bin)
@constraint(m, x >= y)
@objective(m, Min, x - 5)

solve(m)

println("objective = ",getobjectivevalue(m))
println("objective bound = ",getobjbound(m))
```

Output:
```julia
julia> include("test.jl")
Optimize a model with 1 rows, 2 columns and 2 nonzeros
Variable types: 1 continuous, 1 integer (1 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 5e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective 0

Explored 0 nodes (0 simplex iterations) in 0.00 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0 
Pool objective bound 0

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap -
objective = -5.0
objective bound = 0.0
```

Gurobi (or JuMP?) is ignoring the constant (-5) term in the objective. The constant is added back in for getobjectivevalue() but is not for getobjbound().

I tested this with Julia 0.5.0 (Mac), MathProgBase 0.6.4, and JuMP 0.16.2.

**Comment by mlubin** [comment]
This is expected behavior because we don't pass objective constants to the
solvers.

**Comment by adowling2** [comment]
I understand the output of Gurobi. I still think the inconsistency is an issue (unexpected behavior). You can get situations where getobjectivevalue(m) < getobjbound(m) for an optimal solution, which caught me off guard.

**Comment by mlubin** [comment]
I agree that it's problematic.

**Comment by joehuchette** [comment]
Would it be sufficient to print a warning if the constant is nonzero?

**Comment by mlubin** [comment]
> Would it be sufficient to print a warning if the constant is nonzero?

Not really. We have no way of knowing whether a constant was set at the time the model was solved.

**Comment by joehuchette** [comment]
I meant at solvetime. If there's a nonzero constant, print a warning that it's not being passed through to the solver.

**Comment by mlubin** [comment]
You mean ``warn_once`` whenever someone solves a problem with a constant in the objective? If we do that we might as well not support constants in the objective.

**Comment by joehuchette** [comment]
That was going to be my next suggestion.
