### ISSUE TITLE
Posting constraints using ExprGraph

### ISSUE THREAD

**Issue by jac0320** [JuliaOpt/JuMP.jl#1024]
Just wonder if there exist a way to add constraints to a JuMP model using ExprGraph like the one below
:((3.0 * x_lift[8] + 3.0 * x_lift[9] + 3.0 * x_lift[10] + 3.0 * x_lift[11]) - 111.0 >= 0.0)

Tried JuMP.addconstraint() but it doesn't take it.

Any other suggestions?

**Comment by mlubin** [comment]
http://www.juliaopt.org/JuMP.jl/0.16/nlp.html#raw-expression-input

**Comment by jac0320** [comment]
Sorry for the confusion, the intention is to add a linear constraint back. Like in this case,
:((3.0 * x_lift[8] + 3.0 * x_lift[9] + 3.0 * x_lift[10] + 3.0 * x_lift[11]) - 111.0 >= 0.0)
This constraint is a lifted linear constraint that I would like to solve using MIP solver. If do JuMP.addNLconstraint, it will construct a NLconstraint in MathProgBase which MIP solver doesn't takes all the time.

**Comment by mlubin** [comment]
No, if you want JuMP to recognize the constraint as linear you have to write it using ``@constraint``, e.g.,
```julia
@constraint(m, sum(coef[i]*var[i] for i in S) >= b)
```
If you can create the expression graph it shouldn't be hard to create the equivalent data structures ``coef``, ``var``, ``S``, and ``b``.

**Comment by jac0320** [comment]
So the ExprGraph comes from MathProgBase. I have managed to perform some manipulation(flattening and lift to make linear) on the tree and need to insert them back into a different model. It might be easier, maybe, in this case, to have a method of JuMP.addconstraint() to support this type of input (although it can be nasty in terms operations on the tree structure for clean implementation).
Any reason not doing it?

**Comment by mlubin** [comment]
> Any reason not doing it?

You answered your own question: "it can be nasty in terms operations on the tree structure for clean implementation". It also seems a bit too specialized to include this functionality in JuMP. It could appear in a separate package which has utilities for manipulating expression graphs. I think AmplNLWriter has some code to extract the linear structure out of an expression graph.

**Comment by jac0320** [comment]
Right. A user can give some really special expression structure that jeopardizes the fidelity of model building without even realizing it. Thank for the help.

BTW, SymPy also provides some supports.
