### ISSUE TITLE
transition documentation to Documenter

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#1045]
see mathprogbase issue on same topic https://github.com/JuliaOpt/MathProgBase.jl/issues/169 and setup PR JuliaOpt/MathProgBase.jl#166

some attempts with old documentation that may be useful to borrow from:
https://github.com/JuliaOpt/JuMP.jl/pull/286
https://github.com/JuliaOpt/JuMP.jl/pull/607
https://github.com/JuliaOpt/JuMP.jl/pull/485

**Comment by mlubin** [comment]
Documenter is currently set up.
