### ISSUE TITLE
update for new MPB statuses - decide how to break all JuMP models

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#1046]
see the JuliaOpt project for statuses https://github.com/orgs/JuliaOpt/projects/1

**Comment by mlubin** [comment]
This must be a hard breaking change because we will no longer return a symbol from ``solve()``.

**Comment by ccoffrin** [comment]
proposal, update `solve()` to return a Julia object with overloaded method for equality testing to symbols; so that it does not break on old status symbol tests, but also throws a depreciation warning.

**Comment by mlubin** [comment]
MOI is already such a breaking change that it's not clear if this should still be an issue.

**Comment by ccoffrin** [comment]
agreed. >_<

**Comment by mlubin** [comment]
`solve()` was renamed to `optimize()`
