### ISSUE TITLE
completing variable indices

### ISSUE THREAD

**Issue by juan-pablo-vielma** [JuliaOpt/JuMP.jl#105]
The following code fails in the last command.

******************
m = Model()
@defVar(m,x[1,1:2])
@addConstraint(m,x[1,1]+x[1,2]<=1)
@defVar(m,x[1,0]>=0)
@addConstraint(m,x[1,1]+x[1,2]+x[1,0]<=1)

ERROR: key not found: 1
 in getindex at dict.jl:515
 in getindex at no file
******************

This code could be useful when dealing with socp constraints. There is an easy fix bellow, but adding new indices as above could be useful (if it is feasible). 

******************
m = Model()
@defVar(m,x[1,i=0:2]>= ( i == 0 ? 0 : -Inf))
@addConstraint(m,x[1,1]+x[1,2]<=1)
@addConstraint(m,x[1,1]+x[1,2]+x[1,0]<=1)
******************

**Comment by mlubin** [comment]
Is this resolved? Should we add support for ``@defVar(m, x[1:4], SOC)``? Doesn't seem to be in high demand.

**Comment by joehuchette** [comment]
Should be like 10 lines of code, can add once someone asks.
