### ISSUE TITLE
ERROR: Unrecognized function "sum" used in nonlinear expression

### ISSUE THREAD

**Issue by Goysa2** [JuliaOpt/JuMP.jl#1052]
Hi,
I have an issue writing a toy problem. I have the following code:
`using JuMP`
`function testSparse(A,b)`
`       nlp=Model()`
`      @variable(nlp,x[i=1:5])`
`       @NLobjective(`
`       nlp,`
`       Min,`
`       sum((A*x-b).^2)`
`       )`
`       return nlp `
`       end`

When I give a 5x5 Matrix (sparse) and a 5x1 Vector I get the error : ERROR: Unrecognized function "sum" used in nonlinear expression. 

Is there a way to have Matrix in a @NLObjective? Like to calculate the norm of A*x-b for example (I have tried (norm(A*x-b) and norm(dot(A,x)-b)) instead and none of them works).

Thanks!

**Comment by mlubin** [comment]
This is not supported, as explained in the [syntax notes](http://www.juliaopt.org/JuMP.jl/0.17/nlp.html#syntax-notes) for nonlinear modeling. JuMP only understands  nonlinear expressions written in terms of scalar operations.
