### ISSUE TITLE
Set GLPKSolver verbosity 

### ISSUE THREAD

**Issue by tolstoi2000** [JuliaOpt/JuMP.jl#1053]
I would like to track the solver progress during the solving phase and not until the end. 

I know it is possible to compute informational callback at to print them at the end of the solving phase, but is it possible no to wait the end ? 

Thank you in advance !

**Comment by mlubin** [comment]
Please post usage questions at https://discourse.julialang.org/c/domain/opt. The README at https://github.com/JuliaOpt/GLPKMathProgInterface.jl has an example of adjusting the verbosity of GLPK.
