### ISSUE TITLE
investigate documenter formatting issues

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1057]
http://www.juliaopt.org/JuMP.jl/latest/

@ccoffrin

**Comment by ccoffrin** [comment]
At first I was having some issues with rendering then it seemed to work fine.  Hard try refresh?

**Comment by mlubin** [comment]
Here's what I'm seeing: 

![image](https://user-images.githubusercontent.com/1733683/27162421-1ad44024-514f-11e7-8451-a889dc52cb8e.png)

**Comment by ccoffrin** [comment]
I saw that a few times.  Now I only see this and can't get back to that one...

<img width="989" alt="screenshot 2017-06-14 22 35 54" src="https://user-images.githubusercontent.com/1105578/27162910-f568b286-5151-11e7-91e2-59954b51e0b8.png">

**Comment by mlubin** [comment]
Seems ok now for me
