### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1061]
Why don't we have syntax hightlighting on the new documentation with documenter ? We seem to have the same config as Documenter.jl's doc but they have syntax highlighting when doing ` ```julia ... ``` ` and we don't.
**EDIT** I have just built it locally and I have syntax highlighting locally, weird.

**Comment by ccoffrin** [comment]
This was fixed in #1059, it just has not gone live yet due to CI backlog.

**Comment by blegat** [comment]
Make sense, thanks :)
