### ISSUE TITLE
Organization of SD Functions

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1063]
It seems that there are a variety of SD functions in JuMP.jl (e.g. `addconstraint(m::Model, c::SDConstraint)`).  Other expression types have their own files, e.g. `affexpr.jl`, `quadexpr.jl`.  

Should there be an `sdexpr.jl`?

**Comment by blegat** [comment]
We discussed about this [here](https://github.com/JuliaOpt/JuMP.jl/pull/1012). I would also be in favor of having one file per cone.

**Comment by ccoffrin** [comment]
Sounds like a good time to make a new PR for this.  😄  I'll tip my hat someone else who has a better understanding of which methods should move into such a file.
