### ISSUE TITLE
expose the concept of JuMP model being attached to a MathProgBase model

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1069]
@sebmart made a useful suggestion that we should make it more explicit when a JuMP model is attached to a MPB model, and give the user the option to ignore, warn, or error on the case where we cannot pass through a JuMP model modification to the MPB model and need to toss it and regenerate from scratch.

**Comment by jdlara-berkeley** [comment]
@mlubin Is there a way to directly toss an internal model. I figured out that the issues I have posted are all related to the fact that after the model is solved some of the model modifiers do not work and whay I need to do is toss it and regenerate from scratch.

**Comment by blegat** [comment]
`setsolver` didn't do it ?

**Comment by jdlara-berkeley** [comment]
@blegat no, unfortunately, it didn't. I read the comments about changing from MPB to MOI in the newer version of JuMP and it seems that that would fix some of these shortcomings.
