### ISSUE TITLE
allow flipped notation of bound constraint in variable definition

### ISSUE THREAD

**Issue by pierre-haessig** [JuliaOpt/JuMP.jl#1072]
I'm quite new to JuMP, and while trying to adapt the quick start guide to some simple problem, I stumbled across an odd error while creating the model variables. Not sure if it's a bug or a known limitation related to Julia's syntax (at least I didn't found an issue on this)

This is my failing code:
```julia
@variable(m, 0 <= x <= 1 );
@variable(m, 0 <= y );
```
error is raised on 2nd line: `ERROR: MethodError: no method matching getname(::Int64)`.

Indeed, looking closer at the guide, the correct syntax is `@variable(m, y >= 0 )`, but since `@variable(m, lb <= y <= ub )` is allowed, it seems weird that `@variable(m, lb <= y )` is not. Also, when stacking several constraints like in my example, I feel that `@variable(m, lb <= y )` looks better.

If this is not fixable, maybe a small warning in the quick start guide would be useful (and a clearer error message, if possible).

Sorry for the noise if this is a well-known and accepted behavior.

**Comment by mlubin** [comment]
This is an inherent restriction in JuMP's syntax. Otherwise, if you wrote ``@variable(m, a <= b)`` we would have no way to know if you want to declare a new variable ``a`` or ``b``. I agree that a clearer error message would be useful.

**Comment by mlubin** [comment]
I'll consider this resolved by https://github.com/JuliaOpt/JuMP.jl/pull/1308.

**Comment by pierre-haessig** [comment]
Thanks for the follow-up. Thanks @blegat for the PR.
