### ISSUE TITLE
constraint ref name lost

### ISSUE THREAD

**Issue by jdlara-berkeley** [JuliaOpt/JuMP.jl#1074]
I am trying to modify a model using the @constraint macro in the following way: 

1. I have a function that generates a model as follows: 

```julia
function build_model(params)

m = model()

@variables(m, params) 
@constraint(m,ref, params)
@objective(m, params)
@objective(m, params) 

return m

end
```

2. Then I have other functions that I want to use to modify a model depending on what I need as follows

```julia
function modify_model(m)

@variable(m, x, objective = 0.0, inconstraints = [ref], coefficients [ 1.0])

return m

end
```

The approach works when adding new constraints or variables, but when trying to modify the problem it doesn't work. Julia throws an error ```ref is not defined```. It seems as if by passing the model around the information about the constraint ref name is lost. 

How can I perform this operation is using the modification referenced to the name of the constraint doesn't work? 

There is an old open topic about it [link](https://groups.google.com/forum/#!topic/julia-opt/sCBf6hDJ_Y4) not sure if this got implemented.

**Comment by blegat** [comment]
ref is a variable local to the build_model function so it is not accessible from the modify_model function. This has nothing to do with JuMP. You can do m[:ref] instead

**Comment by jdlara-berkeley** [comment]
@blegat thanks, that solved the problem I can define things this way: 
```
@variable(m, x, objective = 0.0, inconstraints = [m[:ref]], coefficients [ 1.0])
```
