### ISSUE TITLE
Problem writers

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#1075]
For a different project I needed light-weight LP and MPS file writers. These have inputs similar to the MPB linear quadratic interface.

https://github.com/odow/LPWriter.jl
https://github.com/odow/MPSWriter.jl

At some point these should be used by JuMP, or put into some sort of "MathOptFileFormats" package that allows reading and writing of common MathOpt file formats like LP, MPS, NL, and OSIL.

This is probably actionable after the re-write, so leaving this as a reminder.

I did pick up a few issues with the current implementations:
- LP writer doesn't support binary variables
- LP writer doesn't check for invalid names properly
- MPS format doesn't support user specified names

**Comment by mlubin** [comment]
Hijacking this issue now that JuMP doesn't have built-in LP or MPS writers. What's the status of MOI-based writers?

**Comment by odow** [comment]
There is an [LP writer](https://github.com/odow/LPWriter.jl) and a [MPS writer](https://github.com/odow/MPSWriter.jl) that support the old MPB format, as well as a [PR](https://github.com/odow/MathOptFormat.jl/pull/15) to convert from MathOptFormat standalone instances to MPB (and therefore LP and MPS). 

It probably just needs a little bit of work, to get everything together.
