### ISSUE TITLE
adding variables recursively 

### ISSUE THREAD

**Issue by jdlara-berkeley** [JuliaOpt/JuMP.jl#1076]
I am trying to use the syntax 
```julia
@variable(m, x, objective = objcoef, inconstraints = constrrefs, coefficients = values)
```
to modify a problem and add variables to a predefined problem. The solution so far is to use that syntax in this way 

```julia
const = getindex(m, :ref)
@variable(m, x, objective = 0.0, inconstraints = [const], coefficients [ 1.0])
```

However, JuMP gives an error ``` Can only create one variable at a time when adding to existing constraints``` if I try to do it within a for loop like this to include different lower boundaries for each variable. 

```julia
const = getindex(m, :ref)
lb = [lb_1, lb_2 ... lb_n]
for i = 1:n
 @variable(m, x[i] >= lb[i], objective = 0.0, inconstraints = [const], coefficients = [1.0])
end
```
Any idea on how to work this issue around?

**Comment by joehuchette** [comment]
What about:
```jl
const = getindex(m, :ref)
lb = [lb_1, lb_2 ... lb_n]
x = Array{Variable}(n)
for i = 1:n
 x[i] = @variable(m, lowerbound = lb[i], objective = 0.0, inconstraints = [const], coefficients = [1.0])
end
```
(I haven't tested this code)

**Comment by jdlara-berkeley** [comment]
it works perfectly, I made a slight modification to include the ```basename``` such that in the print_out the variable is not defined with a anon value. 

```
const = getindex(m, :ref)
lb = [lb_1, lb_2 ... lb_n]
x = Array{Variable}(n)
for i = 1:n
 x[i] = @variable(m, lowerbound = lb[i], objective = 0.0, inconstraints = [const], coefficients = [1.0], basename = "x[$i]")
end
```

**Comment by jdlara-berkeley** [comment]
Something happened that now the line ```x = Array{Variable}(n)``` returns and error ```cannot resize array with shared data```
