### ISSUE TITLE
JuMP should define hash() for GenericAffExpr

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/JuMP.jl#1079]
The documentation for `Base.hash()` says:

```
hash(x[, h::UInt])

  Compute an integer hash code such that isequal(x,y) implies hash(x)==hash(y).
```

JuMP currently defines `isequal()` for affine expressions, but not `hash()`, so this implication doesn't hold:

```julia
julia> m = Model();

julia> @variable m x
x

julia> isequal(x + 1, x + 1)
true

julia> hash(x + 1) == hash(x + 1)
false
```

This causes things like dictionaries with affine expressions as keys to behave weirdly:

```
julia> d = Dict((x + 1) => 1)
Dict{JuMP.GenericAffExpr{Float64,JuMP.Variable},Int64} with 1 entry:
  x + 1 => 1

julia> d[(x + 1)]
ERROR: KeyError: key x + 1 not found
Stacktrace:
 [1] getindex(::Dict{JuMP.GenericAffExpr{Float64,JuMP.Variable},Int64}, ::JuMP.GenericAffExpr{Float64,JuMP.Variable}) at ./dict.jl:474

julia> (x + 1) in keys(d)  # false because Dict uses hash() first
false

julia> (x + 1) in collect(keys(d))  # true because this just does (==) for each element
true
```

I am working around it in my own code by defining the following:

```julia
function _hash(x::JuMP.GenericAffExpr, h::UInt)
    h = hash(x.constant, h)
    for v in x.vars
        h = hash(v, h)
    end
    for c in x.coeffs
        h = hash(c, h)
    end
    h
end
```

and I think we could just move that definition into JuMP to fix the issue. 

There may also be other JuMP types that need the same treatment.

**Comment by blegat** [comment]
We may first need to first sort the variables, merge duplicates and remove zero coefficients in the affine expression such that `x + 1 - x` have the same hash than `1`

**Comment by mlubin** [comment]
Equality of ``AffExpr``s is defined based on equality of the variables and coefficients arrays, not based on reduction to a canonical form, so there's no reason to do that when defining the hash.

**Comment by blegat** [comment]
Indeed, the implementation suggested by @rdeits might be correct then
