### ISSUE TITLE
ForwardDiff 0.5

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1082]
In the REQUIRE, we say that JuMP needs a version of ForwardDiff prior to 0.5. Is there something to do now that ForwardDiff 0.5 has been released ?
cc @jrevels

**Comment by mlubin** [comment]
ReverseDiffSparse is already updated, so it shouldn't be much work to do this. This cannot easily be backported to 0.17 because ForwardDiff 0.5 requires Julia 0.6 or later.
