### ISSUE TITLE
Arrays of JuMP variables can't be defined 

### ISSUE THREAD

**Issue by jdlara-berkeley** [JuliaOpt/JuMP.jl#1087]
I am trying to create an array of JuMP variables using this command 

```julia
A = Array{JuMP.Variable}(2)
```

But it is returning an error: 

```UndefRefError: access to undefined reference```

The code was working before, is there any change in JuMP that might be causing this?

**Comment by blegat** [comment]
This lines works fine on master
```julia
A = Array{JuMP.Variable}(2)
2-element Array{JuMP.Variable,1}:
 #undef
 #undef
```
It creates an array of `JuMP` variables but Julia does not initialize the entries of the arrays as expected.
I suspect that the failure `UndefRefError` comes from a further line.

**Comment by jdlara-berkeley** [comment]
This seems to be a problem related to copy and reuse of JuMP models, I will open another issue.
