### ISSUE TITLE
solving different instances of a model 

### ISSUE THREAD

**Issue by jd-lara** [JuliaOpt/JuMP.jl#1088]
I am trying to reuse JuMP models in the following way. 

```
model_1 = model_creator(parameters...); 
solution_1 = solve_model(model_1, parameters...);
model_2 = model_modifier(model_1, parameters...);
solution_2 = solve_model(model_2, parameters...);
```

The objective is to create basic models that later can be modified with other functions. This works out ok if I modify model_1 before solving it, but if I solve model_1 and then try to modify model_1 then I get errors. 

How can I implement a system where I can have JuMP models that are modifiable and independent?

**Comment by blegat** [comment]
The errors you get might be because the internal solver instance does not support the modification. If you do
```julia
model_1 = model_creator(solver = ClpSolver(), parameters...); 
solution_1 = solve_model(model_1, parameters...);
setsolver(model_1, ClpSolver()) # drop internal model
model_2 = model_modifier(model_1, parameters...);
solution_2 = solve_model(model_2, parameters...);
```
it shouldn't give error.

**Comment by jdlara-berkeley** [comment]
@blegat thanks for the contribution but it didn't work. Let me expand upon the implementation. 

The model creator function has the following form 

```Julia
function model_creator(paramters...) 

    m = Model(solver=Gurobi.GurobiSolver())

    @variable(m, x...)
    @variable(m, y...) 

    @constraint(m, f(x,y)....) 

    #Objective function 

    @objective(m, Min, g(x,y)..)

    return m

end

```

The solve model function has the following form, it takes the model and solves it, returning the solved model. 

```Julia
function solve_ed(m::JuMP.Model)

    JuMP.build(m)
    status = solve(m)

    if status != :Optimal
        println(status)
        error("Problem has no solution.")    
    end

    return m 

end
```

However, if I take the original model that I created with ```model_build``` I can't modify it anymore. Even if after solving I run the line ```setsolver(model_1, GurobiSolver())```.

**Comment by mlubin** [comment]
@jdlara-berkeley it will be easier to others to provide help if you give self-contained code that can reproduce the issue and also say precisely what errors you're seeing.

**Comment by jdlara-berkeley** [comment]
@mlubin I am trying to reproduce the error with a simpler version of the code and the model, but I have not been able to do it. In short, after solving the model if I try to modify it, I get this error.

```
cannot resize array with shared data

Stacktrace:
 [1] push! at ./array.jl:618 [inlined]
 [2] JuMP.Variable(::JuMP.Model, ::Float64, ::Float64, ::Symbol, ::String, ::Float64) at /Users/jdlara/.julia/v0.6/JuMP/src/JuMP.jl:365
 [3] #constructvariable!#96(::Array{Any,1}, ::Function, ::JuMP.Model, ::JuMP.#_error#103{Tuple{Symbol,Expr}}, ::Float64, ::Float64, ::Symbol, ::String, ::Float64) at /Users/jdlara/.julia/v0.6/JuMP/src/macros.jl:834
 [4] macro expansion at /Users/jdlara/.julia/v0.6/JuMP/src/macros.jl:185 [inlined]
 [5] inyection_constraints(::JuMP.Model, ::ps_types.system_param, ::Array{ps_types.load,1}, ::Array{ps_types.ng_generator,1}, ::ps_types.network) at /Users/jdlara/Dropbox/Remote Code Rep/Julia/dispatch_models/transmission_constraints.jl:28
```

(```ps_types`` is the structure that contains all the parameters. )

**Comment by jdlara-berkeley** [comment]
@mlubin the full code is in my repository. The main *.jl file is in this [link](https://github.com/jdlara-berkeley/Julia_testcodes/blob/master/dispatch_models/main_ed.jl)

**Comment by odow** [comment]
@jd-lara what is the status of this? Can it be closed?

**Comment by jd-lara** [comment]
@odow I think this no longer relevant with the way MOI works.

**Comment by odow** [comment]
Please re-open if you find it is still an issue.
