### ISSUE TITLE
deprecation/error message improvements for JuMP/MOI

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1095]
Let's keep a list of errors and deprecations that need to be added before the JuMP 0.19 release:
- [ ] Removal of `norm` (https://github.com/JuliaOpt/JuMP.jl/pull/1093)
- [ ] Statuses (https://github.com/JuliaOpt/JuMP.jl/issues/1046)

**Comment by mlubin** [comment]
We're still missing a useful error message for `norm`.

**Comment by odow** [comment]
Where is the best place to add this? In the macros? Or by overloading norm?

**Comment by blegat** [comment]
Overloading norm I'd say

**Comment by blegat** [comment]
We could also add deprecation messages with `Base.@deprecate` for `getvalue` and `getdual`. For `solve` we should throw an error because it now returns `nothing` instead of `:Optimal`.
