### ISSUE TITLE
Anonymous scalar variable with positional argument

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1100]
Currently, it is not possible to use anonymous scalar variable and using positional argument at the same time.
This is an issue for PolyJuMP since you cannot create an anonymous polynomial, e.g.
```julia
@variable m Poly(X)
```
does not work.

What do you think of detecting `_` as an anonymous variable so that
```julia
@variable m _ Poly(X)
```
would be considered as an anonymous variable just like
```julia
@variable m [1:2] Poly(X)
```
creates an vector of anonymous variable.

**Comment by mlubin** [comment]
> What do you think of detecting _ as an anonymous variable

Feels like a hack. Why not come up with a keyword that can be used to specify ``Poly(X)`` for the anonymous variable case?

**Comment by blegat** [comment]
The return type of `@variable` should only depend on the positional keywords

**Comment by mlubin** [comment]
@blegat, why? This is a macro, not a function.

**Comment by blegat** [comment]
Yes but that how what we decided for `variabletype`

**Comment by blegat** [comment]
@mlubin would you consider a PR implementing this ?

**Comment by mlubin** [comment]
I don't like having a special meaning for `_`. I'd rather have a macro like `@anonvariable`.

**Comment by blegat** [comment]
Or maybe something like
```julia
@variable m type=Poly(X)
```
where the value of the `type` keyword acts like a positional parameter.
