### ISSUE TITLE
Ipopt not finding correct solution depending on variable limits

### ISSUE THREAD

**Issue by jaakkor2** [JuliaOpt/JuMP.jl#1106]
```julia
using JuMP, Ipopt
n = 2
LL = [-1.001 -1.1]
UL = [1.0 1.1]
m = Model( solver=IpoptSolver() )
@variable( m, LL[i] <= x[ i=1:n ] <= UL[i] )
@objective(m, Max, sum( x[i]*x[i] for i=1:n ) )
status = solve( m )
x_sol = getvalue( x )
```

I get
```
julia> status = solve( m )
This is Ipopt version 3.12.2, running with linear solver mumps.
...
EXIT: Optimal Solution Found.
:Optimal

julia> x_sol = getvalue( x )
2-element Array{Float64,1}:
 -1.001
  0.0
```
was expecting [ -1.001 1.1 ] or [ -1.001 -1.1 ]

If
LL = [-1.0 -1.1]
I get a result that is even more wrong
```
EXIT: Optimal Solution Found.
:Optimal

julia> x_sol = getvalue( x )
2-element Array{Float64,1}:
 0.0
 0.0
```

Julia is installed from https://julialang.org/downloads/

Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
JuMP                          0.18.0
Ipopt                         0.2.6

**Comment by mlubin** [comment]
I agree it's a bit unintuitive, but there's no JuMP issue here. Ipopt has no guarantee of returning an optimal solution to a nonconvex problem. Ipopt can converge to a stationary point like (0,0), for example. In the [transition to MOI](https://discourse.julialang.org/t/mathoptinterface-and-upcoming-breaking-changes-in-jump-0-19) we are redoing status reporting to get rid of the misleading `:Optimal`.

**Comment by jaakkor2** [comment]
Thanks for the prompt response.
