### ISSUE TITLE
arg splatting causes `Incorrect number of arguments [...] in nonlinear expression.`

### ISSUE THREAD

**Issue by goretkin** [JuliaOpt/JuMP.jl#1107]
On JuMP 0.18.0

```julia
m = Model()
JuMP.register(m, :f, 2, (x, y) -> +(x, y), autodiff=true)

@variable(m, x[1:2])
@NLobjective(m, Min, f(x[1], x[2])) # works
@NLobjective(m, Min, f(x...)) # does not work with `Incorrect number of arguments for "f" in nonlinear expression.`
```

even though this works:
```julia
f = (x, y) -> +(x, y)
f([1,2]...)
```

**Comment by mlubin** [comment]
This syntax is not supported: http://www.juliaopt.org/JuMP.jl/0.18/nlp.html#syntax-notes
Nothing vector-like can appear in `@NLobjective`.
https://discourse.julialang.org/t/solvers-nonlinear-constraints-and-user-defined-functions
https://stackoverflow.com/questions/44710900/juliajump-variable-number-of-arguments-to-function
https://discourse.julialang.org/t/defining-non-linear-vector-constraints-in-jump

**Comment by goretkin** [comment]
That stackoverflow link was helpful, thanks.
