### ISSUE TITLE
ConstructVariable Array with start 

### ISSUE THREAD

**Issue by Wikunia** [JuliaOpt/JuMP.jl#1114]
It looks like start in `@variable` can only be a number atm.
In my opinion:

```
@variable(m, sf[1:N], Bin, start=heu_sf)
```
makes sense or 

```
@variable(m, sf[1:N], Bin, start=heu_sf[1:N])
```

but it doesn't work. It looks like atm this -> 

```
@variable(m, sf[1:N], Bin)
for f_idx in 1:N
    setvalue(sf[f_idx], heu_sf[f_idx])
end
```

is the only option. Correct?

Would like to implement it on my own but my understanding of julia isn't that good :D

**Comment by mlubin** [comment]
Try this:
```julia
@variable(m, sf[i=1:N], Bin, start=heu_sf[i])
```
or
```julia
@variable(m, sf[1:N], Bin)
setvalue.(sf, heu_sf)
```
https://github.com/JuliaOpt/JuMP.jl/issues/481

**Comment by Wikunia** [comment]
Oh thanks @mlubin
