### ISSUE TITLE
Is it possible to support varargs functions in objective function definition, like `setNLobjective`?

### ISSUE THREAD

**Issue by Non-Contradiction** [JuliaOpt/JuMP.jl#1115]
Currently using varargs functions in `setNLobjective` doesn't work, so there are questions on StackOverflow like 
<https://stackoverflow.com/questions/44710900/juliajump-variable-number-of-arguments-to-function/44711305#44711305>
and 
<https://stackoverflow.com/questions/46632458/an-example-of-nonlinear-optimization-with-jump>

It is natural to solve the issues in these questions by things like `myf(x...)` and `rosen(x...)` as the objective, but this doesn't work.

Is it possible to support varargs functions in objective function definition? For example, we could define a function `varargsExpand!` like this:

```
function varargsExpand!(m :: JuMP.Model, expr :: Expr)
    if expr.head == :... && length(expr.args) == 1 &&
        haskey(m.objDict, expr.args[1]) && typeof(m.objDict[expr.args[1]]) == Vector{JuMP.Variable}
            return([m.objDict[expr.args[1]][i] for i in 1:length(m.objDict[expr.args[1]])])
    else
        expr.args = vcat([varargsExpand!(m, expr.args[i]) for i in 1:length(expr.args)]...)
        return([expr])
    end
end

function varargsExpand!(m :: JuMP.Model, x)
    [x]
end
````

And the function could be used like this:

```
function setNLobjective(m::Model, sense::Symbol, x)
    initNLP(m)
    setobjectivesense(m, sense)
    x = varargsExpand!(m, x)[1]
    ex = NonlinearExprData(m, x)
    m.nlpdata.nlobj = ex
    m.obj = zero(QuadExpr)
    m.internalModelLoaded = false
    return
end
```

This is not a sophisticated way, for example, it only supports things like `rosen(x...)` but doesn't support things like `rosen(x[1:10]...)`, but at least it is better than nothing, and it is really useful and could be improved.

**Comment by mlubin** [comment]
I've been avoiding hacky solutions like this because there's no way to make things work consistently and in a non-surprising way. For example, there's no possible way to support `f(g(x...))` if g is a vector-valued function. I'm willing to revisit this question but not before JuMP 0.19 is released.

**Comment by Non-Contradiction** [comment]
Thank you very much for making JuMP and willing to revisit this problem. I totally understand the rule that the expression in @NLobjective or @NLconstraint has to be a scalar expression. Supporting things like this would be really useful. I hope this problem could be solved consistently with no hacky solutions in JuMP package or in the user code.
