### ISSUE TITLE
JuMP Not Loading/Pre-Compiling

### ISSUE THREAD

**Issue by vgupta1** [JuliaOpt/JuMP.jl#1116]
Trying to use JuMP 0.14.2 with Julia 0.6.0 on Mac OSX 10.12.6
the following code:

```
using JuMP
```
eventually fails with 

> ERROR: LoadError: LoadError: LoadError: invalid subtyping in definition of JuMPArray
> Stacktrace:
>  [1] include_from_node1(::String) at ./loading.jl:569
>  [2] include(::String) at ./sysimg.jl:14
>  [3] include_from_node1(::String) at ./loading.jl:569
>  [4] include(::String) at ./sysimg.jl:14
>  [5] include_from_node1(::String) at ./loading.jl:569
>  [6] include(::String) at ./sysimg.jl:14
>  [7] anonymous at ./<missing>:2
> while loading /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMPArray.jl, in expression starting on line 6
> while loading /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMPContainer.jl, in expression starting on line 11
> while loading /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl, in expression starting on line 63
> ERROR: Failed to precompile JuMP to /Users/vishalgupta/.julia/lib/v0.6/JuMP.ji.
> Stacktrace:
>  [1] compilecache(::String) at ./loading.jl:703
>  [2] _require(::Symbol) at ./loading.jl:490
>  [3] require(::Symbol) at ./loading.jl:398
> 

Full text of warnings etc. below.  Any ideas please?  I"m happy to change the version I use if necessary.

 using JuMP
> WARNING: deprecated syntax "abstract AbstractModel" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:70.
> Use "abstract type AbstractModel end" instead.
> 
> WARNING: deprecated syntax "abstract AbstractConstraint" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:321.
> Use "abstract type AbstractConstraint end" instead.
> 
> WARNING: deprecated syntax "abstract AbstractJuMPScalar" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:324.
> Use "abstract type AbstractJuMPScalar end" instead.
> 
> WARNING: deprecated syntax "typealias LinConstrRef ConstraintRef{Model,LinearConstraint}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:539.
> Use "const LinConstrRef = ConstraintRef{Model,LinearConstraint}" instead.
> 
> WARNING: deprecated syntax "typealias JuMPTypes Union{AbstractJuMPScalar,NonlinearExpression,Norm,GenericAffExpr,QuadExpr,SOCExpr}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:752.
> Use "const JuMPTypes = Union{AbstractJuMPScalar,NonlinearExpression,Norm,GenericAffExpr,QuadExpr,SOCExpr}" instead.
> 
> WARNING: deprecated syntax "typealias JuMPScalars Union{Number,JuMPTypes}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:753.
> Use "const JuMPScalars = Union{Number,JuMPTypes}" instead.
> INFO: Precompiling module JuMP.
> 
> WARNING: deprecated syntax "abstract AbstractModel" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:70.
> Use "abstract type AbstractModel end" instead.
> 
> WARNING: deprecated syntax "abstract AbstractConstraint" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:321.
> Use "abstract type AbstractConstraint end" instead.
> 
> WARNING: deprecated syntax "abstract AbstractJuMPScalar" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:324.
> Use "abstract type AbstractJuMPScalar end" instead.
> 
> WARNING: deprecated syntax "typealias LinConstrRef ConstraintRef{Model,LinearConstraint}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:539.
> Use "const LinConstrRef = ConstraintRef{Model,LinearConstraint}" instead.
> 
> WARNING: deprecated syntax "typealias JuMPTypes Union{AbstractJuMPScalar,NonlinearExpression,Norm,GenericAffExpr,QuadExpr,SOCExpr}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:752.
> Use "const JuMPTypes = Union{AbstractJuMPScalar,NonlinearExpression,Norm,GenericAffExpr,QuadExpr,SOCExpr}" instead.
> 
> WARNING: deprecated syntax "typealias JuMPScalars Union{Number,JuMPTypes}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl:753.
> Use "const JuMPScalars = Union{Number,JuMPTypes}" instead.
> WARNING: Method definition exp(ForwardDiff.Dual{N, T} where T<:Real) in module ForwardDiff at /Users/vishalgupta/.julia/v0.6/ForwardDiff/src/dual.jl:281 overwritten at /Users/vishalgupta/.julia/v0.6/ForwardDiff/src/dual.jl:306.
> WARNING: Method definition sqrt(ForwardDiff.Dual{N, T} where T<:Real) in module ForwardDiff at /Users/vishalgupta/.julia/v0.6/ForwardDiff/src/dual.jl:281 overwritten at /Users/vishalgupta/.julia/v0.6/ForwardDiff/src/dual.jl:311.
> 
> WARNING: deprecated syntax "abstract JuMPContainer{T,N}" at /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMPContainer.jl:10.
> Use "abstract type JuMPContainer{T,N} end" instead.
> ERROR: LoadError: LoadError: LoadError: invalid subtyping in definition of JuMPArray
> Stacktrace:
>  [1] include_from_node1(::String) at ./loading.jl:569
>  [2] include(::String) at ./sysimg.jl:14
>  [3] include_from_node1(::String) at ./loading.jl:569
>  [4] include(::String) at ./sysimg.jl:14
>  [5] include_from_node1(::String) at ./loading.jl:569
>  [6] include(::String) at ./sysimg.jl:14
>  [7] anonymous at ./<missing>:2
> while loading /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMPArray.jl, in expression starting on line 6
> while loading /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMPContainer.jl, in expression starting on line 11
> while loading /Users/vishalgupta/.julia/v0.6/JuMP/src/JuMP.jl, in expression starting on line 63
> ERROR: Failed to precompile JuMP to /Users/vishalgupta/.julia/lib/v0.6/JuMP.ji.
> Stacktrace:
>  [1] compilecache(::String) at ./loading.jl:703
>  [2] _require(::Symbol) at ./loading.jl:490
>  [3] require(::Symbol) at ./loading.jl:398
>

**Comment by mlubin** [comment]
JuMP 0.16 was the first to support Julia 0.6 (https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md). I'd recommend using JuMP 0.18.

**Comment by vgupta1** [comment]
Thanks, Miles!  I think what happened was that JuMPeR is frozen to JuMP
0.14.

I successfully removed JuMPeR, updated JuMP, and everything works fine.
I also installed a second Julia installation with 0.5, and got JuMPeR to
work with an older version of JuMP.

Tank you for all the help!

Vishal
