### ISSUE TITLE
resultdual for JuMP/MOI

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1127]

**Comment by blegat** [comment]
I will start with a PR fixing JuMP with the "no solver" MOI change :-P

**Comment by mlubin** [comment]
Don't put too much work into it, I have some ideas for a larger
restructuring. Maybe just let users provide an empty instance to attach?

**Comment by blegat** [comment]
Yes, I have removed `setsolver` and added an argument to `attach` as discussed in https://github.com/JuliaOpt/MathOptInterface.jl/issues/164

**Comment by blegat** [comment]
What do we do for dual of SDP constraints in JuMP ?
The user could do either
```julia
@SDPconstraint [x y; y z] >= 0
```
or
```julia
@constraint [x, y, z] in MOI.PositiveSemidefinteConeTriangle(2)
```
Both constraints generate exactly the same constraint reference
So in resultvalue we don't know which one was called
What do we return then ? A matrix or a Vector ?

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/1129
