### ISSUE TITLE
testing JuMP without solvers

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1137]
I'd like to make JuMP almost or entirely testable without any external solvers. The JuMP/MPB tests morphed into tests for solvers more so than tests for JuMP itself (https://github.com/JuliaOpt/JuMP.jl/issues/901) and also became really slow (https://github.com/JuliaOpt/JuMP.jl/issues/971) and fragile (https://github.com/JuliaOpt/JuMP.jl/issues/849). 

So we need to decide what exactly to test. I'd propose the following:
- Test that JuMP generates MOI instances correctly (https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/22 will be useful).
- Test that JuMP communicates with a solver correctly. For this we need a mock solver. This work needs to happen in conjunction with or after https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/32.

**Comment by blegat** [comment]
What do you mean by mock solver ? A solver doing grid search ?
One thing we could do is a cheating solver.
```julia
m = Model()
x = @variable m
c = @constraint m x >= 0
@objective m Min x
cheat = CheatInstance()
attach(m, cheat)
MOI.set!(cheat, MOI.VariablePrimal(), x, 0)
MOI.set!(cheat, MOI.ConstraintDual(), c, 1)
solve()
```
Currently, this use of `MOI.set!` isn't really defined to do that but if we allow instance that are not solvers to returns these attributes since they can be in files, ... (see [comment](https://github.com/JuliaOpt/MathOptInterface.jl/pull/169#issuecomment-345529459)) We should also allow to set them.

**Comment by mlubin** [comment]
> A solver doing grid search ?

No, I mean a solver where we've preloaded a solution to return, as in your example. I wouldn't pun on `MOI.set!` for this, call it a separate method like `setfakeresult!`.

**Comment by joehuchette** [comment]
Agreed that the solver tests should no longer live in JuMP, but they should go in a separate package so that they don't have to be rewritten in each solver wrapper.

**Comment by mlubin** [comment]
@joehuchette, solver tests should all go in [MOIT](https://github.com/JuliaOpt/MathOptInterfaceTests.jl).

**Comment by odow** [comment]
https://github.com/odow/MathOptFormat.jl for the fake solver? It would just involve adding VariablePrimal etc as attributes.

**Comment by mlubin** [comment]
The testing with the fake solver shouldn't involve any problem data. We don't need to do this for every category of problem. We just need to check that JuMP loads the solution statuses and vectors correctly. It can look like:
```
m = Model(FakeSolver(fakesolution...))
@variable(m, x[1:10])
solve(m)
# check solution status and query some attributes
```

**Comment by mlubin** [comment]
Maybe we do need some constraint present to test querying constraint attributes.
