### ISSUE TITLE
`=` instead of `==` in constraint could have better error message.

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#1142]
A user had a model with a very large number of  constraints inside an `@constraints` block. It took a while to notice that one constraint had `=` instead of `==`. 
```julia
m = Model()
@variable(m, x)
julia> @constraint(m, x = 1)
ERROR: In @constraint(m): Not enough positional arguments
```
It could do with a better error message.

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/issues/1142 on the 0.18 branch
