### ISSUE TITLE
Julia JuMP gc time

### ISSUE THREAD

**Issue by lsppppp** [JuliaOpt/JuMP.jl#1160]
Dear all, I'm new to Julia and is trying to use JuMP to solve a NLP, below is the code

```julia
m = JuMP.Model(solver=Ipopt.IpoptSolver(max_iter=50,tol=1e-6))

function lkhf(x1,x2,x3,x4,x5,x6,x7,x8)
  x = [x1,x2,x3,x4,x5,x6,x7,x8]
  @time ll = loglikelihood(x,pdpoeFacSim,intercept, pdpoeFacMean, pdpoeFacInitial, pdpoeTarget, pdVar, poeVar,corPDPOE,resRnd)
return ll
end

JuMP.register(m, :lkhf, 8, lkhf, autodiff=true)

@NLobjective(m, Min, lkhf(x1,x2,x3,x4,x5,x6,x7,x8)
```

As you can see from the code, I try to time each time the solver calls my objective function and notice something, below is part of the output:
```
0.224411 seconds (47.41 k allocations: 198.016 MiB, 54.80% gc time)

  0.027915 seconds (30.61 k allocations: 22.983 MiB, 21.84% gc time)

  0.213348 seconds (47.41 k allocations: 198.016 MiB, 56.25% gc time)

  0.026281 seconds (30.61 k allocations: 22.983 MiB, 22.52% gc time)

  0.214388 seconds (47.41 k allocations: 198.016 MiB, 55.36% gc time)

  0.028030 seconds (30.61 k allocations: 22.983 MiB, 22.65% gc time)
```

It seems that the gc time varies a lot even if it is calling the exactly same function. (I dont have much knowledge on gc time neither..)

Could you please give me some advise on how I can speed up my code?

**Comment by joehuchette** [comment]
You can potentially look at disabling julia's gc manually, but I doubt that will end up being a good idea. Honestly, it seems like your code runs fairly quickly with or without gc.

Closing since this isn't a JuMP issue.

**Comment by mlubin** [comment]
Please [link](https://stackoverflow.com/questions/48293111/julia-jump-garbage-collection-time) when cross-posting. Agreed this isn't a JuMP issue until there's evidence to suggest otherwise. See https://docs.julialang.org/en/stable/manual/performance-tips/ for hints on how to track down unexpected memory allocations.

**Comment by lsppppp** [comment]
Thanks for the suggestion!
When I run the my likelihood function separately, it will only take 0.02 seconds (average time over 1000 tests). but somehow when I use it in JuMP, it becomes 10 times longer sometimes, specifically as shown above, one time fast then followed by one time slow. Do you have any idea why this happen?
