### ISSUE TITLE
access MOI constraint from PSD variable

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1161]
https://github.com/JuliaOpt/JuMP.jl/blob/54933b0959a5b22edd5007b536d0553c96c47f3c/test/generate_and_solve.jl#L182-L184

**Comment by blegat** [comment]
We could solve it with https://github.com/JuliaOpt/JuMP.jl/issues/1164. If you want the constraint ref, then you need to do
```julia
@variable(m, x[1:2,1:2], Symmetric)
@constraint(m, x in PSDCone())
```
See
https://github.com/JuliaOpt/JuMP.jl/blob/d44ea54fbeeea80c41a854bfb358eeeeaa1a9c5c/src/sd.jl#L9-L14
