### ISSUE TITLE
constructconstraint! is not consistent with constructvariable!

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1172]
The former creates a constraint that's *not* attached to the model, while the latter creates a variable that *is* attached to the model. Probably one should be renamed. This is also related to the inconsistency between Variable and ConstraintRef:
https://github.com/JuliaOpt/JuMP.jl/blob/2f6d6e570a37922f76606c99694a2b0d35b5629b/src/JuMP.jl#L268-L269

**Comment by mlubin** [comment]
- Are you proposing to rename `JuMP.Variable` to `JuMP.VariableRef`? Makes sense to me.

- What would actually be returned by `constructvariable` in the default case? What's an `AbstractVariable`?

- "build" and "construct" mean the same thing, so we should have names that better distinguish the two actions.

**Comment by blegat** [comment]
> Are you proposing to rename `JuMP.Variable` to `JuMP.VariableRef` ? Makes sense to me.

Yes

> What would actually be returned by `constructvariable` in the default case? What's an `AbstractVariable`?

The default would be something like `RealVariable<:AbstractVariable` or `ScalarVariable<:AbstractVariable`. An `AbstractVariable` is something returned by `constructvariable!` (I know, it is a recursive definition :-P). Other variable type could be `PolynomialVariable` returned by PolyJuMP.

> "build" and "construct" mean the same thing, so we should have names that better distinguish the two actions.

Yes, maybe `parse` or `process` instead of `build` ? What do you think ?

**Comment by blegat** [comment]
Note how easy it would be for a JuMP extension (e.g. `StructJuMP`) to do
```julia
struct MyModel <: JuMP.AbstractModel
    variables::Vector{JuMP.AbstractVariable}
    constraints::Vector{JuMP.AbstractConstraint}
end
JuMP.addconstraint(m::MyModel, v::AbstractVariable) = push!(m.variables, v)
JuMP.addconstraint(m::MyModel, c::AbstractConstraint) = push!(m.constraints, c)
```
If another JuMP extension add `constructconstraint` and/or `parseconstraint` methods, it would automatically be compatible with this extension.

**Comment by blegat** [comment]
@mlubin What would you think of renaming `constructX!` with `buildX` ? The `!` isn't very appropriate since it doesn't modify its argument (`addconstraint` does) and "the `parse`/`build`/`add` pipeline" is more catchy than "the `parse`/`construct`/`add` pipeline" :-P
