### ISSUE TITLE
Update examples for JuMP/MOI and format them as doctests

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1175]
Using [doctests](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/) would make sure the examples keep working over time. This addresses #699.

There are a couple open questions here.

- What solvers should we use for testing?
- We just went through a lot of work to make JuMP testable without solvers.... but using doctests would force us to depend on solvers in CI. A few options are:
  - Collapse JuMP/MOI/MOIU/MOIT into a single package and include one default solver.
  - Make a separate package called JuMPExamples.

I'm not entirely serious about collapsing JuMP/MOI/MOIU/MOIT into a single package, but if you look at any other modeling package like cvxpy, pyomo, etc., JuMP is an outlier in its modularity, and it results in weird situations like not having a solver available to run examples. I expect we'll go with JuMPExamples.

**Comment by joaquimg** [comment]
+1 JuMPExamples

**Comment by joehuchette** [comment]
Yeah, the single package idea is a little too drastic for me.

**Comment by mlubin** [comment]
When updating the examples, let's keep a list of all the things that needed to be changed. That will help us develop a 0.18 -> 0.19 upgrading guide.

**Comment by mlubin** [comment]
Other thing to remember is juliaopt-notebooks. They need to be updated or moved into JuMPExamples or marked as outdated (also the copies hosted on juliaopt.org).

**Comment by mlubin** [comment]
Given that Pkg3 will allow multiple Julia packages in the same repository, I think we should hold off on making a new JuMPExamples.jl and just update them in place for now.
