### ISSUE TITLE
JuMP, ForwardDiff and ReverseDiffSparse.

### ISSUE THREAD

**Issue by lucasfreitas1988** [JuliaOpt/JuMP.jl#1192]
Hello! I'm a Brazilian NewBie in Julia. I want to use Mamba.
I can not use the examples available in Git, a "Model is not defined" message appears.
I think it's a JuMP problem and my Julia version is 0.6.2. When, I use the "using JuMP" command, the messages "ArgumentError: Module ForwardDiff not found in current path." and "Failed to precompile ReverseDiffSparse to C: \ Users \ ACER \ .julia \ lib \ v0.6 \ ReverseDiffSparse.ji." appears in Juno.

It occurs that I think I have correctly installed the ForwardDiff and ReverseDiffSparse packages.

I need help!

Thank you

**Comment by joaquimg** [comment]
Can you run Pkg.status() ?

**Comment by mlubin** [comment]
Closing from lack of activity. Please post at https://discourse.julialang.org/ if you still have issues.
