### ISSUE TITLE
Errror when trying to use nonlinear model

### ISSUE THREAD

**Issue by nkeito** [JuliaOpt/JuMP.jl#1199]
Hi, I'm having a bad time trying to insert this nonlinear model

min    ||  v  ||_1 + || r ||_1                                 (L1 norm)
s.t           ||  segnal - model(  v, r ) ||_2 = 0      (L2 norm)
                 vmin <= v <= vmax                      (for vmin and vmax fixed)
                 rmin <= r <= rmax                      (for rmin and rmax fixed)

where model is a function which takes r and v as input and generates a vector of the size of the variable segnal.
In my implementation I have 2 things:
main.jl which I run in console as julia main.jl
A directory MyModel which contains the actual implementation of the (non usual) function model

So, my main file looks like this:
```julia
include("./MyModel/kennet.jl")
import  kennetM #the name of the module in kennet.jl
using JuMP
n = 15
m = Model()
@variable(m, vmin<= v[1:n] <= vmax )
@variable(m, rmin<= r[1:n] <= rmax )
@objective(m, Min, sum((v)) + sum((r)))
@NLconstraint(m,  norm(kennetM.model(v,r)  -  segnal )  == 0 )
```

but, when I execute the command "julia main.jl" I got the error:

`ERROR: LoadError: Unrecognized function "norm" used in nonlinear expression.`
How shoul I input that kind of constraint?

**Comment by odow** [comment]
You may want to read the relevant docs (particularly around registering your user-defined function `kennetM.model`): http://www.juliaopt.org/JuMP.jl/0.18/nlp.html#user-defined-functions

As it says in the docs, JuMP only recognizes a few built-in functions (the list is [here](https://github.com/johnmyleswhite/Calculus.jl/blob/v0.2.2/src/differentiate.jl#L115). `norm` is not one of them). You could implement `norm(x)` as `sqrt(sum(xi^2 for xi in x))`.

In the future, usage questions like this should be posted on discourse: https://discourse.julialang.org/c/domain/opt

**Comment by barrykertesz** [comment]
sorry to ask on this thread, but if the function would be rand() #selecting a random number from a defined vector, how could it been introduced as NLexpression?

**Comment by barrykertesz** [comment]
sorry to ask in this thread, but if the function would be rand() #selecting a random number from a defined vector, how could it been introduced as NLexpression?

**Comment by odow** [comment]
Hi there. You cannot. JuMP can only solve deterministic problems. 

P.s. please use https://discourse.julialang.org/c/domain/opt for questions like this in future.
