### ISSUE TITLE
Problem using @NLobjective with sum and prod

### ISSUE THREAD

**Issue by JulieSliwak** [JuliaOpt/JuMP.jl#1205]
I would like to use sum and prod functions in @NLobjective but I have a problem. When I try to solve a small optimization problem constructed with a NLobjective containing sum and prod functions, I have a Knitro error: 

> ERROR: Hessian element hess[0] corresponding to
       Row Index           0, Column Index         0,
       is undefined at the current point.
       No further progress can be made.
EXIT: Evaluation error.

Here is the code I've executed:

```julia
using JuMP, KNITRO

mutable struct Degree
    explvar::Int
    conjvar::Int
end

m_pb = Model(solver = KnitroSolver())

##variables
variables_jump = Dict{String, JuMP.Variable}()
variables_jump["v1"] = @variable(m_pb, basename="v1")
variables_jump["v2"] = @variable(m_pb, basename="v2")

##constraints
monome1 = Dict("v1" => Degree(2,0))
monome2 = Dict("v2" => Degree(2,0))
poly = Dict( monome1 => 1.0, monome2 => 1.0)
@NLconstraint(m_pb, 1 <= sum(coeff*prod(variables_jump[varname]^degree.explvar for (varname, degree) in monome) for (monome,coeff) in poly) <=1)

##objective
monome_obj1 = Dict("v1"=> Degree(1,0))
monome_obj2 = Dict("v2"=> Degree(1,0))  
poly_obj = Dict( monome_obj1 => 1.0, monome_obj2 => 1.0)
@NLobjective(m_pb, Min, sum(coeff*prod(variables_jump[varname]^degree.explvar for (varname, degree) in monome) for (monome,coeff) in poly_obj))

print(m_pb)
solve(m_pb)
```

When I write directly the objective `@NLobjective(m_pb, Min, variables_jump["v1"]+variables_jump["v2"]) `, it's working but I need to write my objective from a dictionary like `poly_obj`.

Do you have an idea of what can be wrong?

**Comment by mlubin** [comment]
This is a bug in how JuMP computes the 2nd derivative of `x^1.0` at zero, related to https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/docs/src/user/advanced.md#fixing-naninf-issues.
Zero is the default starting point for unconstrained variables, which is unfortunate in this case. If don't expect your optimal solution to be at zero, then provide another starting point, e.g,  `@variable(m_pb, basename="v1", start=1)`

@jrevels

**Comment by JulieSliwak** [comment]
Thank you Miles for your help. Using `start=1` permits to work around the problem. 

To avoid all `x^1.0`, I've tried to use a ternary operator  : 

`@NLconstraint(m_pb, 1 <= sum(coeff*prod((degree.explvar > 1 ? variables_jump[varname]^degree.explvar : variables_jump[varname] ) for (varname, degree) in monome) for (monome,coeff) in poly) <=1)`
 
This is the error I've got : 

> MethodError: no method matching parseNLExpr_runtime(::JuMP.Model, ::JuMP.GenericQuadExpr{Float64,JuMP.Variable}, ::Array{ReverseDiffSparse.NodeData,1}, ::Int64, ::Array{Float64,1})
> Closest candidates are:
>   parseNLExpr_runtime(::JuMP.Model, !Matched::Number, ::Any, ::Any, ::Any) at D:\Users\julisliw\.julia\v0.6\JuMP\src\parsenlp.jl:196
>   parseNLExpr_runtime(::JuMP.Model, !Matched::JuMP.Variable, ::Any, ::Any, ::Any) at D:\Users\julisliw\.julia\v0.6\JuMP\src\parsenlp.jl:202
>   parseNLExpr_runtime(::JuMP.Model, !Matched::JuMP.NonlinearExpression, ::Any, ::Any, ::Any) at D:\Users\julisliw\.julia\v0.6\JuMP\src\parsenlp.jl:208
>   ...
> in anonymous at base\<missing>
> in macro expansion at JuMP\src\macros.jl:1213 
> in macro expansion at JuMP\src\parsenlp.jl:226 
> in macro expansion at JuMP\src\parseExpr_staged.jl:489 

More precisely, this is the code I've executed : 


```
using JuMP, KNITRO

m_pb = Model(solver = KnitroSolver())

##variables
variables_jump = Dict{String, JuMP.Variable}()
variables_jump["v1"] = @variable(m_pb, basename="v1")
variables_jump["v2"] = @variable(m_pb, basename="v2")

mutable struct Degree
    explvar::Int
    conjvar::Int
end

##constraints
monome1 = Dict("v1" => Degree(2,0))
monome2 = Dict("v2" => Degree(2,0))
poly = Dict( monome1 => 1.0, monome2 => 1.0)

@NLconstraint(m_pb, 1 <= sum(coeff*prod((degree.explvar > 1 ? variables_jump[varname]^degree.explvar : variables_jump[varname] ) for (varname, degree) in monome) for (monome,coeff) in poly) <=1)
```

Let me know if you have an idea of what can be wrong using the ternary operator. 

Thank you very much,

Julie

**Comment by mlubin** [comment]
The ternary operator is not supported (there should be a better error message). You can use `ifelse` instead

**Comment by JulieSliwak** [comment]
Thank you very much for your quick answer, it's working now!

**Comment by mlubin** [comment]
Sorry, I missed your reply. The `NaN` in one of the branches might be poisoning the `ifelse`. I'll take a look.

**Comment by mlubin** [comment]
@JulieSliwak, you can test out the fix with the latest JuMP release by running `Pkg.checkout("ReverseDiffSparse")`. I'll tag a new release of ReverseDiffSparse after you confirm the issue is fixed. `x^1.0` should work perfectly fine now, but there may be similar issues for other powers.

**Comment by KeithWM** [comment]
Not sure if this is the correct place to leave this, but I think the answer here also solves my problem, except that it is horrific.

What I had was

    @JuMP.variable(m, x[i=1:3, j=1:3], Bin)
    @JuMP.constraint(m, some_constraint[i], sum(x[i, j] for j=1:some_fun(x))

but `some_fun(x)` may return values less than one, in which case there should be 0 (sum([]) = 0, is probably not strictly that obvious, but still makes sense). Now if I understand correctly, I have to write

    @JuMP.constraint(m, some_constraint[i], ifelse(some_fun(x) >= 1, sum(x[i, j] for j=1:some_fun(x)), 0)

which given the dozen or so constraints, each with their own some_fun (currently inlined) is very messy.

Or am I missing some way to circumvent this?

**Comment by odow** [comment]
> `@JuMP.constraint(m, some_constraint[i], sum(x[i, j] for j=1:some_fun(x))`

The fundamental idea should work, but this isn't a valid JuMP constraint as it doesn't have a comparison operator. You should post usage questions like this on the [Discourse forum](https://discourse.julialang.org/c/domain/opt). Make sure to take a read of this [PSA](https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757) before posting.
