### ISSUE TITLE
Problem using user cuts and lazy constraints callbacks together

### ISSUE THREAD

**Issue by CBongiova** [JuliaOpt/JuMP.jl#1206]
Hello, 
I have implemented a branch-and-cut framework in julia (solving with Gurobi) and I use both user cuts and lazy constraints callbacks. After defining the MILP, the structure of the code is as follows: 
```julia
function mycutgenerator(cb)
#some user cuts
end 

function mylazygenerator(cb)
#some lazy constraints 
end 

addcutcallback(m, mycutgenerator)
addlazycallback(m, mylazygenerator)
solve(m)
```
As a first step, I have added an empty lazy constraints callback (no lazy constraints added) after the user cuts callback. In this case, since no lazy constraints are added at any node of the B&B tree, I was expecting to get the same solution I would get if I were to only call user cuts. Nevertheless, I have noticed that the solver (Gurobi) provides a different solution. 

Adding the empty lazy constraints callback to the user cuts callback I get: 
Optimal solution found (tolerance 1.00e-04)
Best objective 2.977717854818e+02, best bound 2.977717854818e+02, gap 0.0000%

Without the empty lazy callback (only user cuts callback) I get: 
Optimal solution found (tolerance 1.00e-04)
Best objective 2.881945379299e+02, best bound 2.881945379299e+02, gap 0.0000%

Any idea of why this is happening? 
Thanks in advance for your help!

**Comment by mlubin** [comment]
Hi @CBongiova. The important points to note for cut callbacks in Gurobi are (http://www.gurobi.com/documentation/7.5/refman/c_grbcbcut.html#routine:GRBcbcut):

> When adding your own cuts, you must set parameter PreCrush to value 1. This setting shuts off a few presolve reductions that sometimes prevent cuts on the original model from being applied to the presolved model.

> One very important note: you should only add cuts that are implied by the constraints in your model. If you cut off an integer solution that is feasible according to the original model constraints, you are likely to obtain an incorrect solution to your MIP problem.

**Comment by CBongiova** [comment]
Hi @mlubin. Thanks for your help! I already set the parameter PreCrush to value 1:

solver=GurobiSolver(PreCrush=1, Cuts=0, Presolve=0, Heuristics=0.0)

I am not sure to understand the second note...so I cannot cut-off fractional solutions if they are feasible in the original model? Is this feature solver-dependent? 
Also can I use a user cut callback along with a lazy constraints callback in jump? 

Thanks for your help.

**Comment by mlubin** [comment]
> I cannot cut-off fractional solutions if they are feasible in the original model? 

You cannot cut off any solutions that satisfy the integrality constraints. You're definitely allowed to cut off solutions that do not. This is a standard definition across solvers.

> Also can I use a user cut callback along with a lazy constraints callback in jump?

Yes, I'm not aware of any issues with this.

**Comment by CBongiova** [comment]
So, just to wrap up ideas: 
I am currently getting a different solution when using a lazy constraints callback along with a user cuts callback. This is due to the fact that, according to the original model, I am cutting-off a feasible solution. 

Does it sound right? 
Thanks again for your time.

**Comment by mlubin** [comment]
Gurobi's behavior is entirely undefined if the cut callback does not satisfy the contract, so I would put that as the most likely explanation for your issue. Of course, bugs in Gurobi or Gurobi.jl are also possible but less likely. You many want to contact Gurobi for support if you're convinced that your cut callback is correct.

**Comment by CBongiova** [comment]
Hi @mlubin. I have found a very interesting article which describes CPLEX's behaviour when coupling user cuts and lazy constraints. https://orinanobworld.blogspot.ch/2012/08/user-cuts-versus-lazy-constraints.html

Under section " Why two categories?"

> CPLEX and other solvers do a variety of problem reductions, both at the outset (presolving) and on the fly during the search process, to tighten the feasible regions of node problems and expedite the solution process. Some of those reductions involve solutions to dual problems. User cuts do not affect the reductions, but if you hide some actual constraints in a pool of lazy constraints (or generate them after the reductions have been done), the dual solutions used in the reductions are incomplete (lacking dual variables corresponding to the constraints that are not yet included). This can lead to incorrect results.

> If CPLEX sees the user adding lazy constraints (or, by virtue of the presence of a lazy constraint callback, threatening to add lazy constraints), it automatically turns of reductions that might be incorrect. I recently ran a program that uses CPLEX (12.4) with a lazy constraint callback. The output contained the following message:

> Lazy constraint(s) or lazy constraint callback is present.
    Disabling dual reductions (CPX_PARAM_REDUCE) in presolve.
    Disabling non-linear reductions (CPX_PARAM_PRELINEAR) in presolve.

> As user, you can turn off these reductions manually, but including a lazy constraint callback (or adding constraints to the lazy constraint pool during model construction) will induce CPLEX to do it for you.

So, assuming that different solvers behave similarly, I guess that the presence of a lazy constraint callback modifies the search mechanism. Hence, I get a different result even by adding an empty lazy constraints callback.

**Comment by mlubin** [comment]
Closing this issue as there's no evidence of a problem with JuMP. Please re-open if needed!
