### ISSUE TITLE
CBC supports SemiContinuous but JuMP doesn't support it for CBC 

### ISSUE THREAD

**Issue by blairn** [JuliaOpt/JuMP.jl#1210]
They are a subset of their lotsizing variables.

I'm not sure if I should raise it here, or if i should raise it against CBC.jl

**Comment by joaquimg** [comment]
This should be raised against cbc.jl
JuMP already supoorts it. It needs to be added to cbc julia interface, through MathProgBase (for the existing JuMP releases) and/or MathOptInterface (for future JuMP releases)
