### ISSUE TITLE
old examples

### ISSUE THREAD

**Issue by d3netxer** [JuliaOpt/JuMP.jl#1217]
Why is there a folder called 'old' in the examples folder? JuMP.jl/examples/old/

are all of the examples in here old?

**Comment by mlubin** [comment]
Yes, on the development branch (`master`) the examples have not yet been updated for the transition to MathOptInterface (https://github.com/JuliaOpt/JuMP.jl/issues/1175). See https://github.com/JuliaOpt/JuMP.jl/tree/release-0.18/examples for examples that work with the latest release of JuMP.
