### ISSUE TITLE
Print model fails when a variable array is empty

### ISSUE THREAD

**Issue by jcheyns** [JuliaOpt/JuMP.jl#1224]
When constructing a model based on dynamic input data. I have condidtions in the definition of my variables, like `@variable(m,X[i=1:10,j=1:10;<variable needed based on input data>])`.
In the special case where no variable is needed the print function causes an "ArgumentError: collection must be non-empty" exception.
Minimal example

```julia
using JuMP

model=Model()
@variable(model,X[i=1:2;i>3])
println(model)
```

Proposed solution, in print.jl line 214, check whether _values(d) is empty. Then either skip this variable completely, or (perhaps better) print the empty nature somehow.

**Comment by mlubin** [comment]
This was fixed on the `release-0.18` branch by https://github.com/JuliaOpt/JuMP.jl/pull/1225.
