### ISSUE TITLE
JuMP model LoadError

### ISSUE THREAD

**Issue by YDHsieh** [JuliaOpt/JuMP.jl#1231]
I run a  program, then got an error in terminal like following:
```
ERROR: LoadError: MethodError: no method matching JuMP.Model(; solver=Ipopt.IpoptSolver(Any[]))
Closest candidates are:
  JuMP.Model(; mode, backend, optimizer) at /home/yard/.julia/v0.6/JuMP/src/JuMP.jl:147 got unsupported keyword argument "solver"
```

main function below
```julia
function solveMPC(l,n,m,T,z0,zT,zmax,umax,dt)
    #T : horizon
    #z0 : intial position for every iteration
    #zT : reference   +++++++++++++++
    #n :dim of input
    #m : dim of state
    #
    mpc = Model(solver = IpoptSolver())
    #mpc = Model()
    #setsolver(mpc,Ipopt.IpoptSolver(print_level=0))
    @variable(mpc, -zmax[i] <= z[t=1:T+1,i=1:n] <= zmax[i])
    @variable(mpc, umin[i] <= u[t=1:T,i=1:m] <= umax[i])
    @expression(mpc, bta[i = 1:T], atan( L_r / (L_f + L_r) * tan(u[i,1]) ) )
    # Cost
    #@setObjective(mpc, Min,
    #    sum{100*(z[1,t]+z[2,t]+z[3,t]+z[4,t])^2 + sum{u[j,t]^2,j=1:m},t=0:T})


    @NLobjective(mpc, Min, sum((z[t,1]-zT[t,1])^2+(z[t,2]-zT[t,2])^2+(u[k,1]-u[k-1,1])^2+(u[k,2]-u[k-1,2])^2+10*(u[k-1,1])^2,t=2:T+1,k=2:T))
    
    # Link state and control across the horizon
    for t = 1:T       
        @NLconstraint(mpc, z[t+1,1] == z[t,1] + dt*u[t,2]*((1+0.5^2*u[t,1]^2)^0.5)*cos(z[t,3]+bta[t]))
        @NLconstraint(mpc, z[t+1,2] == z[t,2] + dt*u[t,2]*((1+0.5^2*u[t,1]^2)^0.5)*sin(z[t,3]+bta[t]))
        @NLconstraint(mpc, z[t+1,3] == z[t,3] + dt*u[t,2]*sin(bta[t])/L_r)
        #@addNLConstraint(mpc, z[t+1,4] == z[t,4] + dt*u[t,2])

    end
    
    # Initial conditions
    @constraint(mpc, z[1,:] .== z0)
    # Final state
    #@addConstraint(mpc, z[:,T] .== zT)
    # Solve the NLP
    solve(mpc)
    # Return the control plan
    return getValue(u), getValue(z)
end
```

It seems like that `mpc = Model(solver = IpoptSolver())` , this format is not correct??

How can I change the format??

Thanks

**Comment by blegat** [comment]
Are you using JuMP master or JuMP v0.18.1 ? In JuMP master, it has been changed to `Model(optimizer=IpoptOptimizer())`. You currently also need to [checkout the `ml/moi` branch in `Ipopt`](https://github.com/JuliaOpt/Ipopt.jl/pull/108)

**Comment by YDHsieh** [comment]
How can I check the version of JuMP which I use?

"Pkg.add("JuMP")"   , this is the way that I install Jump in Julia.

**Comment by blegat** [comment]
Whatis the output of `Pkg.status("JuMP")` ? If you have done `Pkg.checkout("JuMP")`, this has the effect of using the development version of JuMP, you can go back to the stable version by doing `Pkg.free("JuMP")`.

**Comment by YDHsieh** [comment]
the result of  Pkg.status("JuMP") is 
> -JuMP                          0.17.1+            master

so change from  Model(solver=IpoptOptimizer()) to Model(optimizer=IpoptOptimizer()) can work 
Thanks a lot !!!

then I do Pkg.free("JuMP")  and the result of Pkg.status("JuMP") became to 
> -JuMP                          0.18.1

In this case, use 
`mpc = Model(solver=IpoptOptimizer())`    can work ,but
encounter another problem:

ERROR: LoadError: Unexpected vector JuMP.Variable[z[1,1], z[1,2], z[1,3]] in nonlinear expression. Nonlinear expressions may contain only scalar expressions.
Stacktrace:

I have no idea how to solve it.  And what's  the meaning of "stable version" ??

**Comment by blegat** [comment]
The `master` branch contains the latest change of the repository. We call this development branch as it is not meant to be used by regular user but rather by developer of JuMP. The user are expected to use the latest release which is sometimes referred to as the "stable version".

**Comment by YDHsieh** [comment]
Thanks a lot ！！
