### ISSUE TITLE
Travis failing on master

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1269]
https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/375158129#L1033

@blegat @odow

**Comment by odow** [comment]
I presume this is because of https://github.com/JuliaOpt/MathOptInterface.jl/pull/346

**Comment by odow** [comment]
Actually, it looks like this should be a `+1`? Because the objective is `min x^2`...

https://github.com/JuliaOpt/JuMP.jl/blob/8a62f7b5ee1b17e1c10a007eb32c5c48cc130ee1/test/generate_and_solve.jl#L194
