### ISSUE TITLE
Product of sparse matrix with transpose

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1276]
If `A` and `X` are sparse matrices, one of them of numbers, the other one of `VariableRef` or `AffExpr` then the product `A * X'` should have eltype `AffExpr` but currently `Base.A_mul_Bc`  converts both matrices to the `AffExpr` eltype and allocates a matrix of `AffExpr` eltype which doesn't work as the product of `AffExpr` is `QuadExpr`.

**Comment by mlubin** [comment]
`Base.A_mul_Bc` doesn't exist anymore. Is this still an issue?

**Comment by blegat** [comment]
There is a broken test:
https://github.com/JuliaOpt/JuMP.jl/blob/c01802926c34aa30e5d272ac1063f1595084aa4a/test/operator.jl#L498
