### ISSUE TITLE
Error with power operation

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1286]
```julia
julia> using JuMP
julia> m = Model()
julia> @variable m x
julia> @constraint m (x+1)^2 == 1
ERROR: MethodError: no method matching +(::Val{false}, ::JuMP.GenericQuadExpr{Float64,JuMP.VariableRef})
```
which is due to line
https://github.com/JuliaOpt/JuMP.jl/blob/5cb9ba3e6fe04d262b28fd28e19e27ce0c375487/src/parseexpr.jl#L497
where `aff` is `Val(false)`

**Comment by mlubin** [comment]
FWIW I don't think this has ever worked in JuMP.
