### ISSUE TITLE
Emptying MOI Models Between Solves

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1290]
In the master version of JuMP one needs to explicitly call `MOI.empty!` between solves, like so,
```julia
optimizer = MyOptimizer()

m1 = Model(optimizer=optimizer)
optimize(m1)

MOI.empty!(optimizer)
m2 = Model(optimizer=optimizer)
optimize(m2)
```
It could be convenient if JuMP did this for the user, possibly with a warning.

**Comment by blegat** [comment]
Should be solved by https://github.com/JuliaOpt/JuMP.jl/pull/1384

**Comment by mlubin** [comment]
Yes, we redesigned the Model constructor with a closure-like object to capture the optimizer without constructing one so that this but can't happen anymore.
