### ISSUE TITLE
Duplicate Variable Name Error

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1292]
In JuMP master, currently adding anonymous variables the same variable names throw an error.  Would this be better suited as a warning?

**Comment by mlubin** [comment]
JuMP stores variable names in the MOI backend, so this would need to be raised at the MOI level.
The big question is what should happen when you lookup a variable by name if we don't enforce uniqueness of names. (Lookup by name didn't exist in MPB.) Gurobi says:

> If multiple variables have the same name, this method chooses one arbitrarily.

http://www.gurobi.com/documentation/7.5/refman/cpp_grbmodel_getvarbyname.html

This seems liable to let bugs slip undetected.

**Comment by ccoffrin** [comment]
Taking one more step back, what is the goal of a variable name?  

In the current version of JuMP my interoperation of a statement like this has been,
```
v_ref = @variable(m, v[i in [1,3,5,7,9]], basename="my_var")
```
`v` should be a unique Symbol id that can be used for looking up the variable, `v_ref` is a unique object/struct that can be used for looking up the variable, `basename` is a string that is used for pretty printing.  At least, this has how I have been using `basename` when building anonymous variables.

Also, in the current implementation, that when building an array of variables you need to add the indexes into the variable name like so,
```
@variable(m, v[i in [1,3,5,7,9], j=1:8], basename="my_var_$(i)_$(j)")
```
I can imagine why this is in the MOI level, but that the JuMP level it feels like overkill; but maybe not depending on what the goal of a variable name is.

**Comment by mlubin** [comment]
The goal of a variable name is changing between JuMP/MPB and JuMP/MOI. Variable names are now either empty or unique identifiers that can be used for lookup. This is useful:
- When reading an LP/MPS/... file into a JuMP or MOI model.
- When writing an LP/MPS/... file from a JuMP or MOI model.
- To do the same lookup tricks you can do with JuMP/MPB but at the MOI level.
- To conveniently track variables when you make copies of a JuMP or MOI model.
- Testing equality of models: https://github.com/JuliaOpt/JuMP.jl/blob/8a4f65f5bdf15ad77f37b95e7ec67d4ccf8cf0b6/test/generate_and_solve.jl#L40
- Hypothetically, for unit testing code that does model generation, e.g.,
``has_constraint(model, "x + y <= 1")`` could be super useful.

It's also a bit problematic and unintuitive even for pretty printing to have multiple variables with the same name.

**Comment by ccoffrin** [comment]
How will these names work and how will be printing be done in the case of anonymous variables?

**Comment by mlubin** [comment]
JuMP's concept of anonymous variables and `model[:x]` lookup is not deeply tied to variable names. The only thing linking them is that anonymous variables don't have names set by default, while non-anonymous variables have names set automatically in the macros. Variable names can be changed at any time with `setname`.
A variable with an empty name is currently printed as "noname":
https://github.com/JuliaOpt/JuMP.jl/blob/8a4f65f5bdf15ad77f37b95e7ec67d4ccf8cf0b6/src/print.jl#L121

This is clearly something we'll need to discuss in the documentation.

**Comment by mlubin** [comment]
Well, if you can come up with a way to generate unique names, I think it would be useful for testing and debugging to keep them around in the JuMP model. Also, if you plan on serializing the models to a file format, e.g., https://github.com/odow/MathOptFormat.jl, then you'll need names.

**Comment by mlubin** [comment]
We're considering dropping the unique name requirement for performance reasons: https://github.com/JuliaOpt/JuMP.jl/issues/1402#issuecomment-427620600

**Comment by ccoffrin** [comment]
Thanks for the heads up.  The discussion in #1402 is quite interesting!
