### ISSUE TITLE
Simple Constraint Type Inspection

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1293]
Is there a clean way to support functions like,
```julia
numlinconstr(model)
numquadconstr(model)
```
Without the user needing to understand all of the constraint variants in MOI?

**Comment by blegat** [comment]
For `numlinconstr`, you can do
```
const MOI = MathOptInterface
MOI.get(model, MOI.NumberOfConstraints{MOI.ScalarAffineFunction{Float64}, MOI.LessThan{Float64}}()) + MOI.get(model, MOI.NumberOfConstraints{MOI.ScalarAffineFunction{Float64}, MOI.EqualTo{Float64}}()) + MOI.get(model, MOI.NumberOfConstraints{MOI.ScalarAffineFunction{Float64}, MOI.GreaterThan{Float64}}()) + MOI.get(model, MOI.NumberOfConstraints{MOI.ScalarAffineFunction{Float64}, MOI.Interval{Float64}}())

**Comment by ccoffrin** [comment]
Right, I was thinking it would be convenient for JuMP users if they did not have to know all these MOI constraint variants and JuMP provided helper functions along this line that called the most common ones.

**Comment by mlubin** [comment]
I'm hesitant to introduce new concepts to describe constraints at the JuMP level. The MOI concepts are simple enough that we should first focus on providing nice syntax to work with them. What was previously "linear constraints" is now:
- affine + less than
- affine + greater than
- affine + equal to
- affine + interval

You could also add to that:
- vector affine + zeros
- vector affine + nonnegatives
- vector affine + nonpositives

**Comment by ccoffrin** [comment]
What if it the function was called something like `numaffineconstr` and `numvectoraffineconstr`, do you see that as adding a new concept?

**Comment by mlubin** [comment]
Would `numvectoraffineconstr` include `VectorAffineFunction{Int}` + `AllDifferent`? E.g., AllDifferent(x, 2y, z + 1).

(`AllDifferent` is hypothetical, not defined in MOI yet.)

**Comment by ccoffrin** [comment]
Without thinking too hard about it, I would be inclined to say no.

MOI is a very general framework, which is good, but I feel like there is fairly short list of concepts in the core of MathProg, so it might be helpful to do the mapping from general MOI to that short list for the users.

On a related note, how would one currently do something along the lines of `numcontr`, which returns the total number of constraints in the model?  At least for my needs, this would be sufficient.

**Comment by mlubin** [comment]
I agree this would be useful to have but I don't consider it blocking for 0.19. There's an example of how to query the number of different MOI constraints here:
https://github.com/JuliaOpt/JuMP.jl/blob/167608da60da3a08209bf9e4629b7e02b166d5b2/src/print.jl#L158-L161
Summing this over all values would give the total number of constraints (excluding nonlinear constraints).

**Comment by mlubin** [comment]
I'm pretty happy with how constraint counting is covered by http://www.juliaopt.org/JuMP.jl/dev/constraints/#Accessing-constraints-from-a-model-1. Users are free to define this as follows:
```julia
function num_linear_constraints(model) 
    return num_constraints(model, AffExpr, MOI.LessThan{Float64}) +
           num_constraints(model, AffExpr, MOI.GreaterThan{Float64}) +
           num_constraints(model, AffExpr, MOI.EqualTo{Float64})
end
```
IMO this is better defined in user code than in JuMP itself, because if we define this inevitably people will come along and ask why we're not also counting the other linear constraints in the model (i.e., with VectorAffineFunction).

Therefore I vote to close the issue.

**Comment by ccoffrin** [comment]
Agreed.  The root of this issue was really about programmatic model inspection, which seems to be well supported at this point.
