### ISSUE TITLE
Inspecting the Size of a JuMPArray

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1294]
Initially I tried to inspect the size of a JuMPArray as follows,
```julia
using JuMP

m = Model()
v = @variable(m, [i in [1,3,5,7,9], j=1:8], basename="$(i)_$(j)", lowerbound = 0, upperbound = 1)

length(v) # ERROR: JuMPArray does not define size().

v_slice = v[3,:]

length(v_slice) # ERROR: JuMPArray does not define size().
```
After inspecting the source, I determined this would do what I need,
```julia
length(indices(v)) # dimensions
length.(indices(v)) # dimension length check
length(indices(v_slice)) # dimensions
length.(indices(v_slice))[1] # dimension length check
```
It might be helpful to have some default behavior for the standard Julia array functions like `length` and `size`.

**Comment by mlubin** [comment]
I was following https://docs.julialang.org/en/latest/devdocs/offset-arrays/, but the guidance may have changed for 0.6/0.7.

**Comment by ccoffrin** [comment]
I see, the logic outlined in offset arrays makes sense to me, but I had not been exposed to them yet so I was lost for the function naming pattern.  A more helpful error message would surely mitigate the issue.

Possibly the root of my confusion is `Array` in the name, it made me think it would behave like typical Julia array, but it is more flexible than that.  Maybe something like `JuMPCollection{N}`, would be more semantics agnostic, and the dimension number `N` would give a hint that it has some features to standard multidimensional arrays.

**Comment by mlubin** [comment]
The use of `Array` in `JuMPArray` is consistent with `OffsetArrays` and [`AxisArrays`](https://github.com/JuliaArrays/AxisArrays.jl). I agree that the error messages should be more helpful.

**Comment by ccoffrin** [comment]
An improved error message sounds good to me.

**Comment by mlubin** [comment]
Both OffsetArrays and AxisArrays now define `size`, so I think it's safe for us to do so also.
