### ISSUE TITLE
@constraintref in JuMP 0.19

### ISSUE THREAD

**Issue by jd-lara** [JuliaOpt/JuMP.jl#1303]
JuMP 0.19 doesn't have a straightforward way to generate constraints programmatically. 

@blegat has suggested using the code in containers.

**Comment by mlubin** [comment]
Could you provide a bit of the context? `@constraintref` was always ugly, I'd prefer not to bring it back in its old form.

**Comment by mlubin** [comment]
Also see https://github.com/JuliaOpt/JuMP.jl/blob/151c75fba8e7a2f8b36e96aa29909441b06e9207/test/containers.jl.

**Comment by jdlara-berkeley** [comment]
@mlubin I have been looking that containers code to enable this. It is important to enable the creation constraints programmatically that can be indexed with the same sets used to define constraints. Before this was achieved using @constraintref. 

If a variable is created as follows ```@variable(m, x[["a", "b"]])```, it is possible to retrieve the set used to create it with ```set = x.axes[1]``, but there is no way to generate constraints indexed over the same axis. This will enable using functions to generate different variables when needed. Enable a syntax that allows something like this (based on the old ```@constraintref```). 

```Julia 
function createvariables(m,set)
   @variable(m, x[set])
end

function constraint1(m,x,set2)
   set1 = x.axes[1]
   @constraintref Lim1[set1, set2]
   for i in set1
      for j in set2
         Lim1 = @constraint(m, x[i,j] >= 10)
      end
   end
end

function constraint2(m,x,set2)
   set1 = x.axes[1]
   @constraintref Lim1[set1, set2]
   for i in set1
      for j in set2
         Lim1 = @constraint(m, x[i,j] >= 8)
      end
   end
end

m1 = Model()
createvariables(m1, ["a","b"])
#Then I can choose any constraint creation function I want or change set2 if I want. 
constraint2(m1,x,[1:10])
```

**Comment by mlubin** [comment]
The less that needs macros to accomplish, the better. I think the same thing could be addressed by directly calling a constructor of `JuMPArray` with the appropriate index sets, e.g., `Lim1 = JuMPArray(Array{ConstraintRef}(...correct dimensions...), set1, set2)`. Then assign into elements of `Lim1`.

**Comment by mlubin** [comment]
It also seems strange to me to assume that users will provide variables only as `JuMPArray`s when they could also naturally be `Array` or `Dict`s.

**Comment by jdlara-berkeley** [comment]
The reason to assume ```JuMPArray``` is that it allows directly creating the constraints using the index sets. It allows us to make sure the data going into the constraint is consistent with the JuMP variable and created variables with the same limit value.  This is useful for models with constraints such as $$x_t \ge a  \forall t$$

For instance, something that might look like this. 

```Julia 
function(m, var, data)
    (length(var.indexsets[1]) != length(data)) ? error("Length of time dimension inconsistent"): true
     set1 = var.axes[1]
   @constraintref Lim1[set1, set2]
   for i in set1
      for j in set2
          Lim1[i,j] = @constraint(m, x[i,j] >= data[i])
      end
   end
    end

```

Probably a better example of the earlier case would also require the constraints to be indexed. 

```Julia 
function createvariables(m,set)
   @variable(m, x[set])
end

function constraint1(m,x,set2)
   set1 = x.axes[1]
   @constraintref Lim1[set1, set2]
   for i in set1
      for j in set2
          Lim1[i,j] = @constraint(m, x[i,j] >= 10)
      end
   end
end

function constraint2(m,x,set2)
   set1 = x.axes[1]
   @constraintref Lim1[set1, set2]
   for i in set1
      for j in set2
         Lim1[i,j] = @constraint(m, x[i,j] >= 8)
      end
   end
end

m1 = Model()
createvariables(m1, ["a","b"])
#Then I can choose any constraint creation function I want or change set2 if I want. 
constraint2(m1,x,[1:10])
```

**Comment by mlubin** [comment]
Sure, if you have complete control and you know that the input will always be a `JuMPArray`, then it makes sense. To improve readability of the code, I'd recommend making this assumption explicit either in comments or in the type signatures.

**Comment by jdlara-berkeley** [comment]
I am trying the suggested syntax (assuming it is valid for any version of JuMP minding the change between ```indexsets``` and ```axes```) as follows: 

```Julia 
m = Model()
x = @variable(m, x[["a","b"], 1:24])
JuMP.JuMPArray(Array{ConstraintRef}(JuMP.size(x)), x.indexsets[1], x.indexsets[2])
```

And got this error 

```
MethodError: no method matching JuMP.JuMPArray(::Array{JuMP.ConstraintRef,2}, ::Array{String,1}, ::UnitRange{Int64})
Closest candidates are:
  JuMP.JuMPArray(::Array{T,N}, ::NT, ::Tuple{Vararg{Any,N}}, ::Dict{Symbol,Any}) where {T, N, NT} at /Users/jdlara/.julia/v0.6/JuMP/src/JuMPArray.jl:7
  JuMP.JuMPArray(::Array{T,N}, ::Tuple{Vararg{Any,N}}) where {T, N} at /Users/jdlara/.julia/v0.6/JuMP/src/JuMPArray.jl:14
```

**Comment by mlubin** [comment]
That should work on master, it calls this constructor:
https://github.com/JuliaOpt/JuMP.jl/blob/6fe7a4a256c4db928cc977e421ec2a8d81358130/src/JuMPArray.jl#L34

**Comment by jdlara-berkeley** [comment]
Thanks, I was testing with Julia v0.6.3 and JuMP 0.18. I will have to stick to @constraintref for 0.18 then and change it once we move to 0.19.

**Comment by jdlara-berkeley** [comment]
In master with ```Julia 0.7-alpha``` I get this error 

```Julia 
julia> x = @variable(m, x[["a","b"], 1:24])
┌ Warning: `shift!` is deprecated, use `popfirst!` instead.
│   caller = @variable(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at macros.jl:990
└ @ JuMP macros.jl:990
┌ Warning: `shift!` is deprecated, use `popfirst!` instead.
│   caller = buildrefsets(::Expr, ::Symbol) at macros.jl:24
└ @ JuMP macros.jl:24
2-dimensional JuMPArray{VariableRef,2,...} with index sets:
    Dimension 1, ["a", "b"]
    Dimension 2, 1:24
And data, a 2×24 Array{VariableRef,2}:
 x[a,1]  x[a,2]  x[a,3]  x[a,4]  …  x[a,21]  x[a,22]  x[a,23]  x[a,24]
 x[b,1]  x[b,2]  x[b,3]  x[b,4]     x[b,21]  x[b,22]  x[b,23]  x[b,24]

julia> JuMP.JuMPArray(Array{ConstraintRef}(JuMP.size(x)), x.indexsets[1], x.indexsets[2])
ERROR: JuMPArray does not define size().
Stacktrace:
 [1] error at ./error.jl:33 [inlined]
 [2] size(::JuMPArray{VariableRef,2,Tuple{Array{String,1},UnitRange{Int64}},Tuple{Dict{String,Int64},Dict{Int64,Int64}}}) at /Users/jdlara/.julia/dev/JuMP/src/JuMPArray.jl:92
 [3] top-level scope
```

**Comment by mlubin** [comment]
See https://github.com/JuliaOpt/JuMP.jl/issues/1294. Also, JuMP is not working on 0.7-alpha yet (https://github.com/JuliaOpt/JuMP.jl/issues/1177).

**Comment by jdlara-berkeley** [comment]
The option in #1294  works pretty good with the proposed syntax that can substitute the old ```@constraintref``` effectively. This could be later addressed in the documentation for programatic creation of constraints.

**Comment by odow** [comment]
I'm not really sure what the outcome of this is. If I understand correctly, you propose that in order to close this we need to document:
 - that `@constraintref` is being removed in JuMP 0.19
 - that `@constraintref C[set1, set1]` is equivalent to 
    `C = JuMPArray(Array{ConstraintRef}(undef, length(set1), length(set2)), set1, set2)`

This seems sub-optimal though since `ConstraintRef` is an abstract type. Why can't you do the second option below?
```julia
function constraint1(m,x,set2)
   set1 = x.axes[1]
   @constraintref Lim1[set1, set2]
   for i in set1
      for j in set2
          Lim1[i,j] = @constraint(m, x[i,j] >= 10)
      end
   end
end

function constraint1(m,x,set2)
   set1 = x.axes[1]
   @constraint(m, Lim1[i=set1, j=set2], x[i,j] >= 10)
end
```
I guess I don't really understand the use-case for `@constraintref`...

**Comment by jd-lara** [comment]
@odow if I have data in a dictionary or other containers indexed with labels or keys, and you want to create constraints programmatically with anonymous constraints it is useful to pre-allocate the JuMP container.

**Comment by mlubin** [comment]
What's missing is a macro that lets you define a JuMP container that holds a user-provided type, e.g.,
```julia
ref_container = JuMP.@container ConstraintRef [1:N, set2, set3]
```

**Comment by odow** [comment]
Can't this be achieved as
```julia
function JuMPContainer(::Type{T}, args...) where T
    return JuMPArray(Array{T}(undef, length.(args)...), args...)
end
function JuMPContainer(::Type{T}, args::UnitRange...) where T
    if all(first.(args) .== 1)
        return Array{T}(undef, length.(args)...)
    else
        return JuMPArray(Array{T}(undef, length.(args)...), args...)
    end
end

julia> JuMPContainer(JuMP.VariableRef, 2:3, [:a, :b])
2-dimensional JuMPArray{VariableRef,2,...} with index sets:
    Dimension 1, 2:3
    Dimension 2, Symbol[:a, :b]
And data, a 2×2 Array{VariableRef,2}:
 #undef  #undef
 #undef  #undef

julia> JuMPContainer(JuMP.Variableref, 1:2)
2-element Array{JuMP.VariableRef,1}
 #undef
 #undef
```

Not sure what to do about dictionaries.

**Comment by mlubin** [comment]
Something like that, yes. I also don't know what to do with dictionaries because we can't pre-allocate keys in a dictionary without values to assign to them. So maybe the macro idea doesn't work at all.

**Comment by odow** [comment]
I don't think the macro is the way to go. The functions above handle most needs. Users can construct the `Dict`s manually if they need them. We can always revisit at a later date.

**Comment by joaquimg** [comment]
We could have a manual section explaining how to allocate an array to hold constraints and to initialize a dict to hold constraints also
