### ISSUE TITLE
The Doc's reference SemiCont variables, but they do not seem to available implemented anymore?

### ISSUE THREAD

**Issue by oxinabox** [JuliaOpt/JuMP.jl#1311]
Mentions in the docs at 
http://www.juliaopt.org/JuMP.jl/0.18/refvariable.html#constructors

(Ctrl+f for `SemiCont`)

But running
```julia
using Cbc
using JuMP
m = Model(solver=CbcSolver())
@variable(m, x, lowerbound=1)
@variable(m, y, lowerbound=1)
@variable(m, z, lowerbound=1)

setcategory(x, :SemiCont)
@constraint(m, 20 <= x+y+z <= 30)
@objective(m, Min, x+y+z)
solve(m)
```

gives

**Error:** Unrecognized variable type SemiCont

**Comment by blegat** [comment]
SemiCont is supported by JuMP but not by Cbc apparently.
There error is sent from here:
https://github.com/JuliaOpt/Cbc.jl/blob/b3fb9d8f891cd05af268816016b974739860d62c/src/CbcSolverInterface.jl#L136-L152
Other solvers such as Gurobi support it:
https://github.com/JuliaOpt/Gurobi.jl/blob/acc523aea7f7d98e35e7b1ae68033e9a02aed213/src/GurobiSolverInterface.jl#L514

**Comment by oxinabox** [comment]
Ah it would nice if it was listed on
http://www.juliaopt.org/JuMP.jl/0.18/installation.html#getting-solvers
like LP and MIP is

**Comment by odow** [comment]
With the new version of JuMP, it isn't going to be practical to list every type of function and set supported by solvers.

Instead, we now offer a much nicer error message at the JuMP level.
```julia
julia> model = JuMP.direct_model(Gurobi.Optimizer())
A JuMP Model

julia> @variable(model, x)
x

julia> @constraint(model, 1.0 * x in MOI.Interval(1, 2))
ERROR: Constraints of type MathOptInterface.ScalarAffineFunction{Float64}-in-MathOptInterface.Interval{Float64} are not supported by the solver, try using `bridge_constraints=true` in the `JuMP.Model` constructor if you believe the constraint can be reformulated to constraints supported by the solver.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] add_constraint(::Model, ::JuMP.ScalarConstraint{JuMP.GenericAffExpr{Float64,VariableRef},MathOptInterface.Interval{Float64}}, ::String) at C:\Users\Oscar\.julia\dev\JuMP\src\constraints.jl:234
 [3] top-level scope at C:\Users\Oscar\.julia\dev\JuMP\src\macros.jl:516
```

Is there anything here that is still actionable?

**Comment by mlubin** [comment]
There may be ways to improve how solver capabilities are listed/reported issue in JuMP/MOI, but we'll deal with them as they come up. This issue is stale because variable categories don't really exist anymore in JuMP. (See the [`Semicontinuous` set](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference.html#MathOptInterface.Semicontinuous).)
