### ISSUE TITLE
Question: Best Solver for JuMP for minimizing an energy function including traces/matrices/complex matrices

### ISSUE THREAD

**Issue by CPPhysics** [JuliaOpt/JuMP.jl#1312]
My question is in the title. I am new to JuMP and Julia optimization and wondering if anyone can point me in the right direction. I am currently thinking of using Ipopt

**Comment by odow** [comment]
Hi @CPPhysics, 

Did you take the time to read the message when posting a [new issue](https://github.com/JuliaOpt/JuMP.jl/issues/new)?

You should post these sorts of questions over on the Discourse site: https://discourse.julialang.org/c/domain/opt. We try to use the JuMP issues for bug reports and feature requests. More people read the discourse site who might be able to help you.

My advice is just to formulate the problem and then try some different solvers. One great thing about JuMP is that it is very easy to change the solver.

Good luck, and I hope you enjoy using JuMP!

**Comment by CPPhysics** [comment]
Ah okay, thank you for the clarification, I apologize.
