### ISSUE TITLE
Feature Request: sensitivity summary for LPs

### ISSUE THREAD

**Issue by lkapelevich** [JuliaOpt/JuMP.jl#1332]
It would be convenient to have an interface to get bounds on the RHS / objective vector where the current duals/reduced costs are valid.

**Comment by mlubin** [comment]
This is a very consistent request for people using JuMP for teaching, so let's just implement it (like we did for `shadow_price`).

CC @EdvinAblad

**Comment by EdvinAblad** [comment]
Agree,  this should not be too cumbersome to do.
That is if we assume that ConstraintBasisStatus is implemented by the solver. (JuliaOpt/MathOptInterface#655)

However, if ConstraintBasisStatus is unsupported/not implemented by the solver how should this be handled?
1. warn/throw error
2. implement a fallback (easy for non-degenerate solutions, brute-force(?) for degenerate ones)

I vote for option 1. it encourage the solver to implement a rather simple feature and do not require a potentially slow/unstable fallback method.

(To my knowledge the basis is needed for the sensitivity analysis of changes in rhs and cost of active constraints and basic variables, respectively. i.e., if not another LP is to be solved..., enlighten me if I'm wrong here=) )

**Comment by mlubin** [comment]
> However, if ConstraintBasisStatus is unsupported/not implemented by the solver how should this be handled?

Throw an error.

**Comment by mlubin** [comment]
This was implemented in https://github.com/JuliaOpt/JuMP.jl/pull/1917.
