### ISSUE TITLE
Heuristic callback test

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#134]
I don't think the heuristic callback test is testing anything, at least for CPLEX and Gurobi, where the model is solved to optimality in presolve (which makes sense, since heuristic callbacks aren't yet implemented in CPLEX...). I'm not sure about GLPK since there is no log dump to STDOUT.

**Comment by mlubin** [comment]
Gurobi's API now allows you to check if a heuristic solution was accepted or not: https://www.gurobi.com/documentation/7.0/refman/c_grbcbsolution.html

**Comment by mlubin** [comment]
Closing since callbacks won't be in JuMP anymore. I think the move towards solver-specific callbacks will make issues like this more testable (e.g., with Gurobi you can do it directly).
