### ISSUE TITLE
How to disable assertion while using Cbc in JuMP

### ISSUE THREAD

**Issue by ycliao** [JuliaOpt/JuMP.jl#1341]
I got "Assertion failed!" while using Cbc solver for a scheduling problem in Julia on my windows machine. Before I hit this message from Cbc, it seemed fine while I used the same model with different data sets. 

I realized that this may be caused by the Cbc solver with assertions enabled and only happens on window platform. I try to find a way to disable the assertion but don't know how. 

So, is there any way to disable assertions of Cbc in JuMP or I have to compile Cbc from the source? 

Thanks for your help.

**Comment by odow** [comment]
Hi @ycliao,

Thanks for your issue. Did you take the time to read the information before posting a new issue? (You can see it [here](https://github.com/JuliaOpt/JuMP.jl/issues/new).) In particular:

> If you're experiencing a bug that is solver-specific (e.g., it only happens when you use Gurobi), the issue is best raised at the relevant solver-wrapper repository

If you go over to the Cbc repository (https://github.com/JuliaOpt/Cbc.jl), you'll see there are similar issues: https://github.com/JuliaOpt/Cbc.jl/issues/30

To disable the assertions, you will need to rebuild Cbc from source with the appropriate settings.

I'm going to close this as it is not JuMP related. In the future, you should post questions like this to the [discourse](https://discourse.julialang.org/) forum.
