### ISSUE TITLE
Excessive nonlinear model (with long expressions) loading time

### ISSUE THREAD

**Issue by jac0320** [JuliaOpt/JuMP.jl#1355]
With nonlinear models that have long expressions, the JuMP model loading time can scale excessively long.

For example, with this instance [elec25.jl](https://github.com/lanl-ansi/MINLPLibJuMP.jl/blob/master/instances/global/elec25.jl), a local test takes about 2.34 seconds. With a larger instance [elec50.jl](https://github.com/lanl-ansi/MINLPLibJuMP.jl/blob/master/instances/global/elec50.jl), the time to load is roughly 10 seconds. Then, it scales pretty badly for [elec100.jl](https://github.com/lanl-ansi/MINLPLibJuMP.jl/blob/master/instances/global/elec100.jl), which takes 140 seconds, and [elec200.jl](https://github.com/lanl-ansi/MINLPLibJuMP.jl/blob/master/instances/global/elec200.jl), which takes 1861 seconds. This is one example.

More example can be found in [this documentation](https://lanl-ansi.github.io/MINLPLibJuMP.jl/latest/minlp2.html) under the column under "LT" . The instances are converted using .gams files collected from the famous [MINLPLib](http://www.minlplib.org/) library. The conversion follows line-by-line parsing of the gams file.

This issue can be dependent on how the model is implemented or how JuMP handles the nonlinear expressions. I'd love to know which part of JuMP to focus on to resolve this issue OR if there exist a better way to implement the model with long symbolic expressions (may be in loops, but clearly that is not the case with the line-by-line parsing).

**Comment by mlubin** [comment]
TODO before closing this issue: add a warning in `@NL...` macros if the expression looks too large.

**Comment by jac0320** [comment]
Thanks! This method can improve the general loading performance of basically all instances from [MINLPLibJuMP.jl](https://github.com/lanl-ansi/MINLPLibJuMP.jl). 

What be a good definition of "looks too large"? length of the string? Or would it be a good idea if the splice can be applied automatically (or enforced)?

**Comment by mlubin** [comment]
I'd probably set the limit at 500-1000 terms in the expression. It's tricky to automatically do this transformation because it doesn't apply if there's a `sum()` present.
