### ISSUE TITLE
Issue with JuMP.fix for variable array

### ISSUE THREAD

**Issue by trivedymk** [JuliaOpt/JuMP.jl#1356]
Hi folks.

I have an MCP optimisation model (using the Complementarity package and PATHSolver) I am trying to solve this problem with variables, declared in the following way

```julia
#Contract sales rate (vol/day)
@variable(m, s_contract[n in nodes, nn in nodes, i in suppliers, s in seasons, t in timeperiods] >=0)
#Spot sales rate (vol/day)                                                          
@variable(m, s_spot[n in nodes, nn in nodes, i in suppliers, s in seasons, t in timeperiods] >=0)
```

Certain variable values need to be fixed so I have been trying to use the JuMP.fix function to set these, but I am running into an error.

I am using this loop to try and fix the values
```julia
for i in suppliers, s in seasons, t in timeperiods
    JuMP.fix(s_contract["EU","UK",i,s,t],0)
    JuMP.fix(s_spot["EU","UK",i,s,t],0)
end
```

This runs on its own, but when I then try to solve the model I get the following error message (on the line solveMCP(m)
```
>  "setvalue for fixed variables is no longer supported. Use JuMP.fix instead.".
```
I'm not using setvalue in the code anywhere... Could it be that this is part of the solver and so once I fix these values with JuMP.fix it's not allowing the array to be changed with setvalue in the solver anymore? I'm quite new to this so my understanding it's great. Is there another way I can fix these particular values of s_contract and s_spot?

**Comment by blegat** [comment]
It seems to be an issue of [Complementarity](https://github.com/chkwon/Complementarity.jl) which uses `setvalue`

https://github.com/chkwon/Complementarity.jl/blob/9f2405d969fe83b2d316e5a8354434c264e611cb/src/mcp.jl#L145

Replacing this `setvalue` call by `JuMP.fix` in [Complementarity](https://github.com/chkwon/Complementarity.jl) should fix the issue. You should probably report it there.

cc @chkwon

**Comment by mlubin** [comment]
Closing since the discussion ended and there's no evidence of a JuMP issue. Feel free to reopen or create a new issue if appropriate.
