### ISSUE TITLE
"sum" with vector argument in nonlinear expression doesn't work

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#1357]
On JuMP 0.18.2 (and also on master) and Julia 0.6.3 (I did not try Julia 0.7), I get the following issue when trying to use `sum` with a vector argument when building an NLexpr:
```
julia> @NLconstraint M log(sum(exp, x)) <= 1
ERROR: Unrecognized function "sum" used in nonlinear expression.
Stacktrace:
 [1] error(::String) at ./error.jl:21
```
for example, on the following simple model:
```
M = Model()
@variable M x[1:3]
@NLconstraint M log(sum(exp, x)) <= 1
@NLconstraint M sum(x.^2) <= 1
@NLconstraint M sum(x) <= 1
```
each of those constraints triggers the same error. Ofc it works when I use generator syntax, but in many cases that is not the most convenient way to write. Given that sum works on vectors in affine/quadratic expressions, it seems like it should in nonlinear ones too too. If that can't be fixed, perhaps the error message should say "sum can't be called on an array; use generator syntax instead".

**Comment by mlubin** [comment]
This falls under the vectorized syntax that we won't support until JuMP's NL code is rewritten. But I agree that we could improve the error message in this case.
