### ISSUE TITLE
The problem of  how to multiply three matrix variants in JuMP

### ISSUE THREAD

**Issue by YinghuiN** [JuliaOpt/JuMP.jl#1368]
Hello, everyone, recently I came into a problem when using Julia. I have defined three variables `M`, `N`, `P1` listed below. And I need to multiply them all. `V` will be what I want in my following NLconstraint. 
```julia
using JuMP, AmplNLWriter, CoinOptServices
m = Model(solver=AmplNLSolver(CoinOptServices.couenne))
@variable(m, M[1:20, 1:23])
@variable(m, N[1:23])
@variable(m, P1[1:23], Int)
V1=P1.*N
V=M*V1
```
But when I run the code, Julia gives me an error like this.
![p1](https://user-images.githubusercontent.com/39766265/42383817-1d892758-8141-11e8-89f8-1a2b98d72ffe.PNG)

And then I tried to use @NLexpression 
```julia
using JuMP, AmplNLWriter, CoinOptServices
m = Model(solver=AmplNLSolver(CoinOptServices.couenne))
@variable(m, M[1:20, 1:23])
@variable(m, N[1:23])
@variable(m, P1[1:23], Int)

@NLexpression(m, V, M*(P1.*N))
```
But it still does not work and shows error like this:

![p2](https://user-images.githubusercontent.com/39766265/42384042-a17ffb22-8141-11e8-9363-a1b39dcdcd66.PNG)

And my question is how could I do this three matrix variables multiply calculation in Julia? Thanks in advance.

**Comment by odow** [comment]
Hi @YinghuiN,

The documentation for the [nonlinear interface to JuMP](http://www.juliaopt.org/JuMP.jl/0.18/nlp.html) contains the following sentence:
> All expressions must be simple scalar operations.

So you can't use the broadcasted notation. Instead, you must unroll the loops. 

In the future, you should post usage questions like this to [discourse](https://discourse.julialang.org/c/domain/opt). It has many more people who may be able to help you.

Thanks for using JuMP!

**Comment by Xx-fractale-xX** [comment]
Hi @YinghuiN,

Under this form, it works:
```julia
@variable(m, M[1:20, 1:23])
@variable(m, N[1:23])
@variable(m, P1[1:23], Int)
@NLexpression(m, V[i=1:20], sum(M[i,j] * P1[j] * N[j] for j=1:23))
```
