### ISSUE TITLE
value missing for constraints

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1394]
Any reason we don't define something like:
```julia
value(cref::ConstraintRef) = MOI.get(cref.m, MOI.ConstraintPrimal(), index(cref))
```
or it just hasn't been done yet ?

**Comment by blegat** [comment]
Should we do this for JuMP-0.19 ?

**Comment by blegat** [comment]
Are you ok with `value` for the name ?

**Comment by blegat** [comment]
One other name could be `slack_value`. Since the constraints have the form `f(x) in set`, we could say that this is the value of the slack where `f(x) = slack` and `slack in set`.
This would make it clearer that this is the value `x + 2y` in `x + 2y in MOI.LessThan(3)` while `JuMP.value` may be ambiguous.
What do you think ?

**Comment by mlubin** [comment]
> f(x) = slack and slack in set

That definition for `slack` isn't consistent with other uses like `Ax - b + slack = 0`, `slack in cone` so it might be more confusing than helpful. `value` seems fine. Users will have to understand the MOI representation of constraints.
