### ISSUE TITLE
solve(m, IpoptOptions=[]) throws Unrecognized keyword arguments: IpoptOptions

### ISSUE THREAD

**Issue by kharazity** [JuliaOpt/JuMP.jl#1414]
I have the following code:
solve(m, IpoptOptions=["tol",1e-10]);
that throws the errors 
"ERROR: LoadError: Unrecognized keyword arguments: IpoptOptions"

Any reason this should be failing? Thanks.

**Comment by blegat** [comment]
Where have you read that `IpoptOptions` was a supported syntax ? Note that these kind of questions are more suited for [discourse](https://discourse.julialang.org/) ;)

**Comment by kharazity** [comment]
I realize now that the website I was on was for an older version of JuMP.
Is there any support for options in Ipopt from Julia/JuMP?

**Comment by blegat** [comment]
Yes, you do `Model(solver=IpoptSolver(tol=1e-10))`

**Comment by kharazity** [comment]
Thanks, that's it.

**Comment by IainNZ** [comment]
@kharazity what website was it?

**Comment by mlubin** [comment]
This breaking change was announced in the release notes for JuMP 0.6 four years ago.
