### ISSUE TITLE
eventual refactoring of macros using MacroTools.jl

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/JuMP.jl#1433]
As I've worked on the 0.18 update for 1.0 I became somewhat familiar with the JuMP macro code (both in 0.18 and in master).  JuMP probably has some of the most complicated macro code of anyexisting Julia package.  This is only natural as JuMP is essentially a domain specific language.  As more macro features are added this code will get more and more difficult to manage.  Perhaps it's just me but I find macro code to be far more difficult to develop than non-metaprogramming related code, not least because stack traces tend to be of somewhat inferior quality and special tools such as `@macroexpand` are needed even for simple things like determining what code actually executed.

I'd like to suggest that in the future JuMP move toward using [MacroTools.jl](https://github.com/MikeInnes/MacroTools.jl).  This package drastically simplifies metaprogramming.  I have argued many times that this package desperately needs to be in stdlib, but unfortunately that hasn't happened yet.  Another advantage of using MacroTools is that it moves most of the dependency on Julia's AST out of JuMP itself and into that package.

Obviously since JuMP has a large amount of complicated macro code it would be a daunting task to just sit down and rewrite it all at once.  I'd like to suggest that MacroTools first be introduced to some of the "leaf" functions such as `_localvar` or `extract_kwargs` (likely some of these functions can ultimately be eliminated completely).  My hope is that gradually over time as `macros.jl` becomes shorter it will become more apparent how to refactor the workhorse parts of the existing code.

I'd like to make a PR at some point to get this process going, but of course before I spend time working on it I'd like to see whether there is any receptiveness to this idea, and to hear suggestions others may have about how it might be best to simplify the macro code (if indeed you guys are open to that idea).

Cheers.

**Comment by mlubin** [comment]
I agree in principle that it would be nice to abstract away some of the dirty details in metaprogramming, and I also agree that the macros need a complete rewrite at some point (the code structure hasn't changed in a very long time). However, every dependency of JuMP makes it harder to update for breaking changes and more likely that things will break beyond our control. I have specific concerns about MacroTools that make me question this direction:

- IIRC MacroTools was broken for most of the 0.7 testing period. Which is fine, but would make it harder for us to keep JuMP running after future breaking changes.
- MacroTools doesn't have code coverage set up (https://github.com/MikeInnes/MacroTools.jl/pull/90).
- There were two recent sloppy changes that broke MacroTools on 0.6 in certain ways without triggering CI failures (see https://github.com/MikeInnes/MacroTools.jl/pull/91, https://github.com/MikeInnes/MacroTools.jl/pull/89).

**Comment by IainNZ** [comment]
I'm receptive to this idea, indeed, had the same thought when fixing #1428 .

I'd weaken it slightly though, but maybe due to my unfamiliarity with MacroTools - I'd suggest a more slow process of extracting out components and testing those directly. Indeed, over time this is the way this file has trended. I think we can just iteratively refactor this way.

**Comment by ExpandingMan** [comment]
Fair enough.  These are some of the reasons that a few times I begged for MacroTools in stdlib, but again, that's just not reality at the moment.

Two comments in response:
- I certainly understand your reluctance to add dependencies, but I definitely think a macro helper (whether that be MacroTools or something else) is so important that it definitely seems to be a case that warrants a dependency.
- Speaking for myself, in the long run I think that even if JuMP maintainers wound up having to maintain MacroTools themselves, it would actually be *easier* than maintaining overly complex macro code in JuMP itself.  The amount of code in macrotools is tiny compared to what's in JuMP.  Of course, I'm a lot less familiar with the JuMP macros than you guys, so you may not share this opinion, but I suspect you'd wind up with more contributions overall (to both packages) if you went the MacroTools route.

**Comment by IainNZ** [comment]
Theres definitely merit to the ideas there. How about pulling things out into JuMP/src/macro_lib.jl that are not really particularly JuMP-ish and seeing what that ends up being?

**Comment by mlubin** [comment]
I would be fine with building up a library of macro helper functions as we find useful. The only reason I can think of for not doing this in the JuMP.jl repo is for license reasons since code here is under MPL unlike most of the Julia ecosystem. If we plan on these to be useful outside of JuMP then we might want to start off in different repository.

**Comment by ExpandingMan** [comment]
At the risk of seeming overly argumentative, if you're going to go that route why not just fork MacroTools?  Really the power in that package is `@capture` and `postwalk` much of which lies in two files in about 200 lines of code, you won't get the same mileage out of anything short of a pattern matching ability.  JuMP is something like half macros and macro related code.

See `wc -l`:
(JuMP)
```
    360 affexpr.jl
    111 containers.jl
wc: Derivatives: Is a directory
      0 Derivatives
    292 JuMPArray.jl
    730 JuMP.jl
   1545 macros.jl
   1120 nlp.jl
    708 operators.jl
     68 optimizerinterface.jl
    512 parseexpr.jl
    262 parsenlp.jl
    406 print.jl
    254 quadexpr.jl
     74 sd.jl
     19 sets.jl
     43 utils.jl
    539 variables.jl
   7043 total
```

(MacroTools)
```
     80 macro.jl
     28 MacroTools.jl
    114 match.jl
     67 structdef.jl
     29 types.jl
     24 union.jl
    402 utils.jl
    744 total
```
And it would even be possible to avoid using most of what's in `utils.jl`.

The `macros.jl` file alone is bigger than the entire MacroTools repo.

**Comment by blegat** [comment]
We have made quite a few changes to the macros in JuMP v0.19 to try to make the code more readable and also make the macro extensible but I agree that there is still room for improvement.
For MacroTools, it remains to be determined how much we can use from it. If I understand correctly, `postwalk` is one line: https://github.com/MikeInnes/MacroTools.jl/blob/7274dffde8a5edafa388ee364255a7c0f53a6419/src/utils.jl#L95 so adding MacroTools as a dependency seems overkill. However trying to see if we can create a function similar to `postwalk` in JuMP might help refactoring into more readable code that avoids the cryptic `.head` and `.args` everywhere.

**Comment by mlubin** [comment]
> if you're going to go that route why not just fork MacroTools? 

Forking is somewhat antisocial. The first choice, if we decide that we need MacroTools, would be to address the outstanding issues via PRs and make the code base reliable enough for JuMP to depend on. That takes a decent amount of effort, however. I don't have a good understanding of what the macros would look like if rewritten using MacroTools or some other collection of helper functions. Some brainstorming and examples would help.

**Comment by mlubin** [comment]
This was a useful discussion but I don't think we need to leave the issue open. Yes, it would be nice to refactor the macros. When someone is ready to put the time into doing it, we can discuss the design more.
