### ISSUE TITLE
condition on variables in constraints

### ISSUE THREAD

**Issue by giadasp** [JuliaOpt/JuMP.jl#1452]
Dear JuMP developers,
I have an issue with my code.
I'm trying to write a constraint in a MILP model in which I want to add a condition based on the values of a variable (`x`) but the resulting values do not fulfill this constraint so I guess there is a problem in the condition since I didn't find a similar thing in the documentation. This is part of the code:

```julia
F=12 
I=10  
G=4  
Ind=[1,2,3,4]
Indtwo=[2,3,4,5]
m=Model(solver=GLPKSolverMIP())
@variable(m, x[i=1:I,f=1:F] , Bin)
#[...] other constrains on x [...]
@variable(m, y[g=1:G] >=0, Int )
@constraint(m, y[g]<=ol_max[g])
#here there is the condition in the constraint:
for g in 1:G
	@constraint(m,  [i=1:I ; x[i,Ind[g]]+x[i,Indtwo[g]]==2.0], y[g]>=sum(x[i,Ind[g]] for i=1:I))
end
solve(m)
```

Can you tell me if there is something wrong and if it's possible to add this type of conditions?
Thanks

Giada

**Comment by odow** [comment]
> Can you tell me if there is something wrong and if it's possible to add this type of conditions?

You cannot use JuMP variables inside the conditional. Instead, you should look at using a package like [ConditionalJuMP.jl](https://github.com/rdeits/ConditionalJuMP.jl).

In the future, please post usage questions like this on our [discourse site](https://discourse.julialang.org/c/domain/opt). Your question is likely to be answered quicker, and we try to reserve the Github issues for bug reports and feature requests.

**Comment by mlubin** [comment]
Closing since the discussion ended and there's no evidence of a JuMP issue. Feel free to reopen or create a new issue if appropriate.
