### ISSUE TITLE
Add set_objective_sense to JuMP master

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1459]
Migrate `setobjectivesense` to `set_objective_sense` for the next release of JuMP.

**Comment by IainNZ** [comment]
That function doesn't exist on master right now?

**Comment by mlubin** [comment]
While we're at it we should move away from symbols to represent the objective sense (it's bad practice). We should either use the MOI objective sense enum or create a JuMP mirror of it.
