### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/JuMP.jl#1462]
Tests pass with JuMP master on Julia 1.0, but not with JuMP 0.18.2. Time to tag a new version?

**Comment by mlubin** [comment]
JuMP `master` is JuMP/MOI which is certainly not ready for release. Do you mean tagging `release-0.18` as 0.18.3? That branch is semi-working but isn't passing tests on 1.0.

**Comment by tkoolen** [comment]
Ah, I was confused, my bad.
