### ISSUE TITLE
Add Support for PSDConeSquare

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1466]
Add support for non-triangular PDS constraints like the following,
```
@constraint(model, X in PSDConeSquare())
```

**Comment by blegat** [comment]
The syntax for the  `MOI.PositiveSemidefiniteConeSquare` is
```julia
@constraint(model, X in PSDCone())
```
If the matrix is known to be symmetric then
```julia
@constraint(model, Symmetric(X) in PSDCone())
```
can be used for the `MOI.PositiveSemidefiniteConeTriangle` cone.

**Comment by ccoffrin** [comment]
In the current JuMP master the following constraint,
```
@constraint(model, X in PSDCone())
```
is giving me the following error
```
ERROR: AssertionError: issymmetric(x)
Stacktrace:
 [1] build_constraint(::Function, ::Array{JuMP.GenericAffExpr{Float64,JuMP.VariableRef},2}, ::JuMP.PSDCone) at home/.julia/v0.6/JuMP/src/sd.jl:69
 [2] macro expansion at home/.julia/v0.6/JuMP/src/macros.jl:479 [inlined]
...
```

**Comment by blegat** [comment]
Should be fixed by https://github.com/JuliaOpt/JuMP.jl/pull/1468
