### ISSUE TITLE
NonlinearParameters still use setvalue and getvalue

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1479]
Maybe these should stay as is (with renaming for style) because parameters don't have start or result values?

**Comment by blegat** [comment]
For comparison:

* ParameterJuMP uses `JuMP.result_value` (sounds weird indeed) and `ParameterJuMP.setvalue!`:
https://github.com/JuliaStochOpt/ParameterJuMP.jl/blob/4dc38ecd73ef4942b406d74b24276b61291898ef/src/ParameterJuMP.jl#L141-L149
If JuMP define `JuMP.set_value` and `JuMP.get_value`, we might use that instead.
cc @joaquimg 
* In Parametron, the value is set by calling the parameter like a function and I don't see any function to get the value
https://github.com/tkoolen/Parametron.jl/blob/44982db6b26f4a639b0d25467af5e8303eb8fa82/src/parameter.jl
cc @tkoolen

**Comment by mlubin** [comment]
I adopted `JuMP.set_value` and `JuMP.value` in #1481

**Comment by blegat** [comment]
The names look good, I am not a big fan the the `get` prefix

**Comment by tkoolen** [comment]
@blegat, in Parametron, the call overloads return the value, and if a `Parameter` is 'dirty' (hasn't been updated since the last call to `setdirty!`), the parameter value is updated automatically using the stored function `f`.

**Comment by joaquimg** [comment]
@blegat i like value and setvalue for parameterjump
