### ISSUE TITLE
0.19 upgrading guide

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1489]
We have an empty upgrading guide at http://www.juliaopt.org/JuMP.jl/latest/updating.html. Should we try to fill this in or drop it for now and focus instead on writing a good NEWS and filling in the existing gaps in the 0.19 docs?

CC @ccoffrin who's been upgrading a large code base

**Comment by ccoffrin** [comment]
So far, my upgrade process has been relatively painless / intuitive; so I would recommend focusing on the other tasks.  The most valuable documentation for me was canonical examples of different types of models, [here](https://github.com/JuliaOpt/JuMP.jl/blob/master/test/generate_and_solve.jl).

Also there is a good chance I could contribute on this updating doc in the next 2-4 weeks.

**Comment by mlubin** [comment]
Putting this on the 0.19 milestone. We should either delete the "updating guide" section in the docs or fill it in.

**Comment by ccoffrin** [comment]
Depending on the timelines, I am still aspiring to contribute to this.

**Comment by mlubin** [comment]
My best guess for the 0.19 release is about a month from now.

**Comment by odow** [comment]
I vote for filling in a good news:
https://github.com/JuliaOpt/JuMP.jl/pull/1758
https://github.com/JuliaOpt/JuMP.jl/pull/1759
