### ISSUE TITLE
JuMP model object clean after solving for memory usage issue

### ISSUE THREAD

**Issue by Reza-rn** [JuliaOpt/JuMP.jl#1494]
Hi

I am using JuMP model calling CPLEX 12.6 solver for my problem. My problem is like that I am running a loop and at each iteration, I am solving a convex optimization problem by calling CPLEX in JuMP. At each iteration I am making new JuMP object.
However, after 80 iterations, I face error 1001:out of memory. It seems memory usage is increased at each iteration of my solution and I need to kind of close or clean the JuMP object at each iteration after solving and saving results. Can you help me how can I clean or close my model at each iteration using ways in JuMP like other programs as `Model.end` or `Model.clean`?

Thanks.

**Comment by odow** [comment]
Cross refs: 
- https://github.com/JuliaOpt/CPLEX.jl/issues/185
- https://discourse.julialang.org/t/memory-usage-in-jump-model/15475

Closing as this is not a JuMP issue and OP found a resolution in https://github.com/JuliaOpt/CPLEX.jl/issues/185.
