### ISSUE TITLE
Hygiene

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1496]
While fixing JuMP v0.18 hygiene test, I noticed that JuMP master does not pass this test either:
```julia
julia> Jimport JuMP
julia> Jmymod = JuMP.Model()
julia> Jmysense = :Min
julia> JuMP.@variable(mymod, x >= 0)
julia> JuMP.@variable(mymod, y[i=r] <= i)
julia> JuMP.@constraint(mymod, x + sum( j*y[j] for j=r ) <= 1)
ERROR: UndefVarError: ##364 not defined
```
This is because [when assigning a global variable in local scope, it creates a new variable](https://docs.julialang.org/en/v1.0.0/manual/variables-and-scoping/#Local-Scope-1).
In this example, `##364` is introduced in global scope in the REPL and then it both modified and used in a for loop. Since it is modified, Julia considers it as a new variable and hence it is used before being set which explains the error.
The simplest fix seems to be to enclose everything in a `let` block to ensure that JuMP macros are run in local scope and never in global scope.

**Comment by odow** [comment]
This scoping change is so sad
