### ISSUE TITLE
Variable name in model export

### ISSUE THREAD

**Issue by gdragotto** [JuliaOpt/JuMP.jl#1512]
Hey community,

I am trying to set the name of the variable in JuliaOPT, in particular, to rename the variables when the model is exported (eg. with CPLEX).
This feature would be very useful in order to write the model with Julia, solve it on different environments, and then take back the results.

I would suggest implementing a method to change the variable name in the exported model. Up to now, there is nothing such that.

Thanks!

**Comment by odow** [comment]
Please see the "basename" keyword in the [documentation](http://www.juliaopt.org/JuMP.jl/0.18/refvariable.html).

See also: https://github.com/JuliaOpt/JuMP.jl/blob/f0bf1875ec132785a104b47d173b466b28f62a63/src/writers.jl#L191

If you use `genericnames=false`, then the `basename` will be used as the name in the LP file.

If you use CPLEX to write the model, the current version of JuMP doesn't have the ability to pass variable names to CPLEX. The new version will.

You may also be interested in https://github.com/odow/MathOptFormat.jl

**Comment by odow** [comment]
Can we close this? JuMP 0.18 provides a mechanism for writing models using the string names.

Model reading and writing will not happen at the JuMP level, but will take place via packages such as MathOptFormat. The task that needs to happen in JuMP to support reading is covered by https://github.com/JuliaOpt/JuMP.jl/issues/1184.

**Comment by mlubin** [comment]
Yes, I don't see any action items for us to do here that aren't covered by existing issues. JuMP/MOI provides much improved handling of variable names, and we can now pass them directly to the solver.
