### ISSUE TITLE
Feature Request: printStats(model)

### ISSUE THREAD

**Issue by vgupta1** [JuliaOpt/JuMP.jl#152]
Gurobi's python interface has a neat function

``` python
model.printStats()
```

which outputs a little block of information like the number of variables, number of constraints, number of non-zeros, and maximum and minimum coefficients in the matrix of the LP.  It can be useful for debugging or checking numerical stability of a problem.  It'd be nice to have similar functionality in JuMP

**Comment by mlubin** [comment]
Open to contributions, but I don't see a need to leave this issue open after 2+ years of inactivity.
