### ISSUE TITLE
Reorder function declarations in JuMPArray.jl to improve compatibility with PackageCompiler

### ISSUE THREAD

**Issue by jwveysey** [JuliaOpt/JuMP.jl#1531]
As described in [this thread](https://discourse.julialang.org/t/change-to-improve-jump-compatibility-with-packagecompiler/15944) on Discourse, I've found the order of function declarations in JuMPArray.jl (release 0.18) creates an incompatibility with PackageCompiler. The problem is there are @generated functions (Base.getindex and Base.setindex!) that reference a regular function (_to_cartesian) before it is declared. This causes an error when using PackageCompiler.

Moving the declaration statements to the end of the JuMPArray.jl file fixes the problem.

**Comment by blegat** [comment]
It would be nice to add a check that JuMP compiles correctly with PackageCompiler in a Travis build stage like the one created by @odow for documentation in https://github.com/JuliaOpt/JuMP.jl/pull/1485

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/1536
