### ISSUE TITLE
`maxcut_sdp.jl` needs to be updated // currently with an assertion fail

### ISSUE THREAD

**Issue by chkwon** [JuliaOpt/JuMP.jl#1547]
`JuMP.jl/examples/old/maxcut_sdp.jl` needs attention. An assertion fails, likely due to some issues regarding Cholesky decomposition. 

#1538 

https://github.com/JuliaOpt/JuMP.jl/blob/27e710261aa935112b4c0623cdbd24ceee93ce41/examples/old/maxcut_sdp.jl

**Comment by IainNZ** [comment]
I think I wrote this initially.
