### ISSUE TITLE
Multi-Objective Optimization Support

### ISSUE THREAD

**Issue by PastelBelem8** [JuliaOpt/JuMP.jl#1557]
I'm working on my master thesis on Multi-Objective Optimization (MOO) and I found JuMP to be a clean and elegant framework. However, you are currently not supporting Multi-Objective optimization. Are you planning to support it in the future? 

Of course, I do know I could instead establish a preference articulation on my objectives and formulate my problem as a Single-Objective Optimization problem. However, I am more interested in providing the users a clear picture of the trade-offs involved in the optimization problem itself, rather than on providing a single solution. I'm aware of MultiJuMP but it does not satisfy my needs as I have not been able to solve the DLTZ1 problem. 

Additionally, the lack of documentation on MultiJuMP also makes it a bit difficult to perceive if I am doing something wrong or not. 

```jl
using JuMP, MultiJuMP
using NLopt

m = MultiModel(solver = NLoptSolver(algorithm=:GN_CRS2_LM, maxeval=100))
f(z...) = 2 + sum([(z[i]-0.5)^2 - cos(20 * 3.14 *(z[i]-0.5)) for i in 1:length(z)])
JuMP.register(m, :f, 2, f; autodiff=true)

@variable(m, 0 <= x <= 1)
@variable(m, 0 <= y <= 1)
@NLexpression(m, f2, 0.5*(1-x)*(1+f(x, y)))
@NLexpression(m, f1, 0.5*x*(1+f(x, y)))

obj1 = SingleObjective(f1, sense = :Min)
obj2 = SingleObjective(f2, sense = :Min)

md = getMultiData(m)
md.objectives = [obj1,obj2]
md.pointsperdim = 10
solve(m, method = :NBI) 
```

Also, are you planning on supporting derivative-free optimization? NLopt supports derivative-free optimization, however, JuMP currently claims that such optimization is not supported. And although I'm aware of BlackBoxOptim, they only provide an unique multi-objective optimization algorith,..

**Comment by blegat** [comment]
I would suggest to post your question on [Discourse](https://discourse.julialang.org/c/domain/opt), it has a wider audience and it gives you more chance to get the answer you are looking for ;)

**Comment by mlubin** [comment]
The answer to "why is X not implemented in JuMP" is usually that none of the JuMP developers have been sufficiently motivated to implement X. This doesn't mean that X isn't a nice feature to have. We have no concrete plans on the roadmap beyond preparing the release of [JuMP 0.19](https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md#version-019-unreleased). 

There are a number of multi-objective extensions for JuMP like [vOptSolver](https://voptsolver.github.io/vOptSolver/). As @blegat mentioned the Discourse forum is a more appropriate place for broad questions. I personally don't know much about MultiJuMP or the multi-objective extensions and can't provide support for it.

**Comment by mlubin** [comment]
That said, if you're interested in contributing on one of these topics, please reach out (e.g., at https://gitter.im/JuliaOpt/JuMP-dev) and we can provide pointers on how to do so.

**Comment by mlubin** [comment]
Continuing the discussion at https://discourse.julialang.org/t/multi-objective-optimization-support/16731.
