### ISSUE TITLE
getvalue for nonlinear expressions

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1562]
https://github.com/JuliaOpt/JuMP.jl/blob/8c36bf2a850af6392a8bba3b8241d3577b69e38a/src/nlp.jl#L1002-L1004

**Comment by odow** [comment]
Related https://github.com/JuliaOpt/JuMP.jl/blob/8c36bf2a850af6392a8bba3b8241d3577b69e38a/src/quad_expr.jl#L250

Or should I open a separate issue?

**Comment by mlubin** [comment]
A separate issue is better. The fixes are unrelated.
