### ISSUE TITLE
the doc build passes when there are failing doctests

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1576]
https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/448846512#L693

**Comment by fredrikekre** [comment]
You are not passing `strict = true` to `makedocs` (https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.makedocs).

**Comment by blegat** [comment]
@fredrikekre Thanks ! I have applied your advise in https://github.com/JuliaOpt/JuMP.jl/pull/1574/commits/1fbb7ff7ab51f358ebadbda82a79f8c02673db22
