### ISSUE TITLE
keys(::JuMPArray) bugs with 1 dimension

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/JuMP.jl#1579]
On master, I get an error on keys with a JuMPArray of 1 dimension, but I don't get the error with 2 or more dimensions.

```julia
julia> begin
           m = Model()
           @variable(m, 0 <= x[2:3] <= 1)
           @show typeof(x)
           @show keys(x)
       end
````
````
typeof(x) = JuMPArray{VariableRef,1,Tuple{UnitRange{Int64}},Tuple{Dict{Int64,Int64}}}
ERROR: JuMPArray does not support this operation.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] LinearIndices(::JuMPArray{VariableRef,1,Tuple{UnitRange{Int64}},Tuple{Dict{Int64,Int64}}}) at /Users/itahiri/.julia/packages/JuMP/uAycC/src/JuMPArray.jl:96
 [3] keys(::JuMPArray{VariableRef,1,Tuple{UnitRange{Int64}},Tuple{Dict{Int64,Int64}}}) at ./abstractarray.jl:100
 [4] macro expansion at /Users/itahiri/.julia/packages/JuMP/uAycC/src/macros.jl:301 [inlined]
 [5] top-level scope at ./REPL[26]:3
````

```julia
julia> begin
           m = Model()
           @variable(m, 0 <= x[2:3, 2:3] <= 1)
           @show typeof(x)
           @show keys(x)
       end
````
````
typeof(x) = JuMPArray{VariableRef,2,Tuple{UnitRange{Int64},UnitRange{Int64}},Tuple{Dict{Int64,Int64},Dict{Int64,Int64}}}
keys(x) = CartesianIndex{2}[CartesianIndex(2, 2) CartesianIndex(2, 3); CartesianIndex(3, 2) CartesianIndex(3, 3)]
2×2 CartesianIndices{2,Tuple{UnitRange{Int64},UnitRange{Int64}}}:
 CartesianIndex(2, 2)  CartesianIndex(2, 3)
 CartesianIndex(3, 2)  CartesianIndex(3, 3)
````

**Comment by IssamT** [comment]
I see that base treats the special case of vectors differently
https://github.com/JuliaLang/julia/blob/master/base/abstractarray.jl#L99

And JuMP only raises an error for LinearIndices:
https://github.com/JuliaOpt/JuMP.jl/blob/0d0e7225a19184091f0fd8eb4f312f91accfbb1f/src/JuMPArray.jl#L96

**Comment by IssamT** [comment]
Commenting the following line solves my issues
https://github.com/JuliaOpt/JuMP.jl/blob/0d0e7225a19184091f0fd8eb4f312f91accfbb1f/src/JuMPArray.jl#L96

But I guess raising the error there was for a reason...

**Comment by odow** [comment]
`keys` isn't part of the `AbstractArray` interface. See:
https://docs.julialang.org/en/v1.0/manual/interfaces/#man-interface-array-1
https://docs.julialang.org/en/v1.0/devdocs/offset-arrays/#man-custom-indices-1

Consider
```julia
model = Model()
@variable(model, x[2:3])
@variable(model, y[2:3, 2:3])
@variable(model, z[2:3, [:a, :b]])
keys(x)  # fails
keys(z)  # fails
keys(y)  # doesn't do what you think it does
for key in keys(y)
    @show y[key]  # will error
end
```
I think you mean `eachindex` instead. It would be nice to get the tuple corresponding to the index though. Maybe something like

```julia
julia> Base.keys(A::JuMPArray) = reshape(collect(Base.product(axes(A)...)), length.(axes(A)))

julia> keys(x)
2-element Array{Tuple{Int64},1}:
 (2,)
 (3,)

julia> keys(y)
2×2 Array{Tuple{Int64,Int64},2}:
 (2, 2)  (2, 3)
 (3, 2)  (3, 3)

julia> keys(z)
2×2 Array{Tuple{Int64,Symbol},2}:
 (2, :a)  (2, :b)
 (3, :a)  (3, :b)
```

**Comment by mlubin** [comment]
`CartesianIndex` doesn't work for `JuMPArrays` in general because the indices in a `CartesianIndex` must be ints. Maybe we could define our own version of `CartesianIndex` that doesn't have that restriction.

Returning a list of tuples from `Base.keys` is also incorrect because they have to be splatted when they're used to index into the JuMPArray.

Added to the 0.19 milestone because this should be resolved one way or another.

**Comment by mlubin** [comment]
@IssamT That makes sense to me.
