### ISSUE TITLE
It is confusing when JuMP modifies the variable bound as opposed to adding a constraint

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#1586]
Is this an intended part of the JuMP design?
```julia
julia> model = JuMP.direct_model(Gurobi.Optimizer())
A JuMP Model

julia> @variable(model, x >= 0)  # Sets the lower bound.
x

julia> JuMP.lower_bound(x)
0.0

julia> @constraint(model, x >= -1) # Adds a constraint.
x >= -1.0

julia> JuMP.lower_bound(x)
0.0

julia> @constraint(model, -2 <= x <= 1) # Sets both bounds.
x in [-2.0, 1.0]

julia> JuMP.lower_bound(x)
-2.0
```

**Comment by blegat** [comment]
The reason is that `@constraint(model, x >= -1)`, everything is moved to the lhs:
https://github.com/JuliaOpt/JuMP.jl/blob/6daac7ae3105d1c2ddcd44a1324acd3769fcef64/src/macros.jl#L340-L342
and not for `@constraint(model, -2 <= x <= 1)`

**Comment by odow** [comment]
I feel like if the user writes `@constraint` we should add an explicit constraint to the model. This `@constraint(model, -2 <= x <= 1)` would add an `ScalarAffineFunction-in-Interval` function.

**Comment by mlubin** [comment]
We can't *always* promote to `AffExpr` because we need a way to write `VectorOfVariables-in-X` and `SingleVariable-in-X` constraints for arbitrary `X`. However, for constraints specified by inequalities (and not `in`) I think there's a good argument that the expected behavior is to promote to `AffExpr`.

**Comment by odow** [comment]
I'd be happy with only promoting when there is an (in)equality.

**Comment by blegat** [comment]
So the issue here is that `@constraint(model, -1 <= x <= 1)` should create a `ScalarAffineFunction`-in-`Interval` and not a `SingleVariable`-in-`Interval` ?

**Comment by mlubin** [comment]
Yes.
