### ISSUE TITLE
Broken links in NEWS.md for v0.19 release notes.

### ISSUE THREAD

**Issue by vtjeng** [JuliaOpt/JuMP.jl#1594]
Links to [installation guide](http://www.juliaopt.org/JuMP.jl/latest/installation.html) and [documentation](http://www.juliaopt.org/JuMP.jl/latest/variables.html#Variable-containers-1) in the latest [`NEWS.md`](https://github.com/JuliaOpt/JuMP.jl/blob/v0.19-alpha/NEWS.md) are broken.

**Comment by blegat** [comment]
Thanks a lot for reporting this ! It is due to https://github.com/JuliaOpt/JuMP.jl/pull/1578
