### ISSUE TITLE
MethodError: no method matching parseNLExpr_runtime

### ISSUE THREAD

**Issue by Ryanlaker** [JuliaOpt/JuMP.jl#1613]
I have an error for the following code in Julia for solving NLP problem
```julia
using JuMP
using Ipopt
using DataFrames,ConditionalJuMP
m = Model(solver=IpoptSolver())

#importing data from csv files
 xi=[-1.016713795   0.804447648 0.932137661 1.064136698  -0.963217531
     -1.048396778   1.076371484 1.099027177 1.061556926  -0.95185481
     -0.980261302   0.271253807 0.184946729 1.062838197  -0.958794505
     -0.980703191   0.278820569 0.231132677 1.062967459  -0.959302488
     -0.953074503   -0.00768112 0.128808175 1.067743779  -0.978524489
     -1.014866259   0.815325963 1.065956208 1.067059122  -0.974682291
     -0.995088119   0.550359991 0.845087207 1.066556784 -0.973154887]
 xj=xi
 pii=[-300
     -259.6530828
     -284.3708955
     -291.3387625
     -342.4479859
     -356.5031603
     -351.0154738]

 sample_size=7
 bus_num=5
 tempsum=0
 #define variables
 @variable(m,aij[1:2*bus_num,1:2*bus_num]) # define  matrix by 
 2bus_num*2bus_num

 for n=1:sample_size
    for i=1:bus_num
       for j=1:bus_num
        tempsum=(aij[i,j]*xi[n,i]*xj[n,j]-pii[n,2])^2+tempsum
       end
    end
 end

 #define constraints
 @constraint(m, [i=1:2*bus_num,j=2*bus_num],aij[i,j]==aij[j,i])
 @constraint(m, [i=1:2*bus_num,j=2*bus_num],aij[i,j]*aij[i,j]<=aij   
 [i,i]*aij[j,j])
 @constraint(m, [i=1:2*bus_num,j=2*bus_num],aij[i,i]*aij[j,j]<=0.25*
 (aij[i,i]+aij[j,j])*(aij[i,i]+aij[j,j]))

 #define NLP objective function

 @NLobjective(m, Min, tempsum)

 solve(m)
 println("m = ",getobjectivevalue(m))
 println("Aij = ", getvalue(aij))
```

but after operation, an error was shown as below.
```MethodError: no method matching parseNLExpr_runtime(::JuMP.Model, ::JuMP.GenericQuadExpr{Float64,JuMP.Variable}, ::Array{ReverseDiffSparse.NodeData,1}, ::Int64, ::Array{Float64,1})```

The error occurs on `@NLobjective(m, Min, tempsum)`, but I dont know how to modify the code. May you please anyone help me ? @chkwon Kwon @mlubin @joehuchette @joaquimg @iamed2 @IainNZ

Besides, I am also confused by how to add positive definite contraints here for the solution Matrix aij, as I want to get a positive definite matrix aij.

Edit(odow): formatting.

**Comment by Ryanlaker** [comment]
@Changhyun Kwon
@mlubin
@joehuchette 
@omus 
@iamed2 
@IainNZ

**Comment by odow** [comment]
Hi @Ryanlaker, 

Did you take the time to [read the template](https://github.com/JuliaOpt/JuMP.jl/issues/new?template=bug_report.md) before opening an issue? We try to keep JuMP issues for bug reports and feature requests.

Usage questions like this are better asked on our [discourse forum](https://discourse.julialang.org/c/domain/opt). (Also, in future, please don't tag people like you've done. Most of these people are already watching the repository and will get a notification regardless.)

To answer your question, please read the syntax notes of the JuMP NLP documentation: http://www.juliaopt.org/JuMP.jl/0.18/nlp.html#syntax-notes
It says that:

> AffExpr and QuadExpr objects cannot currently be used inside nonlinear expressions. Instead, introduce auxiliary variables, e.g.:
```julia
myexpr = dot(c,x) + 3y # where x and y are variables
@variable(m, aux)
@constraint(m, aux == myexpr)
@NLobjective(m, Min, sin(aux))
```

PSD matrices are addressed here: http://www.juliaopt.org/JuMP.jl/0.18/refvariable.html#semidefinite-and-symmetric-variables

If you can't get things working, I suggest that you ask on the [discourse forum](https://discourse.julialang.org/c/domain/opt). 

Thanks for using JuMP!

**Comment by mlubin** [comment]
This exact missing method is implemented in JuMP `master`. The error message should be helpful:
https://github.com/JuliaOpt/JuMP.jl/blob/10878c9fd513036510c0402e9f01402ca5dc12b1/src/parse_nlp.jl#L203-L207

**Comment by Ryanlaker** [comment]
Hi@odow odow. Thanks for your suggestion and help. so sorry for my confused issue. I will post my issues at the disclourse forum in the future.

**Comment by Ryanlaker** [comment]
Hi@mlubin . Thanks for your reminder. I will try it.

**Comment by odow** [comment]
Closing because a better error message exists on JuMP master.
