### ISSUE TITLE
Feasibility killed by tm_lim and/or repeated objective coefficients

### ISSUE THREAD

**Issue by JockLawrie** [JuliaOpt/JuMP.jl#1615]
Hi there,

I am solving a MILP with GLPK.jl and JuMP.jl (v19-alpha).

I have data for an integer problem that fails to solve when `tm_lim` is set, but solves otherwise.
It fails well before the time limit is up too.
Also, if I use different objective coefficients, the problem solves even if `tm_lim` is set.
The 491 objective coefficients in the data have only 41 unique values.

Below is the code, the data is attached.
Any ideas?

```julia
using JSON
using JuMP
using GLPK
using MathOptInterface
const MOI = MathOptInterface

function convert_to_array(v)
    ni = size(v[1], 1)
    nj = size(v, 1)
    a  = fill(0.0, ni,  nj)
    for j = 1:nj
        for i = 1:ni
            a[i, j] = v[j][i]
        end
    end
    a
end


function solve_mip(A, c, set_tm_lim::Bool)
    mdl = set_tm_lim ? Model(with_optimizer(GLPK.Optimizer, tm_lim=5)) : Model(with_optimizer(GLPK.Optimizer))
    nj  = size(c, 1)
    @variable(mdl, x[1:nj], Bin)    # x[j] = 0 or 1.
    @objective(mdl, Min, sum(c[j] * x[j] for j=1:nj))

    # Constraints
    for i = 1:10
        @constraint(mdl, sum(A[i, j] * x[j] for j=1:nj) == 1)
    end
    for i = 11:30
        @constraint(mdl, sum(A[i, j] * x[j] for j=1:nj) <= 1)
    end

    # Solve model and extract result
    JuMP.optimize!(mdl)
    JuMP.result_value.(x)
end

data = JSON.parsefile("miptest.txt")
A = convert_to_array(data["A"])
c = data["c"]
x = solve_mip(A, c, true)   # Fails
x = solve_mip(A, c, false)  # Succeeds (same data, no tm_lim)
x = solve_mip(A, rand(size(A, 2)), true)   # Succeeds (tm_lim, different data)
```
[miptest.txt](https://github.com/JuliaOpt/JuMP.jl/files/2574551/miptest.txt)

**Comment by odow** [comment]
My guess is `Fails` means that `JuMP.value.(x)` fails.

On my machine, `solve_mip(A, c, true)` yields `JuMP.termination_status` of `TimeLimit`, and the primal and dual statuses are `UnknownResultStatus`.

I think this is doing exactly what we expect. With the test data, GLPK can't find a feasible primal solution so it doesn't return one and says so. With different data, or no time limit, it is able to find a feasible primal solution.

**Comment by JockLawrie** [comment]
Sorry, `Fails` means that the solution is a vector of `NaN`s. @odow is right regarding the statuses and likely what is happening. I get similar results on JuMP 0.18.4. The underlying problem is user error...I thought `tm_lim` was in seconds, but it seems it's milliseconds. Apologies!

**Comment by odow** [comment]
Closing in favor of #1621. This is a documentation issue.
