### ISSUE TITLE
Docs: how to interpret and query a solution after optimize!

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#1621]
We have the [Quick Start guide](http://www.juliaopt.org/JuMP.jl/dev/quickstart/), but it really needs a proper page. 

- [ ] `termination_status`
- [ ] `primal_status`
- [ ] `dual_status`
- [ ] `has_values`
- [ ] `has_duals`
- [ ] `JuMP.value`
- [ ] `JuMP.dual`

**Comment by blegat** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/1731
