### ISSUE TITLE
ERROR: LoadError: UndefVarError: with_optimizer not defined

### ISSUE THREAD

**Issue by amoghb13** [JuliaOpt/JuMP.jl#1622]
Stacktrace:
[1] top-level scope at none:0
[2] include at .\boot.jl:317 [inlined]
[3] include_relative(::Module, ::String) at .\loading.jl:1044
[4] include(::Module, ::String) at .\sysimg.jl:29
[5] exec_options(::Base.JLOptions) at .\client.jl:231
[6] _start() at .\client.jl:425

For the Knapsack problem copied from GitHub JuMP examples folder

**Comment by odow** [comment]
The `master` branch of JuMP is transitioning to a new API. Read more about it here:
https://discourse.julialang.org/t/mathoptinterface-and-upcoming-breaking-changes-in-jump-0-19/4874

For the current version of JuMP, use these examples instead: https://github.com/JuliaOpt/JuMP.jl/tree/release-0.18/examples

Here is the relevant documentation: http://www.juliaopt.org/JuMP.jl/0.18/

**Comment by mlubin** [comment]
The JuMP readme has a link to the examples folder that corresponds to the current release. Not sure how else to better address the possible confusion.
