### ISSUE TITLE
Debug features in callbacks

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#164]
This is kind of a cool idea from @IainNZ JuMPeR that would (1) be easy to implement, and (2) more elegant than littering a callback with print statements IMO, especially with more complex logic/multiple cuts. The idea is just to print out all cuts that get added (or heurstic solutions, or branches...) in a nice little block. See https://github.com/IainNZ/JuMPeR.jl/blob/0bd4b43bb53ef5545b0f3e4df19378c64387483e/src/oracle_poly.jl#L139

**Comment by chriscoey** [comment]
@joehuchette any new thoughts on this? and see https://github.com/JuliaOpt/MathProgBase.jl/issues/170

**Comment by joehuchette** [comment]
Not really, I think something like ``addlazycallback(m, func, verbose=true)`` is reasonable and would be a nice addition.

**Comment by mlubin** [comment]
Resolved vacuously. Callbacks don't happen here anymore, but this is still a useful idea for the solver-specific callbacks.
