### ISSUE TITLE
redirect https://jump.readthedocs.io/ to https://www.juliaopt.org/JuMP.jl/dev/

### ISSUE THREAD

**Issue by alkorang** [JuliaOpt/JuMP.jl#1642]
When I googled JuMP documentation, usually https://jump.readthedocs.io/ appears on the top.
But when I clicked the link, it always displays message like this:
```

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```

How about redirect to https://www.juliaopt.org/JuMP.jl/dev/ when people accessed to https://jump.readthedocs.io/ page?

**Comment by blegat** [comment]
See https://github.com/JuliaOpt/JuMP.jl/issues/1221

**Comment by mlubin** [comment]
Unfortunately ReadTheDocs doesn't support this kind of redirect from what I'm able to tell. I hope that it will drop from the search results given that there's no longer any content there.

**Comment by odow** [comment]
> I hope that it will drop from the search results given that there's no longer any content there.

If only we knew people at Google; we could ask them to tweak some dials...
