### ISSUE TITLE
A proposal for common statuses

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1656]
The new status system is precise but a bit overwhelming at first (https://discourse.julialang.org/t/first-alpha-release-of-jump-0-19-jump-mathoptinterface/16099/4). There have been a few proposals to provide simple statuses (https://github.com/JuliaOpt/JuMP.jl/issues/1544#issuecomment-429087152). Here's another take on it that involves additions to MOI.

- Define `@enum CommonSolveStatus Optimal PrimalInfeasible DualInfeasible InfeasibleOrUnbounded NotSolved` in MOI. Import these symbols into JuMP so you can write `JuMP.PrimalInfeasible`.

  - Note: It's not clear how expansive this list should be. I think the list above covers the educational use case. One place to draw the line is to define only cases that map to the "OK" values for [`TerminationStatusCode`](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.TerminationStatusCode).

- Define `RawSolveStatus()` as an MOI optimizer attribute. Solvers can return *either* a `CommonSolveStatus` *or* a value from a solver-specific enum, e.g., `CplexSolveStatus.OptimalInfeasible`. The solver-specific enum should have a 1-1 mapping with the possible statuses reported by the solver.

  - Note: it's important to use enums instead of strings/symbols because there's no upgrade path otherwise if the status values change. Removing an option from an enum will cause an error instead of silently doing the wrong thing.

- `JuMP.solve_status(model)` wraps the MOI attribute.

This accomplishes two things:

1. It's useful to have a way to access the raw statuses from the solvers for debugging. When reporting an issue with a solver to the solver developers, they'll want to know which solver-specific status was returned and not which MOI status.

2. You can write:
```julia
status = JuMP.solve_status(model)
if status == JuMP.Optimal
  ...
elseif status == JuMP.PrimalInfeasible
  ...
else
  println("Got unexpected status $status.")
end
```

This is actually pretty close to statuses in 0.18, except with enums instead of symbols and without `:UserLimit` and similar error cases. For the non-OK cases, we let users deal with the raw status values or direct them to the extensive MOI statuses.

@chkwon @ccoffrin

**Comment by mlubin** [comment]
> Is there a alternative to the enum value Optimal (e.g. Converged, Complete?) that would be a little more ambiguous about the solution quality guarantees?

The solvers are deciding to return these statuses, so if they say optimal they should mean globally optimal. Ipopt should not report optimal unless it knows that the problem is convex, for example.

> When a MIP solver hits a user limit and reports a feasible solution, what status would be reported in the propose scheme? NotSolved?

It should return a solver-specific status. Like `CPXMIP_TIME_LIM_FEAS`.

**Comment by ccoffrin** [comment]
I think I am confused.  How would `CommonSolveStatus` interact with solver-specific statuses?  Both of my questions are concerned with the semantics of `CommonSolveStatus`?

**Comment by mlubin** [comment]
> How would CommonSolveStatus interact with solver-specific statuses?

If none of the cases of `CommonSolveStatus` apply, then solvers should return a value of a solver-specific enum. (The interface is not type stable.)

**Comment by ccoffrin** [comment]
aaaa I get it now.

My guess is that in practice a majority of JuMP users will only use the `CommonSolveStatus`, and only the more advanced users will go beyond this.  Do you agree?

If so, maybe having `CommonSolveStatus` be analogous to scope to AMPL statuses would be suitable?  Those are: `Solved`, `Solved?`, `Infeasible`, `Unbounded`, `Limit`, `Failure`.

**Comment by mlubin** [comment]
I think we need to keep bikesheeding this. It's not ok to have 4 different kinds of statuses (result statuses, termination statuses, `CommonSolveStatus`, and solver-specific statuses). Can we change `MOI.TerminationStatus` instead so that it's usable as an "easy" status?

One of @chkwon's points of confusion in https://discourse.julialang.org/t/first-alpha-release-of-jump-0-19-jump-mathoptinterface/16099/4 was about why `Success` is reported when the problem is infeasible.  Now that we have `NoSolution` as a `ResultStatus`, I'm not sure there's a good reason to keep `InfeasibleNoResult` and `UnboundedNoResult`. We could remove these two and split `MOI.Success` into `Solved`, `Infeasible` and `DualInfeasible`. Then we need `AlmostSolved`, `AlmostInfeasible`, and `AlmostDualInfeasible`.

(Is `UnboundedNoResult` currently used anywhere?)

**Comment by ccoffrin** [comment]
I see, so what is the proposed enum for `MOI.TerminationStatus`?

**Comment by blegat** [comment]
I think splitting `Success` and `AlmostSuccess` into more statuses is a good idea. It is a bit redundant with the result statuses but I don't see a case where we know it is `Success` but we don't know whether it is `Solved`, `Infeasible` or `DualInfeasible`.

> Edit: What I'm not clear about is what we should do when Ipopt converges to an infeasible point. Calling this `Infeasible` is about as bad as calling a local solution `Optimal`.

Maybe we could keep `UnboundedNoResult` and `InfeasibleNoResult` ?

**Comment by mlubin** [comment]
> Why not something like StuckAtInfeasiblePoint or something similar ?

That could work. But if we have statuses to distinguish between local and global infeasibility, shouldn't we also have statuses to distinguish between local and global optimality?

**Comment by blegat** [comment]
> shouldn't we also have statuses to distinguish between local and global optimality

Yes, that might also resolve the concern raised in https://github.com/JuliaOpt/MathOptInterface.jl/pull/478#discussion_r211304180

**Comment by mlubin** [comment]
So we'll have {Almost, ""} x {Local/Global} x {Optimal, Infeasible, DualInfeasible} (12 statuses)? It's a lot but maybe we can have a simple layer on top that drops the "Almost" and the Local/Global distinctions.

**Comment by blegat** [comment]
Yes, it's better to have more expressiveness in the low-level MOI API, it's easier to summarize than the opposite.
Maybe `{"Local", "Global"}` can be replaced by `{"Local", ""}` ?

**Comment by mlubin** [comment]
> Maybe {"Local", "Global"} can be replaced by {"Local", ""} ?

That could work.

I can put together a PR for MOI over the weekend that we can vote and comment on. Changing statuses is breaking so we'll need to tag MOI 0.7, but I don't see a reasonable alternative.

**Comment by blegat** [comment]
> Changing statuses is breaking so we'll need to tag MOI 0.7, but I don't see a reasonable alternative.

That's ok, but we'll need to close at least https://github.com/JuliaOpt/MathOptInterface.jl/issues/583 and https://github.com/JuliaOpt/MathOptInterface.jl/issues/562 if we tag MOI v0.7.

**Comment by mlubin** [comment]
Closes by https://github.com/JuliaOpt/MathOptInterface.jl/pull/596. We'll make the corresponding changes to JuMP once that's released.
