### ISSUE TITLE
What to do with auxiliary constraints/variables?

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#167]
@mlubin and I talked about this a bit today: when handling constraints that require transformations (e.g. normed constraints, absolute values, etc.), should the constraints and variables added be added explicitly to the JuMP model or "silently" passed to the solvers? Concretely, when I do something like
```
@defVar(m,x[1:2])
addConstraint(m, norm(x) <= 1)
```
should printing the model give something like
```
||x|| <= 1
```
or 
```
x[1]^2 + x[2]^2 <= aux1^2
0 <= aux1 <= 1
```
(assuming that printing gives exactly the internal representation of the JuMP model, which is another related question). What about for 
```
addConstraint(m, norm([x[1],x[1]+x[2]]) <= 1)
```
where the real representation would be 
```
x[1]^2 + aux1^2 <= aux2^2
aux1 = x[1] + x[2]
0 <= aux2 <= 1
```
Which is more useful for the user? I tend to think the form the user inputs the constraints is more natural (especially when the formulation tricks can be solver-dependent), but I can see rationales for both sides.

**Comment by mlubin** [comment]
This has been addressed in more recent issues. The decision so far is to avoid transforming the user's input with auxiliary variables at all costs.
