### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by hochB** [JuliaOpt/JuMP.jl#1714]
JuMP has 82 branches besides `master` but most are unecessary (merged or declined patches, old branches that don't apply and so on). For better navigating experience I think it would be good to keep only branches that are useful.
Below is my proposal.

### Keep

**Releases**
```
release-0.18
release-0.17
release-0.16
release-0.15
release-0.14
release-0.13
release-0.12
release-0.11
release-0.10
release-0.9
release-0.8
release-0.7
release-0.6
release-0.5
release-0.4
release-0.3
release-0.2
release-0.1
```

**Branches from PRs that are opened**
```
bl/jumpextprint
od/test_examples
bl/speed_notebook
iain/newtest
bl/ot
```

### Remove
**Branches from PRs that were merged or rejected**
```
bl/kwarg_constraint
bl/moi7
bl/vecquad
bl/broadcastscalardense
bl/broadcastunstable
bl/objective_function_type
mlubin-patch-2
bl/moi
ml/19news
ml/callbacks10
bl/withoptmoduleshortcut
ml/constrobject
bl/catops
documenter
constructvariablecontainer!
setconstraints
free-print
clear-duals
mpb-master-fix
@LinearConstraints
fix-949
singleton-expression
print-tweak
macro-cleanup
anon-NLexpression
unsigned-arrays
anon-singletons
test-tols
jh/nonconstant-exponents
jh/relax
getconstraint
ml/fix05
undef-in-symmetric
anon-vars
macro-error
undef-in-macro
vec-lazy
emptysym
snoopcompile
typestable-solve
array-print
relaxation
runtime-gendict
macro-extensions
extension_docs
```

### Revisit
**Branches that never made it into a PR**
```
jr/broadcast
bl/PR1432
bl/csdp
jr/mulcoverage
juliacon2018/0.19-dev
ml/prep182
bl/affvalue
ml/containers
tk/avtest
ml/nolpsol
free-print
clear-duals
mpb-master-fix
fix889
dual-model
varcheck
gh-pages
```

**Comment by odow** [comment]
Thanks for this, it needed a good weeding. I've deleted the branches in your "Remove" list, and gone through most of the branches in the "Revisit" list, deleting the ones that are either no longer relevant.

**Comment by odow** [comment]
@blegat what do you want to do with `bl/PR1432` and `bl/csdp`? They have weird diffs.

**Comment by blegat** [comment]
@odow I have deleted them, they are outdated

**Comment by odow** [comment]
Closing as we now have 28 branches instead of 82! Thanks @hochB
