### ISSUE TITLE
A[t]_mul_B[!] deprecated upstream

### ISSUE THREAD

**Issue by hochB** [JuliaOpt/JuMP.jl#1716]
I see usage of `A_mul_B`, `A_mul_B!`, `At_mul_B` and `At_mul_B!` in the source code.
Those functions were deprecated in Julia upstream: 
https://github.com/JuliaLang/julia/commit/d83dca96f8f66469d6b9e5232a34844e1e3c65db
https://github.com/JuliaLang/julia/pull/25217

Should JuMP go in the same direction?

**Comment by mlubin** [comment]
Yes, the operator overloading code could use a restructuring. It was updated hastily from Julia 0.6 to 1.0.
