### ISSUE TITLE
Error when getting attributes

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1739]
Discussion started in https://github.com/JuliaOpt/JuMP.jl/pull/1728#issuecomment-451674792

When getting an MOI attribute from JuMP, if the getter is not implemented, the user will get this error:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/70cc356dc8fcd79b20250ecfed0d1576e7d5b36f/src/attributes.jl#L203
This is appropriate if he does
```julia
MOI.get(JuMP.backend(model), attribute)
```
but if he was doing
```julia
MOI.get(model, attribute)
```
it might violate the [MethodError principle](http://www.juliaopt.org/JuMP.jl/dev/style/#User-facing-MethodError-1) because the user didn't try to get the attribute from a `ModelLike` and he needs to figure out that this is due to the fact that the call is redirected to the backend.
However, one might argue that this is simply syntactic sugar and the two calls are equivalent and they should get the same error.

Now suppose the user do
```julia
JuMP.objective_value(model)
```
If the `MOI.ObjectiveValue` getter is not implemented, the same error will be thrown.
Does this violate the MethodError principle or is it again consider syntactic sugar for an equivalent call ?

What do you think ?

**Comment by odow** [comment]
I guess at the JuMP-level, it might be worth paying the `try-catch` penalty for nice, user-friendly errors. 
Consider the following, which is semi-understandable (no optimizer is attached), but it still requires the user to understand `MathOptInterface`, `ConstraintPrimal(1)`, `caching optimizer` and `attached`.
```julia
using JuMP
model = Model()
@variable(model, x)
@constraint(model, c, 2x >= 1)
JuMP.value(c)
```
```julia
ERROR: Cannot query MathOptInterface.ConstraintPrimal(1) from caching optimizer because no optimizer is attached.
Stacktrace:
[1] error(::String) at .\error.jl:33
[2] get(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{JuMP.JuMPMOIModel{Float64}}}, ::MathOptInterface.ConstraintPrimal, ::MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}}) at C:\Users\Oscar\.julia\packages\MathOptInterface\o3zZH\src\Utilities\cachingoptimizer.jl:460
[3] get(::Model, ::MathOptInterface.ConstraintPrimal, ::ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},JuMP.ScalarShape}) at C:\Users\Oscar\.julia\dev\JuMP\src\JuMP.jl:517
[4] value(::ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},JuMP.ScalarShape}) at C:\Users\Oscar\.julia\dev\JuMP\src\constraints.jl:394
[5] top-level scope at none:0
```

**Comment by blegat** [comment]
> Here's a bad case:

It was a bug in `UniversalFallback`, when the attribute was set for some variable, it returned `nothing` for the other ones but when it was set for no variable, it throws this error.
With ..., we now get the correct behavior
```julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x)
x

julia> JuMP.start_value(x)

julia> @variable(model, y, start = 1)
y

julia> JuMP.start_value(x)

julia> JuMP.start_value(y)
1
```

**Comment by blegat** [comment]
Is there any other bad error message that we can address before JuMP v0.19 or do we remove it from the milestone ?

**Comment by mlubin** [comment]
We need a new MOI tag, right? Other than that I think we can drop this from the 0.19 milestone.

**Comment by blegat** [comment]
> We need a new MOI tag, right?

Yes, it was included post MOI v0.8.1

**Comment by blegat** [comment]
Removing v0.19 milestone now that MOI v0.8.2 is tagged we have
```julia
using JuMP
model = Model()
@variable(model, x)
@constraint(model, c, 2x >= 1)
JuMP.value(c)

# output
ERROR: OptimizeNotCalled()
...
```
and
```julia
model = Model()
@variable(model, x)
JuMP.start_value(x)
```
gives no output.

**Comment by odow** [comment]
Is there anything to do here? I don't know if we want to `try-catch` all exceptions in order to print a prettier error on  `OptimizerNotCalled`.

**Comment by blegat** [comment]
No I think we can close
