### ISSUE TITLE
Macro to replace variables with values after optimization

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#176]
Like what CVX does after it solves a problems. We might have to ask the user to explicitly state the variables, e.g.

```
@replaceVars x y z
```

but if we're real clever we might be able to pull the info in the model used for printing and just do something like 

```
@solve(m)
```

**Comment by mlubin** [comment]
The discussion seems to have ended, can be revived in a new issue if there is interest in the future.
