### ISSUE TITLE
Int Return Type for User Defined Functions

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#1774]
An error is thrown if the return type of a user defined function is `Int` instead of `Float`.

Maybe enforcing float provides performance gains, but worth considering.

**Comment by mlubin** [comment]
How can a user-defined function be differentiable if it returns an `Int`?

**Comment by ccoffrin** [comment]
I can't seem to reproduce the bug in a clean example, so I'll close this until I have a good example.
