### ISSUE TITLE
Recursive Expression

### ISSUE THREAD

**Issue by zhangxz1123** [JuliaOpt/JuMP.jl#1775]
Is there a way to define expressions/NLexpressions recursively? For example, I want to define a list of expressions like the following:
`@NLexpression(m, θ[i=1:d,t=1:(T+1)], (if t>1 (θ[i,t-1] + data[i,t-1]) else θ0[i] end) )`
Currently, this will cause the error:
> UndefVarError: θ not defined

Techanically, I could unfold the above expression by written (T+1) NLexpressions as
```
@NLexpression(m, θ1[i=1:d], θ0[i])
@NLexpression(m, θ2[i=1:d], θ1[i] + data[i,1])
.
.
.
@NLexpression(m, θTp1[i=1:d], θT[i] + data[i,T])
```

But when T is large, this is obviously not preferable.

Alternatively, I can use NLconstraint instead of NLexpression, but this will require me to define theta as variables as well, which based on my testing will slow down the computation quite a bit and also requires as much as twice memory space.

**Comment by blegat** [comment]
> But when T is large, this is obviously not preferable.

Why is that ? What's the difference with the recursive version that you would like to work

**Comment by mlubin** [comment]
The macros are not structured in a way that lets you refer to the object that's being created recursively. The following code should work instead (haven't tried it).
```julia
θ = Vector{Any}(undef, d, T+1) # Use a Dict() instead if you have weird index sets.
for i in 1:d, t = 1:(T+1)
    if t > 1
       θ[i, t] = @NLexpression(m, θ0[i])
    else
       θ[i, t] = @NLexpression(m, θ[i, t - 1] + data[i, t - 1]))
    end
end
```

As this is not a bug report or feature request (or not phrased as such), please use [discourse](https://discourse.julialang.org/) for usage questions in the future.
