### ISSUE TITLE
sanity check JuMP's exports

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1790]
Now that we export everything without a starting underscore, we should sanity check that all exported functions are intended to be public. Removing an export is usually considered a breaking change, so this is blocking for 0.19.

Example candidates to unexport in macros.jl: `issum`, `isprod`, `error_curly`, `buildrefsets`, `getloopedcode`. (This is just from a quick look.)

Sanitized files
- [ ] JuMP.jl
- [x] aff_expr.jl https://github.com/JuliaOpt/JuMP.jl/pull/1833
- [x] constraints.jl
- [x] copy.jl https://github.com/JuliaOpt/JuMP.jl/pull/1834
- [x] macros.jl https://github.com/JuliaOpt/JuMP.jl/pull/1813
- [x] nlp.jl
- [x] objective.jl
- [ ] operators.jl https://github.com/JuliaOpt/JuMP.jl/pull/1837
- [x] optimizer_interface.jl
- [x] parse_expr.jl https://github.com/JuliaOpt/JuMP.jl/pull/1838
- [x] parse_nlp.jl
- [x] print.jl https://github.com/JuliaOpt/JuMP.jl/pull/1835
- [x] quad_expr.jl https://github.com/JuliaOpt/JuMP.jl/pull/1833
- [x] sd.jl
- [x] sets.jl
- [x] utils.jl https://github.com/JuliaOpt/JuMP.jl/pull/1814
- [x] variables.jl https://github.com/JuliaOpt/JuMP.jl/pull/1830

**Comment by odow** [comment]
Question. Structs like `VariableInfoExpr` are private right? In which case, should they be renamed `_VariableInfoExpr`?
https://github.com/JuliaOpt/JuMP.jl/blob/a53cf4d9e88b682578a1139740fb1b1f0e0506f0/src/variables.jl#L9-L20

There is a loooot of renaming to do...

**Comment by mlubin** [comment]
> Structs like VariableInfoExpr are private right? In which case, should they be renamed _VariableInfoExpr?

I'd say yes. This struct is used internally for macros. It might be used by JuMP extensions but I'd still say that's private.

**Comment by blegat** [comment]
Yes, I'd say it's private

**Comment by odow** [comment]
Previously we had things like `JuMP.delete` so we didn't have to overload `Base.delete`. But now export user-facing functions suggests that we should export `delete` which implies that we should overload `Base.delete`... Thoughts?

**Comment by mlubin** [comment]
I don't like the idea of extending base methods just because they have the same name (they should have the same meaning), but if we have to because of issues like https://github.com/JuliaOpt/JuMP.jl/issues/1804 then our hands are tied.

**Comment by blegat** [comment]
`Base.delete` and `JuMP.delete` have close meaning if we think of JuMP models are containers and variable/constraint references are indices/keys of this container. I agree that it's not totally the same we don't define `keys`, `indices`, ... but implementing `Base.delete` seems ok.
