### ISSUE TITLE
@SDconstraint error when using `import JuMP` vs `using JuMP` in 0.19-beta2

### ISSUE THREAD

**Issue by pseudocubic** [JuliaOpt/JuMP.jl#1792]
I have encountered an error when using `import JuMP` (as opposed to `using JuMP`) in `@SDconstraint`. Below is a very minimal example to demonstrate the error I encounter.

```julia
import JuMP  
model = JuMP.Model()
JuMP.@variable(model, -1 <= x <= 1)
JuMP.@variable(model, -1 <= y <= 1)
JuMP.@SDconstraint(model, [x y; -y x] >= 0)
```

results in `ERROR: UndefVarError: PSDCone not defined`, whereas the following works.

```julia
import JuMP  
model = JuMP.Model()
JuMP.@variable(model, -1 <= x <= 1)
JuMP.@variable(model, -1 <= y <= 1)
JuMP.@constraint(model, [x y; -y x] in JuMP.PSDCone())
```

However, when using `using JuMP`, both examples work.

Relatedly, in JuMP 0.19, should the proper syntax be to use @SDconstraint, or to do as I have written in the second example?

**Comment by mlubin** [comment]
This is a bug. Thanks for reporting.
