### ISSUE TITLE
Allow for to few degrees of freedom

### ISSUE THREAD

**Issue by TorkelE** [JuliaOpt/JuMP.jl#1799]
Not sure whenever there is a way around this. I am solving a problem type (relating to biochemical reaction networks) where I autogenerate constraints for my model. Some times, I would generate more than n constraints. However, these are is some way degenerate and the problem is still solvable. Right now when I add more than n constraints I simply get `Warning: Ipopt finished with status Not_Enough_Degrees_Of_Freedom` and the solver quits. I could try to figure out which constraints to remove to make the identical problem with only n constraints, however, this is no trivial. If possible it would be easier to simply force JuMP to try anyway (because this time, I might know better then the software).

It is ofcourse possible that there are other reasons this is not possible, in which case I will simply proceed to try an make a subprogram to figure out which constraints to remove and which not to. But if there exist such an option, I would be happy to hear.

Simple example:
```julia
m = Model(solver = IpoptSolver())
@variable(m, x, start = 0.0)
@variable(m, y, start = 0.0)

@NLobjective(m, Min, (1-x)^2 + 100(y-x^2)^2)

# adding a (linear) constraint
@constraint(m, x + y == 10)
@constraint(m, x*y == 20)
@constraint(m, x*y -1 + 1 == 20)
JuMP.solve(m)
```
(In this case the two last constraints are simply identical)

**Comment by odow** [comment]
JuMP's goal is to convert the problem as you write it down into a form that the solver understands. If you provide duplicate constraints, JuMP will happily pass them through.

> It is ofcourse possible that there are other reasons this is not possible, in which case I will simply proceed to try an make a subprogram to figure out which constraints to remove and which not to.

You should probably do this before adding the constraints in the first place. The current version of JuMP (which you are using) doesn't support deleting constraints. The upcoming release will support deleting constraints.

**Comment by mlubin** [comment]
Identifying redundant constraints is not within the intended scope of JuMP. See tools like https://github.com/adowling2/DegeneracyHunter.jl.
