### ISSUE TITLE
tab completion triggers warning

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#1804]
On Julia 1.0:
```julia
using JuMP
julia> Aff<tab>WARNING: both JuMP and Base export "reshape"; uses of it in module Main must be qualified
julia> AffExpr
```

I haven't tried on Julia 1.1.

**Comment by odow** [comment]
It is functions like this getting exported: https://github.com/JuliaOpt/JuMP.jl/blob/9d8d31583be454277bed22103f8437ca0d62ed6c/src/sd.jl#L56
This really calls for #1790

**Comment by mlubin** [comment]
Still, this seems more like a Julia bug than a JuMP bug. Tab completion is a confusing trigger for this warning.

**Comment by blegat** [comment]
We should probably rename it `reshape_result`

**Comment by odow** [comment]
Here is the Julia issue: https://github.com/JuliaLang/julia/issues/14787
