### ISSUE TITLE
JuMP for embedded systems

### ISSUE THREAD

**Issue by AtsushiSakai** [JuliaOpt/JuMP.jl#1809]
First of all, thank you so much for great OSS. I think JuMP is the one of the greatest OSS I've ever found.

I think if JuMP has features for embedded systems, it would be wonderful.

For example,

1) C code generation with JuMP syntax like cvxgen:
 CVXGEN: Code Generation for Convex Optimization https://cvxgen.com/docs/index.html

2) Executable generation with static compile.
This might be helpful. 
JuliaLang/PackageCompiler.jl: Compile your Julia Package https://github.com/JuliaLang/PackageCompiler.jl

I know this is very difficult to implement, so this is just a feature suggestion in the future project of JuMP.

If you don't like this issue, please just close it.

Best

**Comment by mlubin** [comment]
> I think JuMP is the one of the greatest OSS I've ever found.

Thank you for the kind words :)

As you noted, the projects you proposed require a substantial amount of work. To the best of my knowledge, none of the core developers have an interest in embedded systems, so this is unlikely to happen without an external effort (which we can provide support for).

**Comment by AtsushiSakai** [comment]
@mlubin  Thank you for your reply. 

>none of the core developers have an interest in embedded systems,
Oh, I see. I hope that an optimization and programming language expert will have an interest. 
Unfortunately I am not the expert about it..
