### ISSUE TITLE
Type-stability issues

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#1824]
I have some type stability issues that I think are the cause of some performance issues I'm having.

Is it reasonable to expect that calls such as `value` and `dual` will return `Float64`s?
```julia
model = JuMP.Model(with_optimizer(Gurobi.Optimizer, OutputFlag=0))
@variable(model, x)
JuMP.optimize!(model)

@code_warntype JuMP.value(x)
Body::Any
705 1 ─ %1 = MathOptInterface.get::Core.Compiler.Const(MathOptInterface.get, false)
    │   %2 = (Base.getfield)(v, :model)::Model                   │╻  owner_model
    │   %3 = %new(MathOptInterface.VariablePrimal, 1)::MathOptInterface.VariablePrimal
    │   %4 = invoke %1(%2::Model, %3::MathOptInterface.VariablePrimal, _2::VariableRef)::Any
    └──      return %4                                           │
```

**Comment by blegat** [comment]
Is it due to the fact that the `moi_backend` type is not concrete (e.g. what is addressed by https://github.com/JuliaOpt/JuMP.jl/pull/1348) ?
JuMP only support Float64 arithmetic at the moment so adding a type assert seems reasonable.

**Comment by odow** [comment]
Yeah it's probably due to the non-concreteness. Here is the function that fails to infer properly when `is_set_by_optimize` is true:

https://github.com/JuliaOpt/JuMP.jl/blob/1d7c5030ce50300f564b1cde1e1ecfabb82c5494/src/JuMP.jl#L573-L581
