### ISSUE TITLE
@lazyconstraint not defined in Julia 1.1

### ISSUE THREAD

**Issue by Jeffguitarhero** [JuliaOpt/JuMP.jl#1880]
Hello

I try to use @lazyconstraint to version Julia 1.1 but obtain this error:
LoadError: UndefVarError: @lazyconstraint not defined

**Comment by odow** [comment]
JuMP no longer supports solver-independent callbacks. See https://github.com/JuliaOpt/JuMP.jl/issues/1553

**Comment by mlubin** [comment]
This is documented in the JuMP 0.19 release notes: https://github.com/JuliaOpt/JuMP.jl/blob/master/NEWS.md.
