### ISSUE TITLE
getsolvetime in JuMP 0.19

### ISSUE THREAD

**Issue by anelkawang** [JuliaOpt/JuMP.jl#1891]
In the previous JuMP version, there is a "getsolvetime" function to get the solving time. Is there a similar functions in JuMP 0.19? I haven't found the descriptions in the document. Thank you.

**Comment by blegat** [comment]
You can do `MOI.get(model, MOI.SolveTime())`

**Comment by blegat** [comment]
We should add a `solve_time` function, this is a good first issue for new contributors.

**Comment by mlubin** [comment]
Implemented in #1928
