### ISSUE TITLE
Too many open files?

### ISSUE THREAD

**Issue by tamasgal** [JuliaOpt/JuMP.jl#1893]
I have a hard to reproduce problem but I hope that someone might have a clue.

I am running realtime event reconstructions from a neutrino detector and I use `JuMP.jl` and `Ipopt.jl` to solve some optimisation problems. The code is running online as said but after a few hours it simply gets stuck at the `optimize!(...)` step (which is executed in an endless loop). I tried to figure out why this happens but it's really hard since it simply stops outputting anything.

Today I added a few lines to save the reconstruction results in a simple text file (before, during the test phase I just examined the live output) and then  saw this:

```
==================================
Waiting for new event...
Got a new ligier message: CHMessage with tag 'IO_EVT' and length 1102
  successfully parsed event: DAQEvent: 27 triggered hits, 56 snapshot hits
  calibrating...
  number of triggered DOMs: 7  -> starting the reco
  -> success (28.22529 ms): -0.12993476532476544
ERROR: LoadError: SystemError: opening file "reco.txt": Too many open files
Stacktrace:
 [1] #systemerror#43(::Nothing, ::Function, ::String, ::Bool) at ./error.jl:134
 [2] systemerror at ./error.jl:134 [inlined]
 [3] #open#309(::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Bool, ::Function, ::String) at ./iostream.jl:283
 [4] #open at ./none:0 [inlined]
 [5] open(::String, ::String) at ./iostream.jl:339
 [6] do_reco(::String, ::Calibration) at /home/off1user/monitoring/D_ORCA004/scripts/roy.jl:61
 [7] top-level scope at none:0
 [8] include at ./boot.jl:326 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] exec_options(::Base.JLOptions) at ./client.jl:267
 [12] _start() at ./client.jl:436
in expression starting at /home/off1user/monitoring/D_ORCA004/scripts/roy.jl:78
```

I don't really understand why this happening, since I properly open and close the text file, so I guess something in `JuMP.jl` or `Ipopt.jl` is not properly closed? I even moved the log-file handling inside the for loop, and now it looks something like this:

```
while true
    ...
    ...
    model = Model(with_optimizer(Ipopt.Optimizer, print_level=print_level, tol=1e-3))
    ...
    optimize!(model)
    ...
    fobj = open("reco.txt", "a")
    write(fobj2, "$(fit_result),$Q\n")
    close(fobj)
    ...
end
```

I think this might be `Ipopt.jl` calling the `ipopt` binary but not sure. I am sure you guys (the JuMP experts) can tell me where to look...

Meanwhile I try to reproduce this in an MWE.

**Comment by odow** [comment]
Might just be a typo, but:
```julia
    fobj = open("reco.txt", "a")
    write(fobj2, "$(fit_result),$Q\n")
              ^
              Is this 2 meant to be there?
    close(fobj)
```

Impossible to say anything more without a MWE. JuMP doesn't open any files, and I don't think Ipopt does either.

**Comment by tamasgal** [comment]
Yea that was just a typo...

I see, thanks for the feedback, I am working on an MWE.

Btw. I forgot that the only other part of the code dealing with I/O is Plots.jl. I’ll investigate that either (that might be more obvious than JuMP or Ipopt)

**Comment by tamasgal** [comment]
Alright, found the root of the problem: 
https://github.com/JuliaPlots/Plots.jl/issues/1723
