### ISSUE TITLE
Refactor sum

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1899]
There is currently three sum methods:
https://github.com/JuliaOpt/JuMP.jl/blob/c01802926c34aa30e5d272ac1063f1595084aa4a/src/operators.jl#L254-L269
The three methods interact the same way with the arrays, they just iterate over it, so the first method should be defined on `AbstractArray`.
Then it has the same signature than the first method so we can just keep the fastest one.
Lastly, the third method could also work for `GenericQuadExpr` so we could widen the type.

**Comment by Peiffap** [comment]
Did #1902 solve this issue?

**Comment by blegat** [comment]
It did !
Closed by #1902
