### ISSUE TITLE
Improve error on getting duals from variables

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/JuMP.jl#1903]
Currently this is a no method error.
It could return a proper error saying that the user should refer to `UpperBoundRef`, `LowerBoundRef` or `FixRef` to get reduced the dual from these constraints.

Example that returns the error:
```julia
m = Model(with_optimizer(SOLVER))
@variable(m, x == 0)
optimize!(m)
dual(x)
```
The error:
```julia
ERROR: MethodError: no method matching dual(::VariableRef)
Closest candidates are:
  dual(::ConstraintRef{Model,NonlinearConstraintIndex,Shape} where Shape<:AbstractShape) at C:\Users\joaquimgarcia\.julia\packages\JuMP\jnmGG\src\nlp.jl:162
  dual(::ConstraintRef{Model,#s1044,Shape} where Shape<:AbstractShape where #s1044<:MathOptInterface.ConstraintIndex) at C:\Users\joaquimgarcia\.julia\packages\JuMP\jnmGG\src\constraints.jl:480
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by barpit20** [comment]
I tried to return a proper error message by adding the following function to `constraints.jl`:

```
function dual(::VariableRef)
    error("To query the dual variables associated a variable bound, first " *
    "obtain a constraint reference using one of UpperBoundRef, LowerBoundRef, " *
    "or FixRef, and then call dual on the returned constraint reference.")
end
```
However, when Precompiling JuMP, I get the following error message -
`ERROR: LoadError: LoadError: UndefVarError: VariableRef not defined`

VariableRef has been directly used in files like `parse_expr.jl` and `quad_expr.jl` but using it in `constraints.jl` gives me the above error.  Can I get some help regarding this?

On adding `include("./variables.jl")`, JuMP precompiles correctly and everything works fine.

**Comment by odow** [comment]
Hi @barpit20 

JuMP loads files in this order
https://github.com/JuliaOpt/JuMP.jl/blob/c01802926c34aa30e5d272ac1063f1595084aa4a/src/JuMP.jl#L466-L468

So if you try to add it to `constraints.jl`, `variables.jl` hasn't been loaded.

Adding it to variables.jl is the way to go.
