### ISSUE TITLE
Set silent

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1920]
We now have a [`Silent` MOI attribute](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.Silent) (even if it is not yet implemented by many optimizers).
It can be set to JuMP with `MOI.set(model, MOI.Silent(), true)` and unset with `MOI.set(model, MOI.Silent(), false)`.
It would be nice to have a `set_silent` and `unset_silent` that redirect to these `MOI.set` calls.

**Comment by mlubin** [comment]
Closed by #1921
