### ISSUE TITLE
Constants modification

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1937]
I am not convinced by the "standard form" naming for coefficient and constant modification for two reasons:
1) It is confusing with the ["standard form" of linear programming](https://en.m.wikipedia.org/wiki/Linear_programming#Standard_form) so it seems that we are first transforming the problem in standard form and then modify the constant that would be in the standard form.
2) `set_standard_form_rhs` only works for three sets: `EqualTo`, `LessThan` and `GreaterThan` while `set_coefficient` was generic and worked for any set. I am not against having an helper for these three common sets but I prefer if we keep the generic `set_coefficient` rather than renaming it for consistency with a function that only works for 3 sets.

I still like the proposal in https://github.com/JuliaOpt/JuMP.jl/issues/1890#issuecomment-471177008.
If we want more user friendly functions for the `EqualTo`, `LessThan` and `GreaterThan`, why not add methods to the functions used for the same set with `SingleVariable` constraints ? It makes sense since applying it to a `VariableRef` or to a `ConstraintRef` with `SingleVariable` function of the same variable would be equivalent. So we would have
* `set_lower_bound(cref, value)` for the `GreaterThan` set.
* `set_upper_bound(cref, value)` for the `LessThan` set.
* `fix(cref, value)` for the `EqualTo` set. It might seems less natural than with the two above but one way to think about it is that it fixes the value of the function to this value.

**Comment by odow** [comment]
I'm semi-supportive of the standard form confusion, and for extending `set_lower_bound`, but the point of `_standard_form_` was to say "Hey! Something unusual here!" to the user.
So, to me, the following is still ambiguous
```julia
@constraint(model, con, 2x + 1 <= 2)
set_upper_bound(con, 3)
```
I would prefer
```julia
set_normalized_upper_bound(con, 3)
```
This would allow us to modify bounds on interval constraints. We would end up with
```julia
set_normalized_coefficient(con, x, 1)
set_normalized_upper_bound(con, 3)
set_normalized_lower_bound(con, 0)  # Errors: "no lower bound exists"
```
To stay consistent, we would need `has_normalized_upper_bound` and `normalized_upper_bound`.

**Comment by joaquimg** [comment]
I would be ok with `normalized_` instead of `standard_form_`
My favourite is `set_function_constant` or possibly `set_normalized_function_constant`, since we built MOI around the function in set concept.

**Comment by blegat** [comment]
> My favourite is `set_function_constant` or possibly `set_normalized_function_constant`, since we built MOI around the function in set concept.

I agree, it has the advantage to work with any set. We could have both `set_normalized_function_constant` (works with any set, that will be used e.g. by ParameterJuMP which wants a solution working for any set) and `set_normalized_upper_bound` (works with Interval and LessThan).
