### ISSUE TITLE
Large optimization models

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/JuMP.jl#1940]
https://github.com/lanl-ansi/MINLPLib.jl/blob/master/instances/minlp/mbtd.jl
When I load the above MINLP in to JuMP, it throws the following error: 
```
ERROR: LoadError: syntax: invalid syntax (memory-error out of gc handles)
```
But after deleting constraints from lines 35 through 44, it loads fine in JuMP. Is this because these constraints are just too long/big for JuMP to be able to load it into the memory? If so, any fix suggestions will be helpful.

**Comment by ndinsmore** [comment]
@harshangrjn I would guess that is a Julia issue rather than a JuMP issue. 

For the very large constraints try breaking them into smaller expressions when parsing then add them together into one expression.

**Comment by ndinsmore** [comment]
I turned that script into normal julia and it seems to parse so that would make my first thought wrong.

**Comment by harshangrjn** [comment]
@odow Any suggestions for this?

**Comment by odow** [comment]
Not in the near term. Make script to re-write the Julia files/edit by hand? I would do what @ndinsmore suggests and break up the long expression into multiple `@NLexpression`s.

**Comment by mlubin** [comment]
IIRC we discussed this with @kaarthiksundar in the gitter channel. We recommended using MathOptFormat to store models. JuMP was not designed to handle machine-generated models like this.

**Comment by mlubin** [comment]
We don't have any plans to improve macro behavior on machine-generated code. You can use the [raw expression input](http://www.juliaopt.org/JuMP.jl/v0.19.2/nlp/#Raw-expression-input-1) format or MathOptFormat.
