### ISSUE TITLE
raw_status

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1942]
We have a [`RawStatusString`](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.RawStatusString) in MOI which can be accessed with `MOI.get(model, MOI.RawStatusString())` but we should have a `raw_status` function similar to `termination_status`/`primal_status`/`dual_status`.

**Comment by rtwalker** [comment]
I'd like to try my hand at this! I'll plan to have something in the next week if it's not too urgent.

**Comment by blegat** [comment]
@rtwalker Sound perfect :)

**Comment by blegat** [comment]
Closed by #1949
