### ISSUE TITLE
all_variables reverts indices on multi-dimensional arrays

### ISSUE THREAD

**Issue by matbesancon** [JuliaOpt/JuMP.jl#1944]
All in the title

MWE:

```julia
julia> m = Model()
julia> @variable(m, 0 <= x[1:2,1:2] <= 2)
2×2 Array{VariableRef,2}:
 x[1,1]  x[1,2]
 x[2,1]  x[2,2]
julia> reshape(JuMP.all_variables(m), (2,2))
2×2 Array{VariableRef,2}:
 x[1,1]  x[2,1]
 x[1,2]  x[2,2]
```

**Comment by odow** [comment]
I would class this as expected behaviour: 

https://github.com/JuliaOpt/JuMP.jl/blob/79f279addd424693c206643a7e3367e8a874f667/src/variables.jl#L774-L777

We don't make any claim on returning shapes. This stems from the fact that JuMP increments the right-hand most index first when creating the variables. So it adds `x[1,1]`, `x[1, 2]`, `x[2,1]`, then `x[2,2]`.

**Comment by matbesancon** [comment]
The increment order is also not following Julia's column-major convention:
```julia
julia> v = [1 2;3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> Iterators.flatten(v) |> collect
4-element Array{Int64,1}:
 1
 3
 2
 4
```

**Comment by odow** [comment]
> The increment order is also not following Julia's column-major convention:

No, it isn't. The justification is that JuMP translates `x[i=1:2, j=3:4]` into
```julia
for i in 1:2
    for j in 3:4
        add_variable(model)
    end
end
```
This allows it to have triangular indexing (e.g., `x[i=1:4; j=i:4]`).

`all_variables` isn't intended as a way to recover structure. For that you're better off looking up `model[:x]`.

**Comment by mlubin** [comment]
The order of variable creation within a single `@variable` call is an internal implementation detail.

**Comment by matbesancon** [comment]
> This allows it to have triangular indexing (e.g., x[i=1:4; j=i:4]).

Ok yes I see the choice.

> The order of variable creation within a single @variable call is an internal implementation detail.

If it gets exposed through `all_variables` it's not strictly an internal behaviour anymore 

For info, this was related to:
https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/166

**Comment by mlubin** [comment]
> If it gets exposed through all_variables it's not strictly an internal behaviour anymore

Only in the same sense that the order of elements returned when looping through an unordered dictionary is externally visible but shouldn't be depended on.
