### ISSUE TITLE
Style Guide makes no recommendation for fields in structs

### ISSUE THREAD

**Issue by freemin7** [JuliaOpt/JuMP.jl#1952]
Your Style Guide is helpful for me as a newcomer. However you could make it even more helpful:
 
``` julia
module SomeModule end
function some_function end
const SOME_CONSTANT = ...
struct SomeStruct end
@enum SomeEnum ENUM_VALUE_A ENUM_VALUE_B
some_local_variable = ...
some_file.jl # Except for ModuleName.jl.
```
does not specify what naming convention to pick for fields.

If you would change it to:
``` julia
module SomeModule end
function some_function end
const SOME_CONSTANT = ...
struct SomeStruct 
   some_field::SomeType
end
@enum SomeEnum ENUM_VALUE_A ENUM_VALUE_B
some_local_variable = ...
some_file.jl # Except for ModuleName.jl.
```

It would be even more helpful

**Comment by odow** [comment]
Great idea! You can even make the change yourself.

1. Go to https://github.com/JuliaOpt/JuMP.jl/blob/master/docs/src/style.md
2. Click the "Edit this file" pencil on the top-right
3. Make the edits you proposed
4. Scroll to the bottom and click "Propose file change"
5. Follow the instructions to create a pull request

**Comment by freemin7** [comment]
Thanks
Pull request created
