### ISSUE TITLE
set_parameter

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1965]
Add a function `set_parameter` that sets the `RawParameter` attribute that will be added in MOI v0.9: https://github.com/JuliaOpt/MathOptInterface.jl/pull/733

**Comment by mlubin** [comment]
Once this is in place, we should strongly consider removing `with_optimizer` (and adding any necessary helper functions to make the transition easier).

**Comment by blegat** [comment]
Closed by #1974
