### ISSUE TITLE
User defined functions propagate to solver

### ISSUE THREAD

**Issue by Wikunia** [JuliaOpt/JuMP.jl#1969]
We are looking for a better way of propagating user defined functions to our solver Juniper. Currently we have our own `register` function where the user has to provide the same arguments as for `JuMP.register` like this:
```julia
register_args = [:special_minimizer_fct, 2, special_minimizer_fct]
JuMP.register(m, register_args...; autodiff=true)

JuMP.set_optimizer(m, with_optimizer(
        Juniper.Optimizer;
        nl_solver=Ipopt.Optimizer,
        registered_functions=[Juniper.register(register_args...; autodiff=true)]
   )
)
```

which isn't an elegant solution for the user. We are using expression graphs to define models inside our solver therefore we need to call `JuMP.register` from inside our solver package. It would be very handy to be able to have access to the args so that we can simply check whether there are user defined functions and then register them or even better if this would be done automatically somehow. 

If someone has an idea of how to implement this in JuMP I'm also happy to integrate it myself. 

We have discussed user defined functions here https://github.com/lanl-ansi/Juniper.jl/issues/118
@mlubin @ccoffrin

**Comment by mlubin** [comment]
The solution to this falls out from making nonlinear "first-class" in JuMP. This is on the past-1.0 part of the roadmap (see slide 21 [here](http://www.juliaopt.org/meetings/santiago2019/slides/miles_lubin.pdf)), which means that it's a relatively large project and we don't have a core developer who plans to work on it soon.

The way we'd like to fix this is to define an expression-graph format at the MOI level so that JuMP can expose its nonlinear constraint data without needing to go through the NLP evaluator. This is up for grabs if you're interested in contributing.

**Comment by odow** [comment]
For anyone moving forward with this: 

Breadcrumbs to the MathOptFormat expression-graph implementation: https://github.com/odow/MathOptFormat.jl/blob/90f8e2b3e60aa4bed349157398c48405a044ea6f/src/MOF/nonlinear.jl

As well as the JSON schema for the MathOptFormat nonlinear nodes:
https://github.com/odow/MathOptFormat/blob/efdbae0c22c4b5f4f78b1086e6615a03173ef335/mof.schema.json#L152-L260
and scalar nonlinear function
https://github.com/odow/MathOptFormat/blob/efdbae0c22c4b5f4f78b1086e6615a03173ef335/mof.schema.json#L319-L336

**Comment by ccoffrin** [comment]
@mlubin I am totally on board with making nonlinear "first-class" in JuMP, I am on the lookout for ways to support such an effort.   In the meantime, can you see a dirty hack that we can use as a stopgap?  e.g. accessing some registered function datastore inside of JuMP (which is meant to be private) and deep copying it into our internal JuMP models?

**Comment by mlubin** [comment]
> can you see a dirty hack that we can use as a stopgap? accessing some registered function datastore inside of JuMP (which is meant to be private) and deep copying it into our internal JuMP models?

Yes, this is stored in the `_NLPData` struct inside the JuMP model. Copying it should more or less work. Obviously no guarantees that this won't break between JuMP releases.
https://github.com/JuliaOpt/JuMP.jl/blob/2201c60e9acf1cb0381369b293230b16227d510d/src/nlp.jl#L68
https://github.com/JuliaOpt/JuMP.jl/blob/2201c60e9acf1cb0381369b293230b16227d510d/src/JuMP.jl#L165

**Comment by mlubin** [comment]
Closing as there's no specific TODO here. Discussions about how to hack JuMP's internals can take place at https://gitter.im/JuliaOpt/JuMP-dev.
