### ISSUE TITLE
Finding all optimal solutions from solver

### ISSUE THREAD

**Issue by artykbayevk** [JuliaOpt/JuMP.jl#1970]
Hi guys,

is it real to find all optimal solutions from solver, if solution not unique??

I'm working with EMD and transportation problem. 

Thanks a lot!

**Comment by blegat** [comment]
Yes, you can do
```julia
using JuMP
model = Model(...)
@variable(model, x)
...
optimize!(model)
MOI.get(model, MOI.VariablePrimal(1), x) # value at first solution
MOI.get(model, MOI.VariablePrimal(2), x) # value at second solution
```
which solver are you using ?

**Comment by artykbayevk** [comment]
@blegat Gurobi optimizer

**Comment by artykbayevk** [comment]
I have a model as a following:


`model = Model(with_optimizer(Gurobi.Optimizer))
@variable(model, X[axes(cost,1), axes(cost,2)] ≥ 0)
@objective(...)

if sum(P.weights) >= sum(Q.weights)
    @constraint(...)
else
    @constraint(....)
end;`

Then I have a solution:

`solution = value.(X)`

As I know, this is a optimized solution, so can I compute any alternative optimal solutions If they exist??

**Comment by blegat** [comment]
You need to check `MOI.get(model, MOI.ResultCount())` to see if Gurobi has any other solution to share. If it is `1˘, it means that there is no other solution

**Comment by artykbayevk** [comment]
@blegat `a = MOI.get(model, MOI.ResultCount())`
this line of code give the error:

'OptimizeNotCalled()

Stacktrace:
 [1] _moi_get_result(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{JuMP._MOIModel{Float64}}}, ::MathOptInterface.ResultCount) at C:\Users\user\.juliapro\JuliaPro_v1.0.3.2\packages\JuMP\jnmGG\src\JuMP.jl:582
 [2] get(::Model, ::MathOptInterface.ResultCount) at C:\Users\user\.juliapro\JuliaPro_v1.0.3.2\packages\JuMP\jnmGG\src\JuMP.jl:597
 [3] top-level scope at In[275]:1'

do you know why it happens??

**Comment by artykbayevk** [comment]
Oops, it solved. But in the output I see only '1'. But I know that there are any other solutions, so is it real to find any other solutions??

**Comment by odow** [comment]
This functionality isn't implemented yet, both at the JuMP level and for individual solvers. See https://discourse.julialang.org/t/multi-cut-benders-decomposition/23472/2

**Comment by artykbayevk** [comment]
Okay, but that implementation couldn't help me. I will try another way for solving this problem
