### ISSUE TITLE
Value for variable at each iteration step

### ISSUE THREAD

**Issue by UlrichThiele** [JuliaOpt/JuMP.jl#1971]
I am trying to solve Liquid-Liquid Equilibrium problems with JuMP/Ipopt.
Instead of using conventional models (Unifac, Uniquac, NRTL) to calculate the activity coefficient (gamma_i), I am using a Quantumchemical Software that is triggered by a separate function.

An LLE is found, when xp1_i * gamma1_i+ xp2_i * gamma2_i
I have enough constraints and equations to describe the entire Equation System.
My main problem is that gamma_i is a function of x_i, meaning that I need to have the solver retrieve the estimated x_i value and input it to my custom function that triggers the external software that calculates gamma_i.

Is this possible? See my code below

```julia
using JuMP
using Ipopt



m = Model(solver=IpoptSolver(print_level=0))


@variable(m, xp1[1:n_komp])
@variable(m, xp2[1:n_komp])
@variable(m, x[1:n_komp])
@variable(m, y[1:n_komp])
@variable(m, F)
@variable(m, V)
@variable(m, g1[1:n_komp])
@variable(m, g2[1:n_komp])


@NLobjective(m, Min, V+F-1)


@constraint(m, sum(x) == 1)
@constraint(m, sum(y) == 1)
@constraint(m, sum(xp1) == 1)
@constraint(m, sum(xp2) == 1)
@constraint(m, K.*x.-y .== 0)
@constraint(m, F.*x+V*y.-z .== 0)
@constraint(m, xp1.*g1 .==  xp2.*g2 )

@constraint(m, g1 .==  GAMMAP1(t, n_komp, getvalue(xp1))
@constraint(m, g2 .==  GAMMAP1(t, n_komp, getvalue(xp2))

```

**Comment by odow** [comment]
This question has been asked on Discourse: https://discourse.julialang.org/t/jump-variable-constraint-depending-on-variable/24313

In order to avoid splitting the discussion, I'm going to close this issue. Any replies should be posted on the Discourse post.
