### ISSUE TITLE
length(hess_I) > 0

### ISSUE THREAD

**Issue by renkekuhlmann** [JuliaOpt/JuMP.jl#1981]
Hi,
I run into the assertion
https://github.com/JuliaOpt/JuMP.jl/blob/d8985728c863725537b98bf1e441b99f86d9c2b5/src/nlp.jl#L284

What does that assertion mean? How can I fix my model? The model uses a lot of nonlinear constraints that are built from nonlinear expressions, which appear as subexpressions in the model output. Is this a problem?

**Comment by mlubin** [comment]
> What does that assertion mean?

That appears to be a bug.

> How can I fix my model?

Share an example that reproduces the assertion failure, so that we can fix the bug :).

**Comment by renkekuhlmann** [comment]
Okay, my bad. In the creation of the nonlinear expression there was an `==`. I used that expression than to create a constraint like `expr == 0`. So there where two `==`. I didn't noticed that because the expressions are printed just as `subexpression[801] - 0.0 = 0` in the model output etc.
