### ISSUE TITLE
Rename m -> model in test utilities

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#1992]
Rename `m` to `model` in
https://github.com/JuliaOpt/JuMP.jl/blob/36dc0863b5fa6d73bea904f0824dfb0e25cb68d4/test/utilities.jl#L16
then update `m` to `model` in all tests using this macro.

**Comment by rohit-mp** [comment]
Hey @blegat, I'm new to open-source contributions and would like to give this a go. Is there a specific branch you'd like the PR to be addressed to or would the master branch be fine?

**Comment by joaquimg** [comment]
Hi @rohit-mp, welcome!
You can create a fork, commit in your master and open a PR against this repo.
