### ISSUE TITLE
callback with MOI

### ISSUE THREAD

**Issue by alirouhani** [JuliaOpt/JuMP.jl#2020]
Dear community,
I use CPLEX 12.8 and JuMP v0.19. Due to major changes in the new version, I do not succeed to add callbacks. The release notes say that callbacks are now solver-specific, however, I cannot find something about that in the documentation of CPLEX.jl nor the documentation of MathOptInterface. I have some questions:
1. I found that it's possible to use MOI as a transition from CPLEX to JuMP. So, could I use both MOI and JuMP in an integrated model? (I mean that the main problem code as JuMP, and code callback procedure based on MOI.CPLEX)
2. How can uninstall JuMP v0.19 and install JuMP v0.18?
3. Could you help me to use callback procedure in MOI.CPLEX by sharing a simple example?

**Comment by odow** [comment]
We're still in the process of figuring out callbacks. For now, downgrade to JuMP 0.18:

```Julia
] add JuMP#release-0.18
```

**Comment by alirouhani** [comment]
@odow Many thanks, it does well

**Comment by mlubin** [comment]
Callbacks are on the JuMP [milestone page](http://www.juliaopt.org/JuMP.jl/dev/roadmap/); we're very aware that they're missing.
