### ISSUE TITLE
TimeLimitSec

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#2031]
Now that a [TimeLimitSec](https://www.juliaopt.org/MathOptInterface.jl/dev/apireference/#MathOptInterface.TimeLimitSec) attribute in MOI, we could have JuMP function with a syntax more user friendly than `MOI.get(model, MOI.TimeLimitSec())` and `MOI.set(model, MOI.TimeLimitSec(), value)`

**Comment by Wikunia** [comment]
`JuMP.get_time_limit()` and `JuMP.set_time_limit(limit)` ?

**Comment by blegat** [comment]
`time_limit` instead `get_time_limit` would be more consistent with other JuMP functions, e.g. we have `value` instead of `get_value`.

**Comment by Wikunia** [comment]
This can be closed, right?

**Comment by blegat** [comment]
Indeed, thanks!
