### ISSUE TITLE
Simple Example not Working

### ISSUE THREAD

**Issue by EconometricsBySimulation** [JuliaOpt/JuMP.jl#2038]
Working through some basic intro to JuMP and finding that the "simple example" does not work.

http://www.juliaopt.org/JuMP.jl/v0.13/quickstart.html#simple-example

```
status = solve(m)
ERROR: `solve` has been replaced by `optimize!`. Note that `solve` used to return a `Symbol` summarizing the solution while `optimize!` returns nothing and the status of the solution is queried using `termination_status`, `primal_status` and `dual_status`.

status = optimize!(m)
ERROR: NoOptimizer()
Stacktrace:
 [1] #optimize!#79(::Bool, ::Bool, ::Function, ::Model, ::Nothing) at C:\Users\...\.julia\packages\JuMP\ibcEh\src\optimizer_interface.jl:129
 [2] optimize! at C:\Users\...\.julia\packages\JuMP\ibcEh\src\optimizer_interface.jl:105 [inlined] (repeats 2 times)
 [3] top-level scope at none:0
```

**Comment by mlubin** [comment]
@EconometricsBySimulation how did you find that link to the documentation? As the URL suggests, it applies to JuMP version 0.13 which is very old. We link to the latest documentation in the README at https://github.com/JuliaOpt/JuMP.jl.

**Comment by EconometricsBySimulation** [comment]
Ah thanks, that makes sense, I am sure it is whatever popped up when I googled `Julia Jump Simple Example`.
