### ISSUE TITLE
Use of internal objects does not work anymore

### ISSUE THREAD

**Issue by lgo0815** [JuliaOpt/JuMP.jl#2046]
Hello,

I recently switched to v0.20. I'm constructing all my variables and equations via the internal objects like this (I once also made a [related post](https://discourse.julialang.org/t/speed-up-jump-model-storing-objects-as-indexed-tables/24760/4) on the Julia board.)

```julia
using JuMP
using MathOptInterface
using Gurobi
using GLPK
const MOI = MathOptInterface

model = Model() 

Variable_info = VariableInfo(true, 0, false, NaN, false, NaN, false, NaN, false, false)
JuMP.build_variable(error, Variable_info,"x")
JuMP.build_variable(error, Variable_info,"y")
add_constraint(model, build_constraint(_error, x + y, MOI.EqualTo(1.0)))

@objective(model, Min, x)
optimize!(model,with_optimizer(GLPK.Optimizer))
```

However, although they are still included in the documentation, none of these functions is supported anymore. I also tried to import the functions specifically without any success.

**Comment by blegat** [comment]
This should work:
```julia
using JuMP
using MathOptInterface
using Gurobi
using GLPK
const MOI = MathOptInterface

model = Model() 

Variable_info = VariableInfo(true, 0, false, NaN, false, NaN, false, NaN, false, false)
x = JuMP.add_variable(model, JuMP.build_variable(error, Variable_info), "x")
y = JuMP.add_variable(model, JuMP.build_variable(error, Variable_info), "y")
add_constraint(model, build_constraint(error, x + y, MOI.EqualTo(1.0)))

@objective(model, Min, x)
optimize!(model,with_optimizer(GLPK.Optimizer))
```
but this API didn't change between JuMP v0.19 and JuMP v0.20, your code does not run on JuMP v0.19 either.

**Comment by blegat** [comment]
It is documented in the extension section: https://www.juliaopt.org/JuMP.jl/v0.20.0/extensions/#JuMP.build_constraint
It's not really internal function as it's not starting with an underscore but it's meant more for JuMP extension than for casual usage.

**Comment by lgo0815** [comment]
Yes, I have a strong sense, that I updated to 0.2 from a version below 0.19, which caused the error ...
