### ISSUE TITLE
JuMP upgrade problem to V0.20

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaOpt/JuMP.jl#2050]
I upgraded to JuMP V0.20. Various packages do not install anymore:

Clp, KNITRO,CPLEX,CSDP,Xpress,QSQP,SDPA,PROXSDP,SeDuMi
(add package errors)
When will Clp, CPLEX, and Xpress be available for JuMP V0.20
What about SCIP?
thank you for your answer

**Comment by odow** [comment]
See: https://github.com/JuliaOpt/MathOptInterface.jl/issues/736.

These packages will be, or are in the process of, being updated (but there is no hard time-line). If you need a solver that hasn't been updated, I suggest you continue to use JuMP 0.19. 

In addition, if you have the development time, we'd appreciate the help updating and we can help along the way.

**Comment by mlubin** [comment]
Most of these solvers have been updated to support JuMP 0.20. The status of the remaining solvers should be tracked on their respective package repositories, e.g., https://github.com/JuliaOpt/Xpress.jl/pull/44.
