### ISSUE TITLE
Variable variable name

### ISSUE THREAD

**Issue by yakyak462** [JuliaOpt/JuMP.jl#2052]
New to Julia/Metaprogramming. Is there a way to do something like
```jl
function add(model, v::String)
    @variable(model, v)
end
```
The result I want is that `model[Symbol(v::String)]` to work like normal.

**Comment by odow** [comment]
@yakyak462, you can go
```Julia
using JuMP
function add(model, v)
    x = @variable(model, base_name = v)
    model[Symbol(v)] = x
    return x
end
model = Model()
x = add(model, "abc")
model[:abc] == x  # True!
```
This is effectively what JuMP does behind the scenes.

p.s. These usage-type questions are better asked on the Discourse forum: https://discourse.julialang.org/c/domain/opt

**Comment by yakyak462** [comment]
@odow Right answer to the direct question I asked, but does this work with SDDP? Looks like you're using anonymous JuMP variables to me https://github.com/odow/SDDP.jl/issues/250#issuecomment-526712733? Am I misunderstanding/is there a non anonymous way? Will use Discourse forum for future questions.

**Comment by odow** [comment]
No, this won't work with SDDP.jl. My previous answer uses anonymous variables.

I'll close this issue, but let's take the discussion back to https://github.com/odow/SDDP.jl/issues/250. It would be helpful if you could post a simplified version of what you are trying to achieve, and we'll see if there is a way to do it.
