### ISSUE TITLE
Allow `digits` with `round`

### ISSUE THREAD

**Issue by karajan9** [JuliaOpt/JuMP.jl#2064]
I have a cost function where I want to use `round` in. A MWE would be
```julia
using JuMP
using Ipopt

cost(d) = round(d, digits = 1) + d

model = Model(with_optimizer(Ipopt.Optimizer, print_level = 0))
JuMP.register(model, :cost, 1, cost, autodiff = true)

@variable(model, 2.0 <= d <= 20)
set_start_value(d, 10.1)
@NLobjective(model, Min, cost(d))
optimize!(model)
```
This errors with `no method matching round(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(cost),Float64},Float64,1}, ::RoundingMode{:Nearest})`.

However, if I use `cost(d) = round(d * 10) / 10 + d` instead, it works fine and as expected. Since there seems to be no reason to disallow the functionality, it would be nice to allow `round(d, digits = 1)` as well, as it is the straightforward way to implement this functionality.

**Comment by blegat** [comment]
Seems like an issue to be fixed [in ForwardDiff](https://github.com/JuliaDiff/ForwardDiff.jl/blob/c374b69f47095aef60a5486065ddc6fe29c32e9f/src/dual.jl#L271-L272) rather than JuMP.

**Comment by karajan9** [comment]
Ah, thanks for the info, I'll open an issue there.

Related to that, is there a reason that `@NLconstraint(model, d == round(d))` does not work? Is there a fundamental issue or could I try to implement that?

**Comment by odow** [comment]
> is there a reason that @NLconstraint(model, d == round(d)) does not work?

You will need to use `JuMP.register` as you did above.

In addition, you should read: https://discourse.julialang.org/t/jump-piecewise-linear-cost-function/27269. `round(x)` is not a convex function.

**Comment by blegat** [comment]
Closing as there does not seem to be anything we can do in this package.
