### ISSUE TITLE
Switching solver malfunctioning

### ISSUE THREAD

**Issue by haoxiangyang89** [JuliaOpt/JuMP.jl#2074]
Previous to v.0.19 to switch from a solver to another, or modify the solver parameter, all we have to do is: (the following is an example)
```julia
mp = Model(solver = GurobiSolver(OutputFlag = 0));
mp.solver = IpoptSolver(print_level = 0);
```
Once JuMP was upgraded, MOI employs the solver in this way:
```julia
mp = Model();
optimize!(with_optimizer(Gurobi.Optimizer, OutputFlag = 0));
```

Now if I change the solver by running optimize! again, it throws me an error. Here is the code I run to generate this error:
```julia
using JuMP, Ipopt, Gurobi;
mp = Model();
@variable(mp, x1 >= 0);
@variable(mp, x2 >= 0);
@constraint(mp, x1 + 2x2 <= 1);
@constraint(mp, x2 + 2x1 <= 1);
@objective(mp, Max, x1 + x2);
optimize!(mp, with_optimizer(Gurobi.Optimizer));
optimize!(mp, with_optimizer(Ipopt.Optimizer));
```
Here is the printout of the error. The first solve is successful and then the second fails. If I want to solve the model again, I have to use Gurobi.Optimizer without changing any parameters/to another solver. It appears the same if I set up an optimizer when setting up the JuMP model instead of leaving it blank initially.

> ERROR: An optimizer factory cannot both be provided in the `Model` constructor and at the `optimize` call.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] #optimize!#78(::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(optimize!), ::Model, ::OptimizerFactory) at /home/haoxiang/.julia/packages/JuMP/iGamg/src/optimizer_interface.jl:121
>  [3] optimize!(::Model, ::OptimizerFactory) at /home/haoxiang/.julia/packages/JuMP/iGamg/src/optimizer_interface.jl:111
>  [4] top-level scope at REPL[162]:1

**Comment by blegat** [comment]
You can do
```julia
optimize!(mp, with_optimizer(Gurobi.Optimizer))
set_optimizer(mp, with_optimizer(Ipopt.Optimizer))
optimize!(mp)
```
The error message could be improved. Or we could even make it work.

**Comment by mlubin** [comment]
The second argument to `optimize!` makes it look like the optimizer is tossed out after the solve. Given that this is not how it actually works, maybe we should remove this method and force a call to `set_optimizer`.

**Comment by odow** [comment]
:+1: on removing this in favor of `set_optimizer`
