### ISSUE TITLE
Object function may include some third-party library

### ISSUE THREAD

**Issue by kuro26** [JuliaOpt/JuMP.jl#2078]
My object function is calculated using DifferntialEquations, which may include some third-party library.<br />
My code throws out a `ForwardDiff.Dual` error as described in the document, and I check the [ForwardDiff.jl Document](http://www.juliadiff.org/ForwardDiff.jl/v0.10.2/user/limitations.html), and I gauss it is for the third-party code included. <br />
And I am thinking if I should give a finite differencing function myself?

**Comment by odow** [comment]
Take a read of the user-defined function documentation: https://www.juliaopt.org/JuMP.jl/v0.20.0/nlp/#User-defined-Functions-1

> And I am thinking if I should give a finite differencing function myself?

If it isn't differentiable with ForwardDiff, you will need to supply the gradients yourself.

p.s. usage questions like this are better posted on our discourse forum: https://discourse.julialang.org/c/domain/opt. We try to reserve JuMP GitHub issues for bug reports and feature requests.

**Comment by kuro26** [comment]
Thank you for your reply! sorry for posting such problem here
