### ISSUE TITLE
Problem when defining constraints involving symmetric variables

### ISSUE THREAD

**Issue by spironio** [JuliaOpt/JuMP.jl#2102]
Let us define two symmetric matrices:
```julia
using JuMP
m=Model()
@variable(m,x[1:2,1:2],Symmetric)
@variable(m,y[1:2,1:2],Symmetric)
```
Then
```julia
-x -y
```
correctly returns
```
2×2 LinearAlgebra.Symmetric{GenericAffExpr{Float64,VariableRef},Array{GenericAffExpr{Float64,VariableRef},2}}:
 -x[1,1] - y[1,1]  -x[1,2] - y[1,2]
 -x[1,2] - y[1,2]  -x[2,2] - y[2,2]
```

However,
```julia
@constraint(m, -x -y .>= 0)
```
gives
```
2×2 Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},2}:
 -x[1,1] - y[1,1] >= 0.0    -x[1,2] - 2 y[1,2] >= 0.0
 -x[1,2] - 2 y[1,2] >= 0.0  -x[2,2] - y[2,2] >= 0.0
```
Notice the wrong 2 in front of y[1,2].
If instead I define the constraint as
```julia
@constraint(m, 0 -x -y .>= 0)
```
it works fine:
```
2×2 Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},2}:
 -x[1,1] - y[1,1] >= 0.0  -x[1,2] - y[1,2] >= 0.0
 -x[1,2] - y[1,2] >= 0.0  -x[2,2] - y[2,2] >= 0.0
```
More problematically (this is how I noticed this problem), suppose I do
```julia
using LinearAlgebra
@constraint(m, I -x -y in PSDCone())
```
then I get
```
[-x[1,1] - y[1,1] + 1   -x[1,2] - 2 y[1,2]  ;
 -x[1,2] - 2 y[1,2]     -x[2,2] - y[2,2] + 1] in PSDCone()
```
again with a wrong 2 in front of y[1,2].
While
```julia
id = [1 0; 0 1]
@constraint(m, id -x -y in PSDCone())
```
gives as expected
```
[-x[1,1] - y[1,1] + 1  -x[1,2] - y[1,2]    ;
 -x[1,2] - y[1,2]      -x[2,2] - y[2,2] + 1] in PSDCone()
```
The above issue does not happen if the matrices are not declared symmetric:
```julia
@variable(m,u[1:2,1:2])
@variable(m,v[1:2,1:2])
@constraint(m,I-u-v in PSDCone())
```
gives
```
[-u[1,1] - v[1,1] + 1  -u[1,2] - v[1,2]    ;
 -u[2,1] - v[2,1]      -u[2,2] - v[2,2] + 1] in PSDCone()
```

**Comment by odow** [comment]
```Julia
using JuMP
model = Model()
@variable(model, x[1:2,1:2], Symmetric)
@variable(model, y[1:2,1:2], Symmetric)
@constraint(model, -x .- y .>= 0)

**Comment by odow** [comment]
The issue is coming from: 
https://github.com/JuliaOpt/JuMP.jl/blob/6968fbee5450f5da9cd708f1d494d2e61d2f8c01/src/parse_expr.jl#L269-L271

```Julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, x[1:2, 1:2], Symmetric);

julia> @constraint(model, -x - x .>= 0)
2×2 Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},2}:
 -2 x[1,1] ≥ 0.0  -3 x[1,2] ≥ 0.0
 -3 x[1,2] ≥ 0.0  -2 x[2,2] ≥ 0.0

julia> A = -x
2×2 Symmetric{GenericAffExpr{Float64,VariableRef},Array{GenericAffExpr{Float64,VariableRef},2}}:
 -x[1,1]  -x[1,2]
 -x[1,2]  -x[2,2]

julia> JuMP.destructive_add!(A, -1, x)
2×2 Array{GenericAffExpr{Float64,VariableRef},2}:
 -2 x[1,1]  -3 x[1,2]
 -3 x[1,2]  -2 x[2,2]
```

We probably need methods for symmetric matrices.

**Comment by spironio** [comment]
> You likely need the `.-` broadcasting `-` in the constraint:

Indeed with the broadcasting, the issue does not arises. However broadcasting should not be used in SDP constraints such as
`@constraint(m, I -x -y in PSDCone())`
This issue can lead to wrong results if one is not aware of it.

**Comment by spironio** [comment]
> We probably need methods for symmetric matrices.

When defining a matrix to be PSD such as in
`@variable(model, x[1:2,1:2], PSD)`
it is by definition symmetric. Given how ubiquitous semidefinite programming, this issue is really annoying: it will not lead to any error message, but give rise to wrong optimization results. People should be made aware of it if it is not fixed.

**Comment by odow** [comment]
> However broadcasting should not be used in SDP constraints such as

Broadcasting appears to fix the issue as a temporary work-around:
```Julia
julia> using JuMP

julia> using LinearAlgebra

julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
varialeModel mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x[1:2, 1:2], Symmetric)
2×2 Symmetric{VariableRef,Array{VariableRef,2}}:
 x[1,1]  x[1,2]
 x[1,2]  x[2,2]

julia> @constraint(model, I - x .- x in PSDCone())
[-2 x[1,1] + 1  -2 x[1,2]    ;
 -2 x[1,2]      -2 x[2,2] + 1] ∈ PSDCone()

julia> @constraint(model, I - x - x in PSDCone())
[-2 x[1,1] + 1  -3 x[1,2]    ;
 -3 x[1,2]      -2 x[2,2] + 1] ∈ PSDCone()
```

> Given how ubiquitous semidefinite programming, this issue is really annoying: it will not lead to any error message, but give rise to wrong optimization results. People should be made aware of it if it is not fixed.

I've labelled this as a bug. Thanks for finding it!

**Comment by spironio** [comment]
> Broadcasting appears to fix the issue as a temporary work-around:

Indeed!
I'm must confess that I'm new to Julia and don't yet understand exactly when I should use broadcasting and when not. 
For instance
`@constraint(m, - x .- y + I in PSDCone())`
works. But
`@constraint(m, - x .- y .+ I in PSDCone())`
gives an error message. So 
`@constraint(m, - x - y + I in PSDCone())`
looks cleaner to me than the first solution with mixed used of broadcasting. 

> I've labelled this as a bug. Thanks for finding it.

Thanks to you!

**Comment by blegat** [comment]
The issue is that the broadcasting will call `JuMP.add_to_expression!` at `[1, 2]` and `[2, 1]` but it will modify twice the same entry because of the symmetry. @spironio Thanks for reporting this!

**Comment by mlubin** [comment]
Added to the 0.21 milestone because silently returning the wrong answer is very bad.
