### ISSUE TITLE
basic.jl example model is not working

### ISSUE THREAD

**Issue by skad00sh** [JuliaOpt/JuMP.jl#2112]
I found that in [example basic.jl](https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/basic.jl):

`model = Model(GLPK.Optimizer)`

is not working.
I checked GLPK examples. In model, _with_optimizer_ was used which solved the problem.

`model = Model(with_optimizer(GLPK.Optimizer))`

Edit:
I check [the blame for basic.jl](https://github.com/JuliaOpt/JuMP.jl/blame/9baede15489528e09c6fb66dab935d6d44bb4fc0/examples/basic.jl). `with_optimizer` was removed. Can someone please explain to me why it was removed?
I am a pretty newbie to this 😢

**Comment by odow** [comment]
You need to look at the examples corresponding to the most recent release of JuMP, not the `master` branch. You want:
https://github.com/JuliaOpt/JuMP.jl/tree/release-0.20/examples
(There is a link in the README under "Latest release")

The next version of JuMP removes the need for `with_optimizer`.

**Comment by odow** [comment]
> Can someone please explain to me why it was removed?

See the discussion here: https://github.com/JuliaOpt/JuMP.jl/pull/2090
