### ISSUE TITLE
Best way to retrieve the backend solver type from an existing model

### ISSUE THREAD

**Issue by diam** [JuliaOpt/JuMP.jl#2113]
Bonjour,

I have a program which take an option for the external MIP to be used with jump (in the with_optimizer(...) parameter). So my model can be one of the following ones:

```
 model = Model(with_optimizer(CPLEX.Optimizer))
 model = Model(with_optimizer(Clp.Optimizer))
 model = Model(with_optimizer(GLPK.Optimizer))
```

Later in the code (for unit testing purpose) I'd like to know which backend solver has been used for creating the model. With some previous version of JuMP (e.g 0.19.4) I used the following testing code.

```
backend_model = JuMP.backend(sol.solver.mip_model).optimizer.model
@test typeof(backend_model) ==  Clp.Optimizer
```
But that doesn't work any more (since JuMP-0.20.1 or so).
So what is the standard way to retrieve what we put into the first `with_optimizer`

-- Maurice

**Comment by odow** [comment]
There is no standard way. If you control the model building, the easiest way is probably to just store a copy yourself in the `.ext` dictionary:
```Julia
function build_my_model(user_optimizer)
    model = Model(user_optimizer)
    model.ext[:user_optimizer] = user_optimizer
    # ...
    return
end

m = build_my_model(GLPK.Optimizer)
@test m.ext[:user_optimizer] == GLPK.Optimizer
```

Note that `with_optimizer` will be deprecated in the next release of JuMP.

**Comment by mlubin** [comment]
What about looking at the `solver_name`?

**Comment by diam** [comment]
mlubin:
> What about looking at the solver_name?

Thank you very much: that's what I was looking for (it wasn'd documented in 0.19.x version of JuMP, but it is in 0.20.1 version).

odow:
> model = Model(user_optimizer)
>     model.ext[:user_optimizer] = user_optimizer

Thank you very much too, I wasn't aware of that internal Dict object in Model type. It would also has been useful in JuMP-0.18 for passing application specific informations to some methods for witch only Model could be passed as parameter. The `ext` Dict would have solved my problem if `solver_name` didn't exist.

*(I hope you can understand my english ;-)*
-- Maurice

**Comment by mlubin** [comment]
> (I hope you can understand my english ;-)

Tout à fait! :)
