### ISSUE TITLE
Use SemVer (Semantic Versioning)

### ISSUE THREAD

**Issue by igormcoelho** [JuliaOpt/JuMP.jl#2118]
Welcome to JuMP! You can use this Github issue to suggest a new feature for JuMP.

**Is your feature request related to a problem? Please describe.**
I'm just arriving here, it was very strange to me the fact that 0.18, 0.19 and 0.20 were so radically different. In my opinion, this was the case for having 1.X, then 2.X, changing major numbers, with Semantic Versioning. I was also just learning Julia, so pehaps even the package manager will figure out automatically when you fix some bug, or add some feature, to automatically "upgrade" it, but not just upgrade when a new major comes out (as they could break other packages, as it broke mine, something related to Math Solvers, that changed a lot I guess).

**Describe the solution you'd like**
Use semantic versioning. When new big things come out, change major. When small things are added up, improve second number (minor). When just bugs are fixed, change third number.

**Describe alternatives you've considered**
Perhaps you already have a good strategy for this, that I'm not aware of... if that's the case, feel free to desconsider this.

**Additional context**
Discussed slightly here on this closed PR: https://github.com/JuliaOpt/JuMP.jl/pull/2116

> Thanks for contributing to JuMP!

Congratulations for this nice project!

**Comment by odow** [comment]
JuMP uses SemVer. See point 4 https://semver.org.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

We hope to release version 1.0.0 of JuMP in the near future. After which, the API will stabilize. One reason for removing `with_optimizer` now is precisely because we won't be able to after 1.0.

**Comment by mlubin** [comment]
See also the roadmap for JuMP 1.0: http://www.juliaopt.org/JuMP.jl/dev/roadmap/

**Comment by odow** [comment]
Closing since there doesn't seem to be anything actionable here. If you have suggestions for how the README could be clarified, please make a pull request :)
