### ISSUE TITLE
Working with block arrays

### ISSUE THREAD

**Issue by asavasci** [JuliaOpt/JuMP.jl#2122]
I am working on a formulation based on block arrays consisting of quadratic expressions and zero blocks. I wanted to ask about if there is an efficient way of formulating this problem. 

For example 
x1 = [ P[1] dG[1] P[2] dG[2] P[3] dG[3] ]

let the JuMP expression be
X1 = x1'*x1

A = BlockArray{JuMP.GenericQuadExpr{Float64,Variable}}(undef, [6,6,6,6,12,12], [6,6,6,6,12,12])
setblock!(A, X1, 1, 1)

setblock!(A, spzeros(6,6), 1, 2)
setblock!(A, spzeros(6,6), 1, 3)
setblock!(A, spzeros(6,6), 1, 4)
setblock!(A, spzeros(6,12), 1, 5)
setblock!(A, spzeros(6,12), 1, 6)
...

This is working well, but embedding zero blocks after that seems not to be efficient . However, if matrix A could be initialized as sparse block arrays as 

A = BlockArray{Float64}(spzeros(48,48), [6,6,6,6,12,12], [6,6,6,6,12,12])

then, it would be easier to embed JuMP expression blocks. This is not allowed because of the type conversion limitation. Is there any other efficient way to work around this limitation?  I am using JuMP 0.18.

**Comment by blegat** [comment]
> This is not allowed because of the type conversion limitation

Could you elaborate on this?

**Comment by asavasci** [comment]
When matrix A initialized as 

A = BlockArray(spzeros(48,48), [6,6,6,6,12,12], [6,6,6,6,12,12])

and then setting the block

setblock!(X, X1, 1, 1)

gives this output message

MethodError: Cannot `convert` an object of type JuMP.GenericQuadExpr{Float64,Variable} to an object of type Float64
Closest candidates are:
  convert(::Type{T<:Number}, !Matched::T<:Number) where T<:Number at number.jl:6
  convert(::Type{T<:Number}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T<:Number}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...

Isn't [#2107 ](https://github.com/JuliaOpt/JuMP.jl/pull/2107) related to doing arithmetic operations with base types and JuMP variable types ? 

Can this type limitation still be considered under  [#2107 ](https://github.com/JuliaOpt/JuMP.jl/pull/2107) ?

**Comment by blegat** [comment]
If you expect the block array to hold JuMP expression, you should specify it when you build it with something like `BlockMatrix{JuMP.QuadExpr}(...)`

**Comment by asavasci** [comment]
Yes that is correct, but defining matrix A and initializing with zeros seems not possible as 

`A = BlockArray{JuMP.GenericQuadExpr{Float64,Variable}}(spzeros(48,48), [6,6,6,6,12,12], [6,6,6,6,12,12])`

giving output

`MethodError: no method matching BlockArray{JuMP.GenericQuadExpr{Float64,Variable},N,R,BS} where BS<:BlockArrays.AbstractBlockSizes{N} where R<:(AbstractArray{#s14,N} where #s14<:AbstractArray{JuMP.GenericQuadExpr{Float64,Variable},N}) where N(::SparseMatrixCSC{Float64,Int64}, ::Array{Int64,1}, ::Array{Int64,1})`

What I want to do is to avoid to filling blocks with zeros, after defining the matrix A.

**Comment by blegat** [comment]
What about doing something like `BlockArray(spzeros(QuadExpr, 48, 48), QuadExpr[6,6,6,6,12,12], QuadExpr[6,6,6,6,12,12])` ?

**Comment by asavasci** [comment]
It works removing the QuadExpr definitions on blocks sizes

`BlockArray(spzeros(QuadExpr, 48, 48), [6,6,6,6,12,12], [6,6,6,6,12,12])`

Thanks for your time
