### ISSUE TITLE
Performance of pairs interface

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#2125]
We spend allocation constructing Pair{VariableRef, Float64} in JuMP's operator code:
```julia
julia> a() = (model = Model(); x = @variable(model); @time x => 1.0)
a (generic function with 1 method)

julia> a()
  0.000000 seconds (1 allocation: 32 bytes)
noname => 1.0

julia> a()
  0.000000 seconds (1 allocation: 32 bytes)
noname => 1.0
```
Using tuples instead of pairs yields the same result. We might need to use a different interface for the AffExpr constructor or avoid using it to improve performance. In particular, it is currently slower to do `x - y` that `add_to_expression!(x + 0,-1,y)` where x and y are variables, this shouldn't be and is due to the constructor `AffExpr(0.0, x => 1.0, y => -1.0)` which is slow

**Comment by mlubin** [comment]
That's unfortunate. Maybe we should write out explicit constructors for quickly constructing AffExprs with small numbers of elements, like `build_aff_expr(0.0, 1.0, x, -1.0, y)`.
