### ISSUE TITLE
Where can I find a list of all currently working optimizers?

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaOpt/JuMP.jl#2144]
I bet this question has been asked a thousand times, yet I can't find any information using Google. 

http://www.juliaopt.org/packages/ shows all optimizers, including those that do not work with JuMP.jl. I tried the repositories in https://github.com/JuliaOpt, but they are not tagged whether they work with JuMP.jl or not (and many of them are not optimizers at all). 

In particular, I want to find an optimizer for non-linear problems that is using gradients and supports non-linear constraints. I guess there must be one because I distinctly remember solving such problems by hand back at the time when I was studying.

**Comment by blegat** [comment]
You can find the list at https://www.juliaopt.org/JuMP.jl/dev/installation/#Getting-Solvers-1
