### ISSUE TITLE
Where can I find explanation what does mean the columns in the optimization progress table?

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaOpt/JuMP.jl#2145]
The table looks like this (at least it does so for `Ipopt` optimizer. I don't know if they are optimizer-specific, or not.
```
(...)
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
 530  3.3731762e-02 8.98e-07 9.17e-04 -11.0 9.17e-04    -  1.00e+00 1.00e+00h  1
 531  3.3730863e-02 8.98e-07 9.17e-04 -11.0 9.17e-04    -  1.00e+00 1.00e+00h  1
 532  3.3729964e-02 8.99e-07 9.18e-04 -11.0 9.17e-04    -  1.00e+00 1.00e+00h  1
 533  3.3729064e-02 9.00e-07 9.18e-04 -11.0 9.18e-04    -  1.00e+00 1.00e+00h  1
 534  3.3728163e-02 9.01e-07 9.19e-04 -11.0 9.18e-04    -  1.00e+00 1.00e+00h  1
(...)
```

`iter` is iteration number. `objective` is a current value of the objective function. And that is pretty all I can understand. Can you help me with the other columns?

**Comment by mlubin** [comment]
All of the output tables are specific to the solver. You should consult the corresponding solver's documentation.
