### ISSUE TITLE
Rename `set_parameter` to `set_attributes`

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#2149]
https://github.com/JuliaOpt/JuMP.jl/pull/2141 adds `optimizer_with_attributes`, so one can go:
```Julia
model = Model(optimizer_with_attributes(Gurobi.Optimizer, "OutputFlag" => 0))
```
However, we still have `set_parameter`, which means
```Julia
model = Model(Gurobi.Optimizer)
set_parameter(model, "OutputFlag", 0)
```

It would be more consistent if we renamed `set_parameter` to `set_attribute`, with the implication that passing a string was sugar for passing `MOI.RawParameter`.

In addition, we should add `get_attribute`.

**Comment by mlubin** [comment]
What about `set_optimizer_attribute`?
