### ISSUE TITLE
Initialize JuMP model when optimizer is nothing

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#2172]
The NREL folks suggest adding a method:
```Julia
Model(::Nothing; kwargs...) = Model(; kwargs...)
```
so that they can create models if the user doesn't pass an optimizer (e.g., it remains the default `nothing`).

The alternative is them writing
```Julia
model = optimizer === nothing ? Model(; kwargs...) : Model(optimizer; kwargs...)
```
cc @kdheepak, @jd-lara

**Comment by mlubin** [comment]
The alternative is
```julia
m = Model()
if !isnothing(optimizer)
    set_optimizer(m, optimizer)
end
```
I'm not seeing a big issue with that alternative. This is a slippery slope if we start adding `Nothing` versions of all JuMP methods that take objects.

**Comment by odow** [comment]
> This is a slippery slope if we start adding Nothing versions of all JuMP methods that take objects.

Agreed. 

They will continue to implement a work-around down-stream.

For future readers, SDDP.jl implements a similar solution:
https://github.com/odow/SDDP.jl/blob/ff628f52afb01f52e7b64aa9a915cbead48f39f7/src/user_interface.jl#L458-L476
