### ISSUE TITLE
Easy way to determine constraints and/or variables leading to failed solving?

### ISSUE THREAD

**Issue by lfreese** [JuliaOpt/JuMP.jl#2185]
Hi,

I'm solving an optimization over time (1 year by hour, so 8759 runs of the model) by submitting it to a slurm, and during a given number of my timesteps (5001-6000), I get: 
`Parallel mode: deterministic, using up to 32 threads for concurrent optimization.
Row 'c1' infeasible, all entries at implied bounds.
Presolve time = 11.16 sec. (3193.35 ticks)
ERROR: LoadError: The model was not solved correctly.`

I'm wondering if there is a simple way within JuMP to figure out what constraints or variables is causing the inability to solve the model (eg: what timestep, which of my 4 constraints)?

I've looked at the documentation and haven't found something that would specifically work in the context of slurm submissions, but might be mistaken.

**Comment by odow** [comment]
In general:

At present, there is limited support for the accessing the Irreducible Infeasible Subset (IIS) in some solvers: https://github.com/JuliaOpt/JuMP.jl/issues/1035

We also have a GSOC project for this: https://github.com/jump-dev/GSOC2020/blob/master/ideas-list.md#feasibility-and-optimality-checker

For your specific case:

> what timestep

Is each hour a different model?  Impossible to say without your code.

> which of my 4 constraints

From `Row 'c1' infeasible, all entries at implied bounds`, it looks like the first constraint.

If you want detailed advice, it might be better to post on https://discourse.julialang.org/c/domain/opt/13. Make sure to read the first post of https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757 and provide a minimal working example.

**Comment by lfreese** [comment]
Thanks! I'll post on the site there. It does seem to be the first constraint based on the c1, so that makes it clearer.
