### ISSUE TITLE
duals on conic constraints

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#291]
Request from @juan-pablo-vielma. Either integrated with the new conic interface or as an extension of the current quadratic interface. It's not important to support duals for general quadratics at this point.

**Comment by mlubin** [comment]
The true conic solvers (Mosek, ECOS, SCS) properly support returning duals through the conic interface. We should at least return those to the user now that we have explicit support for ``norm`` constraints.

**Comment by emreyamangil** [comment]
I will start looking into this asap! Please let me know if there are any suggestions!

**Comment by emreyamangil** [comment]
First inspection! TODO at line 100 of solvers.jl?

**Comment by mlubin** [comment]
[this](https://github.com/JuliaOpt/JuMP.jl/blob/5611f93b8a2ecade46bd583b6e66d8e52b62bb8f/src/solvers.jl#L501) is where to look for how we map JuMP constraints to conic form

**Comment by emreyamangil** [comment]
perfect!! thanks!

**Comment by emreyamangil** [comment]
So in original form m.sdpconstr, m.quadconstr, m.linconstr, m.socconstr turns into conic form and we can ask its conic dual using getconicdual, however we are not mapping back to its original form, this is the issue right??

**Comment by mlubin** [comment]
Yep, that's the issue.

**Comment by emreyamangil** [comment]
On it!!!
