### ISSUE TITLE
Add support for parameters

### ISSUE THREAD

**Issue by davidanthoff** [JuliaOpt/JuMP.jl#304]
I would actually like to see support for model parameters, a la:

````
@defPar(m, p1)
````

Then ``p1`` could be used in any algebraic expression as if it was a constant, but the value for it could be changed before a ``solve(m)`` call. So I guess ``setValue`` would have to work with ``p1``, but that is probably all.

The scenario I have is that I need to solve the same model very, very many times, but each time I want to vary one of the parameters of the model.

In my mind there is no need for the underlying solver to even know that ``p1`` is not just a constant, so I have no need for duals or anything like that for ``p1``. Microsoft's solver foundation had support for this and it was really handy.

**Comment by mlubin** [comment]
Will be closed by #638 for the nonlinear case. The linear case can be discussed in a separate issue if requested.
