### ISSUE TITLE
Non-range indexing

### ISSUE THREAD

**Issue by yeesian** [JuliaOpt/JuMP.jl#305]
I was looking around for a way to express

```
sum(e in E) x[e] <= 5
```

succinctly, and wasn't aware of the following:

``` julia
@defVar(m, x[E], Bin)
@addConstraint(m, sum{x[e], e in E} <= 5}
```

Going through [the documentation](http://jump.readthedocs.org/en/release-0.6/refexpr.html), I got the sense that only range indices (e.g. `x[i:j]` or `x[i:j:k]`) are supported.

**Comment by mlubin** [comment]
I consider this resolved by the generator syntax. If you know julia syntax it should be obvious that you can use any iterable set.
