### ISSUE TITLE
Piecewise linear objective brainstorming

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#317]
So Gurobi has solver support for piecewise linear, and we have the world expert on piecewise linearity, so, lets think about how to model it. What do we need to have to express a piecewise linear function?
- Gurobi does it on a per variable basis, i.e. a list of points in domain of x and corresponding values of the objective, so

```
z = 2x, x in [0,1]
   = 3x-1, x in [1,2]
```

would be represented as

```
xs = [0, 1, 2]
zs = [0, 2, 5]
```

An alternative reduced form is have the breakpoints, the gradient, and an offset, e.g.

```
xs = [0, 1, 2]
gr = [2, 3]
of = [0, -1]
```

I suppose.

Heres some syntax ideas

``` julia
@setObjective(m, Min, {{2x, 0, 1}, {3x-1, 1, 2}})
```

To be continued, got to catch plane

**Comment by mlubin** [comment]
Closing this as speculative and out of scope for JuMP 1.0.

**Comment by joehuchette** [comment]
I'll take this one :)

**Comment by mlubin** [comment]
@joehuchette as a separate package, right?

**Comment by joehuchette** [comment]
Yep

**Comment by mlubin** [comment]
So technically still out of scope :)
