### ISSUE TITLE
unbounded root node and lazy constraints

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#338]
https://groups.google.com/forum/#!topic/julia-opt/qeJ39VCyyc0

**Comment by IainNZ** [comment]
In JuMPeR I have the same problem, I guess - I currently just add a box.

**Comment by mlubin** [comment]
Unclear what we need to do here, and doesn't seem like a big issue. We can reconsider if someone raises an issue in the future.
