### ISSUE TITLE
Remove comparison operator overloads to construct constraints

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#342]
As discussed in #340, with changes in julia v0.4, we could potentially remove the comparison operators for constructing constraints and force user-facing code to use the macro form ``@addConstraint`` (which is a Good Thing in any case). With this change, we could define a more meaningful definition for ``==`` for library code.

**Comment by mlubin** [comment]
Given the discussion in #10267, we should probably push forward on this.

**Comment by mlubin** [comment]
Closed by #401
