### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#345]
Just ran @timholy PR on Coverage (thanks, Tim!) and inspecting the `.cov` files, I see the following spots where our coverage could improve:
- [ ] `copy(::Model)` with nonempty `nlpdata`
- [ ] changing (QP) objective in model built in memory when `!method_exists(MathProgBase.setquadobjterms!, ...)`
- [ ] adding linear constraint in model built in memory when `!method_exists(MathProgBase.addconstr!, ...)`
- [ ] `addSOS1`/`addSOS2` in model built in memory
- [ ] adding quad. constraint in model built in memory when `!method_exists(MathProgBase.addquadconstr!, ...)`
- [ ] Adding fixed variable to existing constraints
- [ ] lines 95--97, 177--179, 213,  in `writers.jl` (??)
- [ ] `UnsetSolver` for NLP call `solve` (how is this not covered?)
- [ ] Getting infeasible ray when solver does not support it
- [ ] Getting unbounded ray
- [ ] Grabbing solution stuff when status is not in `[:Optimal, :Infeasible, :Unbounded]`
- [ ] MIP solvers not supporting hot-start
- [ ] MIP w/o `stat == :Optimal` (??)
- [ ] `buildInternalModel` for non-continuous model (and possibly QP/QCP/NLP as well)
- [ ] Lazy callback not at `:MIPSol`
- [ ] Adding an empty lazy/user cut
- [ ] Printing a solver that is not UnsetSolver (there's actually a regression here on v0.4 I've noticed)
- [ ] Tiebreaker in `_isless`
- [ ] Needing `:ExprGraph`
- [ ] Quadratic constraints in NLP
- [ ] Linear constraints in NLP (I think?)
- [ ] MINLP (this might just be because I don't have KNITRO locally)
- [ ] `parseExpr` lines 237--239 in `parseExpr_staged.jl` (which I think is unreachable)
- [x] `Base.next(x::JuMPArray, ::Any)` for `ndims(x) > 1` (this code could use optimization anyway, from the looks of it)

Plus a _whole_ bunch of test-throws cases we could add to try to catch bad behavior in user code.

**Comment by mlubin** [comment]
This list is stale, but always worth thinking about coverage
