### ISSUE TITLE
Use staged functions in ``@variable``

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#346]
Currently we don't recognize this as something we can store as a `JuMPArray`:

``` julia
I = 1:3
@defVar(m, x[I])
```

It should be fairly straightforward to add a staged function in the generated macro code that takes the `JuMPArray` branch based on the type of `I`.

**Comment by mlubin** [comment]
As I alluded to in #337 we can't easily implement this until we move over to the dormant ``JuMPArray.jl`` implementation because we're currently generating custom types inside of the macros. That's sketchy enough as it is, I don't think we should try to generate types at runtime within staged functions.

**Comment by joehuchette** [comment]
Should we try to bump the ntuple inlining thing?

**Comment by mlubin** [comment]
Not sure if it will be helpful, it's already a well-known issue.

**Comment by mlubin** [comment]
Don't think this is needed for JuMP 0.10, it'll be easier to do after we drop support for 0.3.

**Comment by joehuchette** [comment]
I meant to tag it 0.15. Thinking about this more, we won't be able to return a ``Vector{Variable}`` for my ``I=1:3`` example above without checking the endpoint at runtime, which will ruin type stability. The best we could do with generated functions is to return a JuMPArray. Is it still worth it? If this is mostly about performance, rather than semantics, type instability seems like a show-stopper.

**Comment by mlubin** [comment]
We should be looking at the new arbitrary-indexed arrays for that: https://github.com/JuliaLang/julia/pull/16260
So definitely after we drop support for 0.4

**Comment by chriscoey** [comment]
any new thoughts on this? #933 was added to 1.0 milestone, should this be also?

**Comment by joehuchette** [comment]
d032934b86197c6814973d8d7679f5368eb42a66
