### ISSUE TITLE
Error messages when trying to use nonlinearities in the linear/quad macros

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/JuMP.jl#349]
This is on JuMP master, Julia 0.3.5-pre+123. (totally artificial example)
```
julia> m = Model();

julia> @defVar(m, 0 <= x1); # I'm sure this one is a well-known annoyance
ERROR: assertion failed: isa(var,Expr)

julia> @defVar(m, x1 >= 0);

julia> @defVar(m, x2 >= 0);

julia> @setObjective(m, Max, x1/x2)
ERROR: Cannot divide by variable
 in / at /home/tkelman/.julia/v0.3/JuMP/src/operators.jl:21

julia> @addConstraint(m, log(x1) - log(x2) >= 1)
ERROR: `log` has no method matching log(::Variable)
```

If there's any reasonable low-performance-impact way of detecting this kind of mistake and suggesting the user should be using `@setNLObjective` and `@addNLConstraint`, would be a bit more user-friendly.

I'd argue the linear/quadratic versions are more specialized and should maybe be aliased or renamed to `@setLinObjective` `@addLinConstraint` etc. I recognize the development history and implementation differences behind the separate names as they are, but to newcomers they don't necessarily make a lot of sense. I've seen people coming from Yalmip frequently forgetting to add the `NL` names.

**Comment by mlubin** [comment]
We could provide some basic overloads for ``log(::Variable)``, ``log(::AffExpr)``, ``log(::QuadExpr)``, etc... and print a useful error message. The name ``addLinConstraint`` seems off since it accepts linear and quadratic. It's in the long-term plans to accept both linear and nonlinear expressions in ``@addConstraint``, but that will require a complete rewrite of the macros with heavy abuse of staged functions.

**Comment by tkelman** [comment]
Could be aliased to `addQuadConstraint`... guess I can be patient and see how much better things get in 0.4, at which point error-message overloads wouldn't be necessary?

**Comment by mlubin** [comment]
What will change in 0.4?
We should just implement these now to address the usability issue.

**Comment by joehuchette** [comment]
Let's implement the fallbacks now and start thinking about how best to consolidate everything under ``@addConstraint`` now (though that necessarily won't get released until after v0.4).

**Comment by tkelman** [comment]
> What will change in 0.4?

Anything that relies on staged functions?

**Comment by mlubin** [comment]
This is mostly resolved by #351, but let's see if we can also improve the error message for
```
@defVar(m, 0 <= x1)
```

**Comment by joehuchette** [comment]
How does this relate to nonlinearities?

**Comment by joehuchette** [comment]
I think we have a separate issue for that one (or we should, at least)

**Comment by mlubin** [comment]
It's not, but it was also raised in this issue.
