### ISSUE TITLE
Expression tree issues

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/JuMP.jl#350]
Trying to start writing an expression-tree OSiL writer. For debugging/testing purposes it's nice to be able to get the expression trees directly from a JuMP model. I tried following the example from the tests of:
```
type DummyNLPSolver <: MathProgBase.AbstractMathProgSolver
end
type DummyNLPModel <: MathProgBase.AbstractMathProgModel
end
MathProgBase.model(s::DummyNLPSolver) = DummyNLPModel()
function MathProgBase.loadnonlinearproblem!(m::DummyNLPModel, numVar, numConstr, x_l, x_u, g_lb, g_ub, sense, d::MathProgBase.AbstractNLPEvaluator)
    MathProgBase.initialize(d, [:ExprGraph])
    println("objexpr = $(MathProgBase.obj_expr(d))")
    # etc
end
```
but that's not very nice for working with the results.

I found the following (undocumented?) interface that partially works for basic examples:
```
# JuMP version of bonminEx1_Nonlinear.osil
julia> m = Model();

julia> @defVar(m, 0 <= x0 <= 1, Bin);

julia> @defVar(m, x1 >= 0);

julia> @defVar(m, x2 >= 0);

julia> @defVar(m, 0 <= x3 <= 5, Int);

julia> @setObjective(m, Min, x0 - x1 - x2);

julia> @addNLConstraint(m, (x1 - 0.5)^2 + (x2 - 0.5)^2 <= 0.25);

julia> @addConstraint(m, x0 - x1 <= 0);

julia> @addConstraint(m, x1 + x2 + x3 <= 2);

julia> A = JuMP.prepConstrMatrix(m)
2x4 sparse matrix with 5 Float64 entries:
        [1, 1]  =  1.0
        [1, 2]  =  -1.0
        [2, 2]  =  1.0
        [2, 3]  =  1.0
        [2, 4]  =  1.0

julia> d = JuMP.JuMPNLPEvaluator(m, A)
JuMPNLPEvaluator(Minimization problem with:
 * 2 linear constraints
 * 1 nonlinear constraints
 * 4 variables: 1 binary,1 integer
Solver set to Default,2x4 sparse matrix with 5 Float64 entries:
        [1, 1]  =  1.0
        [1, 2]  =  -1.0
        [2, 2]  =  1.0
        [2, 3]  =  1.0
        [2, 4]  =  1.0,false,#undef,#undef,#undef,#undef,140692562436280,#undef,#undef,#undef,#undef,0.0,0.0,0.0,0.0,0.0)

julia> MathProgBase.obj_expr(d)
:(1.0 * x[1] + -1.0 * x[2] + -1.0 * x[3])

julia> MathProgBase.constr_expr(d, 1)
:(+(1.0 * x[1]) <= 0.0)

julia> MathProgBase.constr_expr(d, 2)
:(1.0 * x[2] + 1.0 * x[3] + 1.0 * x[4] <= 2.0)

julia> MathProgBase.constr_expr(d, 3)
ERROR: Cannot generate expression, feature was not requested
 in to_flat_expr at /home/tkelman/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:207
 in constr_expr at /home/tkelman/.julia/v0.3/JuMP/src/nlp.jl:416
```

What's going wrong here?

**Comment by tkelman** [comment]
Ok I was missing a `MathProgBase.initialize(d, [:ExprGraph])`, but there's still something up with constraint 1...

**Comment by mlubin** [comment]
That's strange... take a look at the logic here: https://github.com/JuliaOpt/JuMP.jl/blob/master/src/nlp.jl#L402

**Comment by mlubin** [comment]
This should be returning the correct expression graph now. Let us know if there are any other issues.
If it makes sense to document how to get out an AbstractNLPEvaluator maybe we can do so. I could see it being useful.

**Comment by tkelman** [comment]
I think an NL writer will need to do much of the same stuff, just with a different target for the transformation. `ExprToNL` instead of `ExprToOSnL`...

**Comment by tkelman** [comment]
And yeah the expression trees look right now, thanks

**Comment by tkelman** [comment]
Some more issues for you.

```
julia> Pkg.installed("JuMP")
v"0.7.3"

julia> m = Model();

julia> @defVar(m, x);

julia> @setObjective(m, Max, x);

julia> @addConstraint(m, 0 <= x <= 1);

julia> A = JuMP.prepConstrMatrix(m);

julia> d = JuMP.JuMPNLPEvaluator(m, A);

julia> MathProgBase.initialize(d, [:ExprGraph])
ERROR: `convert` has no method matching convert(::Type{NLPData}, ::Nothing)
 in initialize at C:\Users\MPC_CAR\.julia\v0.3\JuMP\src\nlp.jl:69

julia> MathProgBase.obj_expr(d)
ERROR: type Nothing has no field nlobj
 in obj_expr at C:\Users\MPC_CAR\.julia\v0.3\JuMP\src\nlp.jl:390

julia> MathProgBase.constr_expr(d, 1)
:((0.0 +(1.0 * x[1]) 1.0))

julia> dump(MathProgBase.constr_expr(d, 1))
Expr
  head: Symbol comparison
  args: Array(Any,(3,))
    1: Float64 0.0
    2: Expr
      head: Symbol call
      args: Array(Any,(2,))
        1: Symbol +
        2: Expr
          head: Symbol call
          args: Array(Any,(3,))
          typ: Any
      typ: Any
    3: Float64 1.0
  typ: Any
```

1. `obj_expr` doesn't work if the problem is linear. It probably should.

2. For maximization problems, should JuMP be flipping the sign of the `obj_expr` output? "MathProgBase canonical form" is presumably a minimization problem, since I don't see a way to get the objective sense through MPB.

3. Ranged linear `constr_expr` is a little off. It's missing the `<=` Symbols.

**Comment by joehuchette** [comment]
1) Should be fixed now. Looks like you have the fix for 3) in your PR. For 2), what about adding a MPB interface function something like
```julia
MathProgBase.getobjsense(d::JuMPNLPEvaluator) = d.m.objSense
```

**Comment by tkelman** [comment]
Was just about to open an issue at MPB suggesting adding a getter function for objective sense to the nonlinear interface. The linear interface has `getsense` and `setsense!`, but it's hard to tell what, if any, parts of the linear interface are implemented for nonlinear.

It's also not entirely clear to me how much of the work is supposed to happen in `loadnonlinearproblem!` vs `initialize`.

**Comment by joehuchette** [comment]
``getsense``/``setsense`` apply to any model (linear, nonlinear, ...), so maybe adding extra methods for the ``NLPEvaluator``s is superfluous. @mlubin can chime in with more details on the design decisions, but my impression is that the evaluators are mostly there just for querying function values, not getting details about the model. To that end, ``initialize`` sets up all the pieces for function/gradient evaluation, while ``loadnonlinearproblem!`` plugs in everything the solver needs to actually solve the problem (so bounds, problem sense, etc, and also the evaluator).

**Comment by mlubin** [comment]
NLP solvers are free to implement ``getsense`` and ``setsense!``, but this isn't a property of ``AbstractNLPEvaluator``, at least for how things are set up now.
``initialize`` is implemented by a modeling layer (or by users expressing their problem in a low-level form). ``loadnonlinearproblem!`` is implemented by an NLP solver.
I guess there's some tension because ``AbstractNLPEvaluator`` is supposed to be a callback object for evaluating derivatives, whereas if you just want expression trees the callback structure doesn't make that much sense, and you'd rather have a single data structure that contains all of the problem information.

**Comment by mlubin** [comment]
If solvers which want expression graphs and derivatives are really disjoint, we could cook up a separate interface.
