### ISSUE TITLE
document getting an AbstractNLPEvaluator from a JuMP model

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#352]
We should have a documented method to extract an AbstractNLPEvaluator from a JuMP model. This will make it easy to explicitly evaluate derivatives or extract expression graphs from a model for experimental purposes.

CC @tkelman

**Comment by dpo** [comment]
Here's something I like: https://github.com/dpo/NLPModels.jl

**Comment by mlubin** [comment]
Pretty cool! MathProgBase was never meant to be the final interface, just an abstraction layer that everyone can agree on. No reason not to wrap it as you like to make it more convenient to write a solver for.
