### ISSUE TITLE
Not able to define decision variables by indices

### ISSUE THREAD

**Issue by krakeshiitk** [JuliaOpt/JuMP.jl#353]
I want to create new decision variables using @defVar macro in JuMP as below:

--------------------------------------------------------------------------------------------------
#Create decision variables y(b,u)
for b in 1:size(BREAKS,1)
    for u in 1:size(VALIDUNITS[b],1)
         @defVar(m, y[b,u], Bin)
    end
end
---------------------------------------------------------------------------------------------------

But above code is not creating decision variables 'y'. Actually, I am trying to define decision variables by their respective indices but unable to do so. 
Please help to resolve this.

**Comment by mlubin** [comment]
The syntax for ``@defVar`` is that you pass the complete index set. Calling ``@defVar`` inside of a loop is usually incorrect. Try this:
```
@defVar(m, y[b in 1:size(BREAKS,1), 1:size(VALIDUNITS[b],1)])
```

**Comment by krakeshiitk** [comment]
Thanks a lot. Its working :)
