### ISSUE TITLE
Should getNumConstraints count quadratic and nonlinear constraints?

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/JuMP.jl#356]
Slightly misleading to only return the number of linear constraints from this function, isn't it?

**Comment by mlubin** [comment]
Good point, these methods haven't gotten much attention. I'd vote for separating into linear/quadratic/nonlinear constraints.

**Comment by joehuchette** [comment]
What about 
```
(num_lin, num_quad, num_nl) = getNumConstrs
```
?

**Comment by mlubin** [comment]
Seems reasonable to me, only issue is that it's a breaking change.

**Comment by tkelman** [comment]
Maybe a dumb question, but is there a good reason for these to not use the MathProgBase names/interfaces?

**Comment by IainNZ** [comment]
I'm fairly ok with the breaking change without deprecation, as I doubt this is used by casual users of JuMP, so they'll be capable of updating easily enough.

**Comment by mlubin** [comment]
@tkelman, not really a good reason for not using the MPB names here, except to match the JuMP naming style. These functions are low-level enough that maybe it doesn't matter.

**Comment by joehuchette** [comment]
I've only ever used these functions when touching the MPB interface for other reasons (e.g. playing around with the constraint matrix), so it probably makes sense to just adopt the MPB naming conventions
