### ISSUE TITLE
Lazy Constraint/User cut error    EXCEPTION_ACCESS_VIOLATION at ....

### ISSUE THREAD

**Issue by jwnorth** [JuliaOpt/JuMP.jl#359]
I need to use the lazy constraint/user cut functionality of JuMP/Gurobi for a new project I am working on. 

When I run either simplelazy.jl, or simpleusercut.jl, I get the following error:

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0xd5e2dc -- unknown function (ip: 14017244)
unknown function (ip: 14017244)
unknown function (ip: 14017244)

My other models seem to be working using JuMP, it just errors out when attempting lazy constraints.

I am still quite new to programming (<2 years), and am by no means a hacker. 

Below is the version and package information on my machine.
I appreciate any assistance on this.

Version 0.3.5 (2015-01-08 22:33 UTC)

julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 23 entries:
  "Color"             => v"0.3.15"
  "Calculus"          => v"0.1.5"
  "Gurobi"            => v"0.1.23"
  "Iterators"         => v"0.1.7"
  "DualNumbers"       => v"0.1.1"
  "JuMP"              => v"0.7.3"
  "JSON"              => v"0.4.0"
  "NaNMath"           => v"0.0.2"
  "MyCode"            => v"0.0.0-"
  "Compat"            => v"0.2.9"
  "LNR"               => v"0.0.1"
  "FixedPointNumbers" => v"0.0.6"
  "ArrayViews"        => v"0.4.8"
  "ReverseDiffSparse" => v"0.1.9"
  "DataStructures"    => v"0.3.5"
  "Graphs"            => v"0.5.0"
  "Jewel"             => v"1.0.4"
  "JuliaParser"       => v"0.6.1"
  "Requires"          => v"0.1.1"
  "Compose"           => v"0.3.10"

**Comment by mlubin** [comment]
What's the output of ``versioninfo()`? Are you using 32-bit julia on
windows?

**Comment by jwnorth** [comment]
Hi Miles. That was quick!

julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia>

**Comment by jwnorth** [comment]
Yep. 32-bit julia

**Comment by mlubin** [comment]
Callbacks are known to not work on 32-bit julia on windows, but they should
work fine if you set up 64-bit julia with 64-bit gurobi. We should have a
more friendly error message.

**Comment by jwnorth** [comment]
K. I'll give that a shot.

**Comment by jwnorth** [comment]
That did it. Thanks Miles!

**Comment by IainNZ** [comment]
Hey @jwnorth, just because we love to know who our users are, would you mind letting us know if this an academic project or industrial?

**Comment by jwnorth** [comment]
This is an an academic project. It was nice meeting the both of you.

**Comment by IainNZ** [comment]
Great! Let us know if you find anything else not working, or not working like you'd expect.
