### ISSUE TITLE
Two-sided nonlinear constraints

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#361]
e.g.
```julia
@addNLConstraint(m, 3 ≤ x[1]^2 - x[2]^2 + x[4]^2 ≤ 100)
```

**Comment by mlubin** [comment]
Yeah, this is a lazy feature. Do you need it for anything in particular?

**Comment by joehuchette** [comment]
The Baron examples I'm porting over use two-sided constraints. Is it a straightforward addition?

**Comment by mlubin** [comment]
Should be. I think only solver people care about two-sided constraints.

**Comment by tkelman** [comment]
The expression trees for linear 2-sided constraints are also pretty messed up right now https://github.com/JuliaOpt/JuMP.jl/issues/350#issuecomment-70590225
