### ISSUE TITLE
Quadratic over linear

### ISSUE THREAD

**Issue by codingwillow** [JuliaOpt/JuMP.jl#374]
I was looking for a function or functionality similar to `quad_over_lin` in CVX, but couldn't find one. This function is convex and an optimization that uses it can be solved using a QP solver such as Gurobi.

**Comment by mlubin** [comment]
JuMP doesn't perform automatic transformations like CVX (see [Convex.jl](https://github.com/JuliaOpt/Convex.jl)), but ``quad_over_lin`` is actually straightforward to model.
The constraint
```
x'x/t <= t
```
is equivalent to
```
x'x <= t*y
```
which is a rotated second-order cone which you can write down directly in JuMP and pass to Gurobi. Just make sure that you set ``t`` and ``y`` to have lower bounds of zero. E.g.
```
@defVar(m, t >= 0)
@defVar(m, y >= 0)
@addConstraint(m, sum{x[i]^2, i = 1:N } <= t*y)
```

**Comment by codingwillow** [comment]
Thanks
