### ISSUE TITLE
Checking for Ill Conditioned A matrix

### ISSUE THREAD

**Issue by howard4086** [JuliaOpt/JuMP.jl#376]
I have had problems in the past with ill conditioned matrices while solving MIPs, and it results in JuMP calling the problem infeasible.  I believe I have another ill conditioned case where it is believed to be feasible by JuMP, but rounds off and yields a crash while solving.  See this pic:
![picture1](https://cloud.githubusercontent.com/assets/7016773/5964081/46ef5586-a7bf-11e4-8bf4-eb4f327b7237.png)

So my first question is - is this crash due to an ill conditioned matrix do you think?  My second question is I would like to check the condition of the matrix prior to trying to solve, and I can then scale some of my constraints I think to fix it but I don't know how to get A out of JuMP (and I'm too lazy to build A myself, but I suppose I could if there is no other way).  I see the function prepConstrMatrix, but it is not exported.  I tried adding it to the list of exports in JuMP and it caused JuMP to stop loading and crashed my program, so I am clearly doing some wrong.  

Thanks!

**Comment by joehuchette** [comment]
I haven't seen that error message before, what solver are you using? The simplest way to get the constraint matrix is like this:
```jl
using JuMP, MathProgBase
# build your model m up here
buildInternalModel(m) # this builds model in memory with solver
A = MathProgBase.getconstrmatrix(getInternalModel(m))
```

**Comment by mlubin** [comment]
Yes, this could be an issue with poor conditioning, and Cbc/Clp don't handle numerical instability as well as the commercial solvers. I would try solving the problem with Gurobi if you can obtain a license for it (free for academics).

**Comment by howard4086** [comment]
So - as always you guys are fantastic.  I love how quick you guys respond.  

Using your code above I calculated the condition number and found it was 3.73e22 (for a 331x275 matrix), so yes I have a horribly conditioned problem.  Time to fix it!

Thanks for the help!
