### ISSUE TITLE
Don't pass fixed status to ``setvartype!``

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#379]
Not sure why this hasn't broken anything yet.

**Comment by IainNZ** [comment]
Hah, I hit this while preparing  my class on Thursday.  I got an error from MPB layer about not knowing what Fixed was...

**Comment by joehuchette** [comment]
Is there anything to be gained from passing ``:Fixed`` to solvers? Probably not...

**Comment by mlubin** [comment]
No, it's a modeling construct that's redundant (with variable bounds) at the solver level.

**Comment by tkelman** [comment]
was wondering about that... https://github.com/tkelman/CoinOptServices.jl/blob/a1f695810a0be1c5c9046746940fb1d5fceae2b1/src/translations.jl#L55-L56

**Comment by mlubin** [comment]
Closed by #380
