### ISSUE TITLE
Tracking solver progress in JuMP/Gurobi

### ISSUE THREAD

**Issue by colin78** [JuliaOpt/JuMP.jl#382]
Is there an easy way to record solver progress (current solution, optimality gap) for MIP with Gurobi?  I would like to plot these two quantities over time to see how fast the solution converges.

**Comment by IainNZ** [comment]
One way would be to take the gurobi log file and parse it. We could maybe add an "information" callback too.

**Comment by mlubin** [comment]
If you want to do this programmatically, you can add a cut callback and query ``MathProgBase.cbgetobj`` and ``MathProgBase.cbgetbestbound``: http://mathprogbasejl.readthedocs.org/en/latest/mipcallbacks.html#cbgetobj.
We haven't had any requests for purely informational callbacks, but that wouldn't be difficult to add.

**Comment by colin78** [comment]
OK great setting the LogFile parameter worked for me.  A parser function for informational callbacks would also be very useful thanks for the fast reply!

**Comment by joehuchette** [comment]
We should add support for informational callbacks in MPB, I'll try to go and do that. It'll require some delicacy with Gurobi since they only allow one callback to be registered. @mlubin do you know if GLPK supports informational callbacks, or will we have to simulate it?

**Comment by mlubin** [comment]
Looks similar to the Gurobi case:
https://github.com/JuliaOpt/GLPKMathProgInterface.jl/blob/master/src/GLPKInterfaceMIP.jl#L87

Shouldn't be any more complicated than the other callbacks.

**Comment by mlubin** [comment]
See also #233, but that's orthogonal to any changes in MPB.
