### ISSUE TITLE
add SNOPT to supported solvers

### ISSUE THREAD

**Issue by andrewning** [JuliaOpt/JuMP.jl#392]
I'd love to see support for SNOPT.  It is a commercial optimizer written in Fortran, but has been wrapped in Python in [pyOpt](http://www.pyopt.org/reference/optimizers.html)

**Comment by mlubin** [comment]
Thanks for the request @andrewning. Speaking for myself, I see supporting additional commercial solvers (unless we need them for our own work) as having lower priority than adding new features to JuMP or supporting new open-source solvers.

That said, wrapping solvers is particularly easy in Julia, much more so than in Python, and we'd be happy to help out with pointing in right direction and getting a package into shape for release if someone steps forward to do the initial wrapping work.

A wrapper consists of a low-level wrapper using ``ccall`` to expose the solver's API, plus an implementation of the [MathProgBase nonlinear interface](http://mathprogbasejl.readthedocs.org/en/latest/nlp.html) which is used to communicate derivatives to solvers. This is quite modular and doesn't require any understanding of how JuMP works internally.

**Comment by IainNZ** [comment]
It doesn't have a free academic license, so I definitely don't think we'll be able to write a wrapper.

It looks like it works with AMPL though, and we'll soon be able to use the AMPL interface to SNOPT, so thats probably suficient.

**Comment by mlubin** [comment]
Ah yes, if it works with AMPL we'll get it for free pretty soon (thanks to @JackDunnNZ).

**Comment by andrewning** [comment]
Working through AMPL would probably work just fine.  If it doesn't expose all the access I need, I'm willing to spend some time on a direct wrapper.  Great to see an active community in this area.

**Comment by mlubin** [comment]
@andrewning, you can now give the AMPL interface a try through https://github.com/JackDunnNZ/AmplNLWriter.jl.

**Comment by mlubin** [comment]
Any further issues here should be raised at https://github.com/JackDunnNZ/AmplNLWriter.jl
