### ISSUE TITLE
JuMP v0.7.5?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#393]
I'd like to have a new JuMP version tagged around Wednesday. Since solve and print hooks snuck in on 0.7.3 or .4 anyway, I figure we could cherry pick the tweaks I've made to them since to the release-0.7 branch and just do 0.7.5, or if we think it'll make it we could do 0.8 with callback stuff and NL subexpres?

**Comment by mlubin** [comment]
I think we can do 0.8.

**Comment by joehuchette** [comment]
Want to do 0.8 soon, now that #390 is merged?

**Comment by mlubin** [comment]
Let's give it another day to settle. Would like to confirm that #394 is resolved.

**Comment by IainNZ** [comment]
:)
