### ISSUE TITLE
Selection of variables with pre-defined vector.

### ISSUE THREAD

**Issue by tobiassalz** [JuliaOpt/JuMP.jl#394]
In some of my code I would define a variable x[1:3] lets say and then use another predefined vector, y=[1 1 1 1 1 2 2 2 2 3 3 3 3] to select the correct value of x in my JuMP code: x[y[i]] according to the value of i. After updating JuMP this no longer seems possible. I now get the following error message for this: 

ERROR: error compiling _IDXLIST_: unsupported or misplaced expression escape in function _IDXLIST_
 in prep_sparse_hessians at /home/myname/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:64
 in initialize at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:85
 in loadnonlinearproblem! at /home/myname/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /home/myname/.julia/v0.3/JuMP/src/solvers.jl:9
 in estparam at none:116

I am using Julia Version 0.3.5 on Ubuntu and the latest JuMP for this version of Julia. The code above is a non-linear program that interfaces to Ipopt.

**Comment by tobiassalz** [comment]
I guess the only alternative to doing it like this would be to define x for every possible value of i and then introduce additional equality constraints. So for example x[1] = x[3] = ... = x[5], x[6] = ... = x[9], etc.

**Comment by mlubin** [comment]
This should work, can you try ``Pkg.checkout("ReverseDiffSparse")``?

**Comment by tobiassalz** [comment]
INFO: Checking out ReverseDiffSparse master...
INFO: Pulling ReverseDiffSparse latest master...
INFO: No packages to install, update or remove

**Comment by mlubin** [comment]
Well yes, does the code work now?

**Comment by mlubin** [comment]
I can reproduce the issue, looking into it.

**Comment by tobiassalz** [comment]
Thanks

**Comment by mlubin** [comment]
Try ``Pkg.update()`` and see if it works now.

**Comment by tobiassalz** [comment]
I now get this:

ERROR: `getindex` has no method matching getindex(::Variable, ::Array{Float64,4}, ::Variable, ::Int64, ::Int64)
 in _IDXLIST_ at /home/myname/.julia/v0.3/ReverseDiffSparse/src/revmode.jl:376
 in prep_sparse_hessians at /home/myname/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:86
 in initialize at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:85
 in loadnonlinearproblem! at /home/myname/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /home/myname/.julia/v0.3/JuMP/src/solvers.jl:9
 in estparam at none:243

Do you know which version does not have the changes that cause this?

**Comment by tobiassalz** [comment]
I now get error messages that are all over the place for the same code and different runs. For example:

ERROR: `!` has no method matching !(::GenericQuadConstraint{GenericQuadExpr{Float64,Variable}})
 in getindex at abstractarray.jl:450
 in _IDXLIST_ at /home/myname/.julia/v0.3/ReverseDiffSparse/src/revmode.jl:376
 in prep_sparse_hessians at /home/myname/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:86
 in initialize at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:85
 in loadnonlinearproblem! at /home/myname/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /home/myname/.julia/v0.3/JuMP/src/solvers.jl:9
 in estparam at none:243


and 


ERROR: Wrong number of indices for f, expected 1
 in _IDXLIST_ at /home/myname/.julia/v0.3/ReverseDiffSparse/src/revmode.jl:376
 in prep_sparse_hessians at /home/myname/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:86
 in initialize at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:85
 in loadnonlinearproblem! at /home/myname/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /home/myname/.julia/v0.3/JuMP/src/solvers.jl:9
 in estparam at none:243

**Comment by mlubin** [comment]
You can try downgrading to version 0.1.13 of ReverseDiffSparse for the time being.
If you could make a small example of a model that reproduces this error it would very helpful for debugging. Thanks!

**Comment by tobiassalz** [comment]
using JuMP


pi = 30.*rand(24,6)

ssl = 13;
hh = 24;
num_types = 15;

const pick_o = vec(ones(24));
pick_o[13:17] = 2;
pick_o[18:24] = 3;
pick_o[1:5] = 4;
const pick_fine = vec(ones(24));                                                                        
pick_fine[14:18]=2;                                                                                
const lease=vec(ones(24).*105);                                                                                
lease[5:16]=116;                                                                                    
const work_time = vec(ones(24));
work_time[5:17] = 2; 


breakm = rand((24,12,15,6));
active_stop = round(rand((24,12,15,6)));
active_nonstop = round(3.*rand((24,12,15,6)));
inactive_start = round(10.*rand((24,15)));
inactive_nonstart = round(10.*rand((24,15)));
pw = [0.00255578, 0.0886157, 0.408828, 0.408828, 0.0886157, 0.00255578];
nwage = length(pw);
constr_mat = round(rand((num_types,24)))

m = Model()

@defVar(m,  0.0001 <= p_est[1:hh,1:ssl-1,1:num_types,1:nwage] <= 0.9999);                             
@defVar(m,  0.0001 <= q_est[1:hh,1:num_types] <= 0.9999);
@defVar(m, -1000 <= EV[1:hh,1:ssl-1,1:num_types,1:nwage] <= 1700);
@defVar(m, -1000 <= EVA[1:hh,1:ssl-1,1:num_types] <= 1700);
@defVar(m,0 <= λ_1 <= 20);                                                                    
@defVar(m,0 <= λ_2 <= 20);                                                                    
@defVar(m,0 <= λ_0[1:length(unique(pick_o))] <= 250);                                                   
@defVar(m,-100 <= f[1:2] <= 400);
@defVar(m, 0.1 <= σ <= 80);                                                                      
@defVar(m, 0.1 <= σ_s <= 80);                                                               
@defVar(m,-500 <= μ[1:2] <= 600);                             

setValue(λ_1, -8.0);
setValue(λ_2, .8);
setValue(μ[1], 90.0);
setValue(μ[2], 90.0);


setValue(σ_s, 20.4);
setValue(σ, 20.0);


for h in [unique(pick_o)]
setValue(λ_0[h], 20.0)
end;

for h in [unique(pick_fine)]
    setValue(f[h], 30.0)  
end;

for h=1:hh,sl=1:ssl-1, c=1:num_types, a=1:nwage                 
    setValue(p_est[h,sl,c,a], 0.06*sl)  
end;

for h=1:hh,sl=1:ssl-1, c=1:num_types, a=1:nwage                             
setValue(EV[h,sl,c,a], 15)
end;

for h=1:hh,sl=1:ssl-1, c=1:num_types                                      
setValue(EVA[h,sl,c], 15)
end;

for h=1:hh, c=1:num_types                                                
    setValue(q_est[h,c], 0.5)hhend;


@setNLObjective(m, Max, sum{(1/10000)*(active_stop[h,sl,c,a]*log(p_est[h,sl,c,a])+active_nonstop[h,sl,c,a]*log(1-p_est[h,sl,c,a])),h=1:hh,sl=1:ssl-1,c=1:num_types, a=1:nwage}+sum{(1/10000)*(inactive_start[h,c]*log(q_est[h,c])+inactive_nonstart[h,c]*log(1-q_est[h,c])),h=1:hh,c=1:num_types})

for h=1:hh-1,sl=1:ssl-2, c=1:num_types, a=1:nwage
    @addNLConstraint(m, EV[h,sl,c,a]==σ*log(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]]+EVA[h+1,sl+1,c])/σ)))
end


for h=1:hh-1,sl=ssl-1, c=1:num_types, a=1:nwage
    @addNLConstraint(m, EV[h,sl,c,a]==σ*log(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]])/σ)))
end


for h=hh,sl=1:ssl-2, c=1:num_types, a=1:nwage
    @addNLConstraint(m, EV[h,sl,c,a]==σ*log(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]]+EVA[1,sl+1,c])/σ)))
end


for h=hh,sl=ssl-1, c=1:num_types, a=1:nwage
    @addNLConstraint(m, EV[h,sl,c,a]==σ*log(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]])/σ)))
end

for h=1:hh-1,sl=1:ssl-2, c=1:num_types, a=1:nwage
    @addNLConstraint(m, p_est[h,sl,c,a]==exp(1/σ)/(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]]+EVA[h+1,sl+1,c])/σ)))
end

for h=1:hh-1,sl=ssl-1, c=1:num_types, a=1:nwage
    @addNLConstraint(m, p_est[h,sl,c,a]==exp(1/σ)/(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]])/σ)))
end

for h=hh,sl=1:ssl-2, c=1:num_types, a=1:nwage
    @addNLConstraint(m, p_est[h,sl,c,a]==exp(1/σ)/(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]]+EVA[1,sl+1,c])/σ)))
end

for h=hh,sl=ssl-1, c=1:num_types, a=1:nwage
    @addNLConstraint(m, p_est[h,sl,c,a]==exp(1/σ)/(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]])/σ)))
end


for h=1:hh, c=1:num_types
    @addNLConstraint(m, q_est[h,c]==exp((EVA[h,1,c]-lease[h])/σ_s)/(exp((μ[work_time[h]])/σ_s)+exp((EVA[h,1,c]-lease[h])/σ_s)))
end;


for h=1:hh,sl=1:ssl-1, c=1:num_types
    @addNLConstraint(m, EVA[h,sl,c] == sum{pw[a]*EV[h,sl,c,a],a=1:nwage})
end


solve(m)

**Comment by mlubin** [comment]
Thanks @tobiassalz. That model has two identical sets of constraints:
```
for h=1:hh-1,sl=ssl-1, c=1:num_types, a=1:nwage
    @addNLConstraint(m, p_est[h,sl,c,a]==exp(1/σ)/(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]])/σ)))
end
...
for h=hh,sl=ssl-1, c=1:num_types, a=1:nwage
    @addNLConstraint(m, p_est[h,sl,c,a]==exp(1/σ)/(exp(1/σ)+exp((pi[h,a]*(1-breakm[h,sl,c,a])-λ_0[pick_o[h]]-λ_1*sl-λ_2*sl^2-constr_mat[c,h]*f[pick_fine[h]])/σ)))
end
```
Is there a reason for this? This clearly shouldn't cause an error though.

**Comment by tobiassalz** [comment]
The last one is only for h = hh and should have one less term than the first one. I guess I deleted that term while I was trying to fix the issue. Thanks for pointing it out.

**Comment by tobiassalz** [comment]
In this version it complains about not knowing pick_o which is declared as a constant

ERROR: pick_o not defined
 in _SPARSITY_GEN_ at /home/myname/.julia/v0.3/ReverseDiffSparse/src/hessian.jl:154
 in anonymous at no file:31
 in gen_hessian_sparse_color_parametric at /home/myname/.julia/v0.3/ReverseDiffSparse/src/coloring.jl:300
 in prep_sparse_hessians at /home/myname/.julia/v0.3/ReverseDiffSparse/src/exprlist.jl:65
 in initialize at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:85
 in loadnonlinearproblem! at /home/myname/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /home/myname/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /home/myname/.julia/v0.3/JuMP/src/solvers.jl:9
 in estparam at /home/myname/Dropbox/Taxi/programs/julia/mpec/mpec_func_ll_9_d.jl:233

**Comment by tobiassalz** [comment]
I just went back to 0.1.10 and my code works again

**Comment by mlubin** [comment]
@tobiassalz, with the latest master of ReverseDiffSparse, I can run your script without any errors.

**Comment by mlubin** [comment]
@tobiassalz, when you get a chance, please let us know if the issue is resolved. Thanks!

**Comment by tobiassalz** [comment]
Yes, I will have a look at it today. Thanks

**Comment by tobiassalz** [comment]
Script works on latest version, thanks.

**Comment by mlubin** [comment]
Thanks, and sorry for the breakage.
