### ISSUE TITLE
JuMPeR interacting with JuMP macros

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#400]
Something interesting is happening. On 0.3, I have the following code:

```
(*)(u::Uncertain) = u
function addToExpression(aff::GenericAffExpr, c, x)
    return aff + c*x
end
```

and `@addConstraint(rm, (u+w)*x + 2 + w*x <= u*z + 3)` gives `"(u + w) x + w x + -u z <= 1"` as I'd expect.

On Julia 0.4, I needed to add

```
function addToExpression(val::Real, c, x::Union(UAffExpr,FullAffExpr))
    return val + c*x
end
```

and I get `u x + w x + w x + -u z <= 1` now instead - still correct, although unexpected. Is there a 2 second explanation of why this happens, and should I be concerned?

**Comment by mlubin** [comment]
I don't have a quick answer, but I don't think anything needs to be addressed here.

**Comment by IainNZ** [comment]
Yeah I just special cased the tests.
