### ISSUE TITLE
Easily accessing solve time in JuMP

### ISSUE THREAD

**Issue by Shuvomoy** [JuliaOpt/JuMP.jl#405]
Per Miles's suggestion I am opening this issue.

Currently  solve time in JuMP has to be accessed either by looking into the solver print out, or by running `@time begin 
solve (modelName) 
end`,
which gives a slightly higher value. It might be better if it could be accessed more directly.

**Comment by mlubin** [comment]
So MathProgBase has ``getsolvetime``, we just have to expose it and make sure it's actually implemented by solvers. PRs accepted.

**Comment by mlubin** [comment]
You can also try ``MathProgBase.getsolvetime(getInternalModel(jumpmodel))``.

**Comment by IainNZ** [comment]
Would be awesome if you could submit this feature @Shuvomoy, a good start to future larger contributions maybe? :D

**Comment by mlubin** [comment]
Closed by #422, thanks to @odow
