### ISSUE TITLE
ERROR: syntax: function argument names not unique

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/JuMP.jl#406]
I'm trying to build up a complicated nonlinear objective in Julia, and I have run into the error "ERROR: syntax: function argument names not unique".  Here is a small example that reproduces the error:
```
m = Model()
@defVar(m, 1 <= gamma <= 2)
@defNLExpr(first, gamma)
@defNLExpr(second, first + gamma) # Expect 2 gamma
@setNLObjective(m, Max, first + second) # Expect 3 gamma
solve(m) # Expect 6
ERROR: syntax: function argument names not unique
 in genindexlist_parametric at /home/rgiordan/.julia/v0.3/ReverseDiffSparse/src/revmode.jl:385
 in genfgrad_simple at /home/rgiordan/.julia/v0.3/ReverseDiffSparse/src/revmode.jl:663
 in initialize at /home/rgiordan/.julia/v0.3/JuMP/src/nlp.jl:96
 in loadnonlinearproblem! at /home/rgiordan/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /home/rgiordan/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /home/rgiordan/.julia/v0.3/JuMP/src/solvers.jl:9
```
A similar example with the same error is:
```
m = Model()
@defVar(m, 1 <= gamma <= 2)
@defNLExpr(first, gamma)
@defNLExpr(second, first + gamma) # Expect 2 gamma
@defNLExpr(third, first + gamma) # Expect 2 gamma
@setNLObjective(m, Max, second + third) # Expect 4 gamma
solve(m)
```
Is there something wrong, or have I misunderstood how to use defNLExpr?

Thanks in advance,
Ryan

**Comment by mlubin** [comment]
Thanks for the report, we needed a small tweak in the logic but this should be working in a few minutes after running ``Pkg.update()``.

**Comment by rgiordan** [comment]
The fix works great, thank you for the quick response!

**Comment by GraceMabele** [comment]
I have the exact same error but the above solution is not working for. Any suggestions?

**Comment by odow** [comment]
@GraceMabele please make a new post on the community forum: https://discourse.julialang.org/c/domain/opt/13

Before doing so, please [read the first post of this PSA](https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757), and make sure to include a small minimal working example demonstrating your problem.
