### ISSUE TITLE
setNLObjective() with gamma and lgamma functions give InexactError()

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/JuMP.jl#407]
I would like to use the log gamma function in an nonlinear objective, but it gives an `InexactError()`.  `gamma()` does as well.  Are these functions available in JuMP?
```
m = Model()
@defVar(m, 3.0 <= x <= 4.0)
@setNLObjective(m, Max, lgamma(x))
solve(m) # Expect lgamma(4.0)
# ERROR: InexactError()
#  in float64 at float.jl:55
```

**Comment by mlubin** [comment]
This is supposed to work but likely hasn't been tested before. Will look into it.

**Comment by mlubin** [comment]
Fixed by johnmyleswhite/Calculus.jl#64
