### ISSUE TITLE
Decision variable in sum’s condition statement

### ISSUE THREAD

**Issue by stanvt** [JuliaOpt/JuMP.jl#408]
Hi!
Is it possible to use decision variable in condition in sum{}?

e.g. I am trying this
```julia
@defVar(m, x[e] >=0);

@defExpr(x_event[i0 in e] + 1, sum{x[i]) , i=i0 ; getValue(x[i]) == 0 } );

@setObjective(m, Max, sum{ x_event[i], i in e});
```
I am trying to sum all cases where , x[e] is 0.

But I get many warnings variable x[ ] is not defined. Is it possible or Is there way to write this completely differently?

**Comment by IainNZ** [comment]
Hi @stanvt 

The problem you are trying to model, at least in the form you have written it, is not a valid linear optimization problem. May you could describe your actual problem?

**Comment by stanvt** [comment]
@IainNZ 

Thanks for your reply! I just started learning both JuMP and Julia and might not be doing things correctly.

I want to maximize occurrences where decision variable equals zero. 

x ...... ex1
10 => 0
11 => 0
0 => 1

sum(x) + sum(ex1) -> max

I need to introduce a binary variable or maybe modify value of x in setObjective ? But I don't know how to express this in the code.

I can try to write a small example in JuMP if needed.

**Comment by IainNZ** [comment]
OK, I understand you problem now. You do need to introduce a binary variable. Before trying to implement in code, I recommend trying to implement it mathematically as an mixed-integer optimization problem. Once you have the mathematical statement of the problem, the JuMP code should be easy to write.

**Comment by stanvt** [comment]
ok, thanks!
