### ISSUE TITLE
getValue for nonlinear expressions

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/JuMP.jl#409]
Right now, it looks like getValue works for defExpr but not defNLExpr expressions (an example is below).  We're developing a fairly complex model with a lot of interdependent nonlinear expressions, and a feature like this would be very convenient for unit testing and debugging.

```
julia> using JuMP
julia> m = Model()
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver set to Default
julia> @defVar(m, 0 <= beta <= 1)
beta
julia> @defExpr(beta2, beta * beta)
beta² + 0
julia> setValue(beta, 0.5)
julia> getValue(beta)
0.5
julia> getValue(beta2)
0.25
julia> @defNLExpr(beta2nl, beta * beta)
ParametricExpression{0}(:(__R##24112##beta * __R##24112##beta),(symbol("__R##24112##beta"),),(beta,),(),0x557fb675ca10c687)
julia> getValue(beta2nl)
ERROR: `getValue` has no method matching getValue(::ParametricExpression{0})
```

**Comment by mlubin** [comment]
Thanks for the feedback. Nonlinear subexpressions have been around for about two weeks at this point, so it will take a bit more work to polish them up and add features like this.

**Comment by rgiordan** [comment]
That's understandable.  In the meantime, can you suggest any workarounds?  The only thing I've been able to think of to extract the value of an NLExpr is the following, which is very slow and finicky:

```
debug_model = Model()
epsilon = 1e-6
@defVar(debug_model, 5 <= debug_var <= 5 + epsilon)
@defNLExpr(log_debug_var, log(debug_var))
@setNLObjective(debug_model, Max, log_debug_var)
solve(debug_model)
getObjectiveValue(debug_model)
```

**Comment by mlubin** [comment]
Yeah that's pretty ugly! I don't really know a better way at the moment. I'm working on some changes that will make this easier to implement, so hang in there if you can.

**Comment by mlubin** [comment]
Okay, that was easier than expected. Run 
```
Pkg.update(); Pkg.checkout("ReverseDiffSparse","compiled_subexprs")
```
and then you should be able to get the value of subexpressions as:
```
m = Model()
...
@defNLExpr(beta2nl, beta * beta)
ReverseDiffSparse.getvalue(beta2nl, m.colVal)
```
No guarantee that this syntax won't break going forward, but it's available for testing.

**Comment by rgiordan** [comment]
Works great, thanks a lot for the quick feature!

**Comment by mlubin** [comment]
Cool. Let's keep this open until it's available through JuMP's ``getValue()``.
