### ISSUE TITLE
MPL?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#410]
Saw some discussion [here](https://news.ycombinator.com/item?id=9156644) where [MPL](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)) came up. It makes much more sense to me than LGPL, especially for Julia code.
Under MPL:
- If someone embeds JuMP in a commercial application, they must release the source code and any modifications they've made at the source level.

Under LGPL:
- All of the above, and they must "link" to JuMP dynamically and let users "link" in their own version of JuMP.

It's not clear at all what "linking" means for Julia code, and if it's not clear to us, I don't see how anyone else could confidently interpret the license. It doesn't help us to have a licence that's difficult to interpret and apply.

**Comment by mlubin** [comment]
Also, I believe this means that JuMP extensions could be released under any licence if they don't touch any JuMP code.

**Comment by joehuchette** [comment]
I officially register my approval.

**Comment by mlubin** [comment]
@tkelman @jlepird @cmaes @yeesian, do you agree to relicence your contributions to JuMP under MPL?

**Comment by yeesian** [comment]
I agree to relicense my contributions to JuMP under MPL

**Comment by cmaes** [comment]
I agree to relicense my contributions to JuMP under MPL.

**Comment by jlepird** [comment]
I agree to relicense my contributions to JuMP under MPL

**Comment by tkelman** [comment]
I agree to relicense my contributions to JuMP under MPL.

**Comment by mlubin** [comment]
Agreed @IainNZ?

**Comment by mlubin** [comment]
@tkelman, yes, MPL 2.0.
Thanks all for the quick responses!

**Comment by mlubin** [comment]
@tkelman, yes, MPL 2.0.
Thanks all for the quick responses!

**Comment by IainNZ** [comment]
Yes!
