### ISSUE TITLE
Solution that violates constraints

### ISSUE THREAD

**Issue by d10genes** [JuliaOpt/JuMP.jl#411]
Hello,

I'm trying to learn JuMP on a toy problem, and I found a situation where the solution claims it is Optimal, yet violates the constraint. Apologies if this is expected behavior.

The basic setup is as follows, with the 400-length arrays vs and ws [here](https://gist.github.com/d10genes/58a42ea0bda0d1bc1afe)

    using JuMP

    n = 400
    K = 9486367

    m = Model()
    @defVar(m, x[1:n], Bin)
    @addConstraint(m, dot(ws, x) <= K)
    @setObjective(m, :Max, dot(vs, x))

    status = solve(m)
    println(status)
    solX = getValue(x)

    println(int(dot(ws, solX)))
    println(dot(ws, solX) <= K)

The results are

    Optimal
    9486600
    false

the last one seems to violate the constraint (9486600 shouldn't be greater than 9486367). Changing K to K-1 gives me a satisfactory solution, but I was wondering if this is a bug. I installed JuMP and Clp, and am running julia version 0.3.6.

**Comment by IainNZ** [comment]
```
julia> 9486600/9486367
1.000024561562925
```

Which would seem to be within the feasibility tolerance. That it works with `K-1` is probably chance. It doesn't look like Cbc exposes an option to play with this, so I'd suggest trying out Gurobi (if you are an academic).

**Comment by d10genes** [comment]
Thank you @IainNZ.

I was about to look into trial academic versions of commercial solvers--any particular reason Gurobi is recommended over the others?

**Comment by carlobaldassi** [comment]
For the record, GLPK gives:

```
Optimal
9486360
true
```

**Comment by IainNZ** [comment]
@d10genes I recommend Gurobi because its very easy to acquire a license, and the installation is fairly lightweight.

**Comment by IainNZ** [comment]
Mosek is also easy to work with. CPLEX is quite difficult to get a license for.

**Comment by joehuchette** [comment]
GLPK is also easy to try out since you don't need a license, just try ``Pkg.add("GLPKMathProgInterface")``.

Also, if you specify primal tolerance with e.g. ``m=': m=Model(solver=CbcSolver(PrimalTolerance=1e-10))``, I get
```
julia> println(int(dot(ws, solX)))
9486360

julia> println(dot(ws, solX) <= K)
true
```
