### ISSUE TITLE
constraint on sum of rows

### ISSUE THREAD

**Issue by d10genes** [JuliaOpt/JuMP.jl#418]
I'd like to create an `n x n` decision matrix with ones and zeros, where each column and each row sums to 2.

I try

    m = Model()
    @defVar(m, x[1:n,1:n], Bin)
    @addConstraint(m, sum{x[i, :], i=1:n} == 2)

and get "Cannot construct an affine expression with a term of type (Float)*(Array{Variable, 2})"

Am I going about this incorrectly?

More generally, I keep experiencing this 'affine expression' error without an idea what it's referring to (that is, it doesn't look like an affine expression to me). Could someone give me some intuition as to how to correct these in the future? Should I get a hint from a type mismatch or something?

**Comment by mlubin** [comment]
The error message should improve with #404, but ``x[i,:]`` is the ith row, so if you want to constrain the sum of the row to be 2, then just say
```
@addConstraint(m, sum(x[i,:]) == 2)
```
(plus a loop over i, or the three-argument syntax).

**Comment by joehuchette** [comment]
The macro is trying to construct a linear constraint which essentially boils down to constructing an affine expression. Since ``x[i,:]`` creates a slice of the Variables (i.e. a ``Array{Variable,2}``), the macro code is trying to multiply ``(1.0)*x[i,:]`` and add it to an affine expression it's building up to describe the constraint. The error is telling you that it doesn't know how to add a term of the type ``(Float)*(Array{Variable, 2})`` to its (scalar) affine expression. This is because JuMP doesn't currently support vectorized constraints, which is pretty much the norm if you're coming from something like CVX (though that will change with #404).

**Comment by d10genes** [comment]
Thank you, this worked for me: `@addConstraint(m, xloop[i=1:n,i=1:n], sum(x[i, :]) == 2)`

Can't wait for them vectorized constraints!

**Comment by IainNZ** [comment]
@d10genes is that a typo with the two `i`s in the `xloop` indices?

**Comment by d10genes** [comment]
@IainNZ oops, it could be. I should probably do `@addConstraint(m, xloop[i=1:n,j=1:n], sum(x[i, :]) == 2)`, correct?

**Comment by IainNZ** [comment]
Well if thats the case, then the `j` isn't doing anything. I think you want
```julia
@addConstraint(m, rows[i=1:n], sum(x[i,:]) == 2)
@addConstraint(m, cols[j=1:n], sum(x[:,j]) == 2)
```
or
```julia
@addConstraint(m, rows[i=1:n], sum{x[i,j],j=1:n} == 2)
@addConstraint(m, cols[j=1:n], sum{x[i,j],i=1:n} == 2)
```

**Comment by IainNZ** [comment]
or even
```julia
@addConstraints m begin
  rows[i=1:n], sum(x[i,:]) == 2
  cols[j=1:n], sum(x[:,j]) == 2
end
```

**Comment by d10genes** [comment]
Those look like what I'm intending, but I wasn't able to get a good handle on the middle argument (rows[i=1:n]) from the docs.

For some reason I had the impression that, for example, `rows` should have the same dimensions as the thing I'm indexing (that is, the `n x n` matrix `x`) but I guess I just need it to have length `n` if I'm just  getting `i` from the expression.

Still not grokking the whole metaprogramming side :)

**Comment by IainNZ** [comment]
So, `rows` is a name for the "constraint reference" to each of the constraints. Its the constraint analogy to `@defVar`. Its like writing a for loop over its indexing. So `rows[i=1:n]` basically says create a constraint for every value of `i` in `1:n`. Its not related in any other way than that to the particular constraint.

It helps almost to not think too hard about what its doing - everything is basically just a writing a `for` loop in a briefer form, and anything you can do with macros can be done with `for` loops (basically).

Just keep asking questions :D Pull requests to the manual, or mini-tutorials from users to explain their thought processes are welcome!

**Comment by IainNZ** [comment]
Check out the sudoku example too, if you haven't already: https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/sudoku.jl

**Comment by d10genes** [comment]
Thanks, I found your TSP Lazy Constraints tutorial helpful as well.

> Just keep asking questions

You can be sure I will!
