### ISSUE TITLE
Trouble using maximum in expressions

### ISSUE THREAD

**Issue by d10genes** [JuliaOpt/JuMP.jl#420]
I'm trying to minimize the maximum of an array, and would like to use the maximum in several constraints (graph coloring problem). 

But when I try `@defExpr(C, maximum(c))` or `@setObjective(m, Min, maximum(c))`, I get 

    Cannot construct an affine expression with a term of type (Float64)*((int64,Variable))

Have I made a typo, or is this just an ill-suited objective for problems that JuMP handles?

**Comment by joehuchette** [comment]
We don't currently support nonlinear expressions on vectors of Variables, but you can do a simple reformulation of this with
```jl
@defVar(m, t)
@addConstraint(m, constr[i=1:length(c)], t >= c[i])
@setObjective(m, Min, t)
```
[Convex.jl](https://github.com/JuliaOpt/Convex.jl) also has support for modeling the maximum of a vector of variables.

**Comment by d10genes** [comment]
Thanks
