### ISSUE TITLE
Support inf rhs in @addConstraint

### ISSUE THREAD

**Issue by sbebo** [JuliaOpt/JuMP.jl#425]
Just a minor modeling issue, possibly already discussed. It would be nice if adding a constraint with an "Inf" rhs didn't result in an error -- the constraint could just be discarded, possibly with a warning. 

Of course, I can just check for each of them if the rhs is +Inf (what I do), but I was quite surprised the first time I got the error, since "@defVar(m, x<=Inf)" works fine, if I'm not mistaken.

**Comment by mlubin** [comment]
I think the error just comes when we try to print the constraint:
```
julia> using JuMP

julia> m = Model()
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver set to Default

julia> @defVar(m, x)
x

julia> @addConstraint(m, x <= Inf)
Error showing value of type ConstraintRef{GenericRangeConstraint{GenericAffExpr{Float64,Variable}}}:
ERROR: assertion failed: c.ub != Inf
 in sense at /home/mlubin/.julia/v0.3/JuMP/src/JuMP.jl:453

julia> solve(m)
:Optimal
```
Otherwise ``Inf`` bounds should already work. Let us know if you're seeing a different error.

**Comment by joehuchette** [comment]
Yeah, commenting out that assertion and the modeling works fine. I think the solvers will (should?) complain and error out. I would tend to think that's reasonable, and that the more verbose (but clearer) code is probably preferable, rather than leaving it up to each solver to figure out what to do.

**Comment by mlubin** [comment]
There's no reason for solvers to give an error on infinite bounds. Having "free rows" in a problem is a well established practice.

**Comment by IainNZ** [comment]
I know `GRB_INFINITY` isn't equal to `inf`, but maybe it just says that if its `>= GRB_INFINITY` it treats it as infinity.

**Comment by mlubin** [comment]
@sbebo, could you confirm if the issue is just with printing or if a particular solver gives an error?

**Comment by sbebo** [comment]
Sorry, missed the comment.
Actually it's not only a printing issue, there's another failing assertion in GurobiSolverInterface (line 59) and CplexSolverInterface .(line 55) [and maybe for other solvers too?].

**Comment by mlubin** [comment]
I think we need to fix #470 before we have a good solution to this on the JuMP side. One would like to be able to do:

```
    m = Model(solver=solver)
    @defVar(m, x ≥ 0)
    @setObjective(m, Max, x)
    @addConstraint(m, xup, x ≤ Inf)
    status = solve(m)
    @fact solve(m) => :Unbounded
    
    chgConstrRHS(xup, 10)
    status = solve(m)
    @fact solve(m) => :Optimal
    @fact getValue(x) => 10

    # same for lower bounds
    m = Model(solver=solver)
    @defVar(m, x ≤ 0)
    @setObjective(m, Min, x)
    @addConstraint(m, xlo, x ≥ -Inf)
    status = solve(m)
    @fact solve(m) => :Unbounded
    
    chgConstrRHS(xup, -10)
    status = solve(m)
    @fact solve(m) => :Optimal
    @fact getValue(x) => -10
```

**Comment by colinfang** [comment]
I don't think #470 can be fixed easily if Groubi treats that as a feature.
But can we still support rhs = inf given under some conditions?

**Comment by mlubin** [comment]
I think this is entirely resolved now with MOI. JuMP's internal representation of constraints does not depend on the value of the lower/upper bounds to decide the sense.
