### ISSUE TITLE
cannot add KNITRO

### ISSUE THREAD

**Issue by alexfakos** [JuliaOpt/JuMP.jl#429]
Hi,

I first typed Pkg.add("JuMP") and it installed successfully. 
Then I typed Pkg.add("KNITRO") and I got the following error:

ERROR: KNITRO's requirements can't be satisfied because of the following fixed packages: julia
 in wait at task.jl:48
 in add at pkg/entry.jl:314
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:20
 in cd at pkg/dir.jl:28
 in add at pkg.jl:20

Does anyone have an idea what the problem might be?
Thanks a lot,
Alex

**Comment by mlubin** [comment]
What version of Julia do you have installed? Is it older than 0.3?

**Comment by alexfakos** [comment]
Hi,

This is my version:

Version 0.3.0-prerelease+3512 (2014-06-05 19:22 UTC)
 _/ |\__'_|_|_|\__'_|  |  master/e16ee44* (fork: 1572 commits, 407 days)
|__/                   |  x86_64-redhat-linux

**Comment by mlubin** [comment]
Yes, that's a prerelease version of Julia 0.3. Try installing the latest version (0.3.7).

**Comment by alexfakos** [comment]
I don't know if that is possible because I am using my university's HPC and I don't have power over the version installed. I think that the latest version I can load is:
julia/0.3.6_0c24dca65c

I will try it out and let you know. Thanks a lot

**Comment by mlubin** [comment]
Version 0.3.6 should work as well

**Comment by alexfakos** [comment]
After loading julia 0.3.6 I was able to add KNITRO and it works!
Thanks a lot Miles. I really appreciate your help.
Alex
