### ISSUE TITLE
Incorrect sparse hessians in NLExpr containing affine expressions

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/JuMP.jl#435]
The output of ```gen_hessian_sparse_mat``` seems to be incorrect when a NLExpr contains sums of expressions.  A simple example is below.  Note that the sparse hessian is missing the a * b cross terms.

```
using ReverseDiffSparse
using JuMP

m = Model()
@defVar(m, a)
@defVar(m, b)
@defVar(m, c)

@defNLExpr(foo, a * b + c^2);

setValue(a, 1)
setValue(b, 2)
setValue(c, 3)

n = 3

foo_expr = @ReverseDiffSparse.processNLExpr foo;
fg = ReverseDiffSparse.genfgrad_simple(foo_expr);
foo_grad = zeros(n);
fg(m.colVal, foo_grad);

foo_hess_raw, sparsefunc = gen_hessian_sparse_mat(foo_expr, n);
sparsefunc(m.colVal, foo_hess_raw);
# Convert from a lower triangular matrix:
foo_sparse_hess = foo_hess_raw + foo_hess_raw' - sparse(diagm(diag(foo_hess_raw)));

foo_dense_hess = gen_hessian_dense(foo_expr)(m.colVal)

foo_dense_hess
# 3x3 Array{Float64,2}:
#  0.0  1.0  0.0
#  1.0  0.0  0.0
#  0.0  0.0  2.0

full(foo_sparse_hess)
# 3x3 Array{Float64,2}:
#  0.0  0.0  0.0
#  0.0  0.0  0.0
#  0.0  0.0  2.0
```

**Comment by mlubin** [comment]
There are a lot of things that could be going on here, will take a look.

**Comment by mlubin** [comment]
Just pushed a test which shows that JuMP gives the correct answer through MPB (unless travis chokes on it). As I mentioned in https://github.com/mlubin/ReverseDiffSparse.jl/issues/16, I don't have any plans to make the ReverseDiffSparse methods play well with JuMP models. It would create too much surface area to document and test without adding new functionality that isn't available in some form through MPB.
If anything, I'd be open to some clean wrappers to make it easier to evaluate Hessians of JuMP expressions like these, but the wrappers should go through MPB and not low-level ReverseDiffSparse methods.
