### ISSUE TITLE
Move away from RTD

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#439]
RTD pages just got super ugly: http://jump.readthedocs.org/en/latest/
Maybe it's time to move on?

**Comment by joehuchette** [comment]
Are there ads now? Hmmmm

**Comment by IainNZ** [comment]
Pandoc/Judo

**Comment by tkelman** [comment]
Mkdocs looks pretty good https://tshort.github.io/Sims.jl/

**Comment by mlubin** [comment]
0.10 milestone was a bit too optimistic

**Comment by IainNZ** [comment]
Yeah. We'll get there though :+1:

**Comment by mlubin** [comment]
What about hosting on juliaopt.org like http://www.juliadiff.org/ForwardDiff.jl/? Versioned docs don't even work any more on RTD (https://github.com/rtfd/readthedocs.org/issues/1617), so all we get from using RTD is the automatic builds.

**Comment by IainNZ** [comment]
yeah definitely

**Comment by mlubin** [comment]
I'm satisfied with the current setup. RTD for dev docs makes sense since it rebuilds with every commit to master, and we now have self-hosted versioned docs. Closing this since we have other "rewrite the docs" issues (https://github.com/JuliaOpt/JuMP.jl/pull/485 https://github.com/JuliaOpt/JuMP.jl/pull/607)

**Comment by tkelman** [comment]
The fact that RTD defaults to master, which includes renamed everything that isn't in releases yet, has already been immensely confusing to 3 or 4 different people over the last few days. That latest vs stable link is fatally hard to see and realize what it means.

**Comment by mlubin** [comment]
@tkelman, do you have any suggestions for how to make people pay more attention to the big yellow warning box?

**Comment by tkelman** [comment]
Top of every page say first thing "this documentation is for version ... of jump"? slightly redundant but would be easier for people to notice. on the master branch that could also have a warning "this is a prerelease development version"

**Comment by IainNZ** [comment]
![image](https://cloud.githubusercontent.com/assets/692635/14874496/ee71371e-0cce-11e6-8db8-68f59dd4adc1.png)

Isn't that exactly what it is right now?

**Comment by tkelman** [comment]
ah indeed. apparently i never noticed since no one is ever looking at the top of the page, they're looking in some specific section for whatever it is they're trying to do

**Comment by mlubin** [comment]
If you know how to make one of those annoying floating boxes we can put it up.

**Comment by IainNZ** [comment]
I'll take a crack
