### ISSUE TITLE
@defVars

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#440]
```julia
@defVars m begin
    0 <= x[i=1:n] <= u[i], Int
    t >= 0, Bin
    z <= 1
end
```
I'm guessing that @davidanthoff will appreciate this syntax.  I think that the only issue with parsing it as we want is with keyword arguments like ``start`` because ``=`` has higher precedence than ``,`` in this context.

**Comment by davidanthoff** [comment]
You bet, that would clean up our code nicely, very much appreciated!
