### ISSUE TITLE
Accessing solver stats (node count)

### ISSUE THREAD

**Issue by sbebo** [JuliaOpt/JuMP.jl#442]
I was trying to extract the number of nodes at the end of a branch-and-bound. It looks like there's no easy way to do it in JuMP? 

I tried to look at MathProgBase, and it looks like `getnodecount` should do the trick. But `getnodecount(m.internalModel)` doesn't work for Cplex or Gurobi. I had to use `CPLEX.getnodecnt`, or even `CPLEX.get_node_count` and `Gurobi.get_node_count` passing the "raw model". 

Other MathProgBase methods work fine, like `getobjval` or `getobjbound`; other ones, like `getobjgap`, don't. I guess it's just a (boring) matter of implementing the missing method(s) in the solver interfaces. But what I mean is: if I'm using JuMP, I'd rather not use MathProgBase at all, if possible. It would be nice to expose at least a subset (if not all?) of these methods in JuMP.

**Comment by mlubin** [comment]
No reason this hasn't been implemented other than nobody asking for it yet.

The two quick steps are:
1. Implement ``MathProgBase.getnodecount`` in Gurobi.jl and CPLEX.jl
2. Implement ``MathProgBase.getnodecount(::JuMP.Model)`` (like in #422).

We'd gladly accept a PR for this.

**Comment by sbebo** [comment]
Cool, will do.

**Comment by mlubin** [comment]
Fixed by #444
