### ISSUE TITLE
Constraints and extensions don't play nice

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#443]
Ideally we'd have a documented interface for extensions to hook into the macro system for adding constraints, so we didn't need to jump through hoops like this: https://github.com/IainNZ/JuMPeR.jl/blob/a0f5b38d2f8bbd9bd952ab4333cc8c040931ca63/src/robustmacro.jl#L105-L134

**Comment by mlubin** [comment]
30 lines of not overly opaque code is pretty good as far as extensions go, though we do need to document this.

**Comment by joehuchette** [comment]
The net addition isn't so much the problem, it's that it's a seemingly random subset of methods (that we could probably add fallbacks in JuMP to handle, as JuMPeR isn't doing anything particularly interesting here)

**Comment by mlubin** [comment]
Down to 20 lines now. Do we just need to document ``_construct_constraint!``?

**Comment by joehuchette** [comment]
Yeah, seems that way. And change its name: I never intended the leading ``_`` to leak out of JuMP...

**Comment by mlubin** [comment]
Tagged for 0.10

**Comment by mlubin** [comment]
I think it's safe to close this. JuMP internals have changed a lot since 2015.
