### ISSUE TITLE
warn when using too much operator overloading

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#449]
Maybe we can detect and print a useful warning when the user is doing too much operator overloading applied to large expressions, e.g.:
```
S = 0
for i in 1:N
    S += x[i]
end
```

**Comment by joehuchette** [comment]
If there isn't a performance hit to pay, then yeah this seems like a good idea.

**Comment by mlubin** [comment]
Maybe a counter attached to the model which gets incremented on addition of two expressions when one has more than 100 terms.

**Comment by joehuchette** [comment]
Could work.

**Comment by mlubin** [comment]
The overhead should be on the order of bounds checking, which we do already.

**Comment by joehuchette** [comment]
I think the tricky part would be making sure that there aren't too many false positives.

**Comment by mlubin** [comment]
We can adjust the threshold, but I wouldn't print a warning at least until there are 10,000 or so additions.

**Comment by mlubin** [comment]
Let's tack on detecting too many calls to ``getValue(::JuMPContainer)`` also.
