### ISSUE TITLE
@defExpr weirdness

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#454]
On 0.4:

```
julia> using JuMP

julia> m = Model();

julia> @defVar(m,x[1:2]);

julia> @defExpr(y[i=1:2], sum{x[i]; i==1})
ERROR: Three argument form of @defExpr only supports linear expressions
 in anonymous at /home/mlubin/.julia/v0.4/JuMP/src/macros.jl:514
```

The two issues with this are:
- There is no three-argument form of ``@defExpr``. We mean the two-argument form with a nonscalar expression variable.
- The check for ``isa($newaff,AffExpr)`` should be replaced with a check for if the result can be converted to an AffExpr.

**Comment by kaarthiksundar** [comment]
julia> m = ChanceModel();

    julia> A = [1 2 3; 1 2 3; 1 2 3];
    
    julia> @defIndepNormal(m, w, mean=0, var=1);
    
    julia> @defExpr(expr, A[1,1]*w+A[1,2]*w+A[1,3]*w)
    (6.0)*w + 0
    
    julia> @defExpr(expr[i=1:2], sum{A[i,k]*w, k=1:3})
    ERROR: Three argument form of @defExpr only supports linear expressions
     in anonymous at /home/kaarthik/.julia/v0.3/JuMP/src/macros.jl:448

For some reason this does not happen with ordinary variables defined using @defVar

**Comment by mlubin** [comment]
The error message was inaccurate (fixed above), but otherwise this is a known restriction. This will need a bit of thinking to address correctly.

**Comment by kaarthiksundar** [comment]
Is there a way to get around this other that writing a loop?

**Comment by mlubin** [comment]
Currently no, see mlubin/JuMPChance.jl#1
