### ISSUE TITLE
Ipopt and Jump - Duals from each constraint limit and active variable upper/lower limits

### ISSUE THREAD

**Issue by rbacher** [JuliaOpt/JuMP.jl#456]
Any chance to get the duals from the general non-linear solver Ipopt for a non-linear problem defined purely in JuMP? I am currently using Ipopt as a general nonlinear solver (i.e., with @addNLConstraint and @addConstraint). I have upper and lower limits on variables and quadratic / linear
equality/inequality constraints. Non-linear or linear objective function.

**Comment by mlubin** [comment]
@rbacher, this is now implemented. You may use ``Pkg.checkout("JuMP")`` to pull the latest development version of JuMP to test it out. See the example code [here](https://github.com/JuliaOpt/JuMP.jl/blob/09d7bda1c062a972086daec46c8b2ccff9804ce5/test/nonlinear.jl#L321). The only caveat is that we don't yet support duals on quadratic constraints added through ``@addConstraint``, so you can add these with ``@addNLConstraint`` for the time being.

**Comment by mlubin** [comment]
The rest of this (duals for quadratic constraints) falls under #291.
