### ISSUE TITLE
Add method for ConstraintRef to get underlying constraint?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#462]
Is this something we'd want in JuMP? Maybe un-exported?

**Comment by joehuchette** [comment]
Have you run into a situation where this would be useful?

**Comment by IainNZ** [comment]
I'm this very situation right now :) Although its for JuMPeR,
```
con = JuMPeR.getRobust(rm).uncertainconstr[ref.idx]
```
Now worst case for JuMP is not as bad, i.e.
```
con = m.linconstr[ref.idx]
```
but it could be just
```
con = getConstraint(ref)
```
for both.

**Comment by joehuchette** [comment]
Seems reasonable to me. 

Tangentially related, I could see something like ``checkFeasibility(::LinearConstraint)`` being useful at some point as well (as in, I've already written this code a couple times for cuts).

**Comment by IainNZ** [comment]
Yeah, I have something along those lines in JuMPeR I guess, but with a tolerance. i.e. returns one of `:Slack, :Active, :Violate`

**Comment by mlubin** [comment]
Addressed in the linear case by https://github.com/JuliaOpt/JuMP.jl/pull/598.

**Comment by mlubin** [comment]
Addressed in JuMP/MOI by `constraintobject`: https://github.com/JuliaOpt/JuMP.jl/blob/f3e8d5a90bc27f061dd39e49af011540ba015925/test/constraint.jl
