### ISSUE TITLE
Errors while trying to use JuMP

### ISSUE THREAD

**Issue by kostav** [JuliaOpt/JuMP.jl#463]
Hello,
I am really new to Julia and not the best programmer mysefl.
I run linux mint 16 and I installed julia via terminal (sudo apt-get install julia ).
Then when I run Julia on my terminal, while the JuMP package is installed
sth that I believe the following two commands on my terminal prove:

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("JuMP")
INFO: Nothing to be done

Then when I try to use JuMP I get the following error msg:

julia> using JuMP
ERROR: Block not defined
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/kostas/.julia/v0.3/Docile/src/types.jl, in expression starting on line 2
while loading /home/kostas/.julia/v0.3/Docile/src/Docile.jl, in expression starting on line 19
while loading /home/kostas/.julia/v0.3/DataStructures/src/DataStructures.jl, in expression starting on line 48
while loading /home/kostas/.julia/v0.3/Graphs/src/Graphs.jl, in expression starting on line 2
while loading /home/kostas/.julia/v0.3/ReverseDiffSparse/src/coloring.jl, in expression starting on line 1
while loading /home/kostas/.julia/v0.3/ReverseDiffSparse/src/ReverseDiffSparse.jl, in expression starting on line 20
while loading /home/kostas/.julia/v0.3/JuMP/src/JuMP.jl, in expression starting on line 13

Finally the msg I receive for Block is the following:

julia> Pkg.checkout("Block")
ERROR: Block is not a git repo
 in checkout at pkg/entry.jl:190
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in checkout at pkg.jl:33

**Comment by IainNZ** [comment]
Very odd... Can you run `versioninfo()` and post the results, and also run `Pkg.status()` and post the results?

**Comment by tkelman** [comment]
Wasn't this a mailing list post too? It looked there like it may have come from Docile somehow being stuck at a very old tag.

**Comment by mlubin** [comment]
Crossposted [here](https://groups.google.com/forum/#!topic/julia-users/QFREJ9WiGws) and [here](https://groups.google.com/forum/#!topic/julia-opt/lAGjzjHA5pI). Looks like the issue was with using julia 0.3.0-rc.
