### ISSUE TITLE
logical operators in constraints

### ISSUE THREAD

**Issue by stanvt** [JuliaOpt/JuMP.jl#469]
Hi! 
Is it possible to use logical operators (or, and) in constraints and if so how? I think AMPL allows using constraints with logical operators 

JuMP Manual states:
http://jump.readthedocs.org/en/latest/refexpr.html#constructor
Note that only one condition can be added, although expressions can be built up by using the usual && and || logical operators.

I tried:

```
using JuMP

let
m = Model()
@defVar(m, 0 <= x <= 2.2 )
@defVar(m, 0 <= y <= 30.1 )

@setObjective(m, Max, 5x + 3*y )

@addConstraints(m, begin
   (x == 1 || x == 1.1)
end)

print(m)

status = solve(m)

println("Objective value: ", getObjectiveValue(m))
println("x = ", getValue(x))
println("y = ", getValue(y))
end;
```

But constraints seem to be disregarded completely. Is the syntax I use correct?

Thanks!

**Comment by mlubin** [comment]
There's currently no support for logical constraints like this, but there's certainly room to develop future extensions. The statement in the manual is referring to logical conditions used to index over subsets of variables.

**Comment by IainNZ** [comment]
I experimented with some of this here https://github.com/IainNZ/JuMPLogic once upon a time

**Comment by stanvt** [comment]
ok, thank you for clarifying it! 

@IainNZ many thanks! I will explore your example! nice song too :)

**Comment by mlubin** [comment]
Now that we have a proper error message, I think we can mark this specific issue as resolved.
