### ISSUE TITLE
Using nonlinear expressions in multiple models?

### ISSUE THREAD

**Issue by rgiordan** [JuliaOpt/JuMP.jl#473]
Is there any way to re-use nonlinear expressions between multiple models? As a simple (and kind of silly, included only for concreteness) example, suppose I had something like this problem:

```
using JuMP

m = Model()

n = 10
z = exp(rand(n))
@defVar(m, x)
@defVar(m, y[i=1:n]);

@defNLExpr(y_obj[i=1:n], -0.5 * (y[i] - x) ^ 2 - exp(y[i]) + y[i] * z[i]);
@defNLExpr(x_obj, 1 / (1 + x^2) );
@defNLExpr(obj, x_obj + sum{y_obj[i], i=1:n});

@setNLObjective(m, Max, obj)
```

Suppose, for example, that I wanted to optimize each ```y_obj``` separately given a value of ```x```, but still wanted autodiff hessians for ```obj```.  I would want to share the expression ```y_obj[i=1:n]``` between the models used for optimzing and the model used to get the full Hessian.

I don't see how to do it since a variable must be bound to a single model.  Is this possible in JuMP?  Any recommendations for how to approach this use case?

(The example is deliberately oversimplified -- for a more complicated motivating example, you can consider [a variational poisson glmm](https://github.com/rgiordan/variational_bayes/blob/master/poisson_glmm/regression_poisson_componentwise.jl).)

**Comment by mlubin** [comment]
Given the design of variables being tied to models, it's hard to see how this can easily work. I think Casadi enables you to mix and match pieces in this way. You basically have to pass values back and forth across the models, but there are probably way to wrap this up to make it less painful.

**Comment by rgiordan** [comment]
What do you think about using the same model but creating different ```m_eval``` objects, like so:

```
@setNLObjective(m, Min, obj_1)
m_const_mat = deepcopy(JuMP.prepConstrMatrix(m));
m_eval1 = deepcopy(JuMP.JuMPNLPEvaluator(m, m_const_mat));
MathProgBase.initialize(m_eval1, [:ExprGraph, :Grad, :Hess])

@setNLObjective(m, Min, obj_2)
m_const_mat = deepcopy(JuMP.prepConstrMatrix(m));
m_eval2 = deepcopy(JuMP.JuMPNLPEvaluator(m, m_const_mat));
MathProgBase.initialize(m_eval2, [:ExprGraph, :Grad, :Hess])
```

I tried this out on a simple example and it seems to work in the sense of giving you objective values and first and second derivatives with respect to the different objective functions, but I don't know if this violates some hidden design decision I'm unaware of.

**Comment by mlubin** [comment]
Sneaky. It looks like this particular case is safe at the moment, but I can't guarantee that it will be in the future. Some of the evaluation callbacks refer to the original model (e.g., for nonlinear constraints), but nonlinear objectives are a special case where everything needed is saved separately in the NLPEvaluator.

**Comment by mlubin** [comment]
After https://github.com/JuliaOpt/JuMP.jl/pull/638 expressions will be explicitly tied to models, so closing this as wontfix. The workaround is create multiple models and set the values of the variables as needed to compute the desired derivatives.
