### ISSUE TITLE
Unrecognized function abs

### ISSUE THREAD

**Issue by zenna** [JuliaOpt/JuMP.jl#478]
I am trying to use NLOpt from JuMP.  Whenever I have tried to use an objective function with `abs` I get

```julia
m_nl = Model(solver=NLoptSolver(algorithm=:LN_COBYLA))
@defVar(m_nl, 0 <= x <= 1)
@setNLObjective(m_nl, :Min, abs(x))
```

```
ERROR: Unrecognized function abs
 in error at ./error.jl:21
```

Surely, at least some of the algorithms should be able to handle expressions with `abs`

For reference I opened this issue [here on the NLOpt github](https://github.com/JuliaOpt/NLopt.jl/issues/39), but it was closed as not an NLopt issue.

**Comment by joehuchette** [comment]
Seems like adding
```jl
(:abs, :(sign(x))
```
to [this list](https://github.com/johnmyleswhite/Calculus.jl/blob/360624de4f8619f9266ae9b8f14d7d50c2e11f68/src/differentiate.jl#L116-L184) should do the trick.

**Comment by joehuchette** [comment]
It's not an algorithmic issue, we just don't have the derivative rules for working with ``abs`` in place yet.

**Comment by mlubin** [comment]
@joehuchette also will need to implement ``sign(::Dual)`` for hessians. ``ifelse(x >= 0, 1, -1)`` should work immediately.

**Comment by joehuchette** [comment]
Where should that go? DualNumbers?

**Comment by mlubin** [comment]
Yeah

**Comment by dpo** [comment]
Will this be merged into `master`?

**Comment by mlubin** [comment]
This should already be working

**Comment by dpo** [comment]
Oh I'm sorry. I fooled myself with a old warning I added in my code before this got merged.
