### ISSUE TITLE
Absolute values in objective/constraints

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#48]
Essentially, this would be some way to add absolute value terms to the model without forcing the user to deal with the proliferation of auxiliary variables/constraints themselves. More generally, this approach could be applied to other things that can be modeled via LP but require some kind of problem transformation (e.g. convex piecewise linear), but absolute value seems the most immediate (and useful, for my research).

**Comment by iamed2** [comment]
Can we bring this back since that branch never got merged?

**Comment by mlubin** [comment]
@iamed2, what about using @IainNZ example definition of ``abs`` above?

**Comment by omus** [comment]
Gets quite ugly when you are using arrays and doesn't work when you are using `abs` with different variables:

```julia
using JuMP
import JuMP: GenericAffExpr

function abs{V<:GenericAffExpr}(v::Array{V})
	m = first(first(v).vars).m
	@defVar(m, aux[1:length(v)] >= 0)
	@addConstraint(m, aux .>= v)
	@addConstraint(m, aux .>= -v)
	return aux
end

m = Model()
@defVar(m, a[1:10] >= 0)
@defVar(m, b[1:10] <= 0)
@defVar(m, c[1:10] >= 10)
@defVar(m, d[1:10] <= -10)
```

```julia
julia> sum(abs(a + b))
aux[1] + aux[2] + aux[3] + aux[4] + aux[5] + aux[6] + aux[7] + aux[8] + aux[9] + aux[10]

julia> sum(abs(c + d))
aux[1] + aux[2] + aux[3] + aux[4] + aux[5] + aux[6] + aux[7] + aux[8] + aux[9] + aux[10]
```

**Comment by mlubin** [comment]
What doesn't work? Don't worry about the names of the variables overlapping, they're distinct variables.

**Comment by omus** [comment]
According do the documentation @defVar will [redefine variables without warning](http://jump.readthedocs.org/en/latest/refvariable.html). `aux` isn't being overwritten by the second `abs` call?

**Comment by mlubin** [comment]
``@defVar(m,x)`` is equivalent to something like ``x = Variable(m)``. It redefines *Julia* variables in the local scope, not JuMP variables.

**Comment by omus** [comment]
Interesting. Maybe I'm missing something but why isn't the following model respecting the constraint given? Both `a` and `b` both contain all zeros.

```julia
using JuMP
import JuMP: GenericAffExpr

function abs{V<:GenericAffExpr}(v::Array{V})
	m = first(first(v).vars).m
	@defVar(m, aux[1:length(v)] >= 0)
	@addConstraint(m, aux .>= v)
	@addConstraint(m, aux .>= -v)
	return aux
end

m = Model()
@defVar(m, a[1:10] >= 0)
@defVar(m, b[1:10] <= 0)
@addConstraint(m, sum(abs(a + b)) >= 100)

solve(m)
getValue(a)
getValue(b)
```

**Comment by mlubin** [comment]
``sum(abs(a + b)) >= 100`` is not a convex constraint, if you gave it to Convex.jl it would be rejected. The above trick is a poor man's DCP (disciplined convex programming), so to make it work you have to follow the same rules. If you really want to model that constraint, you'd have to introduce integer variables since it's a nonconvex problem.

**Comment by joehuchette** [comment]
This gets to the reticence about adding this type of problem transformation to JuMP: it's surprisingly subtle, and will require a fair amount of thought (and code) to get this working robustly. It will also likely end up reimplementing a decent amount of Convex.jl on top of JuMP. Since the JuMP internals aren't really designed for handling this type of transformation, it probably makes sense to put this functionality to an external package, rather than JuMP itself (at least initially).

**Comment by mlubin** [comment]
``s/reimplementing a decent amount of Convex.jl/reimplementing all of Convex.jl/g``

**Comment by joehuchette** [comment]
Probably not if you're only interesting in adding L1/L_\infty

**Comment by iamed2** [comment]
@mlubin What we wanted was actually `sum(abs(a + b)) <= 100` which does work. But the fact that the solver gives back a solution it says is optimal when it clearly violates constraints seems wrong. 

We're really only going through this in order to implement norm1. It looks like the abs solution does not work in our actual problem. We really want to use JuMP so we can use JuMPeR and such but we can't seem to find a way to get it to work. Switching to Convex.jl will present new problems down the line when we want more features but might just be necessary at this point.

**Comment by mlubin** [comment]
@iamed2, that's exactly why we don't blindly incorporate these transformations into JuMP. Ensuring validity of the transformation requires DCP which the reason why systems like CVX and Convex.jl exist.

What is it exactly that's not working at this point? If you're imposing a norm1 constraint then the abs transformation is valid. JuMPeR itself does support some form of norm1 constraints, but I'll let @IainNZ discuss.

**Comment by IainNZ** [comment]
JuMPeR only supports `norm1` constraints for the uncertainty set, and only for "norm ball" type constraints of the form `norm1(u) <= G`, which are easy for JuMPeR to handle.

@iamed2 the solver isn't lying, and it doesn't violate the constraints - its just that your `abs` is actually `abs_with_caveats` - there is nothing JuMP nor the solver can do about that, unfortunately.
