### ISSUE TITLE
accept vectors for starting values

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#481]
Proposed in #477, this should work:
```
@variable(m, x[1:16], start = xstart)
```
CC @tyleransom

**Comment by mlubin** [comment]
Just to put some ideas down, we can take an array as a starting value under the following conditions:
- The variable is a ``OneIndexedArray``
- The term ``xstart`` doesn't depend on any of the indexing variables in the definition of ``x``
- If the above is true, we can check if the dimensions of ``xstart`` match the dimensions of ``x``

**Comment by joehuchette** [comment]
:+1:

**Comment by mlubin** [comment]
Post 0.10 I think.

**Comment by dpo** [comment]
:+1:

**Comment by mlubin** [comment]
Given that you can just do:
```
@variable(m, x[1:16])
setvalue(x, xstart)
```
I'm not really convinced that we need to implement this feature. I think it's too magical to have the interpretation of the keyword arguments depend the fragile conditions I listed above.
