### ISSUE TITLE
Don't ask for reduced costs until user does?

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/JuMP.jl#483]
Running `OsilBonminSolver` against JuMP master's `test/nonlinear.jl` results in an undefined reference during the first MINLP test, since Bonmin doesn't give duals (at least not in the results osrl file) for MINLP's. The test doesn't actually ask for the duals, so seems like the error could be avoidable.

(p.s. this also means that I hope you don't tag before my talk, or my test example might not work)

**Comment by mlubin** [comment]
We probably shouldn't ask for duals at all when solving MINLP. Don't worry,
not tagging soon.

**Comment by tkelman** [comment]
That should be okay for now, but there might be continuous solvers that don't always give duals. If the user doesn't ask for them should there still be an error?

**Comment by mlubin** [comment]
That's tricky to do with the current infrastructure. I think the cleanest
approach right now would be for the solver to return a vector of NaNs if
duals aren't available.
