### ISSUE TITLE
User defined derivative rules

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#486]
We had a nice conversation with @davidanthoff today about extending the nonlinear modeling to allow user-defined derivative rules. The application is DP problems with expressions of the form ``f(x) + V(g(x,t))``, where ``f`` and ``g`` are standard closed form functions that JuMP works fine with and ``V`` is some structured function (e.g. a large sum). Essentially he would like to plug in his own derivative rules for ``V``, which we were playing around with but hit some scoping issues. CC @mlubin 

(Feel free to make any corrections or elaboration @davidanthoff).

**Comment by mlubin** [comment]
Does ``V`` take scalar input?

**Comment by davidanthoff** [comment]
I think I actually got this working with scalar valued functions:

````julia
using JuMP

# Define V function
function V(x)
    return x^2
end

# Define derivate of V
function dV(x)
    return 2x
end

# Register V with ReverseDiffSparse
ReverseDiffSparse.rules[:(Main.V)] = arg -> ReverseDiffSparse.replace_x(:(Main.dV(x)), arg)

# Use V in a JuMP model
m = Model()
@defVar(m, x)
@setNLObjective(m, Min, 2 + Main.V(x + 5.))
solve(m)
getValue(x)
````

But, Miles is right, ``V`` actually needs to take a vector. In my case ``V`` also has a number of parameters that don't change within one optimization but would change for repeated calls to ``solve``, but I think those I could just handle with closures. Or in 0.4 with the new callable types, or whatever that is called.

So, two issues really: a) can this be done with functions that take arrays, and b) would it make sense that JuMP (or the ReverseDiff package) expose an official API to add functions in this way.

**Comment by IainNZ** [comment]
Hah David that's what I got up to today as well!

**Comment by mlubin** [comment]
Scalar functions are easy to add, as you've discovered. The issue with functions that take vectors is that in general you'd want to have a single function which computes the gradient and outputs into an array. But to make that efficient we'd need to do a restructure of the AD code to keep around arrays for storage when they're needed. That might not realistically happen until the next AD rewrite. We could hack it if you don't mind some extra GC churn for every time the function is called.

**Comment by davidanthoff** [comment]
I think it would make more sense to wait with this for the next AD rewrite: right now we are working on a whole bunch of other problems in our framework and it would be quite some time before we would start using JuMP in any case. Also, our problem ends up with millions if not billions of calls to solve, so GC churn is a big problem for us. So, my vote would be to try to incorporate this in some general way and with an API into the next AD rewrite.

**Comment by anriseth** [comment]
+1 from me. 
Use case: maximising expected utility or other risk measures over arbitrary probability distributions, where you have to approximate ugly integrals.
