### ISSUE TITLE
Lazy SOCP constraints

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/JuMP.jl#495]
I am trying to add a Lazy constraint of the form x*x <= yz using
 
    @addLazyConstraint(cb, varterm[sc,l,t,k]*varterm[sc,l,t,k] <= yterm[sc,l,t,k]*slack[sc,l,t])

Apparently, the syntax is not implemented in JuMPChance or JuMP. 

The error it throws is as follows

    ERROR: `addLazyConstraint` has no method matching addLazyConstraint(::CplexLazyCallbackData, ::GenericQuadConstraint{GenericQuadExpr{Float64,Variable}})

**Comment by joehuchette** [comment]
Yes, only linear lazy constraints are allowed. I don't know a solver that supports lazy SOC constraints; maybe SCIP?

**Comment by kaarthiksundar** [comment]
Doesn't the latest version of CPLEX  (12.6) support this? If I give a SOCP constraint of the form x*x <= yz, and set the solver to use Branch and cut, it does the linearization internally. I have tried this without adding this particular form for SOCP as a Lazy constraint. So I was hoping it would work when added as a Lazy constraint or usercut constraint.

**Comment by joehuchette** [comment]
Do you have a pointer to that? If they do support it then we could add the feature here.

**Comment by mlubin** [comment]
Afaik, there's no solver support for lazy SOC constraints, the two options are to provide the constraint at the beginning or perform the linearization on your own.

**Comment by kaarthiksundar** [comment]
http://www.slideshare.net/IBMOptimization/euro-2015-nodet


This is 12.6.2. It was out in June. I don't know if they have the feature implemented for lazy callback. 



—

**Comment by mlubin** [comment]
@kaarthiksundar, if you can find a function in the CPLEX API to do this, we can think about supporting it. Otherwise there's not much we can do.
