### ISSUE TITLE
Document CoinOptServices and AmplNLWriter

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#497]

**Comment by mlubin** [comment]
CC @tkelman @JackDunnNZ

**Comment by tkelman** [comment]
Sure, where? You mean that they're available for use, or solver table, or ??

(p.s. Stefan Vigerske did merge the Bonmin C API, so that's good news for whenever someone gets some time)

**Comment by mlubin** [comment]
Here: http://jump.readthedocs.org/en/latest/installation.html

**Comment by IainNZ** [comment]
Noted
