### ISSUE TITLE
implement buildInternalModel for NLPs

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#510]
CC @dpo
This will allow you to plug in a "dummy" solver to extract all of the problem info like variable and constraint bounds without solving. This will look like
```
# m is a JuMP model
setSolver(m, myDummySolver())
buildInternalModel(m)
problemdata = getInternalModel(m)
# now problemdata has all of the NLP problem data, bounds, NLP evaluator, etc
```

**Comment by joehuchette** [comment]
Cool. This is feasible for 0.10?

**Comment by mlubin** [comment]
Should be, it's blocking for @dpo to be able to implement solvers

**Comment by dpo** [comment]
We can implement unconstrained solvers (we have one and a second one to come) thanks to `NLPModels`.
