### ISSUE TITLE
Is it possible to print out line numbers from the operator overload warnings?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#521]
I'm getting in some code, presumably from inside something in JuMPeR's reformulation code, but its mildly annoying having to guess. I imagine it'll baffle some people who aren't as familiar.

**Comment by joehuchette** [comment]
Do you have an example of one that's confusing? Not sure how we can improve on julias line number reporting ourself

**Comment by IainNZ** [comment]
I didn't even get a line number...?

**Comment by mlubin** [comment]
Even if we figure out how to throw a line number from a warning, it'll often be wrong if macros are involved.

**Comment by mlubin** [comment]
I think we should relax the limits on the operator warnings, otherwise I agree that we'll drive some people crazy chasing the warnings.

**Comment by joehuchette** [comment]
I think we should bump it up to something really large now, but keep it. It is useful to track down inefficient code; it helped a lot with the vectorization stuff a few weeks ago.

**Comment by mlubin** [comment]
Let's relax the warnings and add an option to disable them (from extensions primarily).

**Comment by joehuchette** [comment]
Bump @mlubin can we increase the limits?

**Comment by mlubin** [comment]
Done

**Comment by mlubin** [comment]
If anyone knows how to print a backtrace from a warning, feel free to revisit this issue.
