### ISSUE TITLE
Different behavior in addquadconstr! between Julia 0.3 and 0.4

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/JuMP.jl#524]
This might be a wontfix if it's intended, and I think it revealed a bug in my code, but worth opening anyway. On 74f5ed42905d7c2c162445197613599f0de27b05 of JuMP, running the following quadratically constrained problem from the tests
```jl
modQ = Model(solver=OsilSolver())
@defVar(modQ, x >= 0)
@addConstraint(modQ, x*x <= 1)
@setObjective(modQ, Max, x)
solve(modQ)
```
results in different inputs to `addquadconstr!` when run on Julia 0.3.11 vs latest 0.4 master.

If I modify the implementation of `addquadconstr!` to start out with
```jl
function MathProgBase.addquadconstr!(m::OsilMathProgModel, linearidx,
        linearval, quadrowidx, quadcolidx, quadval, sense, rhs)
@show linearidx
@show linearval
@show quadrowidx
@show quadcolidx
@show quadval
@show sense
@show rhs
...
```
then on 0.3 I see
```
linearidx => Int32[1]
linearval => [0.0]
quadrowidx => Int32[1]
quadcolidx => Int32[1]
quadval => [1.0]
sense => '<'
rhs => 1.0
```

vs on 0.4
```
linearidx = Int32[]
linearval = Float64[]
quadrowidx = Int32[1]
quadcolidx = Int32[1]
quadval = [1.0]
sense = '<'
rhs = 1.0
```
for the same problem. Is this intended or not?

**Comment by mlubin** [comment]
We use different code paths on 0.3 and 0.4 to process expressions, so this isn't unexpected.

**Comment by tkelman** [comment]
Not unexpected, but is it a desired difference in behavior? Bisected to cec211cc4a97b2f39852c50fb5a3e71036a02867, which maybe isn't surprising given how large that commit was.

**Comment by mlubin** [comment]
It's worth looking into where the zero coefficient is coming from.

**Comment by tkelman** [comment]
The zero coefficient was actually making my life a little simpler, was easier in OSiL bookeeping to always assume there's a nonempty linear part for every quadratic constraint. MPB and OSiL have different notions of how linear and quadratic constraints should coexist (and how they should be ordered and counted) which leads to some messiness. My workaround for now is going to be to put a zero coefficient back if the linear part of a quadratic constraint is ever empty.

**Comment by mlubin** [comment]
Oh, if anything we would remove the zero coefficient.

**Comment by tkelman** [comment]
Yes, that would probably make sense for JuMP's purposes, since there is no linear part of that constraint.

What's odd is even on 0.4, while adding the second (purely-quadratic) constraint to the problem the zero coefficient strikes again:
```
julia> @addConstraint(modQ, 2x*x <= 1)
linearidx = Int32[1]
linearval = [0.0]
quadrowidx = Int32[1]
quadcolidx = Int32[1]
quadval = [2.0]
sense = '<'
rhs = 1.0
```

**Comment by joehuchette** [comment]
I'm guessing it's because of the ``q = zero(AffExpr)`` line at the start:
```
julia> macroexpand(:(@addConstraint(modQ, 2x*x <= 1)))
quote  # /Users/huchette/.julia/v0.4/JuMP/src/macros.jl, line 149:
    JuMP.validmodel(modQ,:modQ) # line 150:
    begin  # /Users/huchette/.julia/v0.4/JuMP/src/macros.jl, line 308:
        #1#q = JuMP.zero(JuMP.AffExpr) # line 309:
        begin
            begin
                #2###6666 = JuMP.addToExpression_reorder(#1#q,2,x,x)
            end
            #3###6665 = JuMP.addToExpression_reorder(#2###6666,-1.0,1)
        end # line 310:
        #4###6664 = JuMP.addConstraint(modQ,JuMP._construct_constraint!(#3###6665,:(<=)))
    end
end
```

**Comment by joehuchette** [comment]
Actually no, duh. It's the ``JuMP.addToExpression_reorder(#1#q,2,x,x)`` line.

**Comment by mlubin** [comment]
That should end up calling https://github.com/JuliaOpt/JuMP.jl/blob/4b4c4639a1cadb9b0ca3560f6c7d60241a0742df/src/v0.4/parseExpr_staged.jl#L71

**Comment by joehuchette** [comment]
Yeah, that makes sense then.

**Comment by mlubin** [comment]
And apparently ``addToExpression(::AffExpr,::Number,::Variable)`` ends up calling https://github.com/JuliaOpt/JuMP.jl/blob/4b4c4639a1cadb9b0ca3560f6c7d60241a0742df/src/v0.4/parseExpr_staged.jl#L253 ??
Seems like we're missing a method that could do something smarter here

**Comment by mlubin** [comment]
We no longer support 0.3 on master, so I guess we can close this
