### ISSUE TITLE
Can we make at-expression more general?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#525]
At the moment if only works for linear expressions, which means it can't be used for extensions (or even quadratics). One option would be just to use JuMPDicts of Anys, I guess, but that could hurt you if you wanted to use it for matrix ops later I suppose.

**Comment by mlubin** [comment]
The scalar ``@defExpr`` should work for generic expressions on 0.4 (but not 0.3).
For collections of expressions, we should probably choose the type of the JuMP container optimistically (like ``map``) and widen it if we need to. Will be easier to implement once the JuMPArray code becomes nicer.

**Comment by IainNZ** [comment]
Yeah I was thinking of collections.

**Comment by mlubin** [comment]
This still doesn't work:
```julia
julia> @expression(m, [i=1:2], x^2)
ERROR: Collection of expressions with @expression must be linear. For quadratic expressions, use your own array.
```

**Comment by blegat** [comment]
We should make containers infer the element type by creating the first element and looking at its value. This would also remove the need for `JuMP.constraint_type` which is bad since it does not return a concrete type

**Comment by mlubin** [comment]
> We should make containers infer the element type by creating the first element and looking at its value.

We shouldn't assume that the element type is homogeneous. We should use the same approach as `map` and widen/promote if needed:
```julia
julia> map(+, Any[1, 2, 3], Any[10, 20, 30])
3-element Array{Int64,1}:
 11
 22
 33

julia> map(+, Any[1, 2, 3], Any[10, 20, 30.0])
3-element Array{Real,1}:
 11  
 22  
 33.0
```

**Comment by blegat** [comment]
> We shouldn't assume that the element type is homogeneous. We should use the same approach as `map` and widen/promote if needed

I agree, normally, this is what is done by `Base.collect_to_with_first!` for `Vector`, implementing `Base.collect_to_with_first!` for Containers might be the way to go.
The broad idea is instead of creating nested loops, we create a function that given the indices, return the element for these indices, we feed this function to a `Base.Generator` and then we `collect`. That is what `map` does.
