### ISSUE TITLE
Setting solver option in Jump

### ISSUE THREAD

**Issue by Smaz89** [JuliaOpt/JuMP.jl#541]
Hi all,

I'm trying to write my first optimization code using JuMP, after years passed on AMPL. I am not able to set solver options as time limit and solution tolerance; setting also a real-time updating of the solution (with actual solution upper bounds) would be useful for me.

Can anyone give me an hint?

P.s. I usually use GLPK and Gurobi as solvers

**Comment by mlubin** [comment]
Hi @Smaz89. You can set solver options by tacking them onto the solver object:
https://github.com/JuliaOpt/GLPKMathProgInterface.jl
```
GLPKSolverLP(method=:Exact, presolve=true, msg_lev=GLPK.MSG_ON)
```
https://github.com/JuliaOpt/Gurobi.jl
```
GurobiSolver(Method=1, IterationLimit=100.)
```
The gurobi options match those in the gurobi documentation.

**Comment by mlubin** [comment]
@Smaz89, feel free to ask any follow up questions on the [julia-opt](https://groups.google.com/forum/#!forum/julia-opt) forum.
