### ISSUE TITLE
Replace ``OneIndexedArray`` with ``Array``

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#544]
So that ``@defVar(m, x[1:n,1:n])`` gives you ``x::Array{Variable,2}``.

**Comment by mlubin** [comment]
What breaks?

**Comment by joehuchette** [comment]
``@defVar(x, x[1:n,1:n], SDP)`` will introduce auxiliary variables, but hopefully that's about it.

**Comment by mlubin** [comment]
Why does it need auxiliary variables?

**Comment by joehuchette** [comment]
I use ``SDPConstraint(::OneIndexedArray)`` as shorthand for ``X >= 0``, which doesn't need auxiliary variables as I can put it in the variable cones. Not a deal breaker, though.

**Comment by mlubin** [comment]
Why can't you still use variable cones here? Just record it on creation.

**Comment by joehuchette** [comment]
Or, more generally, you can just check ``issym(x) && isa(x,
Matrix{Variable})``, it's just a matter or actually writing the code.

**Comment by mlubin** [comment]
How do we know that two different symmetric ``Matrix{Variable}`` objects are disjoint?

**Comment by joehuchette** [comment]
Does the standard stipulate that has to hold? The code would have to be uglier to check that, I guess.

**Comment by mlubin** [comment]
Variable cones have to be disjoint. We can guarantee they're disjoint if we just created the variables in ``@defVar``, but not otherwise.

**Comment by mlubin** [comment]
It's worth trying to get this into 0.10. ``OneIndexedArray`` hasn't shown up in a release yet.

**Comment by joehuchette** [comment]
The printing code is a nightmare, but I think everything else is mostly there.

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/548
