### ISSUE TITLE
Refactor print.jl into a print subfolder?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#550]
I did some local tinkering when trying to improve compilation times to break up the container printing into more self contained functions, but didn't include because it seemed marginal and could have made rebased ~~OneIndexedArrays~~ harder.

I'm thinking that it could be a good idea to do that anyway, just to improve maintainability (especially now its arguably even more complex), but I'd also want to break it up into files at the same time. I didn't want to do that unilaterally though.
# churn

**Comment by joehuchette** [comment]
I don't mind unilateral if it means I don't have to touch the printing code :)

I agree it could use some refactoring; it's pretty inscrutable for me, and I feel like my changes to it have been somewhat hacky because of that. So have at it.

**Comment by mlubin** [comment]
Fine with me

**Comment by mlubin** [comment]
This never happened
