### ISSUE TITLE
langauge

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#562]
This typo has been around for a while
```
# An algebraic modelling langauge for Julia
```

**Comment by IainNZ** [comment]
lol

**Comment by IainNZ** [comment]
https://github.com/JuliaOpt/JuMP.jl/commit/3b1faa7e0d5923aa6830685de02b2abbb3309fd0

**Comment by IainNZ** [comment]
Just realized they are double-L modelling too

**Comment by IainNZ** [comment]
https://github.com/JuliaOpt/JuMP.jl/commit/21cc66b54e591b8120b87f482771bffc0f8b4e52
