### ISSUE TITLE
any chance we can add solver support for SCIP (scip.zib.de)? 

### ISSUE THREAD

**Issue by pixiez** [JuliaOpt/JuMP.jl#565]
this is another excellent open source solver out there and would be good if we can support it

**Comment by mlubin** [comment]
There's an interface under development at https://github.com/ryanjoneil/SCIP.jl, but it's lacking volunteers. It should also be possible to call scip through the https://github.com/JackDunnNZ/AmplNLWriter.jl package, but that hasn't been tested and you won't have access to any advanced features such as callbacks.

**Comment by IainNZ** [comment]
Hope you can contribute to SCIP.jl,  @pixiez !
