### ISSUE TITLE
NLExpressions and multiplication / division with numbers

### ISSUE THREAD

**Issue by anriseth** [JuliaOpt/JuMP.jl#571]
I guess this is an issue with the complexity of dealing with nonlinear expressions, so this is more of a note for people who might have the same problems:

The Hessian sparsity changes drastically depending on how you set your objectives in nonlinear optimisation. Division is bad, so is multiplication with something like (1 - a) for some scalar a.
The way around these issues is using multiplication with dummy-variables. In the following, let nf2 be a ParametricExpression defined by @defNLExpr:

```julia
julia> @setNLObjective(m, :Min, nf2*(1-a))
julia> solve(m)
This is Ipopt version 3.11.9, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:      355
Number of nonzeros in Lagrangian Hessian.............:    61075
*snip*

julia> num = (1-a)
julia> @setNLObjective(m, :Min, nf2*num)
julia> solve(m)
This is Ipopt version 3.11.9, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:      355
Number of nonzeros in Lagrangian Hessian.............:     1495
```

Likewise, if you want `@setNLObjective(m, :Min, nf2 / a)`. It is better to use `b = 1/a` and  `@setNLObjective(m, :Min, nf2 * b)`

**Comment by mlubin** [comment]
Yes, there are a few heuristics in the sparsity detection code. Will be
addressed in the next rewrite.

**Comment by mlubin** [comment]
I'd recommend using ``IpoptNLSolver`` from the AmplNLWriter package as a workaround, but there are some [open issues](https://github.com/JackDunnNZ/AmplNLWriter.jl/issues/6) with that.
