### ISSUE TITLE
Think about function names

### ISSUE THREAD

**Issue by davidanthoff** [JuliaOpt/JuMP.jl#573]
Right now JuMP seems to use naming conventions that are not in line with base julia. For example, camel case is not to be used in base julia for function names, but things like ``setValue`` in JuMP use it. Maybe that should really be ``set_value``, to be consistent? Or just ``setvalue`` (all lower case).

**Comment by mlubin** [comment]
These names were chosen mostly before julia had settled on naming conventions. I'd be reluctant to make a change at this point given the huge amount of churn in user code unless there's a proposal that's convincingly much better than what we have now.

**Comment by joehuchette** [comment]
I think that, if we were starting from scratch, we'd go with the all lower case names option to be more julian. At this point it might not be worth the churn to switch, though we could introduce aliases and see what happens.

**Comment by davidanthoff** [comment]
I really don't feel strong about this, I just noticed it now...

**Comment by IainNZ** [comment]
JuMP predates even Julia 0.1, so yes, a bit unfortunate. I'd be worried even adding aliases could be problematic in terms of sharing code/documentation - not a problem for savvy coders, but would throw off people who want to use JuMP like they use AMPL.

I'd actually be interesting in adding `@defVariable`, I don't like much how `@defVar` is short and the rest is long (see also https://github.com/JuliaOpt/JuMP.jl/issues/31).

Also, pie-in-the-sky maybe, but
`sum{i in 1:10, i*x[i]}`
is arguably clearer than
`sum{i*x[i], i in 1:10}`

**Comment by mlubin** [comment]
Where would conditions go?

**Comment by IainNZ** [comment]
Haven't got that far :+1: Just wanted to throw it out there

**Comment by davidanthoff** [comment]
I'm not a fan of aliasing, that would just be confusing.

My sense is that renaming at this point would still be a lot less intrusive than the kind of changes julia users must suffer through from the main language (say the new dict stuff). So maybe there is an argument to be made that the user base right now still has to be fairly open to these kinds of changes.

But, can easily see the argument for just doing nothing.

**Comment by mlubin** [comment]
I'm open to a serious discussion if someone puts together a comprehensive proposal for renaming everything, though I'm not sufficiently motivated to do it myself.

**Comment by IainNZ** [comment]
One point in favor of the distinct syntax is that it makes it clear that it is an embedded DSL, that doesn't necessarily follow the same rules. The `@`s actually aid in this too.

**Comment by mlubin** [comment]
Yes, I think DSLs have some liberty in coming up with their own naming conventions.

**Comment by mlubin** [comment]
MathProgBase is just a library, not a DSL, so we try to follow julia conventions there.

**Comment by davidanthoff** [comment]
Can't say that I'm motivated to do this ;) The DSL argument works for the macros, but not really for all the helper functions that get values from vars etc, right?

**Comment by IainNZ** [comment]
But then it's a big jumble...

**Comment by davidanthoff** [comment]
I know. Someone should probably just close this issue :)
