### ISSUE TITLE
Norm1 and NormInf, the great debate

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#578]
Perhaps unsurprisingly, someone tried to use these and they didn't work. I think to implement them could require disabling hot starts (due to the complexity of mapping between MPB indices and the original JuMP problem), and would be another complexity increase (but how much I'm not sure)

**Comment by joehuchette** [comment]
Why don't we implement this first as an extension and see how it works?

**Comment by mlubin** [comment]
I'm very much against adding ad-hoc transformations like this. We're going to end up with a huge increase in complexity and a DCP-ish syntax that isn't as useful or consistent as Convex.jl. Either we do full DCP or we don't.

**Comment by joehuchette** [comment]
(Let's do full DCP)

**Comment by IainNZ** [comment]
Taste the rainbow

**Comment by IainNZ** [comment]
I like it being in a little JuMP tools package though

**Comment by mlubin** [comment]
JuDCP?

**Comment by iamed2** [comment]
Is this a thing that wen't forward?

**Comment by mlubin** [comment]
Not at all, should probably close this as too speculative

**Comment by IainNZ** [comment]
I made a start at this in https://github.com/IainNZ/JuMPTools.jl

**Comment by mlubin** [comment]
No reason to leave this open
