### ISSUE TITLE
@LinearConstraint with syntiax as @addConstraint

### ISSUE THREAD

**Issue by FabrizioLacalandra** [JuliaOpt/JuMP.jl#595]
@LinearConstraint(expr) (as well as @QuadConstraint(expr))
does not enable the full expressive power of 
@addConstraint(m::Model, con)

or that of 
@defExpr(ref, expr)

so that the following does not work
MyLCns = @LinearConstraint([i=1:2:4], x[i]+x[i+1] <=1)

It could be useful to have the same expressive power also for  @LinearConstraint to define a (linear/quadratic) constraint without addint it to the model. Later one could get the coefficient of the linear constraints and manipulate them

Fabrizio

**Comment by mlubin** [comment]
It shouldn't be hard to get this working:
```
@LinearConstraint(MyLCns[i=1:2:4], x[i]+x[i+1] <=1)
```
My only concern is that it could be confusing to someone reading the model how this differs from ``@addConstraint``. What about ``@defLinearConstraint`` for consistency with ``@defExpr``?

**Comment by FabrizioLacalandra** [comment]
Totally agree, in fact it is a def of a cns. My final goal is to have this things working
MyLCns.terms.vars

**Comment by mlubin** [comment]
See [@build_constraint](http://www.juliaopt.org/JuMP.jl/v0.20/constraints/#JuMP.@build_constraint). We don't have the one-line version that constructs a JuMP container given index sets. If this is needed, please open a new issue.
