### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/JuMP.jl#599]
I get this warning quite randomly, as in, it doesn't repeat every time I run the same code without doing any modification. Is there something I need to fix in my code? 

Warning: New definition 
    *(S<:Union(GenericQuadExpr{Float64,Variable},GenericAffExpr{Float64,Variable},Variable),T<:GenericQuadExpr{Float64,Variable}) at /Users/harsha/.julia/v0.3/JuMP/src/operators.jl:611
is ambiguous with: 
    *(T<:GenericQuadExpr{Float64,Variable},S<:Union(GenericQuadExpr{Float64,Variable},GenericAffExpr{Float64,Variable},Variable)) at /Users/harsha/.julia/v0.3/JuMP/src/operators.jl:607.
To fix, define 
    *(T<:GenericQuadExpr{Float64,Variable},T<:GenericQuadExpr{Float64,Variable})
before the new definition.

**Comment by mlubin** [comment]
Hi @harshangrjn, have you run ``Pkg.update()`` recently? Might be fixed in the most recent version

**Comment by harshangrjn** [comment]
I actually did it a week ago. But, let me try that again and will keep you updated.

**Comment by mlubin** [comment]
@harshangrjn, has this been resolved?

**Comment by harshangrjn** [comment]
@mlubin, I updated the packages but were incompatible with the previous version of Julia I have. So, reverted back my packages.  As a result, I still see these warnings intermittently.

**Comment by mlubin** [comment]
What's the output of ``Pkg.status()``? If you have any JuMP-related packages on the ``master`` branch, I'd recommend releasing them back to the package manager with ``Pkg.free("...")``

**Comment by mlubin** [comment]
We've gone through a few releases since this was opened. If you're still experiencing it on the latest version, please reopen or file a new issue.
