### ISSUE TITLE
disable constraints

### ISSUE THREAD

**Issue by FabrizioLacalandra** [JuliaOpt/JuMP.jl#606]
I would be nice to have a macro @removeconstraint() working also on a subset of the cns previously defined (?)
so that something like that works

@addConstraint(m, xyconstr[i=1:3,j=6:-2:2], x[i] - y[j] == 1)

@removeconstraint(m, xyconstr[i=1,j=6:-2:4])

Fabrizio

**Comment by mlubin** [comment]
Forgetting about macros, just a "disable constraint" function would be useful.

**Comment by joehuchette** [comment]
Would this delete the constraint forever from the model, or would it flip a boolean stored somewhere else that's referenced when building the model? (and that could be unflipped later to reinstate the constraint)

**Comment by FabrizioLacalandra** [comment]
@mlubin I don't understand why the difference wrt the function, indeed with the funcion would be possible to use the same expressive/compact indexing power of the addConstraint ?
@joehuchette nice question, of course the second choice would be ideal. My use case is that of some blocks of constraints that i want to remove if some conditions are met but these considtions are checked after the model is created, then i solve a sequence of problems reinserting (blocks of ) those cns

Thanks very much
Fabrizio

**Comment by mlubin** [comment]
@FabrizioLacalandra, is this in the context of LP or MILP? (If LP, do you expect an algorithmic hot-start when enabling previously disabled constraints?)

**Comment by FabrizioLacalandra** [comment]
@mlubin definately in the MILP context, not interested in hot start in lp setting

**Comment by ccoffrin** [comment]
I'll also make a case for the ability to deactivate or remove constraints from a model.

My use case is to be able to implement the idea of "constraint relaxation schemes" which we proposed [here](http://link.springer.com/chapter/10.1007%2F978-3-319-23219-5_4).

In short, a constraint relaxation scheme, looks at the variable bounds, then generates a collection of constraints based on those bounds.  The number and form of the constraints can change based on the bounds.  A key example being the function sin(x) around x=0. if the bounds include 0, you have two linear cuts, if they do not include 0 you have one non-linear and one linear cut.

In this [code](https://github.com/ccoffrin/ac-opf-bounds), I implemented relaxation schemes as little classes which only know about a subset of variables and constraints relevant to them, they add and remove their constraints in the gurobi model, when an "update" method is called.

**Comment by mlubin** [comment]
@ccoffrin, is this a convenience argument or performance argument?

**Comment by ccoffrin** [comment]
First order benefit is for convenience in the implementation of such a system.  Notice that a constraint relaxation does not need to know anything else about the model, just it's subset of constraints and variables it relates to.

The second order benefit is in performance in the update process.  If only 1-to-10% of your constraints come from constraint relaxations, then you may not want to rebuild the whole model every time. 

In the case of the implementation I referenced, gurobi **might** also take advantage of the variable values from the last solution to warm-start modified model, to speed of subsequent solves.  I have not confirmed this.

**Comment by mlubin** [comment]
One worry I have is that people will do silly things like solve in a loop and add and disable constraints:
```
m = Model()
N = 1000000
@variable(m, x[1:10])
# add a couple of constraints
# define data
for i in 1:N
    myconstraint = @constraint(m, dot(data[i],x) <= 10)
    JuMP.disable(myconstraint)
end
```
This means that every model generation pass will be O(N) to check which constraints are enabled even though the model is of constant size.

**Comment by ccoffrin** [comment]
That's a good point, and sounds like an argument for *remove* rather than disable, which is fine by me.

**Comment by mlubin** [comment]
Then the question becomes how do you handle constraint references and the fact that they could be renumbered after the fact.

**Comment by ccoffrin** [comment]
I would need to understand the JuMP model object in more detail to suggest a good design.

A simple solution might be to no do a re-numbering.  Have a map from id -> constraint, if the constraint is deleted remove it from the mapping.  Always add constraints with increasing id numbers, regardless of the any deletions.

In principle, a reference to a constraint need not be a number, it could simply be a pointer to a constraint object.  Then you just need a way to decouple the constraint object from the model, when it's deleted.

**Comment by mlubin** [comment]
@ccoffrin, could be a nice little project if you want to get hacking on JuMP

**Comment by ccoffrin** [comment]
sounds like a plan!
