### ISSUE TITLE
Accessing Ipopt solver stats

### ISSUE THREAD

**Issue by ashwincarvalho** [JuliaOpt/JuMP.jl#609]
Similar to #442, #405.

I am looking to get stats such as number of iterations, solve time (with and without function evaluations) while using Ipopt via JuMP. It seems like `MathProgBase.getsolvetime(getInternalModel(jumpmodel))`, etc. have not been implemented for Ipopt.

Also, `MathProgBase.numvar(getInternalModel(jumpmodel))` returns 0 for a simple unconstrained NLP with one variable.

I guess this is a feature request, but is there an easy fix? Thanks!

**Comment by mlubin** [comment]
The numvar issue has an easy fix: https://github.com/JuliaOpt/Ipopt.jl/commit/ed85a1f17289d3bd03d57a27ce4a2efce001f310

For ``getsolvetime``, I don't know if Ipopt has an API to access its internally recorded solution time. @tkelman? Lacking that, you could just add a timer in IpoptSolverInterface.jl. PRs accepted.

**Comment by tkelman** [comment]
yeah, pretty sure there's a solve statistics api that gives you all of this

**Comment by tkelman** [comment]
ah but it's only exposed via c++ right now, so would need to write an extern c wrapper patch and pursue upstreaming it.

**Comment by mlubin** [comment]
That's not *too* much work...

**Comment by mlubin** [comment]
Closing this as it's unrelated to JuMP. Feel free to reopen under Ipopt.jl
