### ISSUE TITLE
simple bug on parseExpr_staged.jl

### ISSUE THREAD

**Issue by emreyamangil** [JuliaOpt/JuMP.jl#621]
line 152 on src/parseExpr_staged.jl has a simple bug, it is currently:

c * qcoeffs * x,

should be

c.qcoeffs * x?

**Comment by mlubin** [comment]
Could you paste the constraint which triggered this bug? It's okay if the data is missing, we just need the algebraic expression

**Comment by emreyamangil** [comment]
portion of objective that causes the issue:

10 Pgc[4,1,1]² + 10 Pgc[4,1,2]² + 20 Pgc[4,2,1]² + 20 Pgc[4,2,2]² + 20 Pgc[4,3,1]² + 20 Pgc[4,3,2]² + 20 Pgc[4,4,1]² + 20 Pgc[4,4,2]² + 20 Pgc[4,5,1]² + 20 Pgc[4,5,2]² + 10 Pgc[6,1,1]² + 10 Pgc[6,1,2]² + 20 Pgc[6,2,1]² + 20 Pgc[6,2,2]² + 20 Pgc[6,3,1]² + 20 Pgc[6,3,2]² + 20 Pgc[6,4,1]² + 20 Pgc[6,4,2]² + 20 Pgc[6,5,1]² + 20 Pgc[6,5,2]² + 10 Pgc[7,1,1]² + 10 Pgc[7,1,2]² + 20 Pgc[7,2,1]² + 20 Pgc[7,2,2]² + 20 Pgc[7,3,1]² + 20 Pgc[7,3,2]² + 20 Pgc[7,4,1]² + 20 Pgc[7,4,2]² + 20 Pgc[7,5,1]² + 20 Pgc[7,5,2]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 20 Pgd[i,d,t][1]² + 20 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 20 Pgd[i,d,t][1]² + 20 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 20 Pgd[i,d,t][1]² + 20 Pgd[i,d,t][2]² + 20 Pgd[i,d,t][3]² + 20 Pgd[i,d,t][1]² + 20 Pgd[i,d,t][2]² + 20 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 10 Pgd[i,d,t][1]² + 10 Pgd[i,d,t][2]² + 10 Pgd[i,d,t][3]² + 200 Bgc[4,2] + 200 Bgc[4,3] + 250 Bgc[4,4] + 250 Bgc[4,5] + 200 Bgc[6,2] + 200 Bgc[6,3] + 250 Bgc[6,4] + 250 Bgc[6,5] + 200 Bgc[7,2] + 200 Bgc[7,3] + 250 Bgc[7,4] + 250 Bgc[7,5] + 100 Pgc_max[4,1] + 100 Pgc_max[4,2] + 100 Pgc_max[4,3] + 100 Pgc_max[4,4] + 100 Pgc_max[4,5] + 100 Pgc_max[6,1] + 100 Pgc_max[6,2] + 100 Pgc_max[6,3] + 100 Pgc_max[6,4] + 100 Pgc_max[6,5] + 100 Pgc_max[7,1] + 100 Pgc_max[7,2] + 100 Pgc_max[7,3] + 100 Pgc_max[7,4] + 100 Pgc_max[7,5] + 200 Bgd[i,d][1] + 200 Bgd[i,d][1] + 250 Bgd[i,d][1] + 300 Bgd[i,d][1] + 250 Bgd[i,d][1] + 200 Bgd[i,d][1] + 200 Bgd[i,d][1] + 250 Bgd[i,d][1] + 300 Bgd[i,d][1] + 250 Bgd[i,d][1] + 200 Bgd[i,d][1] + 200 Bgd[i,d][2] + 200 Bgd[i,d][3] + 200 Bgd[i,d][1] + 200 Bgd[i,d][2] + 200 Bgd[i,d][3] + 250 Bgd[i,d][1] + 250 Bgd[i,d][2] + 250 Bgd[i,d][3] + 300 Bgd[i,d][1] + 300 Bgd[i,d][2] + 300 Bgd[i,d][3] + 250 Bgd[i,d][1] + 250 Bgd[i,d][2] + 250 Bgd[i,d][3]

**Comment by mlubin** [comment]
Here's a reduced test case:

```
m = Model()
@defVar(m, x)

q = x^2
a = x+1
@addConstraint(m, a+q*3 == 0)
```
