### ISSUE TITLE
setName is not working well on this example

### ISSUE THREAD

**Issue by emreyamangil** [JuliaOpt/JuMP.jl#627]
The following example doesn't print correctly the labels of the variables, is this a known issue? many thanks!!!

julia> using JuMP

julia> using CPLEX

julia> numBins = [2,3,1]
3-element Array{Int64,1}:
 2
 3
 1

julia> m = Model(solver=CplexSolver())
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver set to CPLEX.Cplex

julia> N = 3
3

julia> t = Array(Vector{Variable},N)
3-element Array{Array{JuMP.Variable,1},1}:
 #undef
 #undef
 #undef

julia> for k in 1:N
               @defVar(m, t[k][j=1:numBins[k]], Bin)
       end

julia> for k = 1:N
       for j = 1:numBins[k]
       setName(t[k][j], "t[$k][$j]")
       end
       end

julia> println(m)
Min 0
Subject to
 t[k][j] ∈ {0,1} ∀ j ∈ {1,2}
 t[k][j] ∈ {0,1} ∀ j ∈ {1,2,3}
 t[k][j] ∈ {0,1} ∀ j ∈ {1}

**Comment by mlubin** [comment]
I think this is a bug, but you can do
```
@defVar(m, t[k=1:N,1:numBins[k]], Bin)
```
instead.

**Comment by emreyamangil** [comment]
Thanks Miles!! Will certainly switch to this asap!

**Comment by mlubin** [comment]
@joehuchette, another issue here is that the base name for the ``JuMPArray`` shouldn't be ``"t[k]"``

**Comment by joehuchette** [comment]
That's true, but that seems a much trickier thing to handle corrrectly

**Comment by emreyamangil** [comment]
Hey Joey and Miles! First of all many thanks for your time, though I have bad news :(

The following works with setName

``````````````````````````````````
using JuMP



type mymodel
        x
        m
        myx
        function mymodel()
                m = new()
                m.m = Model()
                m.x = Any[]
                return m
        end
end

function addvar(m::mymodel, myind)
        push!(m.x, @defVar(m.m, x[1:10, 1:2]))
        for i = 1:10
                for j = 1:2
                        setName(x[i,j], "x[$myind][$i,$j]")
                end
        end
        @addConstraint(m.m, sum{x[i,1], i = 1:10} <= 10)
        @addConstraint(m.m, sum{x[i,2], i = 1:10} <= 5)
        @setObjective(m.m, Min, m.myx + sum{m.x[j][i,k], i = 1:10, k = 1:2, j = 1:myind})

end

m = mymodel()
m.myx = @defVar(m.m, myx)
addvar(m, 1)
addvar(m, 2)


println(m.m)
``````````````````````````````````

But when you turn myx into an array it doesn't :(

`````````````````````````````````
using JuMP



type mymodel
        x
        m
        myx
        function mymodel()
                m = new()
                m.m = Model()
                m.x = Any[]
                return m
        end
end

function addvar(m::mymodel, myind)
        push!(m.x, @defVar(m.m, x[1:10, 1:2]))
        for i = 1:10
                for j = 1:2
                        setName(x[i,j], "x[$myind][$i,$j]")
                end
        end
        @addConstraint(m.m, sum{x[i,1], i = 1:10} <= 10)
        @addConstraint(m.m, sum{x[i,2], i = 1:10} <= 5)
        @setObjective(m.m, Min, m.myx[1,1] + sum{m.x[j][i,k], i = 1:10, k = 1:2, j = 1:myind})

end

m = mymodel()
m.myx = @defVar(m.m, myx[1:2,1:2])
addvar(m, 1)
addvar(m, 2)


println(m.m)
`````````````````````````````````

any insights why this is not working?

**Comment by mlubin** [comment]
What are you seeing in the second example and how does it differ from what you're expecting to see?

**Comment by mlubin** [comment]
Note on JuMP master you can replace the setName loop with:
```
@defVar(m.m, x[1:10, 1:2], basename="x[$myind]")
```

**Comment by emreyamangil** [comment]
Thanks @mlubin !! We will try this asap, the difference is that [$myind] portion of variable name disappears from the second one, but it is there on the first one, curious bug! :)

**Comment by joehuchette** [comment]
What do you mean by that? If there's a bug, please pass along some code to
reproduce it

**Comment by emreyamangil** [comment]
Hey @joehuchette ! The above code produces it, sorry for not being specific! first code produces variable names as follows:

x[1][1,2] ... etc.

The second code produces the variable names as

x[1,2] ... etc.

The only change among the two is myx changes to an array of Variables, and we didn't change anything about the naming of x or itself as well. Please let me know if this makes sense, many thanks!

**Comment by joehuchette** [comment]
I'm still not sure what you mean, combining yours and Miles' code I get:
```jl
using JuMP

type mymodel
        x
        m
        myx
        function mymodel()
                m = new()
                m.m = Model()
                m.x = Any[]
                return m
        end
end

function addvar(m::mymodel, myind)
        push!(m.x, @defVar(m.m, x[1:10, 1:2], basename="x[$myind]"))

        @addConstraint(m.m, sum{x[i,1], i = 1:10} <= 10)
        @addConstraint(m.m, sum{x[i,2], i = 1:10} <= 5)
        @setObjective(m.m, Min, m.myx[1,1] + sum{m.x[j][i,k], i = 1:10, k = 1:2, j = 1:myind})

end

m = mymodel()
m.myx = @defVar(m.m, myx[1:2,1:2])
addvar(m, 1)
addvar(m, 2)

println(m.m)
```
```
Min myx[1,1] + x[1][1,1] + x[2][1,1] + x[1][1,2] + x[2][1,2] + x[1][2,1] + x[2][2,1] + x[1][2,2] + x[2][2,2] + x[1][3,1] + x[2][3,1] + x[1][3,2] + x[2][3,2] + x[1][4,1] + x[2][4,1] + x[1][4,2] + x[2][4,2] + x[1][5,1] + x[2][5,1] + x[1][5,2] + x[2][5,2] + x[1][6,1] + x[2][6,1] + x[1][6,2] + x[2][6,2] + x[1][7,1] + x[2][7,1] + x[1][7,2] + x[2][7,2] + x[1][8,1] + x[2][8,1] + x[1][8,2] + x[2][8,2] + x[1][9,1] + x[2][9,1] + x[1][9,2] + x[2][9,2] + x[1][10,1] + x[2][10,1] + x[1][10,2] + x[2][10,2]
Subject to
 x[1][1,1] + x[1][2,1] + x[1][3,1] + x[1][4,1] + x[1][5,1] + x[1][6,1] + x[1][7,1] + x[1][8,1] + x[1][9,1] + x[1][10,1] ≤ 10
 x[1][1,2] + x[1][2,2] + x[1][3,2] + x[1][4,2] + x[1][5,2] + x[1][6,2] + x[1][7,2] + x[1][8,2] + x[1][9,2] + x[1][10,2] ≤ 5
 x[2][1,1] + x[2][2,1] + x[2][3,1] + x[2][4,1] + x[2][5,1] + x[2][6,1] + x[2][7,1] + x[2][8,1] + x[2][9,1] + x[2][10,1] ≤ 10
 x[2][1,2] + x[2][2,2] + x[2][3,2] + x[2][4,2] + x[2][5,2] + x[2][6,2] + x[2][7,2] + x[2][8,2] + x[2][9,2] + x[2][10,2] ≤ 5
 myx[i,j] free ∀ i ∈ {1,2}, j ∈ {1,2}
 x[1][i,j] free ∀ i ∈ {1,2,…,9,10}, j ∈ {1,2}
 x[2][i,j] free ∀ i ∈ {1,2,…,9,10}, j ∈ {1,2}
```
Is this not what you want?

**Comment by emreyamangil** [comment]
That is perfect! Thanks Joey, that fixes the setName issue then, we can just safely switch to Miles' code (when we were using setName, for some reason the [1] right after x was dropping, many thanks again!
