### ISSUE TITLE
'Free' constraint sense not supported

### ISSUE THREAD

**Issue by benmoran** [JuliaOpt/JuMP.jl#642]
Is there a reason to prohibit Free constraints, like "x < = Inf" ?

```
using JuMP
m = Model()
@addConstraint m x<=Inf
```

now gives 

```
Error showing value of type JuMP.ConstraintRef{JuMP.GenericRangeConstraint{JuMP.GenericAffExpr{Float64,JuMP.Variable}}}:
ERROR: 'Free' constraint sense not supported
 in sense at /home/ben/.julia/v0.4/JuMP/src/affexpr.jl:145
 in con_str at /home/ben/.julia/v0.4/JuMP/src/print.jl:809
 in show at /home/ben/.julia/v0.4/JuMP/src/print.jl:919
```

But I think older versions of JuMP used to accept such constraints, and I found them useful when formulating lots of different related problems and handling them without special cases.

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/JuMP.jl/issues/425 I think.
Can you confirm if there's an actual issue solving the model or if there's just an error when printing that particular constraint?

**Comment by mlubin** [comment]
`@constraint(m, x + 1 <= Inf)` works now.
