### ISSUE TITLE
condition operations on Affine/Quad expressions

### ISSUE THREAD

**Issue by abhinavuttam** [JuliaOpt/JuMP.jl#645]
Consider the following use case:
value = weights * returns
Minimize [ sum(values > 0) / sum(values <0) ] over given range of weights

Using JuMP, I can define expressions for value but there is no corresponding functionality to do conditional operations on value (value is of type GenericAffExpr).

Am i missing something or this functionality does not exist?

@defVar(myModel, weights[1:n])
@defExpr(value, weights'.*returns)
@defExpr(posValue, sum(value[value.>0]))   <<---- This does not work!

Thanks,
Abhinav

**Comment by IainNZ** [comment]
You'll need to explicitly model that objective function using something like mixed-integer linear programming - JuMP cannot make such a transformation for you.

**Comment by abhinavuttam** [comment]
Thanks.  I think the issue is not exactly the modeling of the problem but more on conditional evaluation of JuMP expressions when the solver is solving a problem.  So on each iteration, I need to segregate my vector based upon certain conditions.  The operations on segregated results help me calculate my objective function.

Additionally, above in non-linear so MILP does not exactly work.  Maybe I am missing something on how that ratio can be modeled linearly?
