### ISSUE TITLE
Replace macros with generated functions

### ISSUE THREAD

**Issue by AzamatB** [JuliaOpt/JuMP.jl#648]
Now that [generated functions](http://docs.julialang.org/en/release-0.4/manual/metaprogramming/#generated-functions) have been introduced in 0.4, it would be nice to replace all the macros with them.

Advantages I see in doing this:
 - From users perspective:
  - functions are by far more popular and more familiar to users than macros.
  - more elegant syntax without ugly `@` symbol, which resonates with the Julia's spirit in general
  - more consistent syntax with `Convex.jl`. This is very handy for those who use these two awesome packages interchangeably depending on the problem type.

- From developers perspective, who will be extending `JuMP` to tailor it to his specific problem.
  - easier to extend
  - less error prone then macros
  - having access to types of inputs makes these functions more powerful and more flexible then macros. One is able to do fancier things without it looking like a hack.
  - ability to debug corresponding functions (once debugger will be introduced)

Disadvantages:
- Will brake a lot of existing code.

**Comment by mlubin** [comment]
Generated functions and macros are mostly orthogonal. Macros let us define our own syntax like:
```
@defVar(m, l[i] <= x[i=1:N] <= u[i])
@addConstraint(m, sum{x[i],i=2:4} <= 5)
```
How do generated functions help replace this?

**Comment by mlubin** [comment]
Please have a look at the discussion in section 3 at http://arxiv.org/pdf/1508.01982v1.pdf for why we use macros.

**Comment by AzamatB** [comment]
Hm, it could be `defVar(m, l, x, u, 1:N)`, but I can see why this is less preferred alternative. Nevermind
