### ISSUE TITLE
make at-defExpr take Model too?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#649]
I realize we wouldn't do anything with this extra field (right now), but I found myself instinctively doing it anyway, and now with the new at-defNLExpr, it sticks out like a sore thumb. Additionally, I don't like how not having the model seems to imply that expressions are somehow model independent like in PuLP.
This would be a deprecation warning change, and could stay as a dep warning for quite a while as it isn't hurting anything right now.
Thoughts?

**Comment by mlubin** [comment]
Seems like the right thing to do, especially for 0.12.

**Comment by IainNZ** [comment]
OK, I'll make a PR

**Comment by IainNZ** [comment]
The one-argument form of `@defExpr` is making it trickier... I didn't even know we had a one argument form, or what it did

**Comment by IainNZ** [comment]
Actually I don't know how to do this. If you pass in two arguments, it could be
```
@defExpr(mymod, 2*x)
```
or
```
@defExpr(myexpr, 2*x)
```
Insert a runtime type check on the LHS? It gets even weirder with containers with loops...

**Comment by joehuchette** [comment]
A runtime check like
```
isa(myexpr, Model) || warn(...)
```
seems best.

**Comment by mlubin** [comment]
I'm ok with dropping the one-argument version for consistency, doesn't seem to be used very often in the wild.

**Comment by mlubin** [comment]
@IainNZ, are you working on this or do you want me to take a stab?

**Comment by IainNZ** [comment]
I started, but I've got no time now :(
