### ISSUE TITLE
Hard-to-find indexing bug (that I'm not sure we can address?)

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#653]
So I have a 3D JuMP variable, e.g.

```
julia> @defVar(m, x[1:3,1:5,1:6])
3x5x6 Array{JuMP.Variable,3}:
...
```

and due to stupidity, I accidentally only indexed it by the first and third variable, i.e.
```
x[1,6]
```
(although they weren't constants, they were `i`, and `T+1`)

What this gives you is `x[1,1,2]`

Now we return an `Array{JuMP.Variable}`, I'm not sure what we can do. But it really sucks.

**Comment by joehuchette** [comment]
We could do error checking with a ``Base.getindex(::Array{Variable}, idx...)`` method, but that's probably not a good idea for a number of reasons. This type of indexing is really strange; why is it allowed at all?

**Comment by IainNZ** [comment]
Really not sure, its hard to see why you'd want this. I could make an argument for
```
x[1,1] == x[1,1,:]
```
but this really exposes the underlying memory model way too much.
Took a lot of `println` debugging, the model was way too big to print.
Looking for a base issue...

**Comment by mlubin** [comment]
Any reason to leave this open? Upstream discussion is at https://github.com/JuliaLang/julia/issues/14770
