### ISSUE TITLE
JuMP error when writing some SOCP constraints with "norm()" AND some with "^2"

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#659]
Whenever I try to write a conic model including constraints using the norm() function and other constraints using the square function, I get an error like this:
```
LoadError: BoundsError: attempt to access 2-element Array{Int64,1}:
 6
 1
  at index [3]
 in conicconstraintdata at /Users/chris/.julia/v0.4/JuMP/src/solvers.jl:610
 in buildInternalModel at /Users/chris/.julia/v0.4/JuMP/src/solvers.jl:276
```
Here is a minimal working example:
```
using Gurobi, JuMP

mod = Model(solver=GurobiSolver(OutputFlag=true))

@defVar(mod, x[1:5] >= 0)
@defVar(mod, 0 <= u <= 5)
@defVar(mod, v)

@setObjective(mod, Max, v)

@addConstraint(mod, norm(x[:]) <= 1)
@addConstraint(mod, v^2 <= u * x[1])

solve(mod)
```
It seems to work only if you convert all SOCP constraints to a form using "norm()", or all to a form using the square function.

**Comment by mlubin** [comment]
This code path for rotated SOCs was probably never really tested.
CC @joehuchette

**Comment by joehuchette** [comment]
Thanks @chriscoey, I'll look into this.

**Comment by joehuchette** [comment]
OK I patched this pretty easily, now we need to add rSOC to the list of cones supported allowed in the MPB translation layer:
https://github.com/JuliaOpt/MathProgBase.jl/blob/2f85f363cbb4ea24997706f9d2c04f77b7fb808e/src/SolverInterface/lpqp_to_conic.jl#L38

**Comment by mlubin** [comment]
@joehuchette does the code work now for Mosek? That's the only solver that takes rSOC natively.

**Comment by joehuchette** [comment]
It looks like there's a 1/2 factor missing somewhere in the interface; it's returning the wrong answer.

**Comment by mlubin** [comment]
The definition of ``SOCRotated`` has a 2. You need that to make it a self-dual cone IIRC

**Comment by mlubin** [comment]
Should be fixed by https://github.com/JuliaOpt/MathProgBase.jl/commit/01aa7bf1f53627f3b83496c08df4da4a7f8b7754 now

**Comment by joehuchette** [comment]
:+1:

**Comment by mlubin** [comment]
Not tagged yet, and not sure if [this](https://github.com/JuliaOpt/MathProgBase.jl/commit/01aa7bf1f53627f3b83496c08df4da4a7f8b7754#commitcomment-15790508) was resolved
