### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by mauriciotm** [JuliaOpt/JuMP.jl#662]
using JuMP

m = Model()

@defVar(m, x[1])
@defVar(m, -1 <= x[2] <= 5)
@defVar(m,-1 <= x[3] <= 5)
@defVar(m, -2 <= x[4] <= 2)

@addConstraint(m, -x[1] + 6x[2] - x[3] + x[4] >= -3)
@addConstraint(m, 7x[2] + x[4] == 5)
@addConstraint(m, x[3] + x[4] <= 2)

@setObjective(m, Max, 3x[1] - x[2])

status = solve(m)

println(m)
println("z = ", getValue(x)
println("Objective value: ", getObjectiveValue(m))
LoadError: KeyError: (1,) not found
while loading In[64], in expression starting on line 319

When I change the variables to x, y, z, and w the problem is solved without error messages. Does anyone know what is the problem of using the vector in this case?

Thanks

**Comment by IainNZ** [comment]
That isn't how `@defVar` works. Each successive call to `@defVar` is overriding the previous `x`.
What you might want to do is:
```
lb = [-Inf, -1, -1, -2]
ub = [+Inf, 5, 5, 2]
@defVar(m, lb[i] <= x[i=1:4] <= ub[i])
```

**Comment by IainNZ** [comment]
The preferred place for questions like this is the mailing list at:
https://groups.google.com/forum/#!forum/julia-opt
