### ISSUE TITLE
Feature Request: Nonlinear Blackbox Objective Function

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaOpt/JuMP.jl#663]
Hey, just a feature request to extend the objectives to allow for user defined functions and then use them in the solver defined by the model. Many of the solvers used by JuMP allow for blackbox optimization, so it would be nice to be able to use those features within the JuMP framework. I would imagine such a feature as letting the user give a reference to a function, with the abilities to specify properties of the function (is it differentiable? etc.) and using those properties to pick a solver.

**Comment by mlubin** [comment]
This is essentially a dup of https://github.com/JuliaOpt/JuMP.jl/issues/486. I'm not keen on supporting derivative-free optimization, but the plan is to let users provide callbacks for derivatives (or try to run autodiff).
