### ISSUE TITLE
Remove deprecated iteration methods for containers?

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#664]
They were deprecated in August last year, for `v0.10` it seems

**Comment by joehuchette** [comment]
Which methods are these?

**Comment by IainNZ** [comment]
https://github.com/JuliaOpt/JuMP.jl/blob/937b02d41a6366f78c9861614ac4ea30b5aa8d0a/src/JuMPContainer.jl#L145-L166

**Comment by joehuchette** [comment]
Fine by me

**Comment by mlubin** [comment]
Ok with me

**Comment by mlubin** [comment]
Closed by #667?
