### ISSUE TITLE
Possible error with equality constraints on SDP variables

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/JuMP.jl#665]
I've been attempting to use JuMP's interfaces for semidefinite programming, but I'm running into some strange issues. It *looks* like a bug in JuMP, but I'm not sure that I'm not just doing something wrong. So far, the minimal example that reproduces the issue is:

```julia
model = Model(solver=MosekSolver())
@defVar(model, Q[1:2, 1:2], SDP)
objective = Q[1,1] * Q[1,1]
@addConstraint(model, Q[1,1] - 1 == Q[2,2])
@setObjective(model, :Min, objective)
solve(model)
@show getValue(Q)
@show getObjectiveValue(model)
@show getValue(objective)
@assert getObjectiveValue(model) == getValue(objective)
```

The trivially optimal solution is Q = [1 0; 0 0]. When solving this with the `MosekSolver`, I instead get: 

```julia
getValue(Q) = [1.9999999999390463 0.0
 0.0 1.0000000000000002]
getObjectiveValue(model) = 0.0
getValue(objective) = 3.9999999997561853
LoadError: AssertionError: getObjectiveValue(model) == getValue(objective)
```

If I replace the `MosekSolver` with `SCSSolver`, I get a better answer, but the same assertion failure: 

```julia
getValue(Q) = [1.0598878224495372 0.0
 0.0 0.0599354023760482]
getObjectiveValue(model) = 0.0
getValue(objective) = 1.1233621961768216
LoadError: AssertionError: getObjectiveValue(model) == getValue(objective)
```

Other variants (flipping the sign in the equality constraint, for example), produce some cases where Mosek is more correct, and others where SCS is more correct, but in general it seems that the answer is invariably wrong. 

One thing I've noticed is that it appears that `getObjectiveValue(model)` does return the truly optimal objective value, just not the value corresponding to the solution that was returned. For example, if I add an offset to the objective: 

```julia
model = Model(solver=SCSSolver())
@defVar(model, Q[1:2, 1:2], SDP)
objective = Q[1,1] * Q[1,1] + 1
@addConstraint(model, Q[1,1] - 1 == Q[2,2])
@setObjective(model, :Min, objective)
solve(model)
@show getValue(Q)
@show getObjectiveValue(model)
@show getValue(objective)
@assert getObjectiveValue(model) == getValue(objective)
```

Then `getObjectiveValue(model)` does return 1.0, which is the correct optimal objective value. But it still does not agree with `getValue(objective)`. That *suggests* to me at least, that the problem is being correctly solved, but the solution is getting mangled on the way back. But I don't know much about the internals of JuMP, so I'm only speculating.

**Comment by rdeits** [comment]
Note that changing the fourth line from 

```julia
@addConstraint(model, Q[1,1] - 1 == Q[2,2])
```

to 

```julia
@addConstraint(model, Q[1,1] == Q[2,2])
```

Fixes the problem (I get the correct optimal solution Q = [0 0; 0 0] and the correct objective value).

**Comment by joehuchette** [comment]
Hey @rdeits, the problem is the quadratic objective: essentially, we don't support mixing QP and SDP. We're only passing along the linear part of the objective (so, 0, which is why you're seeing different optimal solutions across solvers) and ignoring the quadratic portion, which is obviously a bug. I've got a fix on the way to make this an error; you'll have to reformulate your problem to have a linear objective.

**Comment by joehuchette** [comment]
For example,
```jl
model = Model(solver=MosekSolver())
@defVar(model, Q[1:2, 1:2], SDP)
@addConstraint(model, Q[1,1] - 1 == Q[2,2])
@defVar(model, objective)
T = [1 Q[1,1]; Q[1,1] objective]
@addSDPConstraint(model, T ⪰ 0)
@setObjective(model, :Min, objective)
solve(model)
```
should work.

**Comment by rdeits** [comment]
Ok, makes sense. Thanks! Amusingly, our lab's own optimization toolbox had exactly the same issue: https://github.com/spot-toolbox/spotless/issues/14

**Comment by joehuchette** [comment]
What a strange coincidence! Thanks for reporting.

**Comment by rdeits** [comment]
Thanks for the quick resolution!
