### ISSUE TITLE
Parameters for linear/quadratic problems

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#669]
Ref #304, there's still a mismatch between the support for parameters in nonlinear and linear/quadratic problems. Potentially we could store the `A` matrix in the model explicitly and update coefficients for different parameter values, reusing the same sparsity pattern. I think the main hurdle is building up expressions or constraints where `AffExpr`s and parameters are co-mingled.

**Comment by mlubin** [comment]
Just remembered the reason why we can't do this. Let's say ``N`` is a parameter, then you do:
```
@defVar(m, x[1:N])
@addConstraint(m, sum{x[i],i=1:N} <= 1)
```
What happens when you change N? It's not just about updating the coefficients in the constraint matrix.

**Comment by joehuchette** [comment]
Well we can never have that, but there's still the possibility of supporting "coefficient" parameters.

**Comment by mlubin** [comment]
Can they be used inside of filter conditions?

**Comment by joehuchette** [comment]
No, it would only be parameters for variable coefficients or constant terms in affine/quadratic constraints.
```jl
@defParam(model, p)
@addConstraint(model, p*x == p^2-1)
```
By no means as general as the nonlinear parameters, but better than nothing.

**Comment by mlubin** [comment]
The ratio of increased complexity of *everything* in JuMP to usefulness is pretty high here

**Comment by joehuchette** [comment]
Wait, do nonlinear parameters work in sums or filter conditions right now?

**Comment by mlubin** [comment]
No, just inside expressions

**Comment by joehuchette** [comment]
So
```jl
@addNLConstraint(m, sum{x[i],i=1:N} <= 1)
```
doesn't work either?

**Comment by mlubin** [comment]
No, although AFAIK it does in AMPL

**Comment by cossio** [comment]
+1, would really like to have this feature

**Comment by mlubin** [comment]
This is entirely speculative and out of scope for JuMP 1.0, so I'm tempted to close.

**Comment by odow** [comment]
Yeah. I have an application for this, but I don't think the speed improvement gained by poking the constraint matrix over rebuilding the model outweighs the additional complexity in JuMP.

**Comment by mlubin** [comment]
If anyone would like to rewrite JuMP to support this, get in touch. No use keeping the issue open though.
