### ISSUE TITLE
Error message for unrecognized functions in nonlinear expressions

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/JuMP.jl#671]
This used to work.
```jl
using JuMP
m = Model();
@defVar(m, x[1:3]);
@setNLObjective(m, Min, sum(x))
```
```
ERROR: KeyError: sum not found
```

**Comment by joehuchette** [comment]
@mlubin

**Comment by mlubin** [comment]
Are you sure? I don't think it ever worked.

**Comment by joehuchette** [comment]
Hmm so on v0.8 it didn't throw an error immediately, but it would have a cryptic error when you called solve:
```
julia> solve(m)
ERROR: unrecognized keyword argument "need_expr"
 in initialize at /Users/huchette/.julia/v0.3/JuMP/src/nlp.jl:85
 in loadnonlinearproblem! at /Users/huchette/.julia/v0.3/Ipopt/src/IpoptSolverInterface.jl:269
 in solvenlp at /Users/huchette/.julia/v0.3/JuMP/src/nlp.jl:474
 in solve at /Users/huchette/.julia/v0.3/JuMP/src/solvers.jl:9
```

**Comment by mlubin** [comment]
That's a mismatch with ReverseDiffSparse releases, not related to ``sum()``

**Comment by joehuchette** [comment]
Either way, the error message isn't particularly helpful. How tricky would it be to add ``sum`` to our whitelist of functions? I hit this when changing a linear constraint to a nonlinear constraint artificially.

**Comment by mlubin** [comment]
Impossible without another rewrite, requires vector-valued nodes in the expression graph

**Comment by mlubin** [comment]
An error message for unrecognized functions would be useful though
