### ISSUE TITLE
a lot of warnings when you create model under pmap

### ISSUE THREAD

**Issue by emreyamangil** [JuliaOpt/JuMP.jl#673]
Following creates a lot of warnings about union and dot product with a parallel call, is this a known issue? For me it was working fine using ConicModel of MPB to populate models, but a student at the lab is trying to use directly Model from JuMP and seems like addConstraint is complaining, here is a simple example!

```
# call it with julia -p 4 testpmap.jl
@everywhere using JuMP

@everywhere begin
function f(s,count,a)
    m = Model()
    @defVar(m, x[1:2])
    @addConstraint(m, [1.0 2.0]*x .>= 0.0)
    println("process id = $(myid()) s = $s count = $count, $(vecdot([1.0 2.0],[0.5 0.5]))")
    return count^a
end
end

output = pmap((a1,a2,a3)->f(a1,a2,a3), Any["a","b","c"],[i for i = 1:3], [2,3,4])
```

**Comment by emreyamangil** [comment]
@mlubin

**Comment by mlubin** [comment]
@emreyamangil, you should quote chunks of code using backticks so that we don't bother the github users ``@everywhere`` and ``@show``

**Comment by emreyamangil** [comment]
Oh god I didn't see that coming! sorry!

**Comment by mlubin** [comment]
This is a stale issue. If it still occurs, please open a new issue.
