### ISSUE TITLE
Incorrect documentation for @defNLExpr

### ISSUE THREAD

**Issue by shionlau** [JuliaOpt/JuMP.jl#675]
in http://jump.readthedocs.org/en/latest/nlp.html, it says:

> The syntax of @defNLExpr differs from @defExpr. The former requires the model object as the first argument

However, this seems incorrect. When I follow the instruction, I get the following error:

> ERROR: LoadError: in @defNLExpr: too many arguments.

Not including model object in the argument makes my code work.

**Comment by mlubin** [comment]
You're seeing the docs for the development version of JuMP. Unfortunately ReadTheDocs has been broken for months and doesn't let us maintain separate release and development documentation (https://github.com/rtfd/readthedocs.org/issues/1617). I'm not sure of an easy short-term fix.

**Comment by mlubin** [comment]
@IainNZ, could we compile and self-host a version of the release-0.11 docs to fix this?

**Comment by IainNZ** [comment]
Should be possible to build locally

**Comment by mlubin** [comment]
Fixed since 0.12 is released
