### ISSUE TITLE
Vectorized constraints in Lazy Callback

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/JuMP.jl#680]
If v is a vector and P is a square matrix, this doesn't seem to be supported in Lazy callback.
 @addLazyConstraint(cb, v'*P*v .>= 0)

JuMP throws "ERROR: LoadError: LoadError: Cannot add vectorized constraint in lazy callback"

Work around is to create an AffExpr(). However, vectorized constraints in callbacks will be helpful just the way JuMP supports it. 

Thanks.

**Comment by mlubin** [comment]
Isn't this a single constraint? Just use ``dot(v,P*v)``

**Comment by harshangrjn** [comment]
@mlubin:  Didn't realize dot product works inside @addConstraint/@addLazyConstraint.  :+1: 

But when it is a system like V*P == 0, then I need V*P .== 0 or will have to loop with dots I suppose.

**Comment by mlubin** [comment]
Fair enough, feature request accepted :)

**Comment by harshangrjn** [comment]
:+1:

**Comment by harshangrjn** [comment]
Thanks @joehuchette @mlubin. Will try it out soon.
