### ISSUE TITLE
support general colon indexing for JuMPArray

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#684]
https://groups.google.com/forum/#!topic/julia-opt/6eVnmkhiDZg

This is a regression in 0.12:
```
julia> @defVar(m, x[0:3,0:3])

julia> x[1,:]
ERROR: MethodError: `isless` has no method matching isless(::Colon, ::Int64)
Closest candidates are:
  isless(::AbstractFloat, ::Real)
  isless(::ForwardDiff.ForwardDiffNumber{N,T<:Real,C}, ::Real)
  isless(::Real, ::Real)
  ...
 in getindex at /home/mlubin/.julia/v0.4/JuMP/src/JuMPArray.jl:61
```

Related issues: https://github.com/JuliaOpt/JuMP.jl/issues/643 https://github.com/JuliaOpt/JuMP.jl/issues/287

To fix the regression I think we should have a special case for colons and put off handling ranges for later.

**Comment by tkelman** [comment]
My advisor hit this today. Can the notebooks from https://github.com/JuliaOpt/juliaopt-notebooks maybe be run as tests via NBInclude?

**Comment by mlubin** [comment]
@tkelman, I'd love a way to test the notebooks: https://github.com/JuliaOpt/juliaopt-notebooks/issues/5
