### ISSUE TITLE
syntax brainstorming

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#692]
Addressing the issue raised in https://github.com/JuliaOpt/JuMP.jl/pull/688, the current syntax of `@defVar`, despite the name, doesn't make it clear that all we're doing is defining a julia variable. Maybe it's time to brainstorm a new approach:

Both examples below are valid julia syntax:
Idea 1:

``` julia
@variables m begin
    x = (0 <= Variable[i=1:n](Int, start=5) <= i)
    ...
end
```

The trouble here is that it looks like you're assigning x to refer to the constraints enforcing the bounds instead of the variables.

Idea 2:

``` julia
# variant 1
@variables m begin
    x = Variable[i=1:n](Int, start=5,lowerbound=0,upperbound=i)
    ...
end
# variant 2
@variables m begin
    x[i=1:n] = Variable(Int, start=5,lowerbound=0,upperbound=i)
    ...
end
```

We lose some of the magic of using comparison operators, but maybe this is much clearer. You can always use explicit constraints instead if you prefer the mathy syntax. Of the two variants I prefer the first because it's more clear that we're just assigning a collection of variables to `x` whereas the second variant might lead you to think that you can append indices to `x` later on.

CC @StefanKarpinski @carnaval @yeesian @JackDunnNZ @davidanthoff @juan-pablo-vielma @chriscoey

**Comment by davidanthoff** [comment]
I think I like idea 2 variant 1 best. Idea 1 seems too busy, and the syntax too weird, to me.

If you go with the ``x = Variable`` approach, it might be worth thinking about renaming the macro to something like ``@jump``, and then also allow lines that read like ``y = Parameter()``, and maybe even constraints like that? It seems weird to have to use a macro called variable, and then to specify again later that I am adding variables...

**Comment by mlubin** [comment]
Yes, a single ``@jump`` macro is a natural conclusion from idea 2.

**Comment by chriscoey** [comment]
I agree with David on idea 2 variant 1.

I also never liked the LB <= var[...] <= UB syntax in defvar - it messes up
vertical alignment (which helps when quickly glancing over a model) and
doesn't feel like a natural way to code.

**Comment by joehuchette** [comment]
I prefer idea 2 variant 1 the most of the options presented, but still find it less satisfying than the current syntax. We lose the bounds for syntax which I like very much, and although the assignment is a bit clearer with the ``=``, it's still unlike any other assignment you would be able to write in julia (without macros).

**Comment by IainNZ** [comment]
Currently
```julia
@defVar(m, buy[1:n] >= 0, Int)
@defVar(m, 0 <= send[i=1:n,j=1:n] <= capacity[i,j])
@defVar(m, 0 <= sold[i=1:n] <= demand[i])
```
Idea 1
```julia
@variables m begin
    buy = (Variable[i=1:n](Int) >= 0)
    send = (0 <= Variable[i=1:n,j=1:n] <= capacity[i,j]))
    sold = (0 <= Variable[i=1:n] <= demand[i])
end
```
Idea 1 Var. 1
```julia
@jump m begin
    buy = Variable[i=1:n](Int, lowerbound=0)
    send = Variable[i=1:n,j=1:n](lowerbound=0,upperbound=capacity[i,j])
    sold = Variable[i=1:n](Int, lowerbound=0,upperbound=demand[i])
end
```
Idea 1 Var. 2
```julia
@jump m begin
    buy[i=1:n] = Variable(Int, lowerbound=0)
    send[i=1:n,j=1:n] = Variable(lowerbound=0,upperbound=capacity[i,j])
    sold[i=1:n] = Variable(Int, lowerbound=0,upperbound=demand[i])
end
```

I don't really find any of them an improvement to be honest.

**Comment by IainNZ** [comment]
acpower
```julia
@defVar(mod, bus_voltage_min[bus[i].bustype] <= bus_voltage[i=1:nbus] <= bus_voltage_max[bus[i].bustype], start=1)
@defVar(mod, bus[i].b_shunt_min <= bus_b_shunt[i=1:nbus] <= bus[i].b_shunt_max, start=bus[i].b_shunt0)
```

or

```julia
@defVar(mod, bus_voltage_min[bus[i].bustype] <= 
             bus_voltage[i=1:nbus] <=
             bus_voltage_max[bus[i].bustype], start=1)
```

Idea 1 Var 2, formatted nicely
```julia
@jump b begin
  bus_voltage[i=1:nbus] = Variable(start=1,
                                   lowerbound=bus_voltage_min[bus[i].bustype],
                                   upperbound=bus_voltage_max[bus[i].bustype])
  bus_b_shunt[i=1:nbus] = Variable(start=bus[i].b_shunt0,
                                   lowerbound=bus[i].b_shunt_min,
                                   upperbound=bus[i].b_shunt_max)
end
```

**Comment by IainNZ** [comment]
That could be arguably better?

**Comment by mlubin** [comment]
Definitely a lot clearer without any context what is happening in the statement.

**Comment by IainNZ** [comment]
Variant 2 of Idea 2 definitely will still have the "extension" problem, but Variant 1 will not I think.

**Comment by mlubin** [comment]
Yes, I prefer variant 1

**Comment by chriscoey** [comment]
Agreed that it's better in Iain's example. But again I think in that
example it's the LB <= var <= UB syntax that makes it hard to read in
@defvar. That would be fixed by
@defvar(m, varname[i=1:n], Int, >= LB[i], <= UB[i], start = 1)
or
@defvar(m, varname[i=1:n], Int, lb = LB[i], ub = UB[i], start = 1)
though. That's my only real gripe with the current syntax.

Of the variants, I might actually prefer 2 now, because I think you want to
be able to see quickly both the variable name and its indexing, and they're
nicely aligned on the left before "= Variable()". I might prefer "Var" and
"lb" and "ub" instead of the long names though

**Comment by mlubin** [comment]
The syntax
```
@defVar(m, varname[i=1:n], Int, >= LB[i], <= UB[i], start = 1)
```
isn't available to us, would have to be
```
@defVar(m, varname[i=1:n], Int, lb = LB[i], ub = UB[i], start = 1)
```

**Comment by yeesian** [comment]
Echo-ing joey:

I also really like the bounds syntax of at-defVar for most problems that I write. You can always align names using whitespace, e.g.
```julia
@defVar(m, x[i=1:p.nlocations] >= 0, Int, start=warmstart[i])
@defVar(m, d[1:nregions]       >= 0, Int)

@defVar(m, 0          <= p[1:nregions]   <= ub)
@defVar(m, lowerbound <= q[1:nlocations] <= upperbound)
```
For complicated problems, I find the proposals minor improvements over explicit constructions of JuMP Variables, and have not had as much opportunities to remember to use them.

**Comment by ns-1m** [comment]
I like Idea 1 Var. 2
~~~~
@jump m begin
    buy[i=1:n] = Variable(Int, lowerbound=0)
    send[i=1:n,j=1:n] = Variable(lowerbound=0,upperbound=capacity[i,j])
    sold[i=1:n] = Variable(Int, lowerbound=0,upperbound=demand[i])
end
~~~~~

**Comment by mlubin** [comment]
There doesn't seem to be too much consensus here, so I don't see any big changes happening soon. The next step forward to proceed with this would be for someone to put together a prototype JuMP extension to test out the new syntax.

**Comment by IainNZ** [comment]
I think it needs to be tried out for some nontrivial problems/index sets to really capture the impact. Hopefully the things I added here capture at least some use cases

**Comment by mlubin** [comment]
Another point here is that we're removing the semicolon from the ``sum``/``prod``/``norm`` syntax, so now using semicolons to define conditions on variable indices makes very little sense. We might think about moving to a variable declaration syntax more consistent with the generator syntax, e.g,
```jl
@variable(m, x[i,j] for i in X, j in Y if i <= j)
```

**Comment by joehuchette** [comment]
Does that parse reasonably?

**Comment by mlubin** [comment]
@joehuchette, yes, the second argument to the macro is a generator statement.

**Comment by juan-pablo-vielma** [comment]
I like it. Some comments:

1. I imagine X/Y can be something like [1:10]. Any restrictions on what X/Y can be?
2. Do we want to keep the x[1:n,1:m] syntax too? 
3. How would the detection of array indexing v/s general indexing work? If it is problematic, perhaps using the old syntax in point 2. can signal array indexing

**Comment by mlubin** [comment]
> I imagine X/Y can be something like [1:10]. Any restrictions on what X/Y can be?

Anything you can loop over in Julia.

> Do we want to keep the x[1:n,1:m] syntax too?

I wouldn't want to keep multiple inconsistent syntaxes around. If we make a change like this we should be convinced that it's obviously better than the ``x[1:n,1:m]`` so we shouldn't feel bad dropping that syntax.

**Comment by mlubin** [comment]
Let me enumerate the big issues with the current syntax:

1. Confusion about scope and the fact that we're just defining a normal Julia variable (plus registering the symbol in the model and giving a string name)
2. Confusion about "adding to index sets", e.g., ``@variable(m, x[1]); @variable(m, x[2])`` is a common mistake
3. Ugly semicolon syntax for conditions on index sets

If we can find a new syntax that addresses all of these issues and is visually appealing then I could be convinced to switch.

CC @ccoffrin @chkwon

**Comment by ccoffrin** [comment]
I like the idea of lb, ub kwargs in place of `<=`, `>=`.  I had some confusion about this syntax when I was first learning JuMP.

I am also a fan of using the generator syntax, although it probably does not immediately resolve point 2.  I like the original "idea 2" proposals for addressing this issue.  When first learning JuMP it was confusing to me that the variable declaration appears to occur inside a function/macro arguments.

In other solver APIs I have seen things along the lines of,
```
x = [variable(m, INT, lb=0, ub=1) for i in index_set]
```
Variable constructors only support 1 variable at a time and comprehensions are used for making groups of variables.  Inspired by that, here is a proposal,
```
@variable(<model>, <variable name>, <index set generator>, <type>)
@variable(m, x, [1:10], Int)
@variable(m, y, i in [1:10], Int, lb=0, ub=i)
```
By disconnecting the index set from the name of the variable, I suspect it would prevent the confusion around being able to add indexes to sets.

If the variable object pointer became the unique key for all variables in a model you could even imagine a syntax along the lines of,
```
x = variable(m, [1:10], Int)
y = variable(m, i in [1:10], Int, lb=0, ub=i)
```

**Comment by odow** [comment]
In response to the points Miles raised:

1. I like the current syntax. Once you get your head around the scoping, it's clean and makes sense to me. There probably just needs to be some more documentation, especially in the `Quick Start Guide` highlighting the different scoping cases.

2. Throw a big warning/error when someone defines a variable with a name that already exists. Maybe have a flag in `Model(; uniquevariablenames=true)` that can be explicitly turned off (the keyword needs bike-shedding).

3. Change to generators inside the square bracket of variable index
```
@variable(m, 0 <= x[i,j for i in X, j in Y if i <= j] <= 1)
```

I am not in favour of removing the `<=` and `>=` options for bounds. One of the things I really like about JuMP is that if you use the plural form of the macros (i.e. `@variables`), your model file looks virtually identical to the mathematical formulation.

**Comment by mlubin** [comment]
> Throw a big warning/error when someone defines a variable with a name that already exists.

The reason we didn't do this before was lack of anonymous variables. Now that we have these, I'd be in favor of a warning in this case. I don't even see a compelling reason why we should allow people to disable the warning.

> Change to generators inside the square bracket of variable index

The syntax ``x[i,j for i in X, j in Y if i <= j]`` doesn't currently parse. And intuitively it doesn't seem obvious that ``i`` and ``j`` would be in scope to define bounds, for example. I like the direction though.

**Comment by mlubin** [comment]
@ccoffrin, if the syntax is ``@variable(<model>, <variable name>, <index set generator>, <type>)`` and the variable name is optional, then you have an ambiguity with
```
@variable(m, S)
```
where you don't know if you're declaring an anonymous set of variables indexed over S or a single variable named S.

**Comment by odow** [comment]
This parses alright
```
@variable(m, lower[i] <= x[i,j] <= upper[j] for i in X, j in Y if i <= j)
```

**Comment by ccoffrin** [comment]
@mlubin good point.  Some possible solutions,

- Give the variable name argument a specific type,  for example a string or a symbol. 
- Have a sentinel to go in the variable name for unnamed variables, e.g. `nothing`
- Have a separate macro for anonymous variable creation

**Comment by ccoffrin** [comment]
@odow, regarding the syntax`a <= x <= b`.  

My personal experience has been that this notation is not super standard across optimization communities.  I personally have settled in on `x \in (a,b)` in my papers becouse it seems to be comprehensible by the multiple venues I publish in.

Another reason I would advocate moving away from this notation is the following ambiguity.  Does `a <= x <= b` mean a variable with bounds or does it mean an unbounded variable with two constraints on it?  Mathematically they are the same, but in a solver there can be a distinction.

For the sake of discussion, these were the confusions I had about this syntax when first learning JuMP,
- `@variable(m, 0 <= a <= 1)` is valid
- `@variable(m, 0 >= a >= 1)` is valid
- `@variable(m, a <= 1)` is valid
- `@variable(m, a >= 0)` is valid
- `@variable(m, 0 <= a)` is **invalid**
- `@variable(m, 1 >= a)` is **invalid**
It seems strange that last two are not valid.

**Comment by mlubin** [comment]
``@variable(m, 0 <= a)`` and ``@variable(m, 1 >= a)`` are invalid because once you replace the constants with a symbol they mean something entirely different.

**Comment by ccoffrin** [comment]
I am confused, isn't that true for all of the listed expressions?

**Comment by mlubin** [comment]
``@variable(m, a <= 1)`` and ``@variable(m, a <= b)`` both define a variable ``a`` with the specified upper bound.

**Comment by odow** [comment]
This is quite nice and it parses
```
@variable(m, x[i,j] in (lower[i], upper[j]) for i in X, j in Y if i <= j)
```
and it could be one of
```
@variable(m, x in (0, 1))
@variable(m, x in [0, 1])
@variable(m, x in 0:1)
```

**Comment by mlubin** [comment]
Needs to be developed a bit more but I like the idea of specifying a domain. Perhaps this can unify bounds, variable categories (Bin/Int/SemiCont/...), and cones (https://github.com/JuliaOpt/JuMP.jl/issues/715).

**Comment by ccoffrin** [comment]
Bonus, explicitly defining the variable domain is consistent with how CP solvers want their input.  :-)

**Comment by mlubin** [comment]
And DCP

**Comment by ccoffrin** [comment]
@mlubin, I see, to avoid ambiguity by convention a binary operator `<=, >=` should have a variable on LHS, and in the ternary operator it should be in the middle.

There might be some was to work around this by inspecting the types of the given symbols, but my preference would be to resolve it by moving away from this syntax.  :-)

**Comment by mlubin** [comment]
@ccoffrin, symbols have no types at the time of macro evaluation, so its essentially impossible to do without terrible hacking.

**Comment by odow** [comment]
```
@variable(m, x in Bin)
@variable(m, x in Int(0, 1))

@variable(m, x in Cont(0, 1))
@variable(m, x in (0, 1)) # Same as Cont(0,1)

```

**Comment by mlubin** [comment]
@odow, I'd rather think about intersecting domains instead of modifying the intervals. Something like
```
@variable(m, x in [0,5] ∩ Integer)
```
with an ascii fallback like ``&`` for those who don't like unicode.

**Comment by chkwon** [comment]
Like @odow, I am a big fan of the current syntax. The selling point of JuMP to me was the fact that JuMP models look like mathematical formulations. 

I'm quite pessimistic for general unifying macros/functions that solve all problems at once, satisfying both beginners and advanced programmers. I have always wanted to have GAMS/AMPL-like modeling language within a general programming language. When I looked at Pyomo examples, I felt almost like reading a Java code. Too many things to declare, too many keywords that I need to learn from documentations, etc. But JuMP examples were very straightforward.

With those keyword inputs, many things will probably be clearer. But almost every time, I think, I would need to read the documentation, to check what the keyword name that I wanted was. `lb`, `lowerbound`, `lower`, or what was it? Even for the most simplest example code. Well, maybe that's okay; but anyway I like the current `<=` syntax. Please don't remove. :)

**Comment by mlubin** [comment]
@chkwon, what do you think about the interval/domain syntax above?

I don't think ``x in [l,u]`` is any farther removed from the math than ``l <= x <= u``.

**Comment by chkwon** [comment]
@mlubin Would it be like `x in [0, Inf]` for nonnegative variables? For binary variables, should I do `x in Binary` or `x in [0,1] \cap Binary`? Not pretty, but bearable I guess if it can indeed unify this and that. But as a teacher of LP and Network Optimization, I would not be too happy.

But I don't like unicodes, well more that I don't know how to input. lol...

**Comment by mlubin** [comment]
@chkwon, we could follow CVX/CVXPY/Convex.jl and have ``NonNegative`` as a special case for ``[0, Inf]``, maybe. For binary I'd just say ``x in Binary`` or ``x in {0,1}``.

**Comment by mlubin** [comment]
Another thing we could do is keep ``x <= u`` as a shortcut for ``x in [-Inf,u]`` and ``x >= l`` as a shortcut for ``x in [l,Inf]``. We'd remove ``l <= x <= u`` in favor of ``x in [l,u]``.

**Comment by mlubin** [comment]
But it's unclear how to combine those shortcuts with other domain restrictions like integrality.

**Comment by chriscoey** [comment]
I'm a fan of the intersecting domain syntax idea. Ultimately I think it would lead to less confusion to only allow one syntax and not the `=>`, `<=`. I think it's pretty natural. 

Would this suggestion by @odow parse ok?
`@variable(m, x[i,j] in (lower[i], upper[j]) for i in X, j in Y if i <= j)
`

**Comment by chriscoey** [comment]
I also agree with the shortcuts `NonNegative`, `NonPositive`, `Binary`. What about semicontinuous? Would we want a `0 & [lower,upper]`? Or is there a better shortcut that will parse

**Comment by mlubin** [comment]
I like ``{0} ∩ [lower,upper]``. Sure it's a special case but maybe it won't be for too long.

**Comment by chriscoey** [comment]
can we use `|` instead of `&` in that case

**Comment by chkwon** [comment]
Perhaps `Nonnegative` would be fine. But we'll need to fight with non-smooth English forms of:

`x in Binary`
`x in Nonnegative`

Can it be
`x Binary`
`x Nonnegative`
`x in [0,10] and Integer`

(still sad that `<=` syntax would likely be removed.)

**Comment by odow** [comment]
@chriscoey  You can check if it parses by wrapping it in an Expr i.e. `:(x[i,j] in (lower[i], upper[j]) for i in X, j in Y if i <= j)`

```
@variable(m, x[i,j] in SemiContinuous(l, u) for i in I, j in J if i <= j)
```

**Comment by mlubin** [comment]
@chkwon, I also don't like ``x in Binary``, I'd just say ``x in {0,1}``. 

Your other proposals make sense but just don't parse in Julia.

**Comment by odow** [comment]
```
@variable(m, x::Binary)
@variable(m, x::Integer in [0, 1])
@variable(m, x::SemiContinuous(l, u))
```

**Comment by mlubin** [comment]
@odow, I like where this is going. What would you say for an SDP matrix with integer components?

**Comment by chriscoey** [comment]
pet peeve: can we use PSD instead of SDP in syntax

**Comment by mlubin** [comment]
> can we use PSD instead of SDP in syntax

Yes

**Comment by ccoffrin** [comment]
I like the domain union an intersection idea, and the mathematical foundation should give it a clear semantics for users from many backgrounds.  Combining these with some common predefined sets, for example, Boolean, Integer, Positive, Negative, and so on, probably covers most cases.

I personally like the idea of `{}` for discrete sets and `(a,b)` for bound intervals.  For me, arrays `[]` of length 2 are ambiguous and could be either.

**Comment by chkwon** [comment]
Wouldn't `(a,b)` be confused with an open interval?

**Comment by mlubin** [comment]
``Interval(a,b)``?

**Comment by odow** [comment]
I would say that I know nothing about Conic problems and so could very probably suggest something totally irrelevent/incorrect. However,
```
@variable(m, x::PSDMatrix(N, Integer)) # for a matrix of size N x N
```

**Comment by mlubin** [comment]
@odow, not looking for anything conic specific, I was more looking for a way to intersect the PSD and integer constraints in a way that doesn't require the "PSD type" knowing about Integer.

**Comment by mlubin** [comment]
Bed time for me by the way. This is very promising and I'll pick this up tomorrow.

**Comment by odow** [comment]
```
@variable(m, x::PSDMatrix(N)::Integer in [0, 2])
```

**Comment by chriscoey** [comment]
I feel like `SemiContinuous(l,u)` and `Integer in [l,u]` look too different. Maybe it should be `SemiContinuous in [l,u]`. Or `Integer(l,u)` (but then you need `Continuous(l,u)` or `Interval(l,u)` as well really).

**Comment by ccoffrin** [comment]
I think @odow's case is a case where set intersection reasoning could pay off, something like `@variable(m, x in PSDMatrix(N) & Integer & Interval(0, 2))` is clearer to me than nesting `::`

**Comment by odow** [comment]
I think this has a number of things going for it. It plays nicely of Julia's type system. It gets rid of the tertiary `a <= x <= b` issue but people can keep the binary operators if they don't want to use `[lower, Inf]`. The scoping issue with bounds falls out nicely. The only issue is how to include keyword arguments like `start`

Single variable type
```
@variables(m, begin
    x::Continuous
    x in [l, u]    # simple interval
    x <= u         # one sided bound
    x >= l         # one sided bound
    x::Binary
    x::Integer in [l, u]
    x::Integer >= l
    x::SemiContinuous in [l, u]
    x::SemiInteger in [l, u]
    x::PSDMatrix(N)
    x::Symmetric(N)
    x::NonNegative
    x::NonPositive
end)
```

Nesting variable types `∩` or `&`
```
@variables(m, begin
    x::PSDMatrix(N) ∩ Integer
    x::Integer & NonPositive
end)
```

Generators
```
@variables(m, begin
    x[i,j] >= l for i in I, j in J if i <= j
    x[i,j]::Integer in [l[i], u[j]] for i in I, j in J if i <= j
    x[i,j]::PSDMatrix in [l, u] for i in I, j in J # define your own indices but it must still be square
end)
```

Anonymous Variables
```
x = @variable(m, lowerbound=1) # distinguished by the keyword argument
x = @variable(m, ::Continuous >= 1)
x = @variable(m, [i,j]::Integer in [l[i], u[j]] for i in I, j in J if i <= j)
```

**Comment by mlubin** [comment]
A few comments:

```
x::SemiContinuous in [l, u]
```
doesn't feel right because x is *not* restricted to the interval ``[l,u]``. I'd rather have ``SemiContinuous(l,u)``.

```
x::PSDMatrix(N) ∩ Integer
```
doesn't parse with the right precedence. It should be
```
x::(PSDMatrix(N) ∩ Integer) # or
x::(PSDMatrix(N) & Integer)
```
I like how the latter reads as PSD and Integer.

```
x[i,j]::PSDMatrix in [l, u] for i in I, j in J # define your own indices but it must still be square
```
This seems confusing because ``x[i,j]`` is not restricted to be PSD, the whole matrix is. I'd just disallow generator syntax indexing for matrix variables.

**Comment by joehuchette** [comment]
My thoughts:

* I'm OK with the ``x in [0,3]`` syntax (I prefer square brackets to parens, which I read as open intervals), but I would like to keep ``>=`` and friends for one-sided bounds
* I think using faux type annotations like ``::Integer`` is a little too punny and clever
* Semicontinuous variables read nicely as ``{0} | [3,5]``, and as Miles mentions, this leaves open the option for more generic disjunctions in the future
* I'm not sure about specifying variable types. I don't find ``[0,3] & Integer`` particularly intuitive. What about ``{0,1}`` for binary and something like ``{3,...,10}`` for general integer?

**Comment by mlubin** [comment]
@joehuchette, I'd agree that ``x in [0,3] & Integer`` doesn't read well, but ``x::Integer in [0,3]`` certainly does.

**Comment by joehuchette** [comment]
I disagree. Someone without julia programming experience won't know what the ``::`` operator means. And someone with experience will read it as a type annotation, which it isn't. I still think ``x in [0,3], Integer`` is clearer to both groups.

**Comment by odow** [comment]
The problem I have with variations on `{}` or allowing disjunctions is that what should JuMP do with: `{0, 1, 2}`, `{0, 2}`, `{0, 1, 3}`, `{1} | [2, 3]`. 

If the point of changing the syntax is to make it more intuitive, and JuMP doesn't reformulate these cases, then this goes against that.

I would almost argue that we don't need intersecting types. If there is `SemiContinuous` and `SemiInteger` then there should be `PSDMatrixInteger` and `SymmetricInteger`. `NonNegative` and `NonPositive` become sets:

```
@variable(m, x::SymmetricInteger(N) in NonNegative)
```

As a side note/tangent: what are the downsides of stictly typing variables?
```
abstract JuMP.Variable
immutable Integer <: JuMP.Variable
    m
    idx
end
```

**Comment by joehuchette** [comment]
> The problem I have with variations on {} or allowing disjunctions is that what should JuMP do with: {0, 1, 2}, {0, 2}, {0, 1, 3}, {1} | [2, 3].

The first is valid (if we choose), while the other three are errors. If we want to support more exotic CP-style set constraints later on, the syntax is already there, and we can just remove the errors.

> If the point of changing the syntax is to make it more intuitive, and JuMP doesn't reformulate these cases, then this goes against that.

Why? IMO ``{0} | [2,3]`` is so much more intuitive for the lay user than an obscure piece of jargon like ``SemiContinuous``.

> As a side note/tangent: what are the downsides of stictly typing variables?

There are some potential compiler optimizations that may be impossible (i.e. packing ``Variable``s of different types in-line in vectors), but those are probably negligible. I'm not sure what's to be gained though, besides additional complexity. How would you use dispatch on different variable types?

**Comment by mlubin** [comment]
I think we should aim for a well-defined concept of the domain of a variable (or collection of variables) that can be constructed programmatically, and then find the right syntax for it. We're having trouble deciding how integer/bounds/semicontinuous/PSD restrictions interact because it's been pretty ad-hoc up to this point. Now is the right time to look forward to make the concepts and syntax general enough to allow for future extensions to JuMP that could allow unions of domains and/or CP-style domains.

**Comment by joehuchette** [comment]
I agree, but I think the there are two somewhat orthogonal questions here. One is what types/operations to define so that ``@variable(m, x in D)`` works, where we can build up ``D`` programmatically. The second is whether we want DSL sugar like ``@variable(m, x in {0} ∪ [3,5])`` to make things pretty (for the sets we do currently support, and others in the future). We can add one, both, or neither independently, it seems.

**Comment by mlubin** [comment]
@joehuchette, I think it also affects the question of ``x::Integer``, ``x in Integers`` or ``x, Integer``.

**Comment by joehuchette** [comment]
That's a question of syntax, though. Let's choose what we feel is most natural, as you're not going to be programmatically generating that code. If we want to add support for something like
```jl
D = Integer(0,5)
@variable(m, x in D)
```
later, we can.

**Comment by mlubin** [comment]
@joehuchette, could you sketch up a proposal analogous to https://github.com/JuliaOpt/JuMP.jl/issues/692#issuecomment-251342129?

**Comment by mlubin** [comment]
Well.. we could double down on the ``::`` syntax to address the issue with keyword arguments and generators:
```jl
@variable(m, x[i,j]::Integer(name="x[$i,$j]") in [l[i], u[j]] for i in I, j in J if i <= j)
@variable(m, x[i,j]::Integer(name="x[$i,$j]",lowerbound=l[i],upperbound=u[i]) for i in I, j in J if i <= j)
```

**Comment by yeesian** [comment]
maybe we shouldn't have a single macro to do it all?

**Comment by mlubin** [comment]
Declaring variables shouldn't be that hard, not sure why we would need multiple macros for it.

**Comment by yeesian** [comment]
> Well.. we could double down on the :: syntax to address the issue with keyword arguments and generators

I think it's quickly becoming confusing whether the macro is dealing with a "domain" or a "variable". Following [joey's comment](https://github.com/JuliaOpt/JuMP.jl/issues/692#issuecomment-251571658), I can imagine the possibility of something along the lines of

```julia
@domain(m, D[i,j], variabletype = Integer, lowerbound = l[i], upperbound = u[i]))
@variable(m, x[i,j] in D[i,j] for i in I, j in J if i <= j)
```

That allows existing users of JuMP to not worry about a whole new set of rules.

**Comment by yeesian** [comment]
I'm not opposed to new suggestions/syntax. But echoing https://github.com/JuliaOpt/JuMP.jl/issues/692#issuecomment-251285997, it feels alarming (to existing users to stay in the loop and get their opinions heard) when it's supposed to "unify" everything, when preferences differ across communities.

As a particular example: in `@variable(m, x[i,j]::Integer(name="x[$i,$j]",lowerbound=l[i],upperbound=u[i]) for i in I, j in J if i <= j)`, it is unclear why `name="x[$i,$j]",lowerbound=l[i],upperbound=u[i]` is in `Integer` and not in the `variable` macro scope. A case can be made for one or the other, depending on what you're trying to achieve (whether you want to think of them as an attribute of the domain or the variable). Given that it might take a while to assess the suitability of various proposals for describing different domains, providing a separate macro for it allows for existing users to not have to worry too much about keeping up with ideas for syntax innovations.

> I'm a fan of the intersecting domain syntax idea. Ultimately I think it would lead to less confusion to only allow one syntax and not the =>, <=. I think it's pretty natural.

Does your preference extend to the `constraint[s]` macro too?

**Comment by mlubin** [comment]
My intent is to close this issue if there's no substantial progress made at the meetup next week. At this point, radical syntax changes should be first implemented and tested by multiple people in a separate package before we'd force them onto JuMP users.

**Comment by joehuchette** [comment]
I think set inclusion syntax for variables would go a long way, and would be relatively easy to add.

**Comment by mlubin** [comment]
We can open a separate issue for that, because the scope of this issue is
much broader.
