### ISSUE TITLE
Examples according to various solvers

### ISSUE THREAD

**Issue by ns-1m** [JuliaOpt/JuMP.jl#694]
Hi,

I think it would be better to classify the examples according to solvers it run:

e.g.
./Examples/Glpk
./Examples/Cbc
./Examples/Clp
./Examples/Cplex
.//Examples/Gurobi
./Examples/Mosek

This would encourage people to contribute examples to their favourite solvers if they can see that there are only few or one example.
 
Thanks, Noli

**Comment by mlubin** [comment]
Almost all of the examples are independent of the solver.
