### ISSUE TITLE
examples/tsp.jl is not tested

### ISSUE THREAD

**Issue by diam** [JuliaOpt/JuMP.jl#699]
Bonjour,
Some months ago, I've succesfully tested `tsp.jl` with julia-0.3.1 and cplex or glpk (although the example is provide for gurobi).
I'm now testing the new tsp.jl exemple with the last JuMP version and julia-0.4.0 but get some error.
I saw [#684](https://github.com/JuliaOpt/JuMP.jl/issues/684), but it seems to be fixed!

Are code in the `examples` directory supposed to be maintained with each JuMP versions?

-- Maurice

<pre>
----
Inside subtour callback
Current tour starting at city 1:
[1,2,3,1]Adding subtour elimination cut
----
ERROR: LoadError: MethodError: `isless` has no method matching isless(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Int64)
Closest candidates are:
  isless(!Matched::AbstractFloat, ::Real)
  isless(!Matched::ForwardDiff.ForwardDiffNumber{N,T<:Real,C}, ::Real)
  isless(!Matched::Real, ::Real)
  ...
 in subtour at /..../run_tsp_cplex_distrib_20160310.jl:212
 in lazycallback at /.../pkgs/v0.4/JuMP/src/callbacks.jl:65
...
</pre>

**Comment by mlubin** [comment]
Thanks for catching this, I've fixed the example. I'll leave this issue open until we're running tsp.jl as part of the test suite.
