### ISSUE TITLE
errors inside macros give incorrect line numbers

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#7]
In `dummy.jl`:

``` julia
using MathProg
m = Model("max")
@setObjective(m, z)
```

Then:

```
$ julia dummy.jl 
ERROR: z not defined
 in include_from_node1 at loading.jl:92
 in process_options at client.jl:250
 in _start at client.jl:329
at /home/mlubin/.julia/MathProg/test/dummy.jl:139
```

**Comment by mlubin** [comment]
Unfortunately not fixed after https://github.com/JuliaLang/julia/pull/12544:
After a slight syntax update, ``dummy.jl`` becomes
```
using JuMP
m = Model()
@setObjective(m, Max, z)
```
and I get
```
ERROR: LoadError: UndefVarError: z not defined
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/mlubin/dummy.jl, in expression starting on line 584
```

**Comment by sbebo** [comment]
Ouch, no luck on this yet? It's rather annoying :(

**Comment by mlubin** [comment]
We may have to restructure the macros to take advantage of the recent improvements, but I haven't looked into it.

**Comment by mlubin** [comment]
@ihnorton, I didn't follow all of the nuances of JuliaLang/julia#12544, but what do we have to do in JuMP to get call site line numbers reported correctly?

**Comment by ihnorton** [comment]
You want it to report `UndefVarError on line 3`, correct?
Can I just do `Pkg.add("JuMP")` and run your example?

To clarify, 12544 is about getting correct line numbers when *generated code* throws an error. If I am understanding the situation here, the error is being thrown during macro expansion, so none of the generated code is actually running yet. See the second part of my [comment here](https://github.com/JuliaLang/julia/issues/8701#issuecomment-144099222) about errors during macro expansion (can't throw across the flisp stack). [This PR](https://github.com/JuliaLang/julia/pull/13339) is relevant, although I think I might be able to get you `UndefVarError on line 3` without it (or with a much less intrusive version -- only annotate on the flisp side).

**Comment by mlubin** [comment]
Yes, the example should run with vanilla JuMP.

**Comment by mlubin** [comment]
@ihnorton, the error is at run time, not macro expansion.

**Comment by ihnorton** [comment]
Thanks. With the simplified example, 12544 doesn't apply because the  error is being thrown by the interpreter. https://github.com/JuliaLang/julia/pull/13444 should help there.

I assume you also want to use these macros inside of functions, where 12544 would apply, however, the location will still be off because I haven't [figured out](https://github.com/JuliaLang/julia/issues/1334#issuecomment-127648525) how to track the top-level location properly with nested locations, so right now we just default to the starting line number of the function body.

**Comment by mlubin** [comment]
I definitely get a better back trace when I put the code into a function:
```julia
using JuMP
function foo()
    m = Model()
    @setObjective(m, Max, z)
end
foo()
```
gives
```
ERROR: LoadError: UndefVarError: z not defined
 [inlined code] from /home/mlubin/.julia/v0.4/JuMP/src/macros.jl:602
 in foo at /home/mlubin/dummy.jl:601
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/mlubin/dummy.jl, in expression starting on line 7
```
It's pointing to line 601 from dummy.jl which doesn't exist, it's macros.jl:601.

**Comment by ihnorton** [comment]
With https://github.com/JuliaLang/julia/pull/13431 that should show as `dummy.jl:3`. Clearly that's still off by one -- it's the function start rather than the actual line, as per my comment above -- but at least on a line that actually exists!

**Comment by mlubin** [comment]
@ihnorton, on master I'm now getting:
```
ERROR: LoadError: LoadError: UndefVarError: z not defined
 [inlined code] from /home/mlubin/.julia/v0.5/JuMP/src/macros.jl:584
 in foo at /home/mlubin/dummy.jl:4
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:384
 [inlined code] from ./operators.jl:313
 in process_options at ./client.jl:277
 in _start at ./client.jl:377
while loading /home/mlubin/dummy.jl, in expression starting on line 6
while loading /home/mlubin/dummy.jl, in expression starting on line -1
```

**Comment by mlubin** [comment]
This seems to basically be fixed now? If we find another instance of bad backtraces we can open a new issue.
