### ISSUE TITLE
Scope issue with registerNLFunction?

### ISSUE THREAD

**Issue by adowling2** [JuliaOpt/JuMP.jl#705]
The following code does not work with JuMP 0.12:

```
using JuMP

function mysquare(x)
	return x^2
end

function generateModel!(m)

	registerNLFunction(:square, 1, mysquare, autodiff=true)

	@defVar(m, 0 <= x <= 5)
	@addNLConstraint(m, square(x) >= 1)
	@setObjective(m, Min, x)

	return nothing

end

m = Model()

generateModel!(m)
```

`ERROR: LoadError: Unrecognized function square used in nonlinear expression.`

Interestingly, this works if the model generation is NOT placed in a function. Bug or feature?

**Comment by mlubin** [comment]
I think the issue is that the macros are doing a compile-time lookup into the list of operators, so that fails if the macro code is compiled before the ``registerNLFunction`` call. Shouldn't be too hard to fix this.
