### ISSUE TITLE
Time difference in solve and ipopt

### ISSUE THREAD

**Issue by jelavice** [JuliaOpt/JuMP.jl#712]
I was wondering why there is such a big difference between time spent in ipopt solver and JuMP's solve function.

1st run

Number of Iterations....: 0

                                   (scaled)                 (unscaled)
Objective...............:   0.0000000000000000e+00    0.0000000000000000e+00
Dual infeasibility......:   0.0000000000000000e+00    0.0000000000000000e+00
Constraint violation....:   5.1864787851278553e+00    5.1864787851278553e+00
Complementarity.........:   1.9620000196200003e+00    1.9620000196200003e+00
Overall NLP error.......:   5.1864787851278553e+00    5.1864787851278553e+00

Number of objective function evaluations             = 1
Number of objective gradient evaluations             = 1
Number of equality constraint evaluations            = 1
Number of inequality constraint evaluations          = 1
Number of equality constraint Jacobian evaluations   = 1
Number of inequality constraint Jacobian evaluations = 1
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.305
Total CPU secs in NLP function evaluations           =      0.115

EXIT: Maximum CPU time exceeded.
WARNING: Not solved to optimality, status: UserLimit
 44.383629 seconds (10.17 M allocations: 264.919 MB, 1.08% gc time)

2nd run:
Number of Iterations....: 27

                                   (scaled)                 (unscaled)
Objective...............:   5.8745207204647151e+01    5.8745207204647151e+01
Dual infeasibility......:   1.1541133083885860e+01    1.1541133083885860e+01
Constraint violation....:   1.3752994245829289e+00    1.3752994245829289e+00
Complementarity.........:   6.4713672731222881e-09    6.4713672731222881e-09
Overall NLP error.......:   6.4562560541592955e+00    1.1541133083885860e+01

Number of objective function evaluations             = 37
Number of objective gradient evaluations             = 12
Number of equality constraint evaluations            = 37
Number of inequality constraint evaluations          = 37
Number of equality constraint Jacobian evaluations   = 31
Number of inequality constraint Jacobian evaluations = 31
Number of Lagrangian Hessian evaluations             = 28
Total CPU secs in IPOPT (w/o function evaluations)   =      0.060
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Converged to a point of local infeasibility

. Problem may be infeasible.
WARNING: Not solved to optimality, status: Infeasible
  0.125643 seconds (3.41 k allocations: 71.512 KB)
:Infeasible

I understand that the first time the model is solved JuMP needs to create an internal model and that takes time, hence 44 seconds.

But why is there such a big difference between time spent in the ipopt and overall time spent in "solve" in the succeeding runs? All I am doing is updating nonlinear parameters. Can it be that it takes ~70 ms to update model's parameters?? And why does ipopt run 0 iterations in the first run.

To reproduce: 
1. Run "initModel.jl"
2. Run "setAndRun.jl" more than once.

I'm using:

Julia Version 0.4.4-pre+1
Commit e3ad75f (2016-01-12 22:08 UTC)
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 3 (v7l)
  WORD_SIZE: 32
  BLAS: libopenblas (NO_AFFINITY ARMV7)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.1

Thanks,

Edo

P.S Same behavior occurs also on Windows and intel processor. 
[files.zip](https://github.com/JuliaOpt/JuMP.jl/files/185445/files.zip)

**Comment by mlubin** [comment]
Ipopt runs 0 iterations in the first run because you've set a time limit in the code, as the exit status and printout suggest. On the second run, the reported total time spent within solve is about 2x the time spent internally within ipopt. What were you expecting?

**Comment by jelavice** [comment]
Yes, but in some runs CPU time is exceeded and ipopt still runs more than 0 iterations. That's what confuses me. LIke this one:
Number of Iterations....: 24

                                   (scaled)                 (unscaled)
Objective...............:   2.4915341423787851e+01    2.4915341423787851e+01
Dual infeasibility......:   4.9075247987348671e+00    4.9075247987348671e+00
Constraint violation....:   5.2053139032564140e+00    5.2053139032564140e+00
Complementarity.........:   1.4325453739842081e-01    1.4325453739842081e-01
Overall NLP error.......:   5.2053139032564140e+00    5.2053139032564140e+00


Number of objective function evaluations             = 44
Number of objective gradient evaluations             = 15
Number of equality constraint evaluations            = 44
Number of inequality constraint evaluations          = 44
Number of equality constraint Jacobian evaluations   = 29
Number of inequality constraint Jacobian evaluations = 29
Number of Lagrangian Hessian evaluations             = 24
Total CPU secs in IPOPT (w/o function evaluations)   =      0.070
Total CPU secs in NLP function evaluations           =      0.005

EXIT: Maximum CPU time exceeded.
WARNING: Not solved to optimality, status: UserLimit
  0.117998 seconds (3.10 k allocations: 66.523 KB)
:UserLimit

About the overall time; so 2x more than the time spent within the ipopt internally is normal? I didn't know what to expect, since I'm using JuMP for the first time.

**Comment by mlubin** [comment]
The solver's CPU time limit is based on its internal time, not the time spent inside JuMP. This could be improved if JuMP adopts solver-independent parameters.

2x time is not normal, but 0.05 seconds is not on the scale of overhead that we typically care about. If you profile the JuMP code and identify what's slowing it down, we can help speed it up.

**Comment by tkelman** [comment]
Breadcrumb: we did try profiling here but sadly the profiler doesn't work at all on ARM.

**Comment by mlubin** [comment]
Just insert some ``tic()`` and ``toc()`` calls? Should be that hard to bisect the code and find the bottleneck.

**Comment by tkelman** [comment]
It takes about 5-10 minutes to precompile JuMP, and those tic/tocs will need to be inside JuMP since the time is all in `solve`.

**Comment by mlubin** [comment]
That's at least better than printf debugging on a supercomputer to find a crash which only occurred when running on 1024 nodes after a few hours, plus queueing time :)

**Comment by mlubin** [comment]
Closing this. If you can point us to a specific part of the JuMP code that's slower than it should be, please open a new issue
