### ISSUE TITLE
Fail constructing a Model from an existing CplexSolver object

### ISSUE THREAD

**Issue by diam** [JuliaOpt/JuMP.jl#716]
Bonjour,

This example works (e.g. from bnatt350.jl JuMP distrib)

<pre>
using JuMP
using CPLEX
function build_model()
  m = Model(solver=CplexSolver(
    CPX_PARAM_PRELINEAR=0,
    CPX_PARAM_PREIND=0,
    CPX_PARAM_ADVIND=0,
    CPX_PARAM_MIPSEARCH=1,
    CPX_PARAM_MIPCBREDLP=0
  ))
  return m
end
m = build_model()
</pre>

But that example fails:
<pre>
using JuMP
using CPLEX
function build_model()
  solver=CplexSolver(
    CPX_PARAM_PRELINEAR=0,
    CPX_PARAM_PREIND=0,
    CPX_PARAM_ADVIND=0,
    CPX_PARAM_MIPSEARCH=1,
    CPX_PARAM_MIPCBREDLP=0
  )
  m = Model(solver)
  return m
end
m = build_model()
</pre>

with the following erreur:
<pre>
ERROR: MethodError: `convert` has no method matching 
convert(::Type{JuMP.Model}, ::CPLEX.CplexSolver)
This may have arisen from a call to the constructor JuMP.Model(...),
since type constructors fall back to convert methods.
Closest candidates are:
  JuMP.Model(::Any, ::Symbol, ::Any, ::Any, ::Any, ::Any, ::Any, ::Int64, 
::Array{UTF8String,1}, ::Array{UTF8String,1}, ::Array{Float64,1}, 
::Array{Float64,1}, ::Array{Symbol,1}, ::Array{T,1}, ::Array{Tuple{Symbol,Any},1}, 
::Any, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, 
::Array{Float64,1}, ::Array{Array{Int64,1},1}, ::Any, 
::MathProgBase.SolverInterface.AbstractMathProgSolver, ::Bool, 
::Any, ::Any, ::Any, ::Array{T,1}, ::JuMP.IndexedVector{Float64}, ::Any, ::Bool, 
::Dict{Symbol,Any}, ::ObjectIdDict, ::Int64, ::Int64, ::Dict{Symbol,Any})
  JuMP.Model(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, 
::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any,
::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, 
::Any, ::Any)
  call{T}(::Type{T}, ::Any)
  ...

</pre>

**Comment by mlubin** [comment]
The proper syntax is ``m = Model(solver=solver)``

**Comment by diam** [comment]
Oh yes, thank you very much.
I thought it was an affectation to a local variable.
Sorry for having missing that: I should have reread the doc!
-- Maurice
