### ISSUE TITLE
precision of constraint that contains float-type coefficient 

### ISSUE THREAD

**Issue by chenzjames** [JuliaOpt/JuMP.jl#717]
Hi,
I encounter this kind of problem when I have to solve a model iteratively in a certain "column-generation-like" way.

The problem is that the precision of JuMP is "too precise" with Float64 so that a feasible solution turns out to be infeasible (in constraint I have log and exp function, but just for coefficient, not over decision variables)

`println(t_f[5,9] <= vecdot(cost_mtr_log[:,5], alpha_f[:,69]))`
`false`
`println(convert(Float32, t_f[5,9]) <= convert(Float32,vecdot(cost_mtr_log[:,5], alpha_f[:,69])))`
`true`

I hope to force that constraint in JuMP just need to be satisfied in a bit rough precision, by trying following:
`@addConstraint(m, convert(Float32, t_f[5,9]) <= convert(Float32,vecdot(cost_mtr_log[:,5], alpha_mtr[:,69])))`
but fail
`convert has no method matching convert(::Type{Float32}, ::JuMP.Variable)`

Any idea that I could overcome this kind of problem? Sincerely appreciate.

**Comment by IainNZ** [comment]
Tolerances for constraints are not determined by JuMP - they are determined by the solver you are using. Which solver are you using for this problem?

**Comment by chenzjames** [comment]
Thanks. I am using both Gurobi and Mosek.  I am checking if changing solver parameters works.

**Comment by IainNZ** [comment]
Great, they should both have options for changing the constraint satisfaction tolerances.
