### ISSUE TITLE
Better error messages for macros

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#72]
So
```
@addConstraint(x <= 5)
```
is an error because there is no model (even though we could determine it, thats a different issue...)
But, due to Julia's poor line number error printing stuff, if this is in the middle of a largish function it won't tell you where, and won't even tell you what you've done wrong apart from an error about the wrong numbre of arguments.

Suggestion: make @addConstraint(x<=5) a valid macro that just throws an error saying to do it the "right" way.

**Comment by mlubin** [comment]
Upstream issue is resolved:
```
julia> @addNLConstraint(x <= 5)
ERROR: MethodError: `@addNLConstraint` has no method matching @addNLConstraint(::Expr)
Closest candidates are:
  @addNLConstraint(::ANY, ::ANY, ::Any...)
```

Not super user friendly but at least gives the name of the macro and a backtrace.
