### ISSUE TITLE
TSP Example - time windows constraints

### ISSUE THREAD

**Issue by joaopiopedreira** [JuliaOpt/JuMP.jl#721]
Hi, Just arriving here with little to none experience in Julia.

I'd like to know how hard it would be to implement TSP with time windows, vehicle capacity and cost constraints using JuMP.

Cheers, Joao

**Comment by mlubin** [comment]
Hi João. It would be about the same level of effort as using one of Gurobi's or CPLEX's high-level modeling APIs, for example. Please direct "how do I do this?" questions to the [julia-opt](https://groups.google.com/forum/#!forum/julia-opt) list.
