### ISSUE TITLE
NonlinearExpression in LinearQuadratic models

### ISSUE THREAD

**Issue by chkwon** [JuliaOpt/JuMP.jl#724]
Trying to write a JuMP extension involving projection-based algorithms. I was wondering if a LinearQuadratic model can have some `NonlinearExpression` defined in the model, but not used. For example:

```julia
y=[1;1;1]
m = Model(solver=GurobiSolver())
@defVar(m, x[1:3])
@addConstraint(m, sum{ x[i]^2, i=1:3} <= 1 )
@setObjective(m, Min, sum{ (x[i]-y[i])^2 , i=1:3} )

@defNLExpr(m, nle, x[1]^3 + exp(x[2]) + x[3]^2)
solve(m)
```

Without `nle`, it is solved well. However, after defining `nle`, but not using it in the model, it produces an error:
```
ERROR: MethodError: `NonlinearModel` has no method matching NonlinearModel(::Gurobi.GurobiSolver)
 in _buildInternalModel_nlp at /Users/chkwon/.julia/v0.4/JuMP/src/nlp.jl:1190
 in buildInternalModel at /Users/chkwon/.julia/v0.4/JuMP/src/solvers.jl:307
 in solve at /Users/chkwon/.julia/v0.4/JuMP/src/solvers.jl:131
```

The purpose of defining `nle` is to evaluate the value of the operator and use it in the projection procedure, by changing the value of `y` and solving the projection problem again, etc. Something like:

```julia
setValue(x, some_value)
y = getValue(x) - getValue(nle)
@setObjective(m, Min, sum{ (x[i]-y[i])^2 , i=1:3} )
solve(m)
```

Any good way to work around? Should I use two JuMP models?

**Comment by mlubin** [comment]
Why not just write the one line of pure julia code to compute the value instead of going through all of the machinery of JuMP?
```
nle(x) = x[1]^3 + exp(x[2]) + x[3]^2
...
y = getValue(x) - nle(getValue(x))
```

**Comment by chkwon** [comment]
If a user introduces the following JuMP variables:
```julia
@defVar(m, x[1:3])
@defVar(m, y[1:10])
@defVar(m, z[1:100])
```
and supplies a pure julia function
```julia
nle(z1, y1, x1) = # some nonlinear julia function
```
then the user needs to specify which JuMP variable corresponds to which julia variable. Well, I can do that, but was wondering if there were any better way of doing this. Perhaps I should change the design.

**Comment by mlubin** [comment]
Ok, I understand the issue. The right fix would be for JuMP to be able to call out to LP and QP solvers when it detects that an NLP problem is actually LP or QP. I don't want to add a special case for when there are nonlinear expressions but none of them are used. Couldn't you also use Ipopt instead of Gurobi to solve the QPs?

**Comment by chkwon** [comment]
Well, I first tried Ipopt, and it worked well, so wanted to try LP/QP solvers. Thanks for your attention and opinions. Perhaps it's best to stick with Ipopt at this moment. :)

**Comment by chkwon** [comment]
https://github.com/chkwon/JuVI.jl

This is what I am writing, in case you are curious :)  It's an extension of JuMP.
