### ISSUE TITLE
uninformative error message when not passing an expr into a constraint

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#728]
so i hadn't used SDP constraint before and typed `@addSDPConstraint(mod, A)` and got an error:
> ERROR: LoadError: type Symbol has no field head
>  in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in process_options at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in _start at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
> while loading blah blah

which didn't help so of course I called Miles and he said you're dumb, use `@addSDPConstraint(mod, A >= 0)`, at which point I followed his advice and things worked i.e. different errors got thrown instead yay

**Comment by mlubin** [comment]
This actually happens for ``@addConstraint`` and ``@addNLConstraint`` also.
