### ISSUE TITLE
Indexing 0-based JuMPArray: end keyword throws errors

### ISSUE THREAD

**Issue by dourouc05** [JuliaOpt/JuMP.jl#730]
When I ran code on an updated JuMP (0.12), indexing arrays of variables at [end] stopped working (while this code perfectly worked in JuMP 0.11). Here is a 

```
using JuMP

m = Model()
@defVar(m, x[0:2], Bin)
@setObjective(m, Max, x[1])
solve(m)

getValue(x[end])
getValue(x)[end]
```

The errors I get (for both examples) are: 

```
ERROR: Failed attempt to index JuMPArray along dimension 1: 3 ∉ 0:2
 in error at error.jl:21
```

(By the way, is it normal this error does not show where it was triggered from my code?)

**Comment by joehuchette** [comment]
Sorry for the slow reply. Unfortunately I don't think there's much we can do here: the compiler rewrites ``x[end]`` to something like ``x[size(x,1)]``. Are you sure this worked on v0.11?

What do you mean by "this error does not show"? This might be a bug, either on our end or with julia, depending on the behavior.

**Comment by mlubin** [comment]
@joehuchette, I think it uses the ``endof`` method, may we shouldn't [define](https://github.com/JuliaOpt/JuMP.jl/blob/4bbca12b8ba771bb2fc6574791234341992124c8/src/JuMPContainer.jl#L130) it?

**Comment by mlubin** [comment]
The current behavior is dangerous:
```
julia> @variable(m, x[2:4]);

julia> x[end]
x[3]
```

**Comment by joehuchette** [comment]
I'm fine with that

**Comment by mlubin** [comment]
I wonder if we can return a special object from ``endof`` analogous to ``Colon()``

**Comment by mlubin** [comment]
No, that doesn't work because that would break ``end-1``

**Comment by dourouc05** [comment]
@joehuchette: to be precise, I tried a larger piece of code that used to work with JuMP 0.11, and it was broken when I retried with JuMP 0.12.

**Comment by mlubin** [comment]
``end`` on multidimensional arrays uses ``size()``, so it's impossible for us to fix this

**Comment by mlubin** [comment]
Maybe the solution is to define ``size`` as an error and implement ``JuMP.size`` if you actually want to access the dimensions?
