### ISSUE TITLE
LinearConstraint is weird

### ISSUE THREAD

**Issue by colinfang** [JuliaOpt/JuMP.jl#731]
```{julia}
string(LinearConstraint(x + 2, -Inf, 10).terms)
"x + 2"
string(LinearConstraint(x + 2, -Inf, 10))
"x <= 10"
```

It seems the actual constraint added to the model is "x <= 10". Can we add a warning here, and make `LinearConstraint(x + 2, -Inf, 10).terms` become `x`?

#470 is related.

**Comment by IainNZ** [comment]
This isn't a documented public API though, its an internal method.

**Comment by mlubin** [comment]
``@LinearConstraint`` should give the expected answer.
