### ISSUE TITLE
MOSEK warning

### ISSUE THREAD

**Issue by dvij** [JuliaOpt/JuMP.jl#737]
Hi,
I am solving a problem where I get the following MOSEK warning:
MOSEK warning 705: 1 near zero elements are specified in sparse row ''(19) of matrix 'A'.
I checked on the problem and the warning is not relevant to me (it doesn't affect the accuracy/quality of the solution), so I would like to suppress it.

I call solve with suppress_warnings=true, but that doesn't seem to suppress it. Any ideas on how to fix this?

**Comment by mlubin** [comment]
This warning is printed by Mosek, not JuMP, so you should look into Mosek's options for output levels.

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/Mosek.jl/issues/74

**Comment by erling-d-andersen** [comment]
Here is the parameter you can use

  http://docs.mosek.com/7.1/capi/MSK_IPAR_MAX_NUM_WARNINGS.html
