### ISSUE TITLE
Suggestions for naming JuMP extension packages?

### ISSUE THREAD

**Issue by chkwon** [JuliaOpt/JuMP.jl#739]
There are MultiJuMP, and JuMPeR that extend JuMP. Would there any suggested ways of naming such extension packages?

I am writing a package for solving variational inequality (VI) problems and named it as [JuVI](https://github.com/chkwon/JuVI.jl) --- Julia for Variational Inequality. Well, VI is a kind of sub-class of Math Program. Would it be a good name for the package though?

I am also writing a wrapper package for the PATH Solver that solves mixed complementarity problems, and it would be called [PATHSolver.jl](https://github.com/chkwon/PATHSolver.jl). I am also writing a package that uses JuMP modeling language for complementarity problems that calls PATHSolver.jl. What would be a good name for it? JuMCP? Julia for Mixed Complementarity Problems? 

I guess we wouldn't need a special naming rule for extensions, but just seeking suggestions.

**Comment by chkwon** [comment]
I also found JuMPChance.jl and StructJuMP.jl.

JuMPVariationalInequality? JuMPVI? 
JuMPComplementarity? JuMPMCP? 

Well... help.

**Comment by diam** [comment]
Perhaps one should keep JuMP as prefix (or suffix) in the name ?

Then searching all Julia package of the form "JuMP-*" would give a good idea how important JuMP is for the Julia community!

-- Maurice


Le 26 avr. 2016 � 16:06, Changhyun Kwon <notifications@github.com> a �crit :

**Comment by mlubin** [comment]
I think there's a distinction between packages which literally extend JuMP's syntax and packages which define new syntax and mostly use JuMP under the hood (e.g., https://github.com/leclere/StochDynamicProgramming.jl CC @leclere). The former have more of a claim to pun on the JuMP name in the name of the package. I'd just say to choose the name that you prefer, it's your package.

It's worth noting that the julia package naming guidelines discourage including "julia" in the name of the package. The "Ju" prefix might trigger some objections more so than "JuMP", but that said I'm guilty of using the "Ju" prefix myself: https://github.com/mlubin/JuGP.jl

**Comment by chkwon** [comment]
@diam that's what I thought. Probably we need a list of things we can do with JuMP and other extensions. 

@mlubin good point. My packages do not really extend the functionality of JuMP for its original purpose: for solving an optimization problem. Just using the parser and modeling language of JuMP. Alright I'll go ahead with some good names.
