### ISSUE TITLE
signal (11): Segmentation fault error

### ISSUE THREAD

**Issue by novatena2015** [JuliaOpt/JuMP.jl#747]
I got this error:

```
signal (11): Segmentation fault
jl_module_parent at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
Segmentation fault (core dumped)
```

when running the code (below) with large value of N, e.g.  N = 1000. 

I am not sure if the problem lies in the code or JuMP or Julia. Here is some infos:

```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.8
```
```
 - Convex                        0.2.0
 - Gurobi                        0.2.1
 - JuMP                          0.12.2
 - Mosek                         0.3.0
 - PyPlot                        2.1.1
```

Here is my simulation code. It runs with small N, e.g. 10 but fails with large N.
```
using JuMP
using Mosek
using PyPlot

function opt_sum_rate(h2,sigma2,pmax)
    K = length(h2)
    m = Model(solver=MosekSolver(MSK_IPAR_LOG=0))
    @defVar(m, p[1:K] >= 0)
    @setNLObjective(m, Max, sum{log2(1 + p[i]*h2[i]/sigma2), i=1:K})
    @addConstraint(m, sum{p[i], i=1:K} <= pmax)
    solve(m)
    return getObjectiveValue(m)
end

function run_and_plot(N)
    K = 16
    snr_dbs = 0:10
    pmax = 1.0
    sumrate = zeros(length(snr_dbs))
    for (i, snr_db) in enumerate(snr_dbs)
        sigma2 = 10^(-snr_db/10)
        for n = 1:N
            h2 = 1/2*abs(randn(K) + im*randn(K)).^2
            sumrate[i] += opt_sum_rate(h2, sigma2, pmax)/N
        end
    end
    plot(snr_dbs, sumrate)
end

run_and_plot(1000)
```

**Comment by joehuchette** [comment]
Does this occur if you don't include the plotting? If not, that would seem to indicate the segfault is coming from PyPlot.

**Comment by novatena2015** [comment]
I have checked, it still crashes without the plotting.

**Comment by joehuchette** [comment]
I can reproduce this. The segfault isn't deterministic (since there is random data in the problem, AFAICT), but it seems to happen pretty reliably. I've isolated the failure point to [this call to ``getobjval``](https://github.com/JuliaOpt/JuMP.jl/blob/10769fb01462d77a46ed0549ac4e92c0a422ecff/src/nlp.jl#L1235). Thoughts @mlubin?

**Comment by mlubin** [comment]
Does the segfault also occur with Ipopt?

**Comment by novatena2015** [comment]
It seems that the segfault does not occur with Ipopt. 

With Mosek, the problem still happens with deterministic numbers. For example, follow code finds maximum sum log2(1 + p_i) with sum p_i <= 1.0 and p_i >= 0.0. Just run with N large enough then the segfault occurs. 

Maybe this is a bug in mosek?

```
using JuMP
using Mosek

function mytest()
    m = Model(solver=MosekSolver())
    @defVar(m, p[1:4] >= 0.0)
    @setNLObjective(m, Max, sum{log2(1 + p[i]), i=1:4})
    @addConstraint(m, sum{p[i],i=1:4} <= 1.0)
    solve(m)
    return getObjectiveValue(m)
end

function runloop(N)
    for i = 1:N
        mytest()
    end
end
```

**Comment by joehuchette** [comment]
Thanks for the deterministic repro. Yes, this is almost certainly either a bug in Mosek.jl, or in Mosek proper.

**Comment by mlubin** [comment]
There's usually not much of a reason to prefer Mosek over Ipopt as a derivative-based NLP solver.

**Comment by novatena2015** [comment]
I am not sure. But mosek runs much faster than Ipopt, at least 4 times in my machine for the same problem.

**Comment by mlubin** [comment]
If you're comparing the performance of Ipopt, you should compile it with good linear algebra libraries like HSL etc. (http://www.hsl.rl.ac.uk/ipopt/). The open-source redistributable version of Ipopt which we are allowed to package in Julia is not particularly fast.
