### ISSUE TITLE
function registerNLFunction does not accept keyword arguments

### ISSUE THREAD

**Issue by ufechner7** [JuliaOpt/JuMP.jl#753]
The new version of JuMP breaks my current code.

Codesnippet:
```
using JuMP
using Ipopt

include("Model.jl")

EnableNLPResolve()
registerNLFunction(:force1, 2, force1, autodiff=true)
```
This worked fine in JuMP 0.12.2 but gives the following error with 0.13:
ERROR: LoadError: LoadError: ArgumentError: function registerNLFunction does not accept keyword arguments

Any idea?

**Comment by mlubin** [comment]
Thanks for reporting, should be fixed now. We'll tag a patch release shortly.
