### ISSUE TITLE
JuMP not working in Julia Notebook 0.4.5

### ISSUE THREAD

**Issue by Andresj89** [JuliaOpt/JuMP.jl#756]
Hi guys,

I hope you can give me some suggestions to fix this:
![jump error](https://cloud.githubusercontent.com/assets/13351764/15012933/4b8e0100-11f4-11e6-8eb7-270c1c2e87fe.jpg)

I tried the exact steps in Julia 0.3.12 and it worked just fine.

Many thanks,

**Comment by mlubin** [comment]
Jupyter has gotten a bit more fragile after package precompilation, not really related to JuMP. Just don't try installing packages and using them in the same notebook. Restart the the kernel when you run into these precompilation issues.

**Comment by mlubin** [comment]
If the issue hasn't been resolved, you should look to the julia-users google group for help.
