### ISSUE TITLE
Ability to use existing COIN-OR binaries

### ISSUE THREAD

**Issue by MikeRand** [JuliaOpt/JuMP.jl#759]
I'm using a set of COIN-OR binaries compiled from source using COIN-OR's new OptimizationSuite project. I'd like to use these pre-compiled binaries and libraries with JuMP instead of having Julia new copies during the installation process.

**Comment by mlubin** [comment]
You're more than welcome to do so. It's probably sufficient to update ``LD_LIBRARY_PATH`` or ``DYLD_LIBRARY_PATH`` to point to the location of the shared libraries you compiled, and then re-run ``Pkg.build("xxx")`` where ``xxx`` is the name of the corresponding Julia wrapper package. If that doesn't work, ask a question on julia-opt. JuMP itself has nothing to do with COIN-OR binaries; you should look at the corresponding Julia wrapper packages which provide the COIN-OR solvers.
