### ISSUE TITLE
symmetry detection for SDPs is fragile

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#766]
Reported by @chriscoey:
```
q = 2
m = 3
angles1 = linspace(3*pi/4, pi, m)
angles2 = linspace(0, -pi/2, m)
V = [3.*cos(angles1)' 1.5.*cos(angles2)';
     3.*sin(angles1)' 1.5.*sin(angles2)']
p = 2*m
n = 100

####
mod = Model()
@variable(mod, x[j=1:p] >= 0, Int)
@variable(mod, u[i=1:q] >= 0)
@objective(mod, Min, sum(u))
@constraint(mod, sum(x) <= n)
for i=1:q
    @SDconstraint(mod, [V*diagm(x./n)*V' eye(q)[:,i] ; eye(q)[i,:] u[i]] >= 0)
end
f, A, b, var_cones, con_cones = JuMP.conicdata(mod)
@show con_cones[3]
@show full(A)[8:10,:]
@show b[8:10]
```

Shows that we're generating symmetry constraints which are basically exactly zero rows.

**Comment by joehuchette** [comment]
This is arguably the job of the solver (or MBP-level presolver) to handle, not JuMP.

**Comment by mlubin** [comment]
Eh, if there's an easy way for us to avoid generating junk then we shouldn't generate junk.

**Comment by chriscoey** [comment]
Agreed with Miles. Having to deal with this makes Pajarito more complicated.

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/771 and approved by @chriscoey
