### ISSUE TITLE
Support for complex numbers

### ISSUE THREAD

**Issue by jonashelsen** [JuliaOpt/JuMP.jl#767]
I was wondering if JuMP will ever have support for Hermitian (complex valued) matrices in the style of e.g Yalmip for Matlab. It would make the quantum information community very happy I think :D

**Comment by mlubin** [comment]
Not anytime soon, but you should take a look at the GSoC project to implement this in Convex.jl: https://groups.google.com/forum/#!topic/julia-opt/-K4iFK5ohOw
