### ISSUE TITLE
Lazy constraint callback never called with only continuous variables

### ISSUE THREAD

**Issue by leethargo** [JuliaOpt/JuMP.jl#779]
I used JuMP with Gurobi and added a lazy constraint callback to an LP model. This was never called however. I compared it with the `simplelazy` example which features integer variables. With the addition of a `dummy` integer variable, the callback was then called as expected.

Minimal example (uncomment the line for `dummy` variable):

    using JuMP
    using Gurobi

    m = Model(solver=GurobiSolver())
    @variable(m, x >= 0)
    # @variable(m, dummy, Int)
    @objective(m, :Min, x)

    function mylazycons(cb)
        println("I'm called and break everything!")
        @lazyconstraint(cb, x <= -1)
    end
    addlazycallback(m, mylazycons, fractional=true)

    solve(m)

Note that this happens independently of the value of `fractional`. I'm not sure whether this is a bug or intentional. Also, I'm not sure whether the issue relates to JuMP, MathProgBase or Gurobi. Probably related to #154.

My motivation for this setup is the separation of linear inequalities for convex nonlinear constraints (only known to the callback).

CC @fserra

**Comment by mlubin** [comment]
This is intentional since Gurobi doesn't call the callbacks when there are no integer variables. You should write your algorithm in a loop instead. On the JuMP side I guess we should be printing a warning.

**Comment by leethargo** [comment]
OK, thanks for the clarification. I want also want my code to work in a branch-and-cut setting, so I'll keep using the `dummy` variable workaround.

**Comment by IainNZ** [comment]
This is maybe a documentation issue too, although the docs clearly only refer to MIPs. Maybe it needs to be in bigger redder text.

**Comment by fserra** [comment]
well, lp is a subset of mip

**Comment by mlubin** [comment]
Not much we can do on the modeling side besides print a warning. If someone writes an LP solver that uses callbacks for separation then we can revisit the topic.

**Comment by IainNZ** [comment]
Thanks for the math lesson @fserra, I didn't realize that until you pointed that out to me.

@mlubin I've seem the ORC students hit this as well, so warning would seem to be the ideal solution.

**Comment by mlubin** [comment]
Solvers should warn when callbacks are provided but will be ignored (e.g., https://github.com/JuliaOpt/Gurobi.jl/pull/55). Closing this issue here.
