### ISSUE TITLE
SOC and SDP constraint - conflict

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/JuMP.jl#780]
A simplified version of the problem: 
Defined 4 variables, say x1,x2,x3,x4, (continuous and non-neg)

SOC constraints: x3>= x1^2,    x4>= x2^2
SDP constraint:  [x1, 0; 0, x2] >= 0

Issue: Model with either SOC or SDP constraints run well on Mosek/SCS/Convex.jl. However, when I have both constraints, I get this error from solvers.jl of JuMP (line 658):
"ERROR: LoadError: Quadratic constraint -x1² + x3 ≥ 0 must be in second-order cone form"

Is there a different way to pose this problem or is it any conflict in solvers.jl? 

Thanks!!!
@mlubin

**Comment by mlubin** [comment]
``x3>= x1^2`` is a quadratic constraint, not an SOC constraint. There's no solver that supports mixing quadratic and SDP constraints. If you're using Mosek the easiest thing to do is to use a rotated SOC constraint like ``x3*t >= x1^1`` and set ``t==1``. If you're using SCS you have to put it into explicit SOC form.

**Comment by harshangrjn** [comment]
I had tried putting a constant co-efficient next to x^3, but making it a variable worked. Thanks @mlubin !!
