### ISSUE TITLE
docs are a bit confusing on name vs basename

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#781]
[here](http://jump.readthedocs.io/en/latest/refvariable.html?highlight=name)

There is a basename keyword to change printing name, and there is a name keyword when adding a single variable, and there is a setname for after variable is created. Is there a setbasename?

**Comment by mlubin** [comment]
@chriscoey can we close this given the documentation at http://www.juliaopt.org/JuMP.jl/latest/names.html?
