### ISSUE TITLE
looks like a scope issue with `@variable`

### ISSUE THREAD

**Issue by xqrongm** [JuliaOpt/JuMP.jl#785]
I apologize if this is a duplicated issue. Suggestions on how to improve my code is also welcome. Thanks!

![image](https://cloud.githubusercontent.com/assets/12205732/15982971/62537c64-2f66-11e6-9358-18a058f0aae2.png)

![image](https://cloud.githubusercontent.com/assets/12205732/15983000/a5ca45ee-2f67-11e6-8603-c0d4bfbb1423.png)

However, it seems to work just fine in the global scope.

![image](https://cloud.githubusercontent.com/assets/12205732/15982976/a8f85496-2f66-11e6-98e3-fec07b00e109.png)

![image](https://cloud.githubusercontent.com/assets/12205732/15982986/22220146-2f67-11e6-8fea-b354362460d4.png)

**Comment by mlubin** [comment]
``eval`` always works at a global scope, this is unrelated to JuMP. Why not just use plain code to create a variable indexed by a set of symbols?
