### ISSUE TITLE
Error with LazyList when using AmplNLSolver

### ISSUE THREAD

**Issue by mathtd** [JuliaOpt/JuMP.jl#788]
I'm using Knitro through AMPL:

`model = Model(solver=AmplNLSolver("/Applications/ampl/knitro"))
`

The error comes from the following (simplified) constraint 

`@NLconstraint(model, constraint[j=1:n], a <= (sum{A[i]^a , i=find(Ω[:,j].==1)})
`

I get the error:

`ERROR: LoadError: MethodError: `^` has no method matching ^(::Lazy.LazyList, ::Float64)`

This does not happen when instead of using AMPL I use IPopt directly through IpoptSolver().

**Comment by mlubin** [comment]
Closing in favor of https://github.com/JuliaOpt/AmplNLWriter.jl/issues/39. Please don't double post issues without linking them.
