### ISSUE TITLE
testing whether a JuMP expression == 0 

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#789]
I am iterating over JuMP `AffExpr`s and do not wish to add empty (`0 == 0`) constraints to a MIP model. 

Can we have simple way to test whether an expression is just 0? i.e. for affine, the constant and all coefficients on variables are 0. It would be nice to be able to write `if AffExpr == 0` blah blah.

**Comment by mlubin** [comment]
Whoever needs it is welcome to contribute a smarter definition of [equality](https://github.com/JuliaOpt/JuMP.jl/blob/master/src/operators.jl#L246) of ``AffExpr`` objects to handle duplicates and promotion.

**Comment by chriscoey** [comment]
@blegat is this what your PolyJuMP fix does at https://github.com/JuliaOpt/PolyJuMP.jl/pull/11/files#diff-ce657b38c7ecda6fbbcdcc558bf57b86?

**Comment by blegat** [comment]
Yes, this what is done in the PolyJuMP tests. Since JuMP is dropping v0.5, we can define this as Base.iszero in JuMP.

**Comment by chriscoey** [comment]
Great. Now that 0.5 support is dropped (#171) could you move this code to JuMP?

**Comment by mlubin** [comment]
Wrong package, still need a PR to drop 0.5 from JuMP.

**Comment by chriscoey** [comment]
Woops. Karma for using github mobile during a lunch date.

@mlubin can you drop 0.5 for jump too?

**Comment by mlubin** [comment]
`iszero` is implemented and tested (https://github.com/JuliaOpt/JuMP.jl/blob/e392cc873fecea188d6d8d52c891924900eabd13/test/operator.jl#L68). There's could be some debate about the definition and whether it should check for zero coefficients, but that could be a new issue.
