### ISSUE TITLE
Copying extension dictionaries

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#790]
Currently `copy(m::Model)` errors if there is an extension dictionary (https://github.com/JuliaOpt/JuMP.jl/blob/master/src/JuMP.jl#L276).

What are the cons of an approach like
```
dest.ext = try
    deepcopy(source.ext)
catch
    error("Error copying extension dictionary. Is copy defined for all user types?")
end
```

**Comment by mlubin** [comment]
So deepcopy of a dict fails if copy isn't defined? Seems reasonable to me.
