### ISSUE TITLE
writeMPS doesn't output Lower bounds by default

### ISSUE THREAD

**Issue by samiit** [JuliaOpt/JuMP.jl#792]
I know _.mps_ is not used so much, but I tried to create one, for my problem using the `writeMPS()` function. Solvers like CBC, Gurobi (on NEOS server) did not accept the _.mps_ generated by JuMP.

I then checked with the .mps I had generated using python PuLP and found that PuLP writes the lower bounds by default.

I modified the `writeMPS` function to also write the lower bounds by default, and then it worked fine.

Sam

**Comment by mlubin** [comment]
Have you looked at https://github.com/odow/NEOS.jl?

**Comment by odow** [comment]
@samiit what did you modify exactly?

I haven't touched the NEOS package in a while so it will probably need some work!

**Comment by samiit** [comment]
I inserted the condition that the function `writeMPS()` should write the lower bounds always:
`: 
       if m.colLower[col] == 0
            # Always write lower bound
            @printf(f, "  LO BOUND VAR%d ",col)
            print_shortest(f,m.colLower[col])
            println(f)
            if m.colUpper[col] != Inf
:`

**Comment by mlubin** [comment]
As another data point, try having the solvers write the MPS files themselves using ``MathProgBase.writeproblem``. If you can document that all the solvers write the lower bounds, then I'll be willing to make this change in JuMP. Unfortunately MPS is not really a standardized format at all.

**Comment by odow** [comment]
Cbc 2.9.2 does not write the lower bound if it is zero.

Submitting the MPS file (with no lower bound stated) for the problem `max x | 0 <= x <= 1` to Cbc on NEOS doesn't yield any errors.

@samiit perhaps you could post the offending MPS file somewhere? Does it work for other solvers on NEOS? What about via the gurobi command line?

**Comment by samiit** [comment]
Sure, here are the two files:

_Infeasible (due to unbounded)_
[JuMP_InfeasibleSoln.mps.txt](https://github.com/JuliaOpt/JuMP.jl/files/327068/JuMP_InfeasibleSoln.mps.txt)
Gurobi result on NEOS: 
   Job#     : 4728112
   Password : cSFuVwtm

-------------
The same problem with lower bounds (after editing the writeMPS file):
_Feasible solution:_
[JuMP_feasible.mps.txt](https://github.com/JuliaOpt/JuMP.jl/files/327066/JuMP_feasible.mps.txt)

**Comment by samiit** [comment]
Before I close, just a question; I'm new to Julia so please bear with me.

Which file does Julia give to CBC when this solver is invoked within JuMP? .mps or something else?

Sam

**Comment by joehuchette** [comment]
Julia communicates with Cbc (and most other solvers we support) in-memory through their C API, so there aren't files being written, .mps or otherwise.

**Comment by samiit** [comment]
In that case, can you direct me to the code with the default command line
options, in case I want to run my own .mps file.

I found for in my case that running CBC solver via JuMP gives me a lower
objective than by running the same .mps file generated by JuMP and running
it via CBC default command line options (CBC 2.9.1, that comes packaged
with Julia)!

Thanks,

Sam

**Comment by joehuchette** [comment]
I'm not sure I follow? We don't pass any command line arguments.

Can you pass along the code/.mps file? It's possible there's a bug in the mps writer.

**Comment by mlubin** [comment]
Also try using a different solver like GLPK and see what happens with the
direct interface versus MPS files.

**Comment by samiit** [comment]
I'm sorry for the confusion. I should have mentioned that the lower objective was for a yet unsolved problem (stopped due to user specified time limit).

So the reason I wanted to know the command line arguments was to know how CBC arrived at a lower objective early on, when using JuMP? It would be enough to be directed to the piece of code where the CBC solver is invoked in-memory via the C library.

Thank you very much for your great support.

Sam

**Comment by mlubin** [comment]
Have a look at https://github.com/JuliaOpt/Cbc.jl and https://github.com/coin-or/Cbc/blob/master/Cbc/src/Cbc_C_Interface.cpp. We don't explicitly set any parameters that differ from the command-line interface; however, Cbc has some pretty bizarre behavior with ``CbcMain0`` functions so it's hard to tell what exactly is going on.
