### ISSUE TITLE
ForwardDiff v0.2.1?

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/JuMP.jl#797]
I have no overview of the use of ForwardDiff in JuMP, but is it unlikely that the version in REQUIRE will be upped any time soon? Unfortunately, NLsolve requires v0.2.1, and that clashes with JuMP.

**Comment by mlubin** [comment]
Should be easy to update JuMP, but ReverseDiffSparse will take more time. May or may not be able to look into this in the next couple weeks.
CC @jrevels

**Comment by pkofod** [comment]
I was thinking of using it in Optim, but thought that it might make sense to switch around the same time to avoid too many people being annoyed by version clashes.
