### ISSUE TITLE
ERROR: MethodError: `^` has no method matching ^(::Float64, ::JuMP.Variable)

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaOpt/JuMP.jl#798]
The following constraint produce an error:
 
@JuMP.constraint(m, o[1] == p[1] * (1.0 ^ p[2]))

is it possible to have JuMP.Variables in ^?

**Comment by joehuchette** [comment]
You'll need to specify this as a nonlinear constraint:
```jl
@NLconstraint(m, o[1] == p[1] * (1.0 ^ p[2]))
```

**Comment by montyvesselinov** [comment]
Oops. Now it works.
On Sat, Jul 2, 2016 at 10:45 AM Joey Huchette <notifications@github.com>
wrote:

> You'll need to specify this as a nonlinear constraint:
>
> @NLconstraint(m, o[1] == p[1] * (1.0 ^ p[2]))
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaOpt/JuMP.jl/issues/798#issuecomment-230110895>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFXxeJI8Q5QT6ueViki_bSsVsrGfY-blks5qRpWegaJpZM4JDtRr>
> .
>
-- 
-monty
