### ISSUE TITLE
Non-linear User-defined functions

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaOpt/JuMP.jl#799]
I see there is an option to provide User-defined functions:

JuMP.register(:myf, 2, myf, autodiff=true)

if they cannot be autodiff (=false), how the jacobian can be provided?

can we use function that accepts myf(p), where p is a variable array?

@JuMP.variable(m, p[1:np], start=rand())

**Comment by mlubin** [comment]
> if they cannot be autodiff (=false), how the jacobian can be provided?

The syntax and an example are provided in the [docs](http://www.juliaopt.org/JuMP.jl/0.13/nlp.html#user-defined-functions).

> can we use function that accepts myf(p), where p is a variable array?

No, this is not yet supported.

**Comment by montyvesselinov** [comment]
Cool; this is helpful; more questions:

this works great (I really like JuMP):
```
			m = JuMP.Model(solver=Ipopt.IpoptSolver(max_iter=maxiter, print_level=verbosity))
			@JuMP.variable(m, p[i=1:np], start=pinit[i])
			@JuMP.variable(m, o[1:no])
			@JuMP.NLconstraint(m, o[1] == p[1] * (ti[1]^p[4]) + p[2] * ti[1] + p[3])
			@JuMP.NLconstraint(m, o[2] == p[1] * (ti[2]^p[4]) + p[2] * ti[2] + p[3])
			@JuMP.NLconstraint(m, o[3] == p[1] * (ti[3]^p[4]) + p[2] * ti[3] + p[3])
			@JuMP.NLconstraint(m, o[4] == p[1] * (ti[4]^p[4]) + p[2] * ti[4] + p[3])
			@JuMP.constraint(m, p[i=1:np] .>= pmin[i=1:np])
			@JuMP.constraint(m, p[i=1:np] .<= pmax[i=1:np])
			@JuMP.constraint(m, o[i=1:no] .>= omin[i=1:no])
			@JuMP.constraint(m, o[i=1:no] .<= omax[i=1:no])
			@JuMP.NLobjective(m, Max, p[1] * (ti[5]^p[4]) + p[2] * ti[5] + p[3])
```

however, i am not sure how want to make this more general.

This does not seem to work:

```
@JuMP.NLconstraint(m, o[i=1:no] == p[1] * (ti[1:no]^p[4]) + p[2] * ti[1:no] + p[3])
```
Also in even more general case, we would like to do:

```
@JuMP.NLconstraint(m, o[1:no] == myf(p...))
```
where myf(p...) returns a vector; I do not think this is supported, correct?

Any ideas how JuMP might work in this case? 

The only option it might be to generate and register multiple myf's and myg's in a loop:

```
@JuMP.NLconstraint(m, o[1] == myf1(p...))
@JuMP.NLconstraint(m, o[2] == myf2(p...))
@JuMP.NLconstraint(m, o[3] == myf3(p...))
```

**Comment by mlubin** [comment]
There's currently no support at all for anything vector-valued in nonlinear expressions. I've thought about it for quite a while, but implementing this would require a complete rewrite which won't happen anytime soon unless someone else takes the lead. You're on your own to express everything in terms of scalar operations, so something like
```
@JuMP.NLconstraint(m, o[1] == myf1(p[1],p[2],...,p[np]))
@JuMP.NLconstraint(m, o[2] == myf2(p[1],p[2],...,p[np]))
@JuMP.NLconstraint(m, o[3] == myf3(p[1],p[2],...,p[np]))
```
would be reasonable to do. If you'd like to make it parametric on ``np`` or ``no`` you can generate this code programmatically (one of the advantages of Julia).

**Comment by montyvesselinov** [comment]
Cool. this helps! Thank you very much!
