### ISSUE TITLE
P stands for optimization?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#800]
What if we change the tag line to: "Julia for Mathematical oPtimization"?

**Comment by joehuchette** [comment]
Sure

**Comment by diam** [comment]
Yes!
And it's better having "julia + optimization" in the html title page (google search...).

Le 6 juil. 2016 � 21:50, Miles Lubin <notifications@github.com> a �crit :

**Comment by mlubin** [comment]
@IainNZ, any objections?

**Comment by IainNZ** [comment]
RIP math programming :(

But yeah why not
