### ISSUE TITLE
Constraint Programming: Gecode

### ISSUE THREAD

**Issue by samiit** [JuliaOpt/JuMP.jl#801]
As far as I understand, we cannot call the gecode solver from JuMP, can we?

I understand from [this link](http://ampl.com/products/solvers/open-source/) that for combinatorial problems, solvers like Gecode may fair better than CBC. I wanted to access the Gecode solver; so far the only way I could do it was using the MiniZincIDE.
I would be glad if I could do it using JuMP. Any plans for incorporating this in?

Sam

**Comment by mlubin** [comment]
No plans for doing this. To support a new solver within JuMP, we need a wrapper implementing the https://github.com/JuliaOpt/MathProgBase.jl abstraction layer. If you'd like to experiment with this we'd be happy to answer any questions that arise at the JuMP or MathProgBase level.
