### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [JuliaOpt/JuMP.jl#802]
Is it possible to license this under: ASL 2.0, MIT or BSD. Better if it is MIT like rest of Julia and my other Julia packages.

**Comment by mlubin** [comment]
We have no intentions to relicense JuMP. Is there a particular reason why MPL 2.0 doesn't work for you?

**Comment by ihnorton** [comment]
Note that MPL 2.0 is compatible with use in aggregated works under ASL 2.0, MIT/BSD, and GPL licenses. There is almost no practical consequence for use in combination with proprietary development (arguably less than even the LGPL: you are required to release any covered-file modifications, but there is absolutely no linkability requirement).

**Comment by sirinath** [comment]
These licenses are more permissive hence if there is a possibility can you consider this?

**Comment by mlubin** [comment]
@sirinath, you haven't answered why MPL 2.0 isn't sufficient. If you have a particular use case you'd like to discuss, please open a discussion on the julia-opt forum or contact us in private.
