### ISSUE TITLE
Better error message when solver doesn't support callbacks

### ISSUE THREAD

**Issue by hsgan** [JuliaOpt/JuMP.jl#804]
I got the following the error when using lazy callback with Cbc. 
There is no error when I am running it with GLPK.

**************
ERROR: LoadError: MethodError: `setlazycallback!` has no method matching setlazycallback!(::Cbc.CbcMathProgSolverInterface.CbcMathProgModel, ::Function)
 in attach_callbacks at /home/hsgan/.julia/v0.4/JuMP/src/callbacks.jl:75
 in registercallbacks at /home/hsgan/.julia/v0.4/JuMP/src/callbacks.jl:148
 in build at /home/hsgan/.julia/v0.4/JuMP/src/solvers.jl:392
 in solve at /home/hsgan/.julia/v0.4/JuMP/src/solvers.jl:131
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
**************

Here's the code that triggered the error:

**************
using JuMP
using Cbc

m = Model( solver = CbcSolver() )
@variable(m, x >= 0, Int)

function lazyFunction(cb)
  println("test")
end

addlazycallback(m, lazyFunction)
solve(m)
**************

**Comment by mlubin** [comment]
That's because Cbc doesn't support lazy callbacks, but we could use a better error message.

**Comment by hsgan** [comment]
Okay, thanks.

**Comment by mlubin** [comment]
I'll leave this open so we remember to improve the error message.
