### ISSUE TITLE
Inconsistency between keys and the operator [] of JuMP.JuMPArray

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/JuMP.jl#819]
For a binary variable that was created like this:

```
I = 1:10
@variable(m, x[v in I], Bin)

...
solve(m)
b = getvalue(x)
```

This function, I wrote, crashes when I provide b as an argument 
```
function bin_decisions(b::JuMP.JuMPArray)
    ret = []
    for v in keys(b)
        b[v] == 1.0 && push!(ret,v)
    end
    ret
end
```

If I understood well the JuMPArray in this case is indexed with a tuple that contains one element, which I'm fine with, but the issue is that to access an element in b you can t use the 1-element tuple as index => inconsistency between keys and the operator [].

Basically the function that works is this one.
```
function bin_decisions(b::JuMP.JuMPArray)
    ret = []
    for v in keys(b)
        b[v[1]] == 1.0 && push!(ret,v)
    end
    ret
end
```

I am quite new to julia and in particual to JuMP. So, I would like just a confirmation that this is a bug and I will try to find the error and suggest a fix.

**Comment by joehuchette** [comment]
This is closely related to #646. This is a thorny issue and we're not entirely happy with the current implementation, but we also don't have a better solution that avoids the ambiguity [here](https://github.com/JuliaOpt/JuMP.jl/issues/646#issuecomment-216092332) (suggestions welcome). Regardless, this code should work as well:

```jl
function bin_decisions(b::JuMP.JuMPArray)
    ret = []
    for v in keys(b)
        b[v...] == 1.0 && push!(ret,v)
    end
    ret
end
```
(though I haven't tested)

**Comment by IssamT** [comment]
Thanks for the fast reply. I confirm that your code work as well and is more generic than my solution.
The fact that my solution was not generic is the thing that annoyed me the most since I am not a language purist.

However I will think about a way to fix this inconsistency between keys and the operator[] and if I have a suggestion I will provide it in the thread #646 since it is indeed the same issue. So feel free to close this one.
