### ISSUE TITLE
Evaluation of an Exponent Expression

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#822]
```
using JuMP

m = Model()

@variable(m, 1 <= x <= 5)

costs = [10, 1, 0.1]

# gives: ERROR: LoadError: Only exponents of 2 are currently supported. 
# Are you trying to build a nonlinear problem? Make sure you use @NLconstraint/@NLobjective.
@objective(m, Min, sum{ c*x^(p-1), (p,c) in enumerate(costs) } )

solve(m)
```

The issue does not occur when using @NLobjective.

**Comment by joehuchette** [comment]
This is expected behavior: ``@objective`` is only able to handle linear or quadratic expressions. Is this a feature request? Or is the error message not sufficiently clear?

**Comment by ccoffrin** [comment]
In this case p is a constant and the exponent is of degree less than 2 in this input.  At compile time the objective in this example is,

10*x^0 + 1*x^1 + 0.1*x^2

To me the error message is misleading.  Maybe it should be, something like "exponents cannot be expressions", but @mlubin was suggesting that this is something he would like to support.

I don't mind if this is tagged as a feature request, or if you simply prefer to clarify the error message.

**Comment by mlubin** [comment]
Right now it does need to be a constant: https://github.com/JuliaOpt/JuMP.jl/blob/1bd4ab2f83a9c6acf6b68cfc34557e4169476eb7/src/parseExpr_staged.jl#L659
So yes, the error message is misleading and we should support nonconstant exponents also.
