### ISSUE TITLE
extract linear constraints

### ISSUE THREAD

**Issue by edljk** [JuliaOpt/JuMP.jl#828]
Is there a way to obtain the linear constraints of a JuMP model in a (eventually sparse) matrix form ?

**Comment by joehuchette** [comment]
Yep, you can use ``MathProgBase.getconstrmatrix``:
```jl
using JuMP, MathProgBase
m = Model()
@variable(m, x[1:2])
@constraint(m, x[1] + x[2] == 1)
JuMP.build(m)
MathProgBase.getconstrmatrix(internalmodel(m))
```
Usage questions (as opposed to bugs or feature requests) are better suited for the [julia-opt mailing list](https://groups.google.com/forum/#!forum/julia-opt) in the future.
