### ISSUE TITLE
errors in running JuMP basic examples: failed to precompile Lazy

### ISSUE THREAD

**Issue by gstecca** [JuliaOpt/JuMP.jl#829]
I tried to run the basic model but I get the following errors: 

ERROR: LoadError: LoadError: @rec: reduce(f::Function,v,xs::List) = begin  # /home/gstecca/.julia/v0.4/Lazy/src/liblazy.jl, line 109:
        if isempty(xs)
            v
        else 
            reduce(f,f(v,first(xs)),tail(xs))
        end
    end is not a function definition.
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/gstecca/.julia/v0.4/Lazy/src/liblazy.jl, in expression starting on line 111
while loading /home/gstecca/.julia/v0.4/Lazy/src/Lazy.jl, in expression starting on line 100
ERROR: LoadError: Failed to precompile Lazy to /home/gstecca/.julia/lib/v0.4/Lazy.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:240
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/gstecca/.julia/v0.4/ReverseDiffSparse/src/ReverseDiffSparse.jl, in expression starting on line 6
ERROR: LoadError: Failed to precompile ReverseDiffSparse to /home/gstecca/.julia/lib/v0.4/ReverseDiffSparse.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:240
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/gstecca/.julia/v0.4/JuMP/src/JuMP.jl, in expression starting on line 20
ERROR: LoadError: Failed to precompile JuMP to /home/gstecca/.julia/lib/v0.4/JuMP.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:400
 in require at ./loading.jl:266
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/gstecca/coding/julia/model0.jl, in expression starting on line 1

**Comment by mlubin** [comment]
Could you report the output of ``versioninfo()`` and ``Pkg.status()``?

**Comment by gstecca** [comment]
versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Pkg.status()
3 required packages:
 - Gurobi                        0.2.3
 - IJulia                        1.2.0
 - JuMP                          0.14.0
16 additional packages:
 - BinDeps                       0.4.2
 - Calculus                      0.1.15
 - Compat                        0.8.6
 - Conda                         0.2.3
 - DataStructures                0.4.5
 - ForwardDiff                   0.2.2
 - JSON                          0.6.0
 - Lazy                          0.11.0
 - MacroTools                    0.3.1
 - MathProgBase                  0.5.2
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - ReverseDiffSparse             0.5.8
 - SHA                           0.2.0
 - URIParser                     0.1.6
 - ZMQ                           0.3.3

I removed and reinstalled everything with the hope to solve issues but no success.

Many thanks for the help! Giuseppe.

**Comment by mlubin** [comment]
I can't reproduce this. I'd recommend deleting the ``~/.julia`` folder and reinstalling JuMP. If you have further issues with the Lazy package, open an issue at https://github.com/MikeInnes/Lazy.jl/issues/new and CC me.

**Comment by gstecca** [comment]
Dear Miles,
 I just removed and reinstalled JuMP and now problem disappeared. The difference was that when I ran again the model julia recompiled  MacroTools. In particular I did:
Pkg.rm("JuMP")
Pkg.update()
Pkg.add("JuMP")

Then exited julia and run the model. I got this:

julia model0.jl 
INFO: Recompiling stale cache file /home/gstecca/.julia/lib/v0.4/MacroTools.ji for module MacroTools.
Max 5 x + 3 y
Subject to
 x + 5 y ≤ 3
 0 ≤ x ≤ 2
 0 ≤ y ≤ 30
Optimize a model with 1 rows, 2 columns and 2 nonzeros
Coefficient statistics:
  Matrix range    [1e+00, 5e+00]
  Objective range [3e+00, 5e+00]
  Bounds range    [2e+00, 3e+01]
  RHS range       [3e+00, 3e+00]
Presolve removed 1 rows and 2 columns
Presolve time: 0.00s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.0600000e+01   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective  1.060000000e+01
Objective value: 10.6
x = 2.0
y = 0.2

It seems the issue was due to the need to recompile Macrotools. Is  it? I had this issue after installing Xpress module ( I did not have this issue before with simply JuMP and Gurobi modules).
Thanks.
Best regards.
Giuseppe

**Comment by mlubin** [comment]
Sounds like Julia had a hiccup. If you can find a way to reliably reproduce the problem it's worth reporting it as an issue on the Julia repository.
