### ISSUE TITLE
Internal Model not unloaded when SDP constraint added

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#830]
In lines [468 -> 470 of macros.jl](https://github.com/JuliaOpt/JuMP.jl/blob/8b3074af0c51cdb12c9411e9a71175614bfe2866/src/macros.jl#L468-L470) (in macro `SDconstraint`), it is written

        c = SDConstraint($newaff)
        push!($(m).sdpconstr, c)
        c

while I would have expected something like

        addconstraint($m, SDConstraint($newaff))

since this is what is done, e.g., in the macro `constraint`. Indeed, those two blocks of code do not have the same behaviors as the second one also does `m.internalModelLoaded = false` inside the `addconstraint` function which seems important since one constraint has been added. Am I getting it wrong ?

**Comment by mlubin** [comment]
@blegat, good catch, this seems correct. Would you mind submitting a PR?

**Comment by blegat** [comment]
Ok, I do that now :)
