### ISSUE TITLE
Vector arguments for user-defined functions

### ISSUE THREAD

**Issue by lbittarello** [JuliaOpt/JuMP.jl#831]
I'm aware that support for user-defined functions is still a work in progress, but I couldn't figure out the way to register multivariate functions with vector inputs. Consider the log likelihood of the logit model and its gradient, for example:

```
loglike(θ::Vector)= dot(y, x*θ) - sum(log1pexp(x*θ))
gradient!(g::Vector, θ::Vector) = (g[:] = x'*(y - logistic(x*θ)))
```

If I use `JuMP.register(:loglike, 1, loglike, gradient)`, JuMP assumes that `loglike` is univariate and requests a Hessian. I assume it it is misinterpreting the gradient as well, assuming that it would return a derivative instead of filling a vector with the gradient. If I use `JuMP.register(:loglike, n, loglike, gradient)`, where `n` is the dimension of the parameter vector, I get an error as well – JuMP tells me that `loglike` takes only one argument, not `n`.

**Comment by mlubin** [comment]
That's not supported at the moment. As the documentation says, all arguments to user-defined functions must be scalars.
