### ISSUE TITLE
addition operator warning

### ISSUE THREAD

**Issue by kkmann** [JuliaOpt/JuMP.jl#837]
Hi,

I get the "Warning: The addition operator has been used on JuMP expressions a large number of times. This warning is safe to ignore but may indicate that model generation is slower than necessary. For performance reasons, you should not add expressions in a loop. Instead of x += , use append!(x,y) to modify x in place. Uf y is a single variable, you may also use push!(x, coef, y) in place of x += coef*y"-warning when defining an objective via the sum macro for a large number of variables (~ 2 million binary ones). I do not quite understand the error message, nor what I need to do to speed up model creation. Do I just have to live with the slow model creation?

**Comment by IssamT** [comment]
I also had once this confusion. This is not related just to JuMP but to julia in general. The following: 

`x += a`

should be seen as

`x = x + a`

This means a **new object is created** and `x` has now a reference to the new object.

however all functions that end with `!` like `push!` and `append!` often modify their first argument in place without creating a new object which is often more efficient. (Although this is just a convention of naming and not a rule enforced by the language)

**Comment by kkmann** [comment]
Hey thanks, so the problem is the implementation of the @objective macro using the "+" operator?
how would I rewrite sum{a[i,j,k]*x[i,j,k], i=1:n, j = 1:n, k = 1:n} with  n large efficiently?

**Comment by IssamT** [comment]
I don't know why **@objective** is **using +=**. Maybe we can get some info about that from the dev team.

You can solve your issue I think by creating an expression and filling it in a loop using append!

Here is a small exemple:

```
@variable(m, x[1:2], Bin)
exp = 3 * x[1]
#exp += 7 * x[2]
append!(exp, 7 * x[2])
@objective(m , Max, exp)
print(m)
```

**Comment by kkmann** [comment]
Thank you very much, this results in a HUGE speedup, and I do get the underlying system much better now. I agree that it would be very interesting to know why the `convenience' macros are so inefficient. This kinda makes them unusable with very large problems and I would be very helpful to mention this problem in the docs. 

Nevertheless, I cannot stress enough how much I love the JuMP framework. I use it as my sole interface to Gurobi. Makes creation of complex models so much easier!

**Comment by IssamT** [comment]
You are welcome. I'm glad it helped you. 

I have been using juliaOpt (mainly JuMP) for about a month now and I also like it. The dev team are doing great job in most of the packages in juliaOpt. It is also fair to mention that some of the nice features in JuMP were possible thanks to the use of Julia which is a nice modern dynamic language.

If I will have some time I might look at the issue with `@objective`. But first tracing shows the issue comes from the functions `addToExpr` defined in `parseExpr_staged.jl`. example:

```
function addtoexpr{C,V}(ex::Number, c::GenericAffExpr{C,V}, x::V)
    q = c*x
    q.aff.constant += ex
    q
end
```

**Comment by joehuchette** [comment]
@IssamT is correct; the warning is meant to tell users that their code is creating many intermediate objects, which will likely slow things down significantly. However, the main reason the ``@constraint``/``@objective`` macros exist is to avoid this, so there may be something actionable here. It's possible that the ``addtoexpr`` machinery @IssamT mentions is missing a case, which will lead to code taking the "slow" path.

Can you post a short, self-contained snippet that reproduces the warning, as well as the version of julia/JuMP you are using? I can't seem to reproduce this.

**Comment by kkmann** [comment]
I'll try to, it does not seem to be an issue solely with the number of variables. As I said I only have something in the order of one million. However, I also used to add some quite large constraints prior to defining the objective and if they share the same counter it might have caused the warning.

**Comment by mlubin** [comment]
Yes, the same counter is used across the model. If you can't create a short example, any self-contained example that we can run locally will do.

**Comment by mlubin** [comment]
@kkmann, please reopen if you can pinpoint the issue or at least create an example that we can run to investigate further
