### ISSUE TITLE
Concatenation of JuMPArrays

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/JuMP.jl#838]
When running the `@variable` macro on a generic list of type `T`, the return type is,

`JuMP.JuMPArray{JuMP.Variable,1,T,1}}}`

I was expecting that concatenating two jump arrays via  `[a1, a2]` or `vcat(a1, a2)` would yield a new JuMP.JuMPArray with the same type as above.  However, I got,

`Array{JuMP.JuMPArray{JuMP.Variable,1,T,1}}},1}`

This suggests that concatenation wraps the two JuMP arrays inside another array.  It seems like this could become an issue when you want to iterate over all of the variables in a concatenated list of variables?

**Comment by mlubin** [comment]
JuMPArrays are like dictionaries and don't really have a concept of the ordering of their indices. What should happen when you concatenate two dictionaries?

**Comment by ccoffrin** [comment]
Right, I forgot!  Then the current behavior of `[a1, a2]` is reasonable.

Concatenation is well defined for lists / arrays because there is an order and the index is the key.  

With dictionaries there is no order, so concatenation is not well defined. The closest analog would be taking the unions of (key => value) mappings;  But this is problematic because the keys may not be unique.  In Python, dict has update and extend methods, where the former overwrites duplicate keys and later does not.

In the near term, I would recommend,

1.  Clarifying / Removing the note on variable concatenation from here, http://jump.readthedocs.io/en/latest/refexpr.html, it only makes sense when the return type is `Array{Variable}`.
2. Change the type name JuMPArray to something like JuMPDict, so the semantics are clearer.

In my current use case what I want to do is given a `JuMPArray{Variable}`, throw away the key information and simply get a list of the variable objects, e.g. as a `Array{Variable}` or `Set{Variable}`.  Is there any easy way to do that?

**Comment by mlubin** [comment]
> In my current use case what I want to do is given a JuMPArray{Variable}, throw away the key information and simply get a list of the variable objects, e.g. as a Array{Variable} or Set{Variable}. Is there any easy way to do that?

``vcat(a1[:], a2[:])`` should do the trick.

**Comment by mlubin** [comment]
Seems resolved?
