### ISSUE TITLE
Riemann Integral to intialize nonlinear expression

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaOpt/JuMP.jl#839]
I am sure that there is probably a better way of doing this, but I cannot think of it. I have a variable in my model ( the time steps are variable size): 
`
@variable( mdl, 0 <= dt[1:N] <= 0.2 )
`
where N is the number if time steps.

and I am trying to describe the motion of an obstacle using these variable time steps as
`
# initial postion
  @NLexpression(mdl, X_obs[j=1:Q,1],X_0[j])
 @NLexpression(mdl, Y_obs[j=1:Q,1],Y_0[j])

# after the time steps the obstacle has moved
# basically trying to integrate the speed over each time interval 
@NLexpression(mdl, X_obs[j=1:Q,i=2:N], X_0[j] + speed_x[j]*sum(dt[1:(i-1)]))
 @NLexpression(mdl, Y_obs[j=1:Q,i=2:N], Y_0[j] + speed_y[j]*sum(dt[1:(i-1)]))
`
where Q is the total number of obstacles

Is there another way to do this? I get the error:
`
ERROR: LoadError: Unrecognized function :sum used in nonlinear expression.
 in macro expansion; at /home/febbo/.julia/v0.5/JuMP/src/parsenlp.jl:88 [inlined]
 in macro expansion; at /home/febbo/.julia/v0.5/JuMP/src/macros.jl:1167 [inlined]
 in macro expansion; at /home/febbo/Documents/workspace/OCP_julia/main2.jl:255 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
while loading /home/febbo/Documents/workspace/OCP_julia/main2.jl, in expression starting on line 236
`

**Comment by huckl3b3rry87** [comment]
To make this example simpler, I am having an issue in general using the sum() command within the JuMP modules. For instance another example is:

`
@variable( mdl, 0 <= dt[1:N] <= 0.2 )
@NLobjective(mdl, Min,  sum(dt[1:N]))
`
and I get
`
ERROR: LoadError: Unrecognized function :sum used in nonlinear expression.
 in error(::String) at ./error.jl:21
 in include_from_node1(::String) at ./loading.jl:426
while loading /home/febbo/Documents/workspace/OCP/main3.jl, in expression starting on line 88
`
So, I am assuming that the sum() command is not in JuMP. Is this correct?

**Comment by huckl3b3rry87** [comment]
also, I tried a few other work arounds including:
`
	temp1=sum(dt[1:N])
    @NLexpression(mdl,temp2, temp1)
    @NLobjective(mdl, Min,  temp2)
`
which leads to

`
ERROR: LoadError: MethodError: no method matching parseNLExpr_runtime(::JuMP.Model, ::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Array{ReverseDiffSparse.NodeData,1}, ::Int64, ::Array{Float64,1})
Closest candidates are:
  parseNLExpr_runtime(::JuMP.Model, ::Number, ::Any, ::Any, ::Any) at /home/febbo/.julia/v0.5/JuMP/src/parsenlp.jl:228
  parseNLExpr_runtime(::JuMP.Model, ::JuMP.Variable, ::Any, ::Any, ::Any) at /home/febbo/.julia/v0.5/JuMP/src/parsenlp.jl:237
  parseNLExpr_runtime(::JuMP.Model, ::JuMP.NonlinearExpression, ::Any, ::Any, ::Any) at /home/febbo/.julia/v0.5/JuMP/src/parsenlp.jl:244
  ...
 in include_from_node1(::String) at ./loading.jl:426
while loading /home/febbo/Documents/workspace/OCP/main3.jl, in expression starting on line 262
`
any thoughts? Thanks!

**Comment by huckl3b3rry87** [comment]
for the case that N = 2, this works just fine:
`
    @NLobjective(mdl, Min,  dt[1] + dt[2])
`
But, I would like a variable N

**Comment by mlubin** [comment]
@huckl3b3rry87, The [syntax notes in the documentation](http://www.juliaopt.org/JuMP.jl/0.14/nlp.html#syntax-notes) address all of the issues you're running into. In the future, please direct usage questions to the julia-opt list.
