### ISSUE TITLE
solver table broken

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#841]
Since https://github.com/JuliaOpt/JuMP.jl/commit/03012cab0551566953396fdd74b441da0c56f253

**Comment by mlubin** [comment]
The solver table also: https://github.com/JuliaOpt/JuMP.jl/commit/f0cfe94ae7ae13a39b3763558723908a39e5c3da

**Comment by joehuchette** [comment]
Closed by 743d2ce25d37f42eba61891394650999fdc40ffd

**Comment by mlubin** [comment]
:+1:
