### ISSUE TITLE
Make writeLP use proper variable names

### ISSUE THREAD

**Issue by leethargo** [JuliaOpt/JuMP.jl#846]
I was debugging some models in JuMP and found it annoying that they are printed as `VAR*` and not given the names to JuMP. There's a method `getname` that seems to work and I wonder whether `writeLP` should get a keywords arguments (eg, `realnames=false`) to make it use proper variable names.

Of course there could be problems with non-ascii variable names, or arrays of variables (maybe `x[1]` is an invalid variable name in lp format?), but then there could be workarounds or just an error message.

The documentation says something about `setname` being disabled for performance reasons, but anyway this behavior would be optional and non-default.

If you think this is viable and useful, I'd give it a try.

**Comment by joehuchette** [comment]
This seems like a good idea for the default behavior; my only concerns are the cases you bring up. I would rewrite ``x[1,2,3]`` to ``x_1_2_3``. A PR would be very welcome!

**Comment by mlubin** [comment]
Yeah, I think it's okay to make this the default behavior at this point. The performance concerns are not too relevant anymore.

**Comment by mlubin** [comment]
Closed by #848
