### ISSUE TITLE
NLopt fails JuMP's tests

### ISSUE THREAD

**Issue by colbec** [JuliaOpt/JuMP.jl#849]
Pkg.test works fine on Julia 0.4.6, but appears to fail on v 0.6 during NLoptSolver. I say appears to fail since the test appears to go into a very long period of no feedback to REPL. Maybe it is just a very long test and I am not patient enough, but we seem to be ok on 0.4.6. The process in the REPL can be stopped with a Ctl-c, but the CPU core continues locked and processing at 100% and is not responsive to Ctl-d when the main Julia process exits. The process has to be killed.
 Last output to REPL is:

```
[nonlinear] Test entropy maximization (reformulation)
  > With solver Ipopt.IpoptSolver
  > With solver NLopt.NLoptSolver
```

and

```
julia> Pkg.status("NLopt")
 - NLopt                         0.3.3

julia> Pkg.status("JuMP")
 - JuMP                          0.14.0+            master
```

checking out the latest master makes no difference.

**Comment by mlubin** [comment]
That's correct. NLopt behaves weirdly and none of the JuMP developers have
been bothered to look into it. Fixes gladly accepted.

**Comment by colbec** [comment]
Thanks for confirming. Just to add, test is fine on 0.4.6, test fails on Julia 0.5r4 but is able to recover gracefully from ctrl-c and ctrl-d, but system unstable on test in Julia 0.6 dev at least here.

**Comment by colbec** [comment]
FWIW suppressing the specific test "[nonlinear] Test entropy maximization (reformulation)" allows the test routine to complete successfully on Julia v 0.6 with a report of two failed tests, again related to NLoptSolver:
```
[nonlinear] Quadratic equality constraints
  > With solver Ipopt.IpoptSolver
  > With solver NLopt.NLoptSolver
WARNING: Not solved to optimality, status: Suboptimal
    Failure :: (line:272) :: With solver NLopt.NLoptSolver :: fact was false
      Expression: status --> :(:Optimal)
        Expected: :Optimal
        Occurred: :Suboptimal
    Failure :: (line:272) :: With solver NLopt.NLoptSolver :: fact was false
      Expression: getvalue(x) --> roughly([sqrt(1 / 2),0],1.0e-6)
        Expected: [0.0,0.0] ≅ [0.707107,0.0]
```

**Comment by colbec** [comment]
@mlubin Here's another little fact for the mix: the field xtol-abs in NLopt.NLoptSolver() seems to be a bit sensitive. Following the pattern in solvers.jl with a call like:
`NLopt.NLoptSolver(:LD_SLSQP,NaN,1.0e-7,NaN,1.0e-7, **nothing** ,1.0e-7,0,0,nothing,0,nothing,0)`
If I replace the highlighted nothing with a real such as 1.0 then the output from the solver comes back immediately. It produces failures, but at least it comes back.
```
[nonlinear] Test entropy maximization (reformulation)
  > With solver NLopt.NLoptSolver
    Failure :: (line:272) :: With solver NLopt.NLoptSolver :: fact was false
      Expression: norm([getvalue(x[i]) for i = idx] - [1 / 4,1 / 4,1 / 4,1 / 4]) --> roughly(0.0,0.001)
        Expected: 0.16666666666666646 ≅ 0.0
    Failure :: (line:272) :: With solver NLopt.NLoptSolver :: fact was false
      Expression: getvalue(entropy[1]) --> roughly(-(1 / 4) * log(1 / 4),0.0001)
        Expected: 0.2986265782046761 ≅ 0.34657359027997264
    Failure :: (line:272) :: With solver NLopt.NLoptSolver :: fact was false
      Expression: getvalue(zexpr[1]) --> roughly(-(1 / 4) * log(1 / 4),0.0001)
        Expected: 0.8333333333333333 ≅ 0.34657359027997264
Out of 4 total facts:
  Verified: 1
  Failed:   3
(::delayed_handler) (generic function with 4 methods)

```
Now for the interesting part. A value of 0.0 produces the problem. If I start reducing the value 1.0 to find a sensitive point it occurs somewhere in the interval 0.33 to 0.34. A value less than 0.34 in xtol_abs leads to a process that goes on for a very long time.

**Comment by mlubin** [comment]
An assignment of the parameters that fixes the hanging would be an
improvement on its own.

**Comment by mlubin** [comment]
NLopt is no longer run during JuMP's tests, so I consider this issue resolved.
