### ISSUE TITLE
2D JuMPArray (symbols-integers): indexing fails with column

### ISSUE THREAD

**Issue by dourouc05** [JuliaOpt/JuMP.jl#851]
I am defining a series of variables with one dimension being symbols and the other integers; then I am trying to work with ranges of variables, but this yields strange errors. 

```julia
using JuMP
m = Model()
@variable(m, w[1:2], Bin)
@variable(m, x[[:1,:2]], Bin)
@variable(m, y[[:1, :2], [1, 2]], Bin)
@variable(m, z[[1, 2], [:1, :2]], Bin)
```

When there is only one dimension, indexed with symbols, columns work as expected: 

```
julia> x[:]
2-element Array{JuMP.Variable,1}:
 x[1]
 x[2]
```

However, when selecting a subset of variables, this no more works (unlike with basic integers for indexing): 

```
julia> w[:]
2-element Array{JuMP.Variable,1}:
 v[1]
 v[2]

julia> x[[:1, :2]]
ERROR: Failed attempt to index JuMPArray along dimension 1: [1,2] ∉ [1,2]
 in error at error.jl:21
```

Things become worse with more than one dimension, as nothing works as expected when slicing on the symbol or the integer variables (only selecting one symbol value works): 

```
julia> y[:1,1]
y[1,1]

julia> y[:,1]
ERROR: Failed attempt to index JuMPArray along dimension 1: Colon() ∉ [1,2]
 in error at error.jl:21

julia> y[:1,:]
ERROR: Failed attempt to index JuMPArray along dimension 2: Colon() ∉ [1,2]
 in error at error.jl:21

julia> y[:,:]
ERROR: Failed attempt to index JuMPArray along dimension 1: Colon() ∉ [1,2]
 in error at error.jl:21
```

(The same tests fail on `z` when switching symbols and integers for indexing.)

To solve this issue, I am currently forced to use the `sum{}` construction, which is much less nice just to sum over a dimension (like `sum(y[:1, :])`. 

```
@constraint(m, sum{z[h, g], g in gs} == 1)
@constraint(m, sum(z[h, :]) == 1)
``` 

Would this issue be similar to https://github.com/JuliaOpt/JuMP.jl/issues/833 or https://github.com/JuliaOpt/JuMP.jl/issues/730?

**Comment by mlubin** [comment]
If you index with anything except a numeric range then you cannot slice or use any array-like properties.

**Comment by dourouc05** [comment]
This does not make sense to me… Why then allow using anything else than integers for indexing, if it's just going to bite you the second after?

**Comment by mlubin** [comment]
What kind of object would you expect ``y[:,1]`` to produce? Julia doesn't allow slicing over dictionaries:
```jl
julia> d = Dict(:a => 1, :b => 2);

julia> sum(d[:])
ERROR: KeyError: Colon() not found
 in getindex at dict.jl:738
```

**Comment by dourouc05** [comment]
Why couldn't `y[:,1]` be of the same type as `x`? That would be the most intuitive solution to me. Exactly like for other cases that are not handled by basic Julia arrays: 

```
julia> @variable(m, u[1:4, 0:4], Bin)
u[i,j] in {0,1} for all i in {1,2,3,4}, j in {0,1,..,3,4}

julia> typeof(u)
JuMP.JuMPArray{JuMP.Variable,2,Tuple{UnitRange{Int64},UnitRange{Int64}}}

julia> typeof(u[1, :])
Array{JuMP.Variable,2}
```

**Comment by mlubin** [comment]
We've been heading in this direction, see https://github.com/JuliaOpt/JuMP.jl/pull/782. PRs accepted.

**Comment by mlubin** [comment]
I believe this is a dup of https://github.com/JuliaOpt/JuMP.jl/issues/643

**Comment by dourouc05** [comment]
OK, thanks! So I'm closing this, and having a look at these issues (and maybe send a PR, at least for a better error message).
