### ISSUE TITLE
argmax v^2 between -1 and 1 = 0, between -1 and 1.01 = 1.01

### ISSUE THREAD

**Issue by maxlarsen** [JuliaOpt/JuMP.jl#852]
I am encountering this weird behavior:

~~~julia
function oo()
    prog = Model(solver=IpoptSolver(print_level=0))
    @variable(prog, -1.0 <= v <=1.01 )
    @objective(prog, Max,  v^2)       
    status = solve(prog)
    getvalue(v)
end

julia> dev.oo()
1.01
~~~

~~~julia
function oo()
    prog = Model(solver=IpoptSolver(print_level=0))
    @variable(prog, -1.0 <= v <=1.0 )
    @objective(prog, Max,  v^2)       
    status = solve(prog)
    getvalue(v)
end

julia> dev.oo()
0.0
~~~

Everything should be up to date:
~~~
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
~~~

**Comment by mlubin** [comment]
Nothing weird at all. Ipopt has returned you a stationary point, which is about all you can hope for when solving a nonconvex problem. You might try giving it a different starting point.

**Comment by maxlarsen** [comment]
Ok, thanks for explaining. Changing the starting point does not resolve anything (even starting at the maximum). I hope you will agree this can be "suprising" to the non-expert even if you don't find it "weird".

I have no idea why this is resolved by changing the boundary values to -1.0 and 1.01 but I trust you if you say this is normal behavior. So would it be more reliable to use a nonlinear solver here?

~~~
function oo()
    prog = Model(solver=IpoptSolver(print_level=0))
    @variable(prog, -1.0 <= v <=1.0,start=1 )
    @objective(prog, Max,  v^2)       
    status = solve(prog)
    getvalue(v)
end

julia> dev.oo()
0.0
~~~

**Comment by mlubin** [comment]
Ipopt is a nonlinear solver. It would be more reliable to reformulate your problem into something where you can expect a globally optimal solution, e.g., convex or mixed-integer convex.

**Comment by mlubin** [comment]
Or use a global solver like Couenne or BARON.

**Comment by maxlarsen** [comment]
Thank you.
