### ISSUE TITLE
Passing m.ext to loadproblem?

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/JuMP.jl#854]
On src/Solvers.jl (ligne 339)

Would it be a problem if we passed also `m.ext`, which is just a generic Dict, to `loadproblem`?

namely using:

`MathProgBase.loadproblem!(m.internalModel, A, collb, colub, f, rowlb, rowub, m.objSense, m.ext)`

instead of 

`MathProgBase.loadproblem!(m.internalModel, A, collb, colub, f, rowlb, rowub, m.objSense)`

Solvers not using it can still ignore that parameter, right?

**Comment by mlubin** [comment]
What's the point? If you'd like to pass other information to the solver you can do so directly.

**Comment by mlubin** [comment]
E.g.,
```jl
JuMP.build(m)
# do whatever you want with m.internalModel
solve(m)
```

**Comment by IssamT** [comment]
I see what is in m.ext is part of the model so it is better to not pass it directly to the solver if other solvers can use it as well.

But you are right. Passing this info can be done after the build, for instance by using `solvehook`.

Thanks for your help.

**Comment by IssamT** [comment]
Well `solvehook` is probably a bad example but I undrestood your point. Thanks.
