### ISSUE TITLE
Trouble differencing  2*log(x-2)

### ISSUE THREAD

**Issue by vepiteski** [JuliaOpt/JuMP.jl#855]
The problem arises with the function f(x)  defined as (x is of dimension 1)
- ifelse(x<=3.0,(x-2.0)^2, 2*log(x-2.0)+1.0)
Its derivative at x=0 evaluates as NaN

I tracked down the problem to 
- 2*log(x-2.0)
since with log(x-2.0)+log(x-2.0) instead of 2*log(x-2.0), it evaluates correctly to -4.0

This is not the end of the story. With log(x-2.0)+log(x-2.0), the derivative at x=2.0 evaluates to NaN but should be 0.0. At x=2.0 + or - epsilon, it evaluates OK, but not for the minimum (x=2) of the function.

Here is the complete code for f

# probl3m 18 from
# http://infinity77.net/global_optimization/test_functions_1d.html#d-test-functions

function AMPGO18()
   nlp = Model()

   @variable(nlp, x, start=0.0)

   @NLobjective(
    nlp,
    Min,
    #ifelse(x>3.0, log(x-2.0)+log(x-2.0)+1.0, (x-2.0)^2)  # grad works but not for x=2 (NaN)
    ifelse(x<=3.0, (x-2.0)^2, 2*log(x-2.0)+1.0)  # grad evaluates to NaN for x<=2
   )

   return nlp
end

**Comment by mlubin** [comment]
Looks like a bug, thanks for reporting.
Why do you say that the derivative of log(x) at x = 0 should be 0?

**Comment by mlubin** [comment]
Sorry, I misunderstood.
