### ISSUE TITLE
anonymous variables unconstrained inputs

### ISSUE THREAD

**Issue by jac0320** [JuliaOpt/JuMP.jl#856]
Somehow I found this type of variable extremely useful especially when creating variables when needs flexible variables that I can refer easily.

So I was trying to setup a single continuous variable  
X[1] = @variable(m, basename="x1")
This will give me an error saying "basename undefined", 

Then I tried (by cleaning everything),
X[1] = @variable(m, [1], basename = "x1"),
this is fine and returns me an array of one variable in it, it is usable, but not idea since the indexing adds  an extra layer

Then I tried (by cleaning everything),
X[1] = @variable(m, Real, basename = "x1"),
This returns me an single continuous variable, which is ideal and fine.

However, this is the last I tried,
X[1] = @variable(m, whatever, basename="x1"),
The return of this the same the previous one, but the input is just weird

Should this be an issue?

**Comment by mlubin** [comment]
Try on JuMP master, it's likely fixed.

**Comment by jac0320** [comment]
It is solved. Thanks.
