### ISSUE TITLE
Creating arrays of variables with UInt bounds

### ISSUE THREAD

**Issue by allbits** [JuliaOpt/JuMP.jl#857]
The following does not work.

function build()
   m = Model()
   n::UInt = 4
   @variable(m,x[1:n])
end

Changing UInt to Int works.

**Comment by joehuchette** [comment]
This is a surprisingly subtle issue, caused by the fact that ``length(1:UInt(4))`` returns a ``UInt(4)`` (rather than an integer, as is usually the case). I believe there's an open issue in the julia repo for this.

**Comment by joehuchette** [comment]
Closed by #862, thanks for reporting
