### ISSUE TITLE
[Regression?] Operator .^ in objective functions no more working in Julia 0.5

### ISSUE THREAD

**Issue by dourouc05** [JuliaOpt/JuMP.jl#861]
When trying some of my code on the new Julia 0.5.0, I am getting error messages which I did not have with 0.4.6. With both, I'm using JuMP 0.14.1 (I've run `Pkg.update()` on both today). 

This is the incriminate code: 

```julia
m = Model()
@variable(m, xs[1:5] >= 0)
@objective(m, Min, sum(xs .^ 2))
```

Julia 0.4.6 has no problem with it, but 0.5.0 shouts: 

```
ERROR: MethodError: no method matching .^(::JuMP.Variable, ::Int64)
Closest candidates are:
  .^(::Range{T}, ::Number) at range.jl:813
  .^(::Number, ::Number) at operators.jl:151
  .^(::BitArray{N}, ::Integer) at bitarray.jl:1195
  ...
 in collect(::Base.Generator{Array{JuMP.Variable,1},Base.##164#166{Int64}}) at .\array.jl:307
 in .^(::Array{JuMP.Variable,1}, ::Int64) at .\arraymath.jl:79
```

Is this something about that "fused broadcast syntax" that came with 0.5?

**Comment by mlubin** [comment]
Seems like a bug. Most likely the implementation of ``.^`` changed.

**Comment by mlubin** [comment]
As an obvious workaround you can do
```jl
@objective(m, Min, sum(xs[i]^2 for i in 1:5))
```
