### ISSUE TITLE
writeLP does not include SOS constraints

### ISSUE THREAD

**Issue by leethargo** [JuliaOpt/JuMP.jl#867]
But solvers such as Gurobi or SCIP include them in the `.lp` output.

See also [SCIP implementation](http://scip.zib.de/doc/html_devel/reader__lp_8c_source.php#l02818).

**Comment by mlubin** [comment]
PRs welcome.

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/1118 for JuMP/MPB. Will also need to be implemented for whatever we do to write LP files under JuMP/MOI. CC @odow 

Closing for now.
