### ISSUE TITLE
Coveralls: Source not available

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/JuMP.jl#869]
I get this when trying to view a file in Coveralls [e.g.](https://coveralls.io/builds/8286309/source?filename=src%2FJuMP.jl)

```
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.
```

**Comment by mlubin** [comment]
Does codecov work?
CC @IainNZ

**Comment by blegat** [comment]
Yes codecov works

**Comment by mlubin** [comment]
Then we'll get rid of coveralls.

**Comment by blegat** [comment]
This seems fixed now :-P
