### ISSUE TITLE
Non linear modeling 

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/JuMP.jl#872]
How do I do the modeling of the following expression without running into ``parseNLExpr_runtime`` issues. 

````
f_expr = alpha[1]*2.0 # this expression can also be bilinear like alpha[1]*rho[2]
t_expr = rho[3] # can also be bilinear
# the types can be JuMP.Variable, JuMP.GenericAffExpr, or JuMP.GenericQuadExpr
@NLexpression(m, rhs, t_expr*t_expr - f_expr*f_expr)
````

**Comment by mlubin** [comment]
This is more of a usage question that should go to the julia-opt list.
Anyway, don't create QuadExpr objects, use ``@NLexpression`` to create them. For AffExpr objects you can do the same or create auxiliary variables as suggested at http://www.juliaopt.org/JuMP.jl/0.14/nlp.html#syntax-notes.
