### ISSUE TITLE
setvartype! in LPQPtoConicBridge

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/JuMP.jl#874]
I was testing Xpress.jl soc interface and the errors led me to the following:

I ended up testing the following with Gurobi:

```
using JuMP
using Gurobi

m = Model(solver = GurobiSolver())

@variable(m, x[1:5])
@objective(m, Max, x[1] + x[2] + x[3] + x[4] + 2*x[5])
@constraint(m, constrcon1, norm(x[2:5]) <= x[1])
@constraint(m, constrlin1, x[1] <= 5)
@constraint(m, constrlin2, x[1]+2*x[2] - x[3] <= 10)
@constraint(m, constrcon2, norm([2 3;1 1]*x[2:3]-[3;4]) <= x[5] - 2)

solve(m)
```

it runs just ok, but when I intercepted `solve(m)` with gallium: `breakpoint(Gurobi.setvartype!)`

I noticed that that the model has "10 rows, 13 columns and 22 nonzeros", ok, JuMP added 8 extra variables (directly in the `internalModel`) to represent the SOC.
However `setvartype!` receives as arguments the vector of type corresponding the original JuMP model without the extra variables, at this point the models are completely not synchronized JuMP has 5 cols but Gurobi has 13, and `setvartype!` is setting the type of the first 5.

I did not understand this behavior...

**Comment by mlubin** [comment]
Looks like my email reply didn't go through:

> That's correct. If the length of the vector passed to setvartype! is less than the number of variables in the model, just set the first n variable types and don't modify the types of the remaining variables.

**Comment by joaquimg** [comment]
Okay! I will fix that on Xpress. I was worried because the routine was setting variables, but I just noticed that for conic models the model is rebuilt every time, that should keep indexing okay (which was my main worry).
Well for me its okay to close it then, unless you want to keep the discussion for further modifications on jump.

**Comment by mlubin** [comment]
Don't see a need to leave this open

**Comment by mlubin** [comment]
That's correct. If the length of the vector passed to setvartype! is less
than the number of variables in the model, just set the first n variable
types and don't modify the types of the remaining variables.
