### ISSUE TITLE
constraints being ignored/removed

### ISSUE THREAD

**Issue by rb004f** [JuliaOpt/JuMP.jl#877]
I am building some fairly complicated convex quadratic constraints from data where sometimes the coefficient of the quadratic term is 0.0 (or sometimes very small).  It looks like if such a constraint is constructed, then the entire constraint ignored, even if there is other information in the constraint. 
I expect this is done to improve numerically stability, but is this overall desired behavior? Would better behavior be to just drop the close to zero atoms from the constraint, rather than the whole constraint? 

Here is some simple example code that reproduces what I see

```

using MathProgBase
using JuMP
using Gurobi
using CPLEX

gurobi_solver = GurobiSolver()
cplex_solver = CplexSolver()

# The constraint appears to be ignored because there is a 0 coefficient in the x^2 term (Gurobi)
m = Model(solver=gurobi_solver)
@variable(m, 0 <= v <= 2)
@variable(m, 1 <= x <= 5)
c = @constraint(m, v >= 0.0 * x^2 + x)
println(c)
@objective(m, Min, v)
status = solve(m)
println("Objective value: ", getobjectivevalue(m))

# The constraint appears to be ignored because there is a 0 coefficient in the x^2 term (cplex)
m = Model(solver=cplex_solver)
@variable(m, 0 <= v <= 2)
@variable(m, 1 <= x <= 5)
@constraint(m, v >= 0.0 * x^2 + x)
@objective(m, Min, v)
status = solve(m)
println("Objective value: ", getobjectivevalue(m))

# If I drop the ) * x^2 term, everything is ok
m = Model(solver=gurobi_solver)
@variable(m, 0 <= v <= 2)
@variable(m, 1 <= x <= 5)
@constraint(m, v >= x)
@objective(m, Min, v)
status = solve(m)
println("Objective value: ", getobjectivevalue(m))

# Similarly, if I make the coefficient of the x^2 term non zero, everything is ok
m = Model(solver=gurobi_solver)
@variable(m, 0 <= v <= 2)
@variable(m, 1 <= x <= 5)
c = @constraint(m, v >= 0.01 * x^2 + x)
println(c)
@objective(m, Min, v)
status = solve(m)
println("Objective value: ", getobjectivevalue(m))



```

**Comment by mlubin** [comment]
I'm not aware of any code in JuMP that could cause this, so it will likely take some digging down into the solver wrappers to figure out what's going on.

**Comment by rb004f** [comment]
Yes, I am not sure if this a solver or Jump thing. I thought at first it was a gurobui thing, but I saw the same behavior in both cplex and gurobi, so thought it might be Jump.  

If I turn on logging, I see this message pop up "Warning for adding constraints: zero or small (< 1e-13) coefficients, ignored" which helped me track down why I was seeing incorrect solutions.  I have a constraint like this

```c = @constraint(ggm.model, ql >= sum{ ggm.sets.gens[i]["heat_rate"][1]*pg[i]^2 + ggm.sets.gens[i]["heat_rate"][2]*pg[i] + ggm.sets.gens[i]["heat_rate"][3], i in generators})
```
and I can hack a fix by doing this

```
c = @constraint(ggm.model, ql >= sum{ ggm.sets.gens[i]["heat_rate"][1] == 0.0 ? 0 : ggm.sets.gens[i]["heat_rate"][1]*pg[i]^2, i in generators} + sum{ ggm.sets.gens[i]["heat_rate"][2]*pg[i], i in generators} + sum{ ggm.sets.gens[i]["heat_rate"][3], i in generators})
```

**Comment by mlubin** [comment]
Mosek reports the correct solution and that's going through the same interface as Gurobi and CPLEX, so my preliminary bet is that JuMP is passing the correct problem data. However, Gurobi's representation of the problem is not correct, as you can see from calling:
```jl
MathProgBase.writeproblem(internalmodel(m),"test.mps")
```
after solving the first model. It could be in Gurobi itself or Gurobi.jl.

**Comment by mlubin** [comment]
Well that's resolved now. We should add this as a unit test.
