### ISSUE TITLE
constraint names, better print behavior

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/JuMP.jl#880]
A typical scenario is to have a simple constraint that involves a very large number of scalar variables.  For instance
```julia
@constraint(m, ref, sum(A*x) ≥ c)
```
Sometimes it is useful to output the identification of constraints succinctly, especially when there is a huge number of them, for example after one computes the IIS.  Currently, if one prints one of these constraint references one gets a huge string of the constraint being explicitly written out in terms of components.  It would be nice if there were a better print behavior, as it is often desirable to look at which constraints are in the IIS and manually contemplate them before deciding on how to deal with them.  This is currently possible, but unless I'm missing something it's hardly elegant: to know which constraints are in my IIS I currently have to create a dictionary mapping the constraints to some easily human-parseable name, and I really don't see any way around that.
 
There are several nice possibilities, but I think by far the easiest would be to allow the user to provide a string that gives the name of the constraint.

Of course, I realize that with the way things work currently the constraints returned from computing the IIS would not retain the names they were given before they were added to the model, however with the ability to name constraints it would be trivial to just check which of the original constraints are returned after computing the IIS.  Additionally some solvers internally support the ability to name constraints, and in those cases one can preserve the names.

A really cool but more difficult to implement alternative would be to attempt to print a string showing the impression as it was originally provided to the constraint macro (so, for the above example it would be `sum(A*x) ≥ c`).  This would be very simple in many cases (maybe it would even be an appropriate default), but the possible presence of iterables in the expression might make it difficult to get this right.

**Comment by joehuchette** [comment]
We've thought a bit about this, but weren't able to come up with a more satisfactory approach than what we currently have.

> It would be nice if there were a better print behavior, as it is often desirable to look at which constraints are in the IIS and manually contemplate them

FWIW most LP/IP solvers will provide you with an IIS if you ask for it. We have this support wrapped at the solver level (e.g. [Gurobi](https://github.com/JuliaOpt/Gurobi.jl/blob/02fc617bb2efedc90f839a1832f1f8b3b3220cab/src/grb_solve.jl#L12-L19)), and could conceivably add better support at the modeling level.

> A really cool but more difficult to implement alternative would be to attempt to print a string showing the impression as it was originally provided to the constraint macro

This is actually not difficult at all, since we capture the entire expression graph in the ``@constraint`` macro. The problem is that the preferable behavior is a lot less clear when, instead of ``sum``, you have some black-box function ``random_constraint``, in which case it would be much more helpful to inspect the individual terms in the constraint, rather than the raw constraint expression.

**Comment by ExpandingMan** [comment]
Hmm... interesting.  I think I might not have been clear about my problem, however.

> FWIW most LP/IP solvers will provide you with an IIS if you ask for it.

Yes, and because of this, there is definitely a workaround (which isn't too painful).  However, suppose for example that I get the IIS back from Gurobi.  What it gives me is an integer index of which constraints are in the IIS.  With this I can do two things: either I can identify which are the IIS constraints by keeping track of the order in which I added them, or I can create `ConstraintRef` objects using the JuMP model object.  With the way things are currently, neither is really ideal for identifying to me as a human the IIS constraints if I have a large number of them.  It's hard to keep track of thousands of integers specifying a dozen different types of constraints, and if I look at the `ConstraintRef`s I will see the huge dump of explicitly expanded linear algebra.  So, in order for me to really understand which constraints are in the IIS, I create a dictionary mapping the original `ConstraintRef`s to `String` names, and then I can get human readable names back from the IIS.  This isn't really difficult, but doesn't seem quite ideal, but it certainly isn't obvious to me what is the best possible solution for this.

**Comment by joehuchette** [comment]
I've also been a little frustrated by this in the past, but I don't really have any ideas on how to make it easier. If you have some concrete suggestions, we can discuss and see about implementing them.

**Comment by ExpandingMan** [comment]
Have you looked at the idea of allowing users to (optionally) pass a string to `ConstraintRef` objects?  It definitely doesn't seem to be the most elegant solution but it'd get the job done.  The most unfortunate side-effect of this that I can see is that now `ConstraintRef` objects have to carry around strings, and with large numbers of them in memory I don't really know where this might affect performance (though my understanding is that it really shouldn't).  On the bright side, some solvers already have this functionality built-in (for example Gurobi) and in those cases the feature could be nicely implemented.  Perhaps it would even make sense to make the default name in those cases the string generated from the original constraint expression, letting the user over-ride it in cases where he implements some black-box function (because even in many of those cases displaying the constraint as `blackbox(x) >= 0` would be the desirable behavior).

Obviously you guys will be much better than me at judging which use cases are most common, but this is the only solution that I can think of that would be completely satisfactory from my perspective.  (In fact I have used the Gurobi Python API this way, and, as terrible as that API is, this particular issue was not a problem at all.)

**Comment by joehuchette** [comment]
We could conceivably store a String name for constraints, much as we do for Variables, e.g. store the name ``"foo[1]"`` for the constraint ``@constraint(m, foo[i=1:3], x >= i)``. You could then change this later via ``setname(foo, "constraint name")`` or something. I thought about this a bit in the context of computing duals for LPs. I'm still not certain I see how to use this information in printing, though. Printing ``x >= 1`` seems much more useful than ``foo[1]`` IMO.

**Comment by ExpandingMan** [comment]
> Printing x >= 1 seems much more useful than foo[1] IMO.
I completely agree, however, it is currently very common to have constraints for which the currently implemented methods won't display something so nice and beautiful (essentially any time there is an index contraction, which covers a huge class of cases).  I guess one other possibility is to detect the length of the string that prints and if it exceeds a pre-defined limit, to instead print the name of the constraint variable as you suggested.

**Comment by joehuchette** [comment]
> I guess one other possibility is to detect the length of the string that prints and if it exceeds a pre-defined limit, to instead print the name of the constraint variable as you suggested.

I'd be open to something like this. Another (not necessarily orthogonal) idea would be to print summations constructed via ``sum{}`` compactly.

**Comment by ExpandingMan** [comment]
> Another (not necessarily orthogonal) idea would be to print summations constructed via sum{} compactly.

Yes that sounds like a great idea.  I'm not very experienced with metaprogramming so I'm wondering if it would be difficult to capture all cases of this.  For example, could you capture inner products, matrix multiplications and all possible contractions of higher rank tensors?  However, even if only the simplest cases were captured (inner products and matrix multiplications), it would be a drastic improvement over current behavior.

**Comment by mlubin** [comment]
Constraints have names now in JuMP/MOI (still missing a bit of infrastructure to work with them: https://github.com/JuliaOpt/JuMP.jl/issues/1184). I'm not sure if all of the issues raised here are resolved, but the discussion is now stale. Please open a new issue if needed.
