### ISSUE TITLE
How to write t(X) * diag(omega) * X using NLexpression?

### ISSUE THREAD

**Issue by yinsenm** [JuliaOpt/JuMP.jl#881]
I read the documentation for NLexpression and it said that a matrix–vector product will not work inside a call to the `@NLconstraint` macro. 

If I define a variable omega as a size n vector as followed, `@variable(m, omega[1:n]);` and X is a data matrix of size n by p. How can I add a nonlinear expression of X' * diagm(omega) * X to the model?
I tried `@expression(m, XtOmegaX, X' * diagm(omega) * X);` but it gives me errors when I add some other nonlinear constraints.

I also tried `@expression(m, XtOmegaX[i = 1:p, j = 1:p], X' * diagm(omega) * X[i,j] );` but it is not correct either. Is there any hint for such a nonlinear expression?

Thank you so much!

**Comment by mlubin** [comment]
At the moment the best way is to write it directly in terms of scalar operations, no ``diagm`` or matrix-vector products.

**Comment by yinsenm** [comment]
I figured out an equivalent code could be 
`@NLexpression(m, XtOmegaX[i = 1:p, j = 1:p], sum{stat.X'[i,k] * omega[k] * stat.X[k, j], k = 1:n});`
Thank you for your hint!
