### ISSUE TITLE
Anonymous single non-linear expression

### ISSUE THREAD

**Issue by kaarthiksundar** [JuliaOpt/JuMP.jl#885]
I am trying to create a single anonymous NLexpression using the following command

````
m = Model()
fexpr = Array{Any,1}(2)
@variable(m, x[1:5])
fexpr[1] = @NLexpression(m, [1], x[1]*x[2]*x[3])
fexpr[2] = @NLexpression(m, [1], x[2]^4)

@NLconstraint(m, cons, fexpr[1]^2+fexpr[1]+fexpr[2] == 0)
````
The last command throws an error because ``fexpr[1]`` is of type ``JuMP.JuMPArray{JuMP.NonlinearExpression,1,Tuple{Int64}}``. Hence, in this case, ``@NLconstraint(m, cons, fexpr[1][1]^2+fexpr[1][1]+fexpr[2][1] == 0)`` would work. How does one avoid doing this and make ``@NLconstraint(m, cons, fexpr[1]^2+fexpr[1]+fexpr[2] == 0)`` work by creating proper single anonymous expression and store its reference?

**Comment by mlubin** [comment]
I'm not sure we have a proper syntax for single anonymous nonlinear expressions. ``[1]`` creates an expression indexed by the iterable object ``1``, which is why you get a collection of expressions returned.
