### ISSUE TITLE
missing colNames in function()

### ISSUE THREAD

**Issue by jac0320** [JuliaOpt/JuMP.jl#886]
So it seems like m.colNames will lose track of some of the variable names if called under a function.
I was trying to obtain this name-based vector for me to generate a master-x-symbol-vector for cut generation.

This what I tried first:
julia> using JuMP

julia> m=Model()
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver is default solver

julia> @variable(m,x[1:5])
@5-element Array{JuMP.Variable,1}:
 x[1]
 x[2]
 x[3]
 x[4]
 x[5]

julia> @variable(m,eta)
eta

julia> m.colNames
6-element Array{String,1}:
 "x[1]"
 "x[2]"
 "x[3]"
 "x[4]"
 "x[5]"
 "eta" 

If I put all these process into a function, the colNames only keeps the single variables.
julia> using JuMP

julia> function foo()
           m = Model()
           @variable(m, x[1:5])
           @variable(m, eta)
           return m
       end
foo (generic function with 1 method)

julia> m = foo()
Feasibility problem with:
 * 0 linear constraints
 * 6 variables
Solver is default solver

julia> m.colNames
6-element Array{String,1}:
 ""   
 ""   
 ""   
 ""   
 ""   
 "eta"

Is there an issue? Or am I doing this wrong?

**Comment by mlubin** [comment]
Use ``getname``. ``colNames`` is an internal field which we make no promises about.
