### ISSUE TITLE
MethodError when matrix-multiplying transpose of sparse matrix

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/JuMP.jl#887]
I get the following error when attempting to matrix-multiply a constant (in this case integer) vector by the transpose of a sparse matrix of variables i.e.
```julia
x'*v
```
where `v` is a constant, `Int64`-valued vector.

```
ERROR: MethodError: no method matching Ac_mul_B!(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::SparseMatrixCSC{JuMP.Variable,Int64}, ::Array{Int64,1}, ::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Array{JuMP.GenericAffExpr{Float64,JuMP.Variable},1})
Closest candidates are:
  Ac_mul_B!(::Number, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Number, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/linalg.jl:51
  Ac_mul_B!(::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/linalg.jl:97
  Ac_mul_B!(::AbstractArray{T,1}, ::Union{AbstractArray{T,1},AbstractArray{T,2}}, ::AbstractArray{T,1}) at linalg/matmul.jl:123
  ...
 in Ac_mul_B(::SparseMatrixCSC{JuMP.Variable,Int64}, ::Array{Int64,1}) at ./sparse/linalg.jl:85
```

This seems very strange to me because `x*w` works perfectly fine.

A workaround is available by doing 
```julia
(v'*x)'
```

**Comment by blegat** [comment]
Could you give a code that fails ?
For me, this code works on master
```
m = Model()
@variable(m, x)
@variable(m, y)
X = sparse([1, 3], [2, 3], [x, y])
@show typeof(X)
@show X
v = 2
Y = X' * v
@show typeof(Y)
@show Y
```

**Comment by ExpandingMan** [comment]
Like I said, v should be a vector, so the following code
```julia
m = Model()
@variable(m, x)
@variable(m, y)
X = sparse([1, 3], [2, 3], [x, y])
@show typeof(X)
@show X
v = [2, 2, 2]
Y = X' * v
@show typeof(Y)
@show Y
```
Crashes with the same error I quoted.

**Comment by ExpandingMan** [comment]
For anyone else that this is making crazy, one thing you can do as a really quick and dirty "fix" is define
```julia
import Base.*
import JuMP.*

function *{T<:JuMP.Variable, Ti<:Integer}(v::Vector, x::SparseMatrixCSC{T, Ti})
    squeeze((v'*x)', 2)
end

function *{T<:JuMP.GenericAffExpr, Ti<:Integer}(v::Vector, x::SparseMatrixCSC{T, Ti})
    squeeze((v'*x)', 2)
end
```
However, be **warned** that this does *not* conform with the standard Julia multiplication behavior, which would require left-multiplied vectors to be transposed.  Even worse, it still crashes sometimes depending on how the `JuMP.GenericAffExpr` are formed (seems to always be safe on `JuMP.Variable`).  But it will save you from having to write some pretty horrendous looking expressions right into your constraints...

Hopefully if I get some time I'll work on a version of [Einsum.jl](https://github.com/ahwillia/Einsum.jl) that works on sparse matrices, which may or may not bypass this issue altogether.

**Comment by blegat** [comment]
I think that this is an issue in Julia Base.
If you do
```julia
type A
    x
end
import Base.*, Base.+
(*)(a::A, b::A) = A(a.x*b.x)
(*)(a::A, b) = A(a.x*b)
(*)(a, b::A) = A(a*b.x)
(+)(a::A, b::A) = A(a.x+b.x)
(+)(a::A, b) = A(a.x+b)
(+)(a, b::A) = A(a+b.x)
X = sparse([1, 3], [2, 3], [A(1), A(2)])
v = [2, 2, 2]
import Base.zero
zero(::Type{A}) = A(0)
X * v
```
you get
```
ERROR: MethodError: no method matching A_mul_B!(::Int64, ::SparseMatrixCSC{A,Int64}, ::Array{Int64,1}, ::A, ::Array{A,1})
Closest candidates are:
  A_mul_B!(::Number, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Number, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/linalg.jl:51
  A_mul_B!(::Number, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::AbstractSparseArray{Tv,Ti,1}, ::Number, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/sparsevector.jl:1466
  A_mul_B!(::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::SparseMatrixCSC{Tv,Ti<:Integer}, ::Union{Base.ReshapedArray{T,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,1},DenseArray{T,2},SubArray{T,1,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at sparse/linalg.jl:96
  ...
```
so you see that `A_mul_B!` has sort of only been defined if the first and fourth arguments are `Number`s.
So either they expect you to define `A_mu_B!` every time you define a new type or they are missing a definition in Julia Base.

**Comment by ExpandingMan** [comment]
Ouch.  This is actually a very frustrating problem.  The error is slightly different though, one is `Ac_mul_B!` the other is `A_mul_B!`, though I suspect you are probably right.  

By the way, if you guys who are experts on JuMP know of a more effective work-around, it would be greatly appreciated in the meantime.  I haven't been able to think of anything more effective than what I posted above.

**Comment by ExpandingMan** [comment]
Hmm... so it seems there are quite a few problems here.  To make a long story short it seems that sparse matrix multiplication for sparse matrices of user types isn't implemented (at least not fully) and it is up to users to do it.  Indeed, I don't yet fully understand what is in [operators.jl](https://github.com/JuliaOpt/JuMP.jl/blob/66379c4cd9e58eae30ce307fa9618aa9711ab452/src/operators.jl) but it seems that the original authors of JuMP manually implemented sparse matrix multiplication (which fails when one of the matrices is transposed, for reasons I don't understand).

Another thing worth mentioning is that for some reason, in the code you wrote above, if you instead do `X' * v` you get 
```
ERROR: LoadError: MethodError: no method matching one(::Type{Any})
Closest candidates are:
  one(::BitArray{2}) at bitarray.jl:413
  one(::Number) at number.jl:63
  one{T<:Number}(::Type{T<:Number}) at number.jl:64
  ...
 in Ac_mul_B(::SparseMatrixCSC{A,Int64}, ::Array{Int64,1}) at ./sparse/linalg.jl:85
 in include_from_node1(::String) at ./loading.jl:488
while loading /home/savastio/src/prodbug.jl, in expression starting on line 23
```
which is again strange because it is not the same error we got with the JuMP variables.  So, I'm confused.  I don't see any issues about this in Julia base, so I'm going to raise one when I have the time to put my thoughts together on it.

**Comment by ExpandingMan** [comment]
Ok, I've been doing some reading and some thinking, and I think I understand the situation somewhat better now, though the result isn't too happy.  Matrix operations in Julia are not generic in the sense that there is no default implementation for them for user defined types.  It is up to the user to define all matrix operations.  One reason it is not possible to have built-in matrix code for user types is because it requires special knowledge about the ring operators `*, +` on types: Julia Base cannot infer the type of `*(A::Matrix{UserType}, B::Matrix{UserType})` until runtime.  Perhaps there should be a way of doing that, but that doesn't necessarily mean that matrix operations should be defined in the first place.

The best solution I think is to write macros which allow users to generate generic code for matrix operations.  Regardless, for JuMP's case I think it means that somebody with the know-how needs to write all the necessary matrix operation code, and right now some of it is missing.  At some point I'll take a crack at it, but I don't know how good my solution will be.

**Comment by ExpandingMan** [comment]
Ok, after what was obviously a ton of confusion on my part, I've discovered what the problem is with this.

It appears to be a simple JuMP bug, `Vector` is omitted in a list where it should be included.  In operators.jl, lines 406, 407 and 408 should read
```julia
(*){T<:JuMPTypes}(             A::Union{Matrix{T},Vector{T},SparseMatrixCSC{T}}, x::Union{Matrix,   Vector,   SparseMatrixCSC})    = _matmul(A, x)
(*){T<:JuMPTypes,R<:JuMPTypes}(A::Union{Matrix{T},Vector{T},SparseMatrixCSC{T}}, x::Union{Matrix{R},Vector{R},SparseMatrixCSC{R}}) = _matmul(A, x)
(*){T<:JuMPTypes}(             A::Union{Matrix,   Vector, SparseMatrixCSC},    x::Union{Matrix{T},Vector{T},SparseMatrixCSC{T}}) = _matmul(A, x)
```
In master, `Vector` does not appear in the list for the first argument.  As far as I can tell, methods for the first argument being `Vector` are fully implemented, but were simply omitted in these definitions.  

In case you are worried about this causing `v*w` to be defined where `v` and `w` are both `Vector`, this isn't really a problem because `_matmul` throws and entirely appropriate "Incompatible Sizes" error.

I think `SparseVector` should also appear in both sides of that list, but I haven't tested it.

There is however another problem where sparse matrix multiplication isn't implemented correctly and takes forever (see #907), but this is a more complicated issue, and I'm still trying to figure it out.

**Comment by mlubin** [comment]
@ExpandingMan, seems like you're on the right track. Would you mind turning this fix into a PR with appropriate new tests?

**Comment by ExpandingMan** [comment]
Ok, the pull request is up, with unit tests.

I'm wondering, does anyone happen to know if there has been any talk about boiler-plate code generation for sparse matrices in `Base` (or wherever sparse matrices ultimately wind up)?

In light of the discussion I was having with myself above, I see that it isn't super simple to define this in a uniform way, but it would be really nice if there were some macros exposed in `Base` for helping with this kind of code generation, because as things are right now it is really complicated for someone to have to define all the sparse matrix operations on a custom type.  Perhaps it's worth raising a suggestion issue over there?
