### ISSUE TITLE
vecnorm with generator syntax

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#892]
I am getting confused having to switch between `norm`, `norm2`, and `vecnorm` when I'm using generator syntax and JuMP. Julia 0.5 supports `vecnorm(i for i in 1:5)` so I think it makes sense to deprecate JuMP-specific `norm2` and use `vecnorm` for JuMP types. Then later Julia will allow `norm(i for i in 1:5)` (see https://github.com/JuliaLang/julia/issues/19289) and that is all we should ever need.

**Comment by mlubin** [comment]
Makes sense

**Comment by mlubin** [comment]
``norm2`` was originally a parsing workaround for the curly syntax, so definitely not needed anymore.

**Comment by mlubin** [comment]
Do we still need ``vecnorm`` if ``norm`` works directly?

**Comment by chriscoey** [comment]
No, but in order to have consistency between JuMP and Julia syntax, maybe you could go into Julia and implement generator syntax for `norm`? See https://github.com/JuliaLang/julia/issues/19289).

**Comment by mlubin** [comment]
I'll leave that up for grabs
