### ISSUE TITLE
JuMP is ignoring callbacks if using a conic solver

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#893]
`registercallbacks` is only called if `!conic`: https://github.com/JuliaOpt/JuMP.jl/blob/308419802afa956e76429a68702e846132c6116b/src/solvers.jl#L395

from @mlubin: if it didn't ignore callbacks we'd get an explicit error for the missing method in `lpqp_to_conic`

@joehuchette this is needed for MISDP

**Comment by chriscoey** [comment]
related to #878 maybe

**Comment by mlubin** [comment]
I think we'll first need to implement the callbacks in ``lpqp_to_conic`` so that we can test using callbacks with gurobi/cplex as MISOCP solvers

**Comment by chriscoey** [comment]
can this be closed yet?

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/JuMP.jl/pull/894
