### ISSUE TITLE
more user-friendly functions for macro calls

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/JuMP.jl#897]
Sometimes it is desirable to embed parts of JuMP in a larger code base for some reason.  For example, I frequently encounter large-scale linear and quadratic optimization problems which require JuMP variables to be embedded in sparse matrices.  As things are right now, it can be extremely difficult to write code for doing that in a generic way.  For example, it is very hard to have a generic way of specifying the shape of variable tensors created with the `@variable` macro.  Currently my workaround is to stick my code inside other `helper` macros, but really the right way to do this would be to just write a macro that calls the same methods that `@variable` does.  Obviously it's already possible to do this, but the expressions output by the macros in JuMP are quite obtuse, and it would take me quite a lot of work to figure out how to write my own.

I realize that nobody is going to go in and change all the function calls required for macros, but I thought that it might be nice going forward, if any changes really are made to the internal workings of the macros, to consider that users might want to write their own.  Really sparse matrices are the only big pain point that I can think of in declaring variables and constraints at the moment.  As it sits right now, it requires an awful lot of boiler-plate code to specify sparse variables.

**Comment by mlubin** [comment]
What do you mean by JuMP variables embedded in a sparse matrix? If you want a sparse matrix of variables you can do something like:
```jl
sparse(I,J,[@variable(m) for i in 1:length(I)])
```

**Comment by ExpandingMan** [comment]
Embarrassingly, I wasn't even aware that call existed (a case of RTFM).  I kept trying to assign entire blocks (which would be easier, but impossible to write generically).  I'm definitely concerned about the performance limitations of a huge number of repeated calls to `@variable`, especially if I need to set bounds and names.  I'll give it a shot and see how it performs.

**Comment by mlubin** [comment]
There are no performance limitations of repeated calls to ``@variable``, especially if you're just creating scalar variables.

**Comment by ExpandingMan** [comment]
It seems to go through a lot of code to parse its arguments (granted it mostly just goes through if constructs), so I wasn't sure, it'll have to be called millions of times, but I'll see how it works, thanks.

It still seems like a bit of an issue to me that the variable and constraint code isn't more generic.  It's hard to foresee every possible use case, and there are some surprising difficulties with passing function arguments to macros, though it might just be another case of my not being knowledgeable enough about it.

**Comment by mlubin** [comment]
The parsing step only happens once per each time that the macro call appears in a line of source code. You can call it a million times in a loop without any issue at all.

**Comment by ExpandingMan** [comment]
Ohhh... I see.  Yeah that's great, thanks.  

Ok, I'll close this issue since now it seems to me like in the worst case scenario there's nothing stopping you from just assigning individual variables in huge loops, that pretty much solves any of the types of problems I can think of.

Sorry, should have read up on this stuff more before posting an issue.
