### ISSUE TITLE
make it easier to run JuMP's tests for a specific (nondefault) solver

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#901]
CC @tkelman 
Ref #849

**Comment by tkelman** [comment]
Make the solver list variables from testsolver.jl JuMP module level globals? That way you could import JuMP, include test/solvers.jl, then push to the lists before including other test files.

**Comment by mlubin** [comment]
@tkelman, you can basically already do that: https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/test/runtests.jl

**Comment by mlubin** [comment]
Also closed vacuously. JuMP doesn't have any tests for solvers anymore. MathOptInterfaceTests is meant for testing solvers.
Potentially related: https://github.com/JuliaOpt/JuMP.jl/issues/1175
