### ISSUE TITLE
number of parallel threads invoked by CPLEX parallel optimizer not working

### ISSUE THREAD

**Issue by CBongiova** [JuliaOpt/JuMP.jl#904]
Dear all,

I have included callbacks in my JuMP function, which in return turns off parallel processing in CPLEX. 
Having a look online, I found I can invoke the **CplexSolver** and set **CPX_PARAM_THREADS=4**. This parameter specifies how CPLEX should bind threads to cores on platforms where CPLEX supports binding threads to cores ( see https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.6.3/ilog.odms.cplex.help/CPLEX/Parameters/topics/Threads.html) 

Nevertheless, when I then run my runfile I get the following message: 

**"Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64f645ea -- jl_gc_pool_alloc at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gc.c:832
while loading C:\Users\bongiova\Desktop\Scripts_Julia\EDARP\run.jl, in expression starting on line 13"**

where my expression starting on line 13 is just the following:

**model.solveEDARP("C:/Users/bongiova/Desktop/Scripts_Julia/EDARP/mor2-16.txt",solver=CplexSolver(CPX_PARAM_CUTSFACTOR=1,CPX_PARAM_THREADS=4),valid=true)**

(where solveEDARP(path; relax=false, solver=CplexSolver(), valid::Bool = true) is my function containing the optimization model in JuMP)

Does anyone have an idea about what is going on? Is this a Julia bug? 

![screenshot 48](https://cloud.githubusercontent.com/assets/24223801/20666727/091c0d9c-b566-11e6-9a93-8ac24c88f448.png)

**Comment by joehuchette** [comment]
Yes, it appears that julia and CPLEX's multithreading are not interacting properly. What version of Julia/JuMP/CPLEX are you using?

**Comment by CBongiova** [comment]
Hi joehuchette, 
Thanks for your answer! I am using julia 0.5.0 (the latest release) with cplex version 12.6.2.0. My JuMP version is 0.14.1

**Comment by joehuchette** [comment]
Could you post a minimal reduction of your code that completely reproduces the problem

**Comment by CBongiova** [comment]
[Joehuchette.zip](https://github.com/JuliaOpt/JuMP.jl/files/617271/Joehuchette.zip)
Hi Joehuchette, 

Please find a runfile (where I set the CPLEX multithreading), readfile (where I read the data in the text file), and a reduced version of my model. You just need to include the run to see the problem. 

Thanks! 

[Joehuchette.zip](https://github.com/JuliaOpt/JuMP.jl/files/617281/Joehuchette.zip)

**Comment by mlubin** [comment]
http://www.ibm.com/support/knowledgecenter/SSSA5P_12.6.2/ilog.odms.cplex.help/CPLEX/UsrMan/topics/progr_adv/callbacks_adv/05_thread_safety.html

> It is then the responsibility of the user to implement that control callback in such a way that the callback is thread-safe.

I wouldn't expect this to work at all in Julia, would need some deep technical work to understand and correctly fix the issue. You could try using Gurobi which doesn't require its callbacks to be thread safe.

Anyway we ought to display a warning in CPLEX.jl if you use threads and callbacks until this is resolved.

**Comment by CBongiova** [comment]
Thanks, multithreading seems to be working fine in Gurobi.

**Comment by mlubin** [comment]
Closed in favor of https://github.com/JuliaOpt/CPLEX.jl/issues/98
