### ISSUE TITLE
Update for ForwardDiff 0.3

### ISSUE THREAD

**Issue by finmod** [JuliaOpt/JuMP.jl#905]
Pkg.update() including JuMP warns of conflicting requirements for ForwardDiff and errors on ReverseDiffSparse with: fixed packages introduce conflicting requirements for ReverseDiffSparse

**Comment by mlubin** [comment]
We need to update to ForwardDiff 0.3, but this should not cause any conflicting requirements unless you've manually checked out certain package versions.
