### ISSUE TITLE
addition operator warning during matrix operations

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/JuMP.jl#907]
Normal matrix multiplication of a sparse matrix of variables applied to a vector
```julia
X*v
```
generates the following warning when `X` is sufficiently large (in my case about 5*10^6 non-zero entries) 
```
WARNING: The addition operator has been used on JuMP expressions a large number of times. This warning is safe to ignore but may indicate that model generation is slower than necessary. For performance reasons, you should not add expressions in a loop. Instead of x += y, use append!(x,y) to modify x in place. If y is a single variable, you may also use push!(x, coef, y) in place of x += coef*y.
```
This seems non-ideal.  Since `*` of a matrix of JuMP variables is a method of JuMP, shouldn't it just use the most efficient method available?

I have tested this on a dense matrix with approximately the same number of (non-zero) elements, and it is quite fast and does not generate a warning, so this appears to only be an issue with dense matrices (unless it somehow has to do with the matrix size).

**Comment by mlubin** [comment]
We would welcome a contribution of an efficient specialized implementation. By default we fallback on Julia's generic implementations which are not efficient for working with JuMP expression objects.

**Comment by ExpandingMan** [comment]
I see.  I've been looking into this and it actually seems to be rather a huge amount of work, which is probably what it hasn't been done (there are other problems with sparse matrices as well, #887 has been rather a big problem for me).

I'm not sure I have the expertise to do a really perfect job on this, but I'm going to experiment with it today, as all these have been ongoing issues for me.  Will post here again if I make progress.

**Comment by ExpandingMan** [comment]
Ok, I'm definitely learning a lesson about not putting the *complete* code I used to get the error or warning in the issue reports.

I could have sworn that I was getting this from matrix multiplication alone, but for some reason today I can only reproduce it within a macro.

```julia
using JuMP

const m = 100
const n = 100

const M = 60000
const N = 60000

model = Model()

X = spzeros(Variable, M, N)
i, j = 1, 1
while (i + m - 1 ≤ M) && (j + n - 1 ≤ N)
    X[i:(i+m-1), j:(j+n-1)] = @variable(model, [1:m, 1:n])
    i += m
    j += n
end

u = rand(N)
v = rand(N)

@constraint(model, X*u .≥ X*v)
```
The last line produces the addition warning.  The macro expansion is the following
```
quote  # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 243:
    (JuMP.validmodel)(model,:model) # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 244:
    begin  # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 465:
        begin  # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 399:
            #12#q = (JuMP.zero)(JuMP.AffExpr) # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 400:
            begin 
                begin 
                    #13###280 = (JuMP.addtoexpr_reorder)(#12#q,X,u)
                end
                begin 
                    #14###279 = (JuMP.addtoexpr_reorder)(#13###280,-1.0,X,v)
                end
            end # /home/savastio/.julia/v0.5/JuMP/src/macros.jl, line 401:
            #15###278 = (JuMP.addVectorizedConstraint)(model,(JuMP.constructconstraint!)(#14###279,:(>=)))
        end # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 466:
        !true && (JuMP.registercon)(model,Symbol("##277"),#15###278) # /home/user/.julia/v0.5/JuMP/src/macros.jl, line 467:
        #15###278
    end
end
```
It certainly isn't obvious to me what in this macro is causing the warning, but I'm going to look through it a bit and try to figure it out.

**Comment by ExpandingMan** [comment]
Ok, I have definitely tracked down the problem, but am not yet entirely sure how to fix it.  In parseExpr_staged.jl line 271 currently reads
```julia
addtoexpr(ex, c, x) = ex + c*x
```
I believe that this should basically be 
```julia
addtoexpr(ex, c, x) = append!(ex, c*x)
```
which seems to fix the above example (it's faster and it doesn't throw a warning), but if you then run the macros unit tests there are 4 method errors arising from instances where `append!` isn't defined for some argument types.  I'm not sure whether it'll be necessary to create new `append!` methods or if it will suffice to just create a single new, specific method for `addtoexpr`.

By the way, can somebody explain to me why `+` doesn't *always* call the most efficient method?  My current understanding is that it has something to do with the specific solver API's, because I know that a lot of them annoyingly have this sort of behavior, and I'm thinking maybe JuMP is just inheriting that.

**Comment by mlubin** [comment]
```jl
addtoexpr(ex, c, x) = ex + c*x
```
is meant to be the generic fallback. If you know that ``append!`` is implemented and works for a particular type ``T`` you can implement a more specific method.
```jl
addtoexpr(ex::T, c, x) = append!(ex, c*x)
```

> By the way, can somebody explain to me why + doesn't always call the most efficient method?

Because nobody has been sufficiently motivated yet to make it do so?

**Comment by ExpandingMan** [comment]
Ok, it is definitely possible to put in a more specific method that fixes the warning but it really isn't much faster.

I'm starting to think that this warning should just be removed.  Please compare the code for `append!` to the code for `+`
```julia
function Base.append!{C,V}(aff::GenericAffExpr{C,V}, other::GenericAffExpr{C,V})
    append!(aff.vars, other.vars)
    append!(aff.coeffs, other.coeffs)
    aff.constant += other.constant
    aff
end

(+){C,V<:JuMPTypes}(lhs::GenericAffExpr{C,V}, rhs::GenericAffExpr{C,V}) = (operator_warn(lhs,rhs); GenericAffExpr(vcat(lhs.vars,rhs.vars),vcat(lhs.coeffs, rhs.coeffs),lhs.constant+rhs.constant))
```
So the difference (at least for these argument types) is only that `+` makes a copy and `append!` is in-place.  Sure, that means `append!` is likely to be slightly faster, but doesn't that just mean that they are different use cases?  If they are different use-cases, does it really make sense to have a warning?  It seems to me that the design of JuMP should be such that the user is *only* ever expected to use `+`, because its most powerful feature is the ability to write code algebraically.

By the way, I fixed this by adding the following to parseExpr_staged.jl
```julia
function addtoexpr{T<:GenericAffExpr}(ex::Array{T}, c::AbstractArray, x::AbstractArray) # method for when c*x is some sort of matrix product
    p = c*x
    @assert length(p) == length(ex) "Length of array of new terms must equal length of array of old terms."
    append!.(ex, p)
end
```
Yes, this has different behavior from the existing `ex + c*x` which makes a copy, but all of the other `addtoexpr` seem to use `append!` (without doing any deep-copying of course) so I think this is appropriate.  It seems to be passing all unit tests.

Let me know what you think about this, and I'll make a pull request if it's appropriate, or if it's easier you can just add it yourself.
