### ISSUE TITLE
Generic solver preferences

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#91]
I don't really care which solver JuMP uses a lot of the time, but if I want to set fairly generic options I need to specify a solver just to do so. The one I'm thinking of right now is some option about how much it prints to the console, but I think MIPGap falls in this category too. This could be implemented using a keyword argument to Model, and a new function in MathProgBase - solvers would honour as many options as they want however they want.

**Comment by mlubin** [comment]
This is available to a limited extent via ``setparameters!`` in the MPB interface. The only real motivation for addressing this issue is for solvers which use solvers (e.g., Pajarito).

**Comment by odow** [comment]
Ref the discussion in MOI https://github.com/JuliaOpt/MathOptInterface.jl/issues/61

**Comment by mlubin** [comment]
MOI has a number of solver-independent options, e.g., http://www.juliaopt.org/MathOptInterface.jl/v0.9/apireference/#MathOptInterface.Silent. We don't have MIPGap, but I think it's safe to close this anyway because the infrastructure is in place to add more options as we need them.
