### ISSUE TITLE
Faster way to add constraints?

### ISSUE THREAD

**Issue by kibaekkim** [JuliaOpt/JuMP.jl#911]
I am wondering if there is a faster way to add the following constraints. This seems taking long time (more than 1 hour; quitted after 1 hour).
```julia
@constraint(m, cons[v=V,i=I; haskey(B,(v,i)) == true], sum{x[e], e=E; e[1] == v && e[2] == i} - sum{x[e], e=E; e[1] == v && e[3] == i} == B[v,i])
@constraint(m, cons[v=V,i=I; haskey(B,(v,i)) == false], sum{x[e], e=E; e[1] == v && e[2] == i} - sum{x[e], e=E; e[1] == v && e[3] == i} == 0)
```
where |I| > 80000 and |V| = 200.

**Comment by mlubin** [comment]
Yes, loop through the existing keys/edges directly instead of looping through all possible combinations and checking if they exist, just as you would if you were writing an algorithm on the graph. JuMP does not do any magic here.
