### ISSUE TITLE
`MethodError` when multiplying sparse matrices of `Variable`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaOpt/JuMP.jl#912]
The following code
```julia
m = Model()
@variable(m, X11)
@variable(m, X23)
X = sparse([1, 2], [1, 3], [X11, X23], 3, 3)
X*X
```
Causes the following error to be thrown on the last line
```
ERROR: MethodError: *(::SparseMatrixCSC{JuMP.Variable,Int64}, ::SparseMatrixCSC{JuMP.Variable,Int64}) is ambiguous. Candidates:
  *{Tv,Ti}(A::SparseMatrixCSC{Tv,Ti}, B::SparseMatrixCSC{Tv,Ti}) at sparse/linalg.jl:125
  *{T<:Union{JuMP.AbstractJuMPScalar,JuMP.GenericNormExpr{2,Float64,JuMP.Variable},JuMP.GenericNorm{P,Float64,JuMP.Variable},JuMP.NonlinearExpression},R<:Union{JuMP.AbstractJuMPScalar,JuMP.GenericNormExpr{2,Float64,JuMP.Variable},JuMP.GenericNorm{P,Float64,JuMP.Variable},JuMP.NonlinearExpression}}(A::Union{Array{T,2},SparseMatrixCSC{T,Ti<:Integer}}, x::Union{Array{R,1},Array{R,2},SparseMatrixCSC{R,Ti<:Integer}}) at /home/user/.julia/v0.5/JuMP/src/operators.jl:406
```
Note that this is among a number of existing problems with sparse matrices (see #887 and #907).  The solution to #887 will not fix this.

**Comment by mlubin** [comment]
Thanks for reporting. A fix is just to implement a more specific method to avoid the ambiguity warning.

**Comment by ExpandingMan** [comment]
I actually tried doing that as part of #908, but I couldn't get it to work.  I'm going to have to carefully think about the type graph and try again.  There is a problem that comes up in a similar context that seems to have a completely different cause, so I'm going to post it in a separate issue.
