### ISSUE TITLE
Exception error when using callbacks with Gurobi

### ISSUE THREAD

**Issue by CBongiova** [JuliaOpt/JuMP.jl#925]
I am currently using callbacks in a branch-and-cut framework for a MILP. I am using Gurobi because Cplex seems to have issues is multi-threading when using callbacks. Nevertheless, from times to times I get the following error while running my code: 
```
**WARNING: Method definition 

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffbacb77c0d -- GRBsetdblparam at C:\gurobi701\win64\bin\gurobi70.DLL (unknown line)
while loading C:\Users\bongiova\Desktop\Scripts_Julia\EDARP\run.jl, in expression starting on line 19**
```
I don't always get this error, when this occurs I normally clear the console and run it again (most of the times the exception does not re-appear). 
What is this error due to? Is this due to a compatibility issue between julia and gurobi?

Please find a reduced version of my code attached.
Thanks for your help!
[example_code.zip](https://github.com/JuliaOpt/JuMP.jl/files/660767/example_code.zip)

**Comment by mlubin** [comment]
You may try contacting Gurobi support and opening an issue at Gurobi.jl. This very likely not an issue with JuMP itself.
