### ISSUE TITLE
calling getvalue on a subset of decision variables

### ISSUE THREAD

**Issue by CBongiova** [JuliaOpt/JuMP.jl#926]
Hi, 

Is it possible to use `getvalue(x[a,b,c])` where `a`, `b` and `c` are vectors? Or can I only retrieve such values through for loops? For example, say that `a=[1 2]`, `b=[13 36 48]`, `c=`all possible nodes in the 3rd dimension -- in matlab it would be :

Thanks!

**Comment by mlubin** [comment]
If ``x`` is plain Julia array with 1-based indices then you're free use Julia syntax to take slices. Slicing other kinds of arrays is not yet supported. See https://github.com/JuliaOpt/JuMP.jl/issues/851 and https://github.com/JuliaOpt/JuMP.jl/issues/643.
