### ISSUE TITLE
verify_ownership() not being called during expression construction

### ISSUE THREAD

**Issue by ktarplee** [JuliaOpt/JuMP.jl#932]
The below code generates an error when solve(m) is called but it is detectable when @objective is called because x is a variable that does not belong to model m (it belongs to m_old).

```
using JuMP

m_old = Model()
@variable(m_old, 0 <= x <= 2 )

m = Model()
@variable(m, 0 <= y <= 30 )

@objective(m, :Max, 5x + 3*y )
@constraint(m, 1x + 5y <= 3.0 )

print(m)
solve(m)
@show(getobjectivevalue(m))
```

The reason I bring this up is to determine if this is a defect or the desired behavior.  If it is a defect then I would be happy to submit a pull request to ensure that all variables in expressions belong to the same model as the expression itself.  

StructJuMP.jl current depends on this behavior.  Each StructuredModel call creates it's own JuMP.Model that mixes variables from various models in the objectives and constraints of the subproblems (scenarios).

**Comment by mlubin** [comment]
This is intentional, to allow for use cases like StructJuMP.

**Comment by ktarplee** [comment]
OK, then is there a mechanism to change the model to which a variable belongs?

**Comment by mlubin** [comment]
It's not necessarily a well defined operation, but see https://github.com/JuliaOpt/JuMP.jl/blob/7c4ab9e70a7b08cd84ffd00bb84add4470151101/src/JuMP.jl#L476

**Comment by ktarplee** [comment]
Awesome.  So I can copy the variable into a new model but how do I go about updating the expression (such as part of a linear constraint) that references the old (wrong) instance of the variable?

**Comment by mlubin** [comment]
You don't, really. Why do you want to do that?

**Comment by ktarplee** [comment]
I really just want to solve stochastic linear programing problems with JuMP.  I would like to convert then to the deterministic equivalent LP then solve with something like Clp or Cbc.  I looked at StructJuMP and I like the interface but the solvers are overkill for what I need at the moment.  I have written my own code with JuMP to solve two-stage problems but I want to make it more flexible.

**Comment by mlubin** [comment]
The "correct" way is to use something like StructJuMP to model the problem and then have a layer that converts the structured model into the deterministic equivalent at the matrix level. The [Benders](https://github.com/StructJuMP/StructJuMP.jl/blob/master/src/BendersBridge.jl) example code might be helpful. This is outside the scope of the JuMP issue, we can continue on discourse or if it's development focused, at https://gitter.im/JuliaOpt/JuMP-dev.

**Comment by ktarplee** [comment]
That is the approach I have been taking so far. I wanted to make sure I was not using a feature from JuMP that was unintentional.  Thanks for your help.
