### ISSUE TITLE
Support for Base.OneTo(3)

### ISSUE THREAD

**Issue by colinfang** [JuliaOpt/JuMP.jl#933]
Shall we support `Base.OneTo` now that it becomes commonly used in `Base`.

```
m = Model()
@variable(m, 0 <= x[Base.OneTo(3), 1:2] <= 3, Int)

0≤x i,j≤3,∈ℤ,∀i∈{1,2,3},j∈{2}

@constraint(m, sum(x[:, 1]) == 1)
Failed attempt to index JuMPArray along dimension 1: Colon() ∉ Base.OneTo(3)
```

**Comment by mlubin** [comment]
What's the point of this if you can write ``1:3``?

**Comment by colinfang** [comment]
I want to define variables/constraints programmatically. I used to do it like the following because Julia recommends `eachindex(x)` over `1:length(x)`. However after v0.5 the former returns `OneTo`

```
idx = eachindex(3:5)
@constraint(m, sum(x[:, 1]) == 1)
```

**Comment by mlubin** [comment]
``idx`` is not used in that example

**Comment by mlubin** [comment]
Anyway since ``OneTo`` is a range with "lower limit ... guaranteed (by the type system) to be 1" it's a potential solution for the type instability issue in https://github.com/JuliaOpt/JuMP.jl/issues/346. So it's possible to support, although I don't understand your use case.
