### ISSUE TITLE
anonymous SDP variables

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#936]
Not addressed by https://github.com/JuliaOpt/JuMP.jl/pull/935

**Comment by mlubin** [comment]
@joehuchette, what do you think the syntax for this should look like?

**Comment by joehuchette** [comment]
``@variable(m, [1:3,1:3], category=:SDP)`` is maybe the simplest. Something like ``@variable(m, [1:3,1:3], cone=:SDP)`` might be clearer, though.

**Comment by mlubin** [comment]
``@variable(m, [1:3,1:3], category=:SDP)`` is a misnomer, I'd prefer ``@variable(m, [1:3,1:3], cone=:SDP)``

**Comment by mlubin** [comment]
Also the syntax needs to support symmetric matrices.

**Comment by mlubin** [comment]
Wait. ``@variable(m, [1:3,1:3], SDP)`` is not ambiguous and seems to be working already. I think there's nothing to do here!
