### ISSUE TITLE
Dot operator of vectors of AffExpr should avoid warning (like sum)?

### ISSUE THREAD

**Issue by cossio** [JuliaOpt/JuMP.jl#940]
For example, a constraint of the form;

```julia
JuMP.@constraint(model, dot(u,v) == 0)
```
is very slow if `u,v` are large, and it generates a warning:

> WARNING: The addition operator has been used on JuMP expressions a large number of times. This warning is safe to ignore but may indicate that model generation is slower than necessary. For performance reasons, you should not add expressions in a loop. Instead of x += y, use append!(x,y) to modify x in place. If y is a single variable, you may also use push!(x, coef, y) in place of x += coef*y.

However, using `sum` is very fast and doesn't generate a warning:

```julia
JuMP.@constraint(model, sum(u[k] * v[k] for k = 1:N) == 0)
```

When `u,v` are vectors of `AffExpr` or vectors of JuMP variables, maybe `dot(u,v)` should automatically fall back on `sum(u[k] * v[k] for k = 1:N)`. If this is correct, I could try to implement it myself... although I could use some guidance on the codebase.

**Comment by mlubin** [comment]
The fix would be to add a specialized method for ``dot`` [here](https://github.com/JuliaOpt/JuMP.jl/blob/dd4f5ea2e4cb9b2e142a0dc6162299b7ce5cb333/src/operators.jl#L306). The contribution is welcome, and should be a one-liner.

**Comment by cossio** [comment]
@mlubin Please, review it.

**Comment by cossio** [comment]
Here is a minimum example that raises the warning:

```
using JuMP
m = Model()
@variable(m, x[1:1_000_000]);
@constraint(m, dot(x, 1 : 1_000_000) <= 1);
```

**Comment by joehuchette** [comment]
Great, thanks. For this particular case, I believe a fix will be to change ``Array`` to ``AbstractArray`` and ``Vector`` to ``AbstractVector`` here: https://github.com/JuliaOpt/JuMP.jl/blob/d725975b571309ffaff840ca9709e739287c8d41/src/operators.jl#L299-L322
