### ISSUE TITLE
setlowerbound & setupperbound for vectors

### ISSUE THREAD

**Issue by cossio** [JuliaOpt/JuMP.jl#945]
Is it possible to extend `setlowerbound` and `setupperbound` for vectors? Basically, I want to avoid to have to write something like:

```julia
for i = 1:M
   JuMP.setlowerbound(x[i], lb[i])
end
```

when I could just write:

```julia
JuMP.setlowerbound(x, lb)
```

and let JuMP do the loop.

**Comment by mlubin** [comment]
You can now do ``JuMP.setlowerbound.(x, lb)`` so it's not clear why we need to manually vectorize this in JuMP. But anyway this is a dup of https://github.com/JuliaOpt/JuMP.jl/issues/740.

**Comment by cossio** [comment]
@mlubin  What version? I am using JuMP0.15 and `setlowerbound(x, lb)` gives an error:

> ERROR: MethodError: no method matching setlowerbound(::Array{JuMP.Variable,1}, ::Array{Float64,1})

**Comment by mlubin** [comment]
Julia 0.5 and later

**Comment by cossio** [comment]
Oh, sorry, I missed the dot. Yes, you are right.
