### ISSUE TITLE
Assigning a constant to an expression indexed by strings or symbols

### ISSUE THREAD

**Issue by bbrunaud** [JuliaOpt/JuMP.jl#949]
Hello, I was trying to build a complex expression and I found the following.

```
using JuMP

m = Model()

@expression(m, ex, 0.0)   # Works
@expression(m, ex[i in 1:3], 0.0) # Works
@expression(m, ex[i in 1:3, j in 1:3], 0.0) # Error

@expression(m, ex[i in 1:3, j in 1:3], AffExpr(0.0)) # Workaround
```

regards

Braulio

**Comment by joehuchette** [comment]
What version of JuMP are you using? This works for me on 0.15.0.

**Comment by bbrunaud** [comment]
0.15.0

I'm sorry, I didn't reproduce the error correctly. This happens when one of the sets is an Array of Strings or Symbols. Then internally the representation is a dictionary and not an array

```
sites = [:A :B :C]
@expression(m, ex[i in 1:3, j in sites], 0.0)
```
The error is
```
ERROR: MethodError: no method matching setindex!(::JuMP.JuMPArray{JuMP.GenericAffExpr{Float64,JuMP.Variable},2,Tuple{UnitRange{Int64},Array{Symbol,2}}}, ::Float64, ::Int64, ::Symbol)
 in macro expansion; at /home/bbrunaud/.julia/v0.5/JuMP/src/macros.jl:750 [inlined]
```

**Comment by mlubin** [comment]
This is covered by https://github.com/JuliaOpt/JuMP.jl/issues/525 but we might be able to fix this particular case before we do the complete overhaul that's needed.

**Comment by joehuchette** [comment]
Whoops, meant to push that to a PR. Will revert if needed.

**Comment by mlubin** [comment]
Does it pass tests?
I think the better fix is to implement a ``setindex!`` method which does the conversion.

**Comment by joehuchette** [comment]
It passed the tests I added, not sure why it would break anything else. I'm fine adding the method, but it was trickier to figure that out than it was to do this.

**Comment by mlubin** [comment]
It could break the scalar ``QuadExpr`` case
