### ISSUE TITLE
parallel model generation

### ISSUE THREAD

**Issue by kkmann** [JuliaOpt/JuMP.jl#958]
Hey,

is it currently possible to generate a JuMP model in parallel (most importantly: adding constraints)? 

Best,

Kevin

**Comment by mlubin** [comment]
Could you clarify what you mean by parallel? Julia has both shared memory and distributed memory parallelism.

**Comment by kkmann** [comment]
Shared memory parallelism on a single machine. Basically like a SharedArray only for JuMP models.

**Comment by mlubin** [comment]
No, this is not supported. I'd be very interested to see a case where the serial model generation takes longer than actually solving the problem (and hence would be a bottleneck worth parallelizing).

**Comment by kkmann** [comment]
I optimize functionals over integer integer -> integer valued functions by breaking it down to a binary variables assignment problem (binary variables only). Works fine with Gurobi but for large problems (>7 mio binary variables) constraint generation IS the bottleneck x)

**Comment by mlubin** [comment]
If you post some code (on [discourse](https://discourse.julialang.org/c/domain/opt) please) you may get some suggestions on how to speed it up. After following Julia's performance tips and accounting for possible quirks in JuMP, I'd be very surprised if model generation is really a bottleneck.
