### ISSUE TITLE
Querying dual information of MIP that has previously been solved

### ISSUE THREAD

**Issue by odow** [JuliaOpt/JuMP.jl#960]
In the following scenario, it is possible for the dual information to be out of date.

```julia
m=Model()
@variable(m, x, Bin)
@objective(m, Max, x)

solve(m)
getdual(x) # errors

solve(m, relaxation=true)
getdual(x) # 1.0

solve(m)
getdual(x) # 1.0
```

Is this user-beware or should the dual information be set to NaN in the `else` branch of [here](https://github.com/JuliaOpt/JuMP.jl/blob/v0.15.1/src/solvers.jl#L155).

**Comment by mlubin** [comment]
The dual information should be cleared. More evidence for reworking MPB to better communicate which solution information is available and what its status is (https://github.com/JuliaOpt/JuMP.jl/pull/938).

**Comment by mlubin** [comment]
@joehuchette, closed by https://github.com/JuliaOpt/JuMP.jl/pull/963?

**Comment by joehuchette** [comment]
Yes
