### ISSUE TITLE
Quering solve time of mode

### ISSUE THREAD

**Issue by Zlinki** [JuliaOpt/JuMP.jl#961]
Hello! 
Once you solve a model m using solve(m), you get a message displaying, among other things, the number of iterations and the solving time. 
For example, i get the message "Solved in 27 iterations and 0.02 seconds". Is there a method for extracting this time? for example something like `gettimevalue(m)`?

Thanks in advance.

**Comment by blegat** [comment]
If I am not mistaken, this message is showed by the solver itself and there currently isn't a standardized way to ask for the solve time in MathProgBase. Which solver are you using ?

**Comment by mlubin** [comment]
http://www.juliaopt.org/JuMP.jl/0.15/refmodel.html#methods
``getsolvetime(m::Model)`` - returns the solve time reported by the solver if it is implemented.

**Comment by Zlinki** [comment]
Thanks!

**Comment by mlubin** [comment]
Please use [discourse](https://discourse.julialang.org/c/domain/opt) for "how do I do this?" questions going forward.
