### ISSUE TITLE
Solve relaxation after a solve raises CPLEX error

### ISSUE THREAD

**Issue by bbrunaud** [JuliaOpt/JuMP.jl#967]
I was trying to solve a relaxation after having solved the MIP problem and I got an error using CPLEX. I tried manually changing the variable types (calling MathProgBase.setvartype!) and it didn't work. Here is the example. 

```
using JuMP
using CPLEX

m = Model(solver=CplexSolver())
@variable(m, x[1:2] >= 0, upperbound = 4)
@variable(m, y[1:2], Bin)

@constraint(m, con[i=1:2], x[i] <= 4y[i])
@constraint(m, y[1] + y[2] == 1)
@objective(m, Max, x[1] + x[2])

solve(m)
solve(m, relaxation=true)
```
CPLEX Error  1017: Not available for mixed-integer problems.

**Comment by joehuchette** [comment]
@bbrunaud this is a CPLEX-specific feature request, I've opened an issue on that repository.

**Comment by bbrunaud** [comment]
Thank you!. I wasn't sure if it a problem on CPLEX.jl side or JuMP

**Comment by mlubin** [comment]
Fixed in latest CPLEX.jl release
