### ISSUE TITLE
Transpose not currently implemented for JuMPArrays with arbitrary index sets

### ISSUE THREAD

**Issue by muditdham** [JuliaOpt/JuMP.jl#968]
So I am trying to use JuMP library to maximize an expression in Julia, but seem to get this error "**Transpose not currently implemented for JuMPArrays with arbitrary index sets.**". 
Is there a work around for this at the moment ? 
Also, I am new to this library, is my implementation of the model correct ?
My implementation so far
```julia
function getSharpeRatio(W,ex_mu,S)
    return ( dot(W', ex_mu) / sqrt(dot(W',S*W)) )
end
items  = [1;2;3;4;5]
using JuMP 
m = Model()
@variable(m, 0 <= W[items] <= 1)
shapreratio = getSharpeRatio(W,ex_mu,S) 
@constraint(m, sum{ W[item] , item in items} == 1)
@NLobjective(m, Max, getSharpeRatio(W,ex_mu,S))
solve(m)
println(getvalue(W))
```
Here W is (5x1) FLoat64 vector on which constraints are defined 
- sum of W should always be 1, and 
- All W values should lie in the range 0 to 1 

ex_mu is a (5x1) Float64 vector and S is (5x5) Float64 Array.
' is Transpose and sqrt is function for square root

**Comment by blegat** [comment]
You do not need to transpose the left operand of `dot`, e.g.:
```julia
> dot([1, 2], [3, 4])
11
```
By the way, I would suggest you to use `sum` instead:
```julia
sum(W[i] * ex_mu[i] for i in 1:5)
sum(W[i] * S[i, j] * W[j] for i in 1:5 for j in 1:5)
```
Please ask usage question on [Discourse](https://discourse.julialang.org/c/domain/opt).

**Comment by muditdham** [comment]
I updated my implementation as follows from you inputs , 

    function getSharpeRatio(W,ex_mu,S)
       (sum(W[i] * ex_mu[i] for i in 1:5))/ (sum(W[i] * S[i, j] * W[j] for i in 1:5 for j in 1:5))
     end
    using JuMP
    m = Model()
    @variable(m, 0 <= W[1:5] <= 1)
    @constraint(m, sum{ W[item] , item in items} == 1)
    @objective(m, Max, getSharpeRatio(W,ex_mu,S))
    solve(m)
    println(getvalue(W))

Now i get the following error

    /(::JuMP.GenericAffExpr{Float64,JuMP.Variable},::JuMP.GenericQuadExpr{Float64,JuMP.Variable}) is not     defined. Are you trying to build a nonlinear problem?

**Comment by blegat** [comment]
You may wan to do directly
```julia
@NLobjective(m, Max, (sum(W[i] * ex_mu[i] for i in 1:5)) / (sum(W[i] * S[i, j] * W[j] for i in 1:5 for j in 1:5)))
```

**Comment by muditdham** [comment]
I get a ReadOnlyMemoryError() when trying to run solve(m).

**Comment by blegat** [comment]
I guess you are using the `Ipopt` solver. See [this issue](https://github.com/JuliaOpt/Ipopt.jl/issues/77).
