### ISSUE TITLE
epsilons in A matrix when calling SDconstraint on a matrix that should be symmetric already

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#972]
This causes numerical difficulties for solvers and shouldn't happen. Example:

```julia
using JuMP, Pajarito

V = [-6.0 -3.0 8.0 3.0; -3.0 -9.0 -4.0 3.0; 3.0 1.0 5.0 5.0]
(q, p) = size(V)
n = 7
nmax = ceil(Int, 2*n/p)

eOpt = Model(solver=PajaritoSolver())
np = @variable(eOpt, [j=1:p], Int, lowerbound=0, upperbound=nmax)
t = @variable(eOpt)
@objective(eOpt, Max, t)
@constraint(eOpt, sum(np) <= n)
@SDconstraint(eOpt, V * diagm(np./n) * V' - t * eye(q) >= 0)

(c, A, b, var_cones, con_cones) = JuMP.conicdata(eOpt)
@show c
@show A
@show b
@show var_cones
@show con_cones
```

In the A matrix I get -4.44089e-16 entries. I have other examples where the same thing happens.

**Comment by chriscoey** [comment]
Maybe there should be a way to tell JuMP that your matrix is symmetric already

**Comment by mlubin** [comment]
I propose:
```jl
@SDconstraint(eOpt, Symmetric(V * diagm(np./n) * V' - t * eye(q)) >= 0)
```
should avoid adding symmetry constraints.

**Comment by chriscoey** [comment]
Sounds good

**Comment by mlubin** [comment]
Right now we drop symmetry constraints if things are exactly equal but we could also use a tolerance instead of introducing new syntax.

I wonder how CVXPY handles this... calling in @SteveDiamond

**Comment by SteveDiamond** [comment]
There are a few different ways to impose PSD constraints in cvxpy. One way is to declare a PSD variable, ``A = Semidef(n)``. Here ``A`` is defined over the vector space of symmetric matrices, so no symmetry constraints are needed. Another way is to create a PSD variable and use it in an equality constraint, e.g., ``A == Semidef(n)``. This imposes ``A == A^T`` as constraints. If the symmetry constraint adds rows of all zeros to the constraints matrix, these are removed in preprocessing.

Yet another way is to write ``A >> 0``, which imposes the constraint ``x^TAx >= 0`` for all ``x`` but not ``A == A^T``. This syntax was requested by a user, and it was essential that no unnecessary symmetry constraints were created. At some point I want to change cvxpy to track symmetry as a property of expressions and use this information when generating the ``A >> 0`` and ``A == Semidef(n)`` constraints.

**Comment by mlubin** [comment]
Thanks @SteveDiamond! That's useful to know for reference.

Unless someone is jumping up and down to implement the new syntax in JuMP, I think we should try using a numerical tolerance to detect and remove symmetry-enforcing constraints with all tiny coefficients and see if that does a good job covering the cases that arise in practice.
