### ISSUE TITLE
Lazy constraint macro while using bender's Decomposition with callbacks

### ISSUE THREAD

**Issue by loylobo** [JuliaOpt/JuMP.jl#993]
The following bug report when I'm solving a MILP with bender's Decomposition on Julia Opt:

Following is the output when lazy constraint is added:
```julia
 LoadError: MethodError: no method matching isless(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Float64)

Closest candidates are:
  isless(::Float64, ::Float64) at float.jl:283
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:40
  isless(::ForwardDiff.Dual{N,T<:Real}, ::AbstractFloat) at C:\Users\Loy\.julia\v0.5\ForwardDiff\src\dual.jl:160
  ...
 in <=(::Float64, ::JuMP.GenericAffExpr{Float64,JuMP.Variable}) at .\operators.jl:65
 in addBendersCut(::Gurobi.GurobiCallbackData) at C:\Users\Loy\AppData\Local\Julia-0.5.0\ccstry.jl:337
 in lazycallback(::Gurobi.GurobiCallbackData, ::JuMP.Model, ::Array{JuMP.LazyCallback,1}) at C:\Users\Loy\.julia\v0.5\JuMP\src\callbacks.jl:78
 in (::JuMP.##125#126{JuMP.Model,Array{JuMP.LazyCallback,1}})(::Gurobi.GurobiCallbackData) at C:\Users\Loy\.julia\v0.5\JuMP\src\callbacks.jl:96
 in mastercallback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Void}) at C:\Users\Loy\.julia\v0.5\Gurobi\src\GurobiSolverInterface.jl:566
 in optimize(::Gurobi.Model) at C:\Users\Loy\.julia\v0.5\Gurobi\src\grb_solve.jl:5
 in optimize!(::Gurobi.GurobiMathProgModel) at C:\Users\Loy\.julia\v0.5\Gurobi\src\GurobiSolverInterface.jl:294
 in #solve#97(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\Loy\.julia\v0.5\JuMP\src\solvers.jl:142
 in solve(::JuMP.Model) at C:\Users\Loy\.julia\v0.5\JuMP\src\solvers.jl:117
 in include_from_node1(::String) at .\loading.jl:488
while loading C:\Users\Loy\AppData\Local\Julia-0.5.0\ccstry.jl, in expression starting on line 351
```

The part of the code: 
```julia
@lazyconstraint(cb,sum(capacitypipemin[d]*ItaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitypipemax[d]*DeltaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitys[i]*Opensource[i]*AlphaCurrent[i]for i=SOURCE)-sum(capacityr[i]*Openreservoir[i]*BetaCurrent[i]for i=RESERVOIR)+ TauCurrent*T<=0)
```

where following is the data and parameters generated:
```julia
T = 10
SOURCE = ["S1", "S2"]
RESERVOIR = ["R3", "R4", "R5"]
DIAMETER = ["fourinch", "sixinch"]
NODES = union(SOURCE,RESERVOIR)
#Data
fixedcosts	= Dict("S1" => 500,	"S2" => 600, "R3" =>0, "R4"=>0,	"R5"=>0)
variablecosts = Dict("S1" => 0.035, "S2" => 0.040,"R3" =>0, "R4"=>0,"R5"=>0)
capacitys = Dict("S1" => 13,	"S2" => 20,"R3" =>0, "R4"=>0,"R5"=>0)

fixedcostr	= Dict("S1" => 0,	"S2" => 0, "R3" =>500, "R4"=>300,	"R5"=>600)
variablecostr = Dict("S1" => 0,	"S2" => 0,"R3" =>0.025, "R4"=>0.030,	"R5"=>0.025)
capacityr	= Dict("S1" => 0,	"S2" => 0,"R3" =>6, "R4"=>6,	"R5"=>6)
fixedcostpipe = Dict("fourinch"=> 100 , "sixinch"=> 150)

variablecostpipe = 315
capacitypipemax = Dict("fourinch"=> 25 , "sixinch"=> 50)
capacitypipemin = Dict("fourinch"=> 0 , "sixinch"=> 25)


@variable(masterProblemModel,Opensource[s=NODES], Bin)
@variable(masterProblemModel,Openreservoir[r=NODES], Bin)
@variable(masterProblemModel,W[a=NODES,b=NODES,d=DIAMETER]>=0)
@variable(masterProblemModel, Z>=0)



TauCurrent = getvalue(Tau)
AlphaCurrent=Dict{String,Float64}()
for i=NODES
push!(AlphaCurrent,"$(i)" =>  getvalue(Alpha[i]))
end

BetaCurrent=Dict{String,Float64}()
for i=NODES
push!(BetaCurrent,"$(i)" =>  getvalue(Beta[i]))
end

GammaCurrent=Dict{String,Float64}()
for i=NODES
push!(GammaCurrent,"$(i)" =>  getvalue(Gamma[i]))
end

DeltaCurrent = Dict{Array{String,1},Float64}()
for i = NODES
for j=NODES
push!(DeltaCurrent,["$(i)","$(j)"] => getvalue(Delta[i,j]))
		end
		end

ItaCurrent = Dict{Array{String,1},Float64}()
for i = NODES
	for j=NODES
	push!(ItaCurrent,["$(i)","$(j)"] => getvalue(Ita[i,j]))
end
end   
```

The code works fine until the lazy constraint macro.
Please help solve this bug.

**Comment by blegat** [comment]
Could your replace
```julia
@lazyconstraint(cb,sum(capacitypipemin[d]*ItaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitypipemax[d]*DeltaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitys[i]*Opensource[i]*AlphaCurrent[i]for i=SOURCE)-sum(capacityr[i]*Openreservoir[i]*BetaCurrent[i]for i=RESERVOIR)+ TauCurrent*T<=0)
```
by
```julia
println(macroexpand(:(@lazyconstraint(cb,sum(capacitypipemin[d]*ItaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitypipemax[d]*DeltaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitys[i]*Opensource[i]*AlphaCurrent[i]for i=SOURCE)-sum(capacityr[i]*Openreservoir[i]*BetaCurrent[i]for i=RESERVOIR)+ TauCurrent*T<=0))))
```
and give us the output ?

**Comment by loylobo** [comment]
Did the same and the output generated was as below:

ERROR: LoadError: MethodError: no method matching isless(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Float64)
Closest candidates are:
  isless(::Float64, ::Float64) at float.jl:283
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:40
  isless(::ForwardDiff.Dual{N,T<:Real}, ::AbstractFloat) at C:\Users\Loy\.julia\v0.5\ForwardDiff\src\dual.jl:160
  ...
 in <=(::Float64, ::JuMP.GenericAffExpr{Float64,JuMP.Variable}) at .\operators.jl:65
 in addBendersCut(::Gurobi.GurobiCallbackData) at C:\Users\Loy\AppData\Local\Julia-0.5.0\ccstry.jl:337
 in lazycallback(::Gurobi.GurobiCallbackData, ::JuMP.Model, ::Array{JuMP.LazyCallback,1}) at C:\Users\Loy\.julia\v0.5\JuMP\src\callbacks.jl:78
 in (::JuMP.##125#126{JuMP.Model,Array{JuMP.LazyCallback,1}})(::Gurobi.GurobiCallbackData) at C:\Users\Loy\.julia\v0.5\JuMP\src\callbacks.jl:96
 in mastercallback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Void}) at C:\Users\Loy\.julia\v0.5\Gurobi\src\GurobiSolverInterface.jl:566
 in optimize(::Gurobi.Model) at C:\Users\Loy\.julia\v0.5\Gurobi\src\grb_solve.jl:5
 in optimize!(::Gurobi.GurobiMathProgModel) at C:\Users\Loy\.julia\v0.5\Gurobi\src\GurobiSolverInterface.jl:294
 in #solve#97(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\Loy\.julia\v0.5\JuMP\src\solvers.jl:142
 in solve(::JuMP.Model) at C:\Users\Loy\.julia\v0.5\JuMP\src\solvers.jl:117
 in include_from_node1(::String) at .\loading.jl:488
while loading C:\Users\Loy\AppData\Local\Julia-0.5.0\ccstry.jl, in expression starting on line 351

**Comment by joehuchette** [comment]
This would imply that the error is coming from some other line in your code.

**Comment by blegat** [comment]
Yes, the issue seems to come from the line `in addBendersCut(::Gurobi.GurobiCallbackData) at C:\Users\Loy\AppData\Local\Julia-0.5.0\ccstry.jl:337`

**Comment by loylobo** [comment]
That line doesn't show up as an error while running the first iteration.

Please see the following part of the function in the code:

function addBendersCut(cb)
#println("ITERATION NUMBER = ", length(stringOfBenderCuts)+1)
fmCurrent = getvalue(Z)
OpensourceCurrent=Dict{String,Int64}()
for i=NODES
push!(OpensourceCurrent,"$(i)" =>  getvalue(Opensource[i]))
end

OpenreservoirCurrent=Dict{String,Int64}()
for i=NODES
push!(OpenreservoirCurrent,"$(i)" =>  getvalue(Openreservoir[i]))
end

SelectCurrent = Dict{Array{String,1},Int64}()
for i = NODES
	for j=NODES
	for d=DIAMETER
	push!(SelectCurrent,["$(i)","$(j)","$(d)"] => getvalue(Select[i,j,d]))
		end
		end
	end
#println("with ", length(stringOfBenderCuts), " added lazy constraints")
# Now we solve the subproblem
subProblemModel = Model(solver=GurobiSolver())    
@variable(subProblemModel, Delta[a=NODES,b=NODES]>=0)
@variable(subProblemModel, Ita[a=NODES,b=NODES]>=0)
@variable(subProblemModel, Gamma[a=NODES]>=0)
@variable(subProblemModel, Alpha[a=NODES]>=0)
@variable(subProblemModel, Beta[a=NODES]>=0)
@variable(subProblemModel, Tau >=0)
@constraint(subProblemModel,[i=NODES,j=NODES],Ita[i,j]-Delta[i,j] + Gamma[i]-Gamma[j] <= variablecostpipe)

@constraint(subProblemModel,[i=SOURCE],Tau - Alpha[i]- Gamma[i]<= variablecosts[i])

@constraint(subProblemModel,[i=RESERVOIR],Gamma[i] - Beta[i]<= variablecostr[i])
 
@objective(subProblemModel,Max,sum(SelectCurrent[String[i,j,d]]*capacitypipemin[d]*Ita[i,j]for i=NODES,j=NODES,d=DIAMETER)-sum(SelectCurrent[String[i,j,d]]*capacitypipemax[d]*Delta[i,j]for i=NODES,j=NODES,d=DIAMETER)-sum(Alpha[i]*OpensourceCurrent[i]*capacitys[i]for i=SOURCE)- sum(Beta[j]*OpenreservoirCurrent[j]*capacityr[j]for j=RESERVOIR)+ Tau*T)


println("The subproblem is being solved")

statusSubProblem = solve(subProblemModel) 
#We store the DSP results in conventional data structures      
fsxCurrent = getobjectivevalue(subProblemModel) 
TauCurrent = getvalue(Tau)
AlphaCurrent=Dict{String,Float64}()
for i=NODES
push!(AlphaCurrent,"$(i)" =>  getvalue(Alpha[i]))
end

BetaCurrent=Dict{String,Float64}()
for i=NODES
push!(BetaCurrent,"$(i)" =>  getvalue(Beta[i]))
end

GammaCurrent=Dict{String,Float64}()
for i=NODES
push!(GammaCurrent,"$(i)" =>  getvalue(Gamma[i]))
end

DeltaCurrent = Dict{Array{String,1},Float64}()
for i = NODES
for j=NODES
push!(DeltaCurrent,["$(i)","$(j)"] => getvalue(Delta[i,j]))
		end
		end

ItaCurrent = Dict{Array{String,1},Float64}()
for i = NODES
	for j=NODES
	push!(ItaCurrent,["$(i)","$(j)"] => getvalue(Ita[i,j]))
end
end   
#Display the solution corresponding to the subproblem 
println("SUBPROBLEM INFORMATION")
println("Current status of the subproblem is ", statusSubProblem)
println("Current Value of DSP is: ", fsxCurrent)
println("\n")
# Check the status of the algorithm and add Benders cuts          

if statusSubProblem == :Optimal && fsxCurrent+sum(fixedcosts[i]*Opensource[i]for i=SOURCE)+ sum(fixedcostr[j]*Openreservoir[j]for j=RESERVOIR)+sum(Select[i,j,d]*fixedcostpipe[d] for i=NODES,j=NODES,d=DIAMETER)==fmCurrent+0.0001
return
end 
println("---ADDING LAZY CONSTRAINT--")#(AT ITERATION NUMBER = 
#", #length(stringOfBenderCuts), ")---"

if statusSubProblem == :Optimal && fmCurrent+0.0001 <= fsxCurrent+sum(fixedcosts[i]*Opensource[i]for i=SOURCE)+ sum(fixedcostr[j]*Openreservoir[j]for j=RESERVOIR)+sum(Select[i,j,d]*fixedcostpipe[d] for i=NODES,j=NODES,d=DIAMETER)
println(macroexpand(:(@lazyconstraint(cb,Z>=sum(fixedcosts[i]*Opensource[i]for i=SOURCE)+sum(fixedcostr[j]*Openreservoir[j]for j=RESERVOIR)+sum(Select[i,j,d]*fixedcostpipe[d] for i=NODES,j=NODES,d=DIAMETER)-sum(capacitypipemax[d]*DeltaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)+sum(capacitypipemin[d]*ItaCurrent[String[i,j]]*Select[i,j,d]for i=NODES,j=NODES,d= DIAMETER)-sum(capacitys[i]*Opensource[i]*AlphaCurrent[i]for i=SOURCE)-sum(capacityr[i]*Openreservoir[i]*BetaCurrent[i]for i=RESERVOIR)+TauCurrent*T))))
end

if statusSubProblem == :Unbounded
println("\nThere is an  extreme ray, adding the constraint")
println(macroexpand(:(@lazyconstraint(cb,sum(capacitypipemin[d]*ItaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitypipemax[d]*DeltaCurrent[String[i,j]]*Select[i,j,d] for i=NODES,j=NODES,d= DIAMETER)-sum(capacitys[i]*Opensource[i]*AlphaCurrent[i]for i=SOURCE)-sum(capacityr[i]*Openreservoir[i]*BetaCurrent[i]for i=RESERVOIR)+ TauCurrent*T<=0))))
end
      
end

addlazycallback(masterProblemModel,addBendersCut) 
solve(masterProblemModel)

Please help me identify the line of errror

**Comment by joehuchette** [comment]
I'm guessing your problem is with the if statements like
```jl
if statusSubProblem == :Optimal && fsxCurrent+sum(fixedcosts[i]*Opensource[i]for i=SOURCE)+ sum(fixedcostr[j]*Openreservoir[j]for j=RESERVOIR)+sum(Select[i,j,d]*fixedcostpipe[d] for i=NODES,j=NODES,d=DIAMETER)==fmCurrent+0.0001
```
since ``Opensource`` is a ``Variable`` (I think). You probably want its optimal value (use ``getvalue``). Same goes for the other ``Variable``s.

In the future, please post usage questions on our [mailing list](https://discourse.julialang.org/c/domain/opt).

**Comment by loylobo** [comment]
Thank you so much!
