### ISSUE TITLE
suppress_warnings does not suppress a warning

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#996]
specifically:
`WARNING: Solver does not appear to support adding constraints to an existing model. JuMP's internal model will be discarded.`

**Comment by mlubin** [comment]
``suppress_warnings`` is passed to ``solve()``. We don't have a flag to suppress warnings outside of ``solve()`` (I imagine this warning is coming from a call to ``@constraint``).

**Comment by chriscoey** [comment]
OK

**Comment by mlubin** [comment]
If it bothers you we can leave the issue open and figure out a fix
