### ISSUE TITLE
Callback function to be called when Master problem reaches optimal at that iteration (in JuMP's example, it is called@ any feasible sub-optimal integer point)

### ISSUE THREAD

**Issue by loylobo** [JuliaOpt/JuMP.jl#997]
Hi,
I'm working on Bender's decomposition of a MILP on the Julia interface with JuMP package on a Gurobi solver. In the example here, the callback function of lazy constraints is called when the master problem reaches an integer feasible solution(of an iteration).  However, as per my math, the function should ideally be called only at an optimal solution of the Master Problem(at the iteration). 

When I run the standard Bender's example code, it calls the callback function when master Problem reaches any random integer feasible solution (hence, it gives trouble with convergence)

Could you suggest the method to call the function at optimal solutions for each iteration of master problem model? Following is the description of the code:

loading of the solver and JuMP
loading of master Problem

function addBendersCut(cb)
subproblem loading and solving
test for global optimum
lazy constraints
end

addlazycallback(masterProblemModel,addBendersCut) 
statusMP=solve(masterProblemModel)

**Comment by mlubin** [comment]
This has been [answered](https://discourse.julialang.org/t/benders-decomposition-callback-function-to-be-called-when-master-problem-reaches-optimal-at-that-iteration-in-jumps-example-it-is-called-any-feasible-sub-optimal-integer-point/2856).
