### ISSUE TITLE
can't add SOC constraints to an LP

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/JuMP.jl#998]
In Pajarito we need to be able to start with an MILP problem, solve it, and iteratively add SOC constraints. But without a dummy SOC constraint in the first LP model, JuMP will think it is LinearQuadratic. I want to be able to JuMP that this is to be a conic model.

See https://github.com/mlubin/Pajarito.jl/pull/318

**Comment by mlubin** [comment]
Will be resolved with https://github.com/JuliaOpt/JuMP.jl/issues/1006
